SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
#if GERMAN
	.string "Weißt du irgendetwas über diese\n"
	.string "Steinkammer?$"
#else
	.string "Do you know anything about this\n"
	.string "stone chamber?$"
#endif

SevenIsland_TanobyRuins_Text_BrandonDefeat::
#if GERMAN
	.string "Das war überraschend. Du\n"
	.string "hättest nicht so grob sein müssen.$"
#else
	.string "That was uncalled for.\n"
	.string "You didn't have to be so rough.$"
#endif

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
#if GERMAN
	.string "Die Tanibo-ruinen sind mindestens\n"
	.string "1500 Jahre alt.\p"
	.string "Aber zunächst ist es ein Geheimnis,\n"
	.string "warum sie überhaupt gebaut wurden.$"
#else
	.string "The TANOBY RUINS date back at\n"
	.string "least 1,500 years.\p"
	.string "But it's a baffling mystery as to\n"
	.string "why it was built in the first place.$"
#endif

SevenIsland_TanobyRuins_Text_BenjaminIntro::
#if GERMAN
	.string "Man sagt, dass hier ein mystisches\n"
	.string "Pokémon schlafen soll.$"
#else
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here.$"
#endif

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
#if GERMAN
	.string "Ich bin nicht gut beim Kämpfen.$"
#else
	.string "I'm not much good in battle.$"
#endif

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
#if GERMAN
	.string "Ich habe gehört, dass es noch\n"
	.string "andere Ruinen wie diese geben\l"
	.string "soll.\l"
	.string "Vielleicht sind sie die Ruhestätten\l"
	.string "anderer, mystischer Pokémon.$"
#else
	.string "I hear there are other ruins like\n"
	.string "the one here.\p"
	.string "Might they be the resting places\n"
	.string "of other mystic POKéMON?$"
#endif

SevenIsland_TanobyRuins_Text_EdnaIntro::
#if GERMAN
	.string "Tom bringt mir das Malen bei!$"
#else
	.string "CLIFFORD is teaching me how to\n"
	.string "paint.$"
#endif

SevenIsland_TanobyRuins_Text_EdnaDefeat::
#if GERMAN
	.string "Wir könnten Ärger bekommen, wenn\n"
	.string "wir hier so viel Lärm machen.$"
#else
	.string "We might get in trouble for being\n"
	.string "noisy here.$"
#endif

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
#if GERMAN
	.string "Ich sagte, dass ich ein altes\n"
	.string "Gebäude malen wollte.\p"
	.string "Also hat Tom mich hierher\n"
	.string "gebracht.$"
#else
	.string "I said that I wanted to paint an\n"
	.string "old building.\p"
	.string "So CLIFFORD brought me here.$"
#endif

SevenIsland_TanobyRuins_Text_CliffordIntro::
#if GERMAN
	.string "Heute hat er mir im Anschluss an\n"
	.string "die Unterrichtsstunde die Kammer\l"
	.string "gezeigt.$"
#else
	.string "Today, in addition to our lesson,\n"
	.string "we came to see the chamber.$"
#endif

SevenIsland_TanobyRuins_Text_CliffordDefeat::
#if GERMAN
	.string "Oh, wie außergewöhnlich.$"
#else
	.string "My, how extraordinary.$"
#endif

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
#if GERMAN
	.string "Ah, du studierst also ganz alleine\n"
	.string "Pokémon…\p"
	.string "Ja, du bist wirklich eine außer-\n"
	.string "ordentliche Persönlichkeit.$"
#else
	.string "Ah, so you are studying POKéMON\n"
	.string "on your own…\p"
	.string "Yes, you certainly are quite the\n"
	.string "extraordinary person, indeed.$"
#endif
