SixIsland_WaterPath_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_EventScript_HornWantedSign::
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end

SixIsland_WaterPath_EventScript_RouteSign::
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end

SixIsland_WaterPath_Text_RoseIntro::
#if GERMAN
	.string "Ich wurde von einer angenehmen\n"
	.string "Brise hierher gebracht.$"
#else
	.string "I let a pleasant breeze lead me\n"
	.string "all the way here.$"
#endif

SixIsland_WaterPath_Text_RoseDefeat::
#if GERMAN
	.string "Kicher… du bist süß, wenn\n"
	.string "du so entschlossen bist.$"
#else
	.string "Giggle… You're so cute when you're\n"
	.string "determined.$"
#endif

SixIsland_WaterPath_Text_RosePostBattle::
#if GERMAN
	.string "Ich möchte dort drüben in den\n"
	.string "Wald, aber…\p"
	.string "Es gibt dort eine Menge Käfer-Pokémon.\n"
	.string "Das macht mir ein wenig Angst.$"
#else
	.string "I want to go to the woods over\n"
	.string "there, but…\p"
	.string "There are lots of BUG POKéMON.\n"
	.string "They scare me a little.$"
#endif

SixIsland_WaterPath_Text_EdwardIntro::
#if GERMAN
	.string "Ich trainiere heimlich, damit mich\n"
	.string "niemand sieht.$"
#else
	.string "I'm practicing in secret so no one\n"
	.string "can see me.$"
#endif

SixIsland_WaterPath_Text_EdwardDefeat::
#if GERMAN
	.string "Niemand hat gesehen, wie ich\n"
	.string "verloren habe, oder?$"
#else
	.string "Nobody saw me losing, right?$"
#endif

SixIsland_WaterPath_Text_EdwardPostBattle::
#if GERMAN
	.string "Da ich ein Artist bin, möchte ich nicht,\n"
	.string "dass die Leute sehen, wie sehr ich mich\l"
	.string "anstrenge.$"
#else
	.string "As a performer, I don't want people\n"
	.string "to know about the effort I put in.$"
#endif

SixIsland_WaterPath_Text_SamirIntro::
#if GERMAN
	.string "Wie, du behauptest, du hättest genug\n"
	.string "von Schwimmern wie mir?\l"
	.string "Argh, sei nicht so abweisend!$"
#else
	.string "What, you're suggesting that you're\n"
	.string "sick of seeing SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!$"
#endif

SixIsland_WaterPath_Text_SamirDefeat::
#if GERMAN
	.string "Oh, nein!$"
#else
	.string "Oh, no, no, no.$"
#endif

SixIsland_WaterPath_Text_SamirPostBattle::
#if GERMAN
	.string "Ich konnte nicht widerlegen, dass ich\n"
	.string "ein Schwimmer bin…$"
#else
	.string "I couldn't lift the stigma of being\n"
	.string "a SWIMMER…$"
#endif

SixIsland_WaterPath_Text_DeniseIntro::
#if GERMAN
	.string "Mein Freund ist stets sehr beschäftigt,\n"
	.string "daher schwimme ich alleine.$"
#else
	.string "My boyfriend's always busy, so I\n"
	.string "come swimming by myself.$"
#endif

SixIsland_WaterPath_Text_DeniseDefeat::
#if GERMAN
	.string "Ich wusste, das würde passieren!$"
#else
	.string "Awww, I knew this would happen!$"
#endif

SixIsland_WaterPath_Text_DenisePostBattle::
#if GERMAN
	.string "Wenn ich nicht bei meinem Freund sein\n"
	.string "kann, bin ich mit den Pokémon zusammen,\l"
	.string "die er mir gegeben hat.$"
#else
	.string "When I can't be with my boyfriend,\n"
	.string "I spend time with the POKéMON he\l"
	.string "gave me.$"
#endif

SixIsland_WaterPath_Text_EarlIntro::
#if GERMAN
	.string "Sag mir, wo hier in der Gegend\n"
	.string "die Berge sind.$"
#else
	.string "Tell me, where are the mountains\n"
	.string "around these parts?$"
#endif

SixIsland_WaterPath_Text_EarlDefeat::
#if GERMAN
	.string "Ich habe mich verlaufen, als ich\n"
	.string "gekämpft habe.$"
#else
	.string "I lost my way while I was busy\n"
	.string "battling!$"
#endif

SixIsland_WaterPath_Text_EarlPostBattle::
#if GERMAN
	.string "Gibt es in dieser Gegend keine\n"
	.string "Berge?$"
#else
	.string "Aren't there any mountains around\n"
	.string "these parts?$"
#endif

SixIsland_WaterPath_Text_MiuIntro::
#if GERMAN
	.string "Lea: Hallo, Pokémon!\n"
	.string "Zeit zum Spielen!$"
#else
	.string "MIU: Hello, POKéMON!\n"
	.string "It's time to play!$"
#endif

SixIsland_WaterPath_Text_MiuDefeat::
#if GERMAN
	.string "Lea: Oh, nein!\n"
	.string "Mamsi!$"
#else
	.string "MIU: Oh, no!\n"
	.string "Mommy!$"
#endif

SixIsland_WaterPath_Text_MiuPostBattle::
#if GERMAN
	.string "Lea: Eine Niederlage erfüllt mich\n"
	.string "mit Trauer…$"
#else
	.string "MIU: It makes me all sad inside\n"
	.string "when we lose…$"
#endif

SixIsland_WaterPath_Text_MiuNotEnoughMons::
#if GERMAN
	.string "Lea: Mia und ich sind Zwillinge.\n"
	.string "Wir wollen gemeinsam kämpfen.$"
#else
	.string "MIU: MIA and I are TWINS.\n"
	.string "We want to battle together.$"
#endif

SixIsland_WaterPath_Text_MiaIntro::
#if GERMAN
	.string "Mia: Hallo, Pokémon!\n"
	.string "Zeit zum Kämpfen!$"
#else
	.string "MIA: Hello, POKéMON!\n"
	.string "It's time to battle!$"
#endif

SixIsland_WaterPath_Text_MiaDefeat::
#if GERMAN
	.string "Mia: Du bist fies!\n"
	.string "Ein schlechter Gewinner!$"
#else
	.string "MIA: You're mean!\n"
	.string "You're bad for winning!$"
#endif

SixIsland_WaterPath_Text_MiaPostBattle::
#if GERMAN
	.string "Mia: Oh…\n"
	.string "Es tut mir Leid, meine Pokémon…$"
#else
	.string "MIA: Ohh…\n"
	.string "I'm sorry, my POKéMON…$"
#endif

SixIsland_WaterPath_Text_MiaNotEnoughMons::
#if GERMAN
	.string "Mia: Oh, du hast nur ein Pokémon?\p"
	.string "Bist du nicht einsam?$"
#else
	.string "MIA: Oh, you only have one\n"
	.string "POKéMON?\p"
	.string "Don't you feel lonesome?$"
#endif

SixIsland_WaterPath_Text_WantedUltimateHorn::
#if GERMAN
	.string "Gesucht!\n"
	.string "Das Ultimative Horn!$"
#else
	.string "Wanted!\n"
	.string "The Ultimate Horn!$"
#endif

SixIsland_WaterPath_Text_RouteSign::
#if GERMAN
	.string "Wasserweg\n"
	.string "Führt ins Ruinental$"
#else
	.string "WATER PATH\n"
	.string "Leads to RUIN VALLEY$"
#endif

