Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
#if GERMAN
	.string "Du trägst Pokémon bei dir! Lass\n"
	.string "uns kämpfen!$"
#else
	.string "You have POKéMON with you!\n"
	.string "You're mine!$"
#endif

Route9_Text_AliciaDefeat::
#if GERMAN
	.string "Du hast gewonnen!$"
#else
	.string "You deceived me…$"
#endif

Route9_Text_AliciaPostBattle::
#if GERMAN
	.string "Du benötigst eine Lichtquelle, um\n"
	.string "den Tunnel zu durchqueren!$"
#else
	.string "The tunnel coming up is pitch-black\n"
	.string "inside.\p"
	.string "You'll need FLASH to get through\n"
	.string "there.$"
#endif

Route9_Text_ChrisIntro::
#if GERMAN
	.string "Heh, wer bist du?\n"
	.string "Deine Pokémon sehen fit aus!$"
#else
	.string "Who's that walking there with those\n"
	.string "good-looking POKéMON?$"
#endif

Route9_Text_ChrisDefeat::
#if GERMAN
	.string "Schnell und präzise besiegt!$"
#else
	.string "Out like a light!$"
#endif

Route9_Text_ChrisPostBattle::
#if GERMAN
	.string "O.K., geh einfach weiter!$"
#else
	.string "Keep walking!$"
#endif

Route9_Text_DrewIntro::
#if GERMAN
	.string "Ich gehe durch den Felstunnel\n"
	.string "nach Lavandia...$"
#else
	.string "I'm taking the ROCK TUNNEL to\n"
	.string "go to LAVENDER…$"
#endif

Route9_Text_DrewDefeat::
#if GERMAN
	.string "Mit dir habe ich mich übernommen!$"
#else
	.string "Can't measure up…$"
#endif

Route9_Text_DrewPostBattle::
#if GERMAN
	.string "Möchtest du auch den Felstunnel\n"
	.string "benutzen?$"
#else
	.string "Are you off to ROCK TUNNEL, too?$"
#endif

Route9_Text_CaitlinIntro::
#if GERMAN
	.string "Trau dich ruhig, mit mir zu\n"
	.string "kämpfen!$"
#else
	.string "Don't you dare patronize me!$"
#endif

Route9_Text_CaitlinDefeat::
#if GERMAN
	.string "Das war zu viel des Guten!$"
#else
	.string "No!\n"
	.string "You're too much.$"
#endif

Route9_Text_CaitlinPostBattle::
#if GERMAN
	.string "Du hast sehr viel Talent! Viel\n"
	.string "Glück auf deinem weiteren Weg!$"
#else
	.string "You're obviously talented.\n"
	.string "Good luck to you!$"
#endif

Route9_Text_JeremyIntro::
#if GERMAN
	.string "Endlich kommt jemand!\n"
	.string "Mir war richtig langweilig!$"
#else
	.string "Bwahaha!\n"
	.string "Great! I was bored, eh!$"
#endif

Route9_Text_JeremyDefeat::
#if GERMAN
	.string "War das etwa schon alles?\p"
	.string "Oh! Ich habe kein einsatzbereites\n"
	.string "Pokémon übrig!$"
#else
	.string "Keep it coming, eh!\p"
	.string "Oh wait.\n"
	.string "I'm out of POKéMON!$"
#endif

Route9_Text_JeremyPostBattle::
#if GERMAN
	.string "Deine Knie haben ganz schön\n"
	.string "geschlackert, oder?$"
#else
	.string "You sure had guts standing up to\n"
	.string "me there, eh?$"
#endif

Route9_Text_BriceIntro::
#if GERMAN
	.string "Du hast keine Chance, du nerviges\n"
	.string "Balg!$"
#else
	.string "Hahaha!\n"
	.string "Aren't you a little toughie!$"
#endif

Route9_Text_BriceDefeat::
#if GERMAN
	.string "Was ist passiert?$"
#else
	.string "What's that?$"
#endif

Route9_Text_BricePostBattle::
#if GERMAN
	.string "Haha!\n"
	.string "Kinder sollten Hallodris sein!$"
#else
	.string "Hahaha!\n"
	.string "Kids should be tough!$"
#endif

Route9_Text_BrentIntro::
#if GERMAN
	.string "Ich stehe jeden Tag früh auf, um meine\n"
	.string "Pokémon in ihren Kokons zu pflegen!$"
#else
	.string "I got up early every day to raise\n"
	.string "my POKéMON from cocoons!$"
#endif

Route9_Text_BrentDefeat::
#if GERMAN
	.string "Was?\p"
	.string "Das war die reinste\n"
	.string "Zeitverschwendung!$"
#else
	.string "WHAT?\p"
	.string "What a total waste of time!$"
#endif

Route9_Text_BrentPostBattle::
#if GERMAN
	.string "Ich sollte nicht nur Käfer sammeln,\n"
	.string "um stärker zu werden...$"
#else
	.string "I have to collect more than bugs\n"
	.string "to get stronger…$"
#endif

Route9_Text_AlanIntro::
#if GERMAN
	.string "Ha!\n"
	.string "Wie wäre es mit einem Kampf?$"
#else
	.string "Hahahaha!\n"
	.string "Bring it on!$"
#endif

Route9_Text_AlanDefeat::
#if GERMAN
	.string "Haha!\n"
	.string "Ein fairer Kampf!$"
#else
	.string "Hahahaha!\n"
	.string "You beat me fair!$"
#endif

Route9_Text_AlanPostBattle::
#if GERMAN
	.string "Haha!\n"
	.string "Wir Scherzbolde lachen ständig!$"
#else
	.string "Hahahaha!\n"
	.string "Us hearty guys always laugh!$"
#endif

Route9_Text_ConnerIntro::
#if GERMAN
	.string "Du hast keine Chance gegen meine\n"
	.string "Käfer-Pokémon!$"
#else
	.string "Go, my super BUG POKéMON!$"
#endif

Route9_Text_ConnerDefeat::
#if GERMAN
	.string "Meine Käfer-Pokémon...$"
#else
	.string "My bugs…$"
#endif

Route9_Text_ConnerPostBattle::
#if GERMAN
	.string "Wer keine Käfer mag, den mag ich\n"
	.string "auch nicht!$"
#else
	.string "If you don't like BUG POKéMON,\n"
	.string "you bug me!$"
#endif

Route9_Text_RouteSign::
#if GERMAN
	.string "Route 9\n"
	.string "Azuria City - Felstunnel$"
#else
	.string "ROUTE 9\n"
	.string "CERULEAN CITY - ROCK TUNNEL$"
#endif

