#ifndef GUARD_CONSTANTS_FLAGS_HOENN_DE_H
#define GUARD_CONSTANTS_FLAGS_HOENN_DE_H

// =====================================================================
// Smaragd-/Hoenn-Bereich (hns_de / modern_hns_engde)
// flags_hns.h ueberlagert bzw. aliasiert viele Hoenn-Flags mit der
// Kanto-/Johto-Welt. Alle betroffenen Hoenn-Flags liegen hier per
// #undef/#define in einem eigenen Block oberhalb aller HnS-Flags.
// flags_hns.h bleibt unangetastet (Upstream-Mergefaehigkeit).
// Regel: Neue Smaragd-Flags NUR aus diesem Bereich vergeben.
// Hidden Items: Offset zu FLAG_HIDDEN_ITEMS_START ist 13 Bit breit
// (global.fieldmap.h) - dieser Block liegt sicher im Fenster.
// =====================================================================

#define HOENN_FLAGS_START 0x0B72

#undef  FLAG_ARRIVED_AT_MARINE_CAVE_EMERGE_SPOT
#define FLAG_ARRIVED_AT_MARINE_CAVE_EMERGE_SPOT (HOENN_FLAGS_START + 0x000)
#undef  FLAG_ARRIVED_AT_NAVEL_ROCK
#define FLAG_ARRIVED_AT_NAVEL_ROCK (HOENN_FLAGS_START + 0x001)
#undef  FLAG_ARRIVED_ON_FARAWAY_ISLAND
#define FLAG_ARRIVED_ON_FARAWAY_ISLAND (HOENN_FLAGS_START + 0x002)
#undef  FLAG_BEAT_MAGMA_GRUNT_JAGGED_PASS
#define FLAG_BEAT_MAGMA_GRUNT_JAGGED_PASS (HOENN_FLAGS_START + 0x003)
#undef  FLAG_BEAUTY_PAINTING_MADE
#define FLAG_BEAUTY_PAINTING_MADE (HOENN_FLAGS_START + 0x004)
#undef  FLAG_BIRCH_AIDE_MET
#define FLAG_BIRCH_AIDE_MET (HOENN_FLAGS_START + 0x005)
#undef  FLAG_CAUGHT_LATIAS_OR_LATIOS
#define FLAG_CAUGHT_LATIAS_OR_LATIOS (HOENN_FLAGS_START + 0x006)
#undef  FLAG_CHOSE_CLAW_FOSSIL
#define FLAG_CHOSE_CLAW_FOSSIL (HOENN_FLAGS_START + 0x007)
#undef  FLAG_CHOSE_ROOT_FOSSIL
#define FLAG_CHOSE_ROOT_FOSSIL (HOENN_FLAGS_START + 0x008)
#undef  FLAG_CONTEST_SKETCH_CREATED
#define FLAG_CONTEST_SKETCH_CREATED (HOENN_FLAGS_START + 0x009)
#undef  FLAG_COOL_PAINTING_MADE
#define FLAG_COOL_PAINTING_MADE (HOENN_FLAGS_START + 0x00A)
#undef  FLAG_CUTE_PAINTING_MADE
#define FLAG_CUTE_PAINTING_MADE (HOENN_FLAGS_START + 0x00B)
#undef  FLAG_DAILY_BERRY_MASTERS_WIFE
#define FLAG_DAILY_BERRY_MASTERS_WIFE (HOENN_FLAGS_START + 0x00C)
#undef  FLAG_DAILY_BERRY_MASTER_RECEIVED_BERRY
#define FLAG_DAILY_BERRY_MASTER_RECEIVED_BERRY (HOENN_FLAGS_START + 0x00D)
#undef  FLAG_DAILY_FLOWER_SHOP_RECEIVED_BERRY
#define FLAG_DAILY_FLOWER_SHOP_RECEIVED_BERRY (HOENN_FLAGS_START + 0x00E)
#undef  FLAG_DAILY_LILYCOVE_RECEIVED_BERRY
#define FLAG_DAILY_LILYCOVE_RECEIVED_BERRY (HOENN_FLAGS_START + 0x00F)
#undef  FLAG_DAILY_ROUTE_111_RECEIVED_BERRY
#define FLAG_DAILY_ROUTE_111_RECEIVED_BERRY (HOENN_FLAGS_START + 0x010)
#undef  FLAG_DAILY_ROUTE_114_RECEIVED_BERRY
#define FLAG_DAILY_ROUTE_114_RECEIVED_BERRY (HOENN_FLAGS_START + 0x011)
#undef  FLAG_DAILY_ROUTE_120_RECEIVED_BERRY
#define FLAG_DAILY_ROUTE_120_RECEIVED_BERRY (HOENN_FLAGS_START + 0x012)
#undef  FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY
#define FLAG_DAILY_SOOTOPOLIS_RECEIVED_BERRY (HOENN_FLAGS_START + 0x013)
#undef  FLAG_DECLINED_BIKE
#define FLAG_DECLINED_BIKE (HOENN_FLAGS_START + 0x014)
#undef  FLAG_DECLINED_RIVAL_BATTLE_LILYCOVE
#define FLAG_DECLINED_RIVAL_BATTLE_LILYCOVE (HOENN_FLAGS_START + 0x015)
#undef  FLAG_DECLINED_WALLY_BATTLE_MAUVILLE
#define FLAG_DECLINED_WALLY_BATTLE_MAUVILLE (HOENN_FLAGS_START + 0x016)
#undef  FLAG_DEFEATED_DEWFORD_GYM
#define FLAG_DEFEATED_DEWFORD_GYM (HOENN_FLAGS_START + 0x017)
#undef  FLAG_DEFEATED_ELECTRODE_1_AQUA_HIDEOUT
#define FLAG_DEFEATED_ELECTRODE_1_AQUA_HIDEOUT (HOENN_FLAGS_START + 0x018)
#undef  FLAG_DEFEATED_ELECTRODE_2_AQUA_HIDEOUT
#define FLAG_DEFEATED_ELECTRODE_2_AQUA_HIDEOUT (HOENN_FLAGS_START + 0x019)
#undef  FLAG_DEFEATED_ELITE_4_DRAKE
#define FLAG_DEFEATED_ELITE_4_DRAKE (HOENN_FLAGS_START + 0x01A)
#undef  FLAG_DEFEATED_ELITE_4_GLACIA
#define FLAG_DEFEATED_ELITE_4_GLACIA (HOENN_FLAGS_START + 0x01B)
#undef  FLAG_DEFEATED_ELITE_4_PHOEBE
#define FLAG_DEFEATED_ELITE_4_PHOEBE (HOENN_FLAGS_START + 0x01C)
#undef  FLAG_DEFEATED_ELITE_4_SIDNEY
#define FLAG_DEFEATED_ELITE_4_SIDNEY (HOENN_FLAGS_START + 0x01D)
#undef  FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY
#define FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY (HOENN_FLAGS_START + 0x01E)
#undef  FLAG_DEFEATED_FORTREE_GYM
#define FLAG_DEFEATED_FORTREE_GYM (HOENN_FLAGS_START + 0x01F)
#undef  FLAG_DEFEATED_GROUDON
#define FLAG_DEFEATED_GROUDON (HOENN_FLAGS_START + 0x020)
#undef  FLAG_DEFEATED_GRUNT_SPACE_CENTER_1F
#define FLAG_DEFEATED_GRUNT_SPACE_CENTER_1F (HOENN_FLAGS_START + 0x021)
#undef  FLAG_DEFEATED_KYOGRE
#define FLAG_DEFEATED_KYOGRE (HOENN_FLAGS_START + 0x022)
#undef  FLAG_DEFEATED_LATIAS_OR_LATIOS
#define FLAG_DEFEATED_LATIAS_OR_LATIOS (HOENN_FLAGS_START + 0x023)
#undef  FLAG_DEFEATED_LAVARIDGE_GYM
#define FLAG_DEFEATED_LAVARIDGE_GYM (HOENN_FLAGS_START + 0x024)
#undef  FLAG_DEFEATED_MAGMA_SPACE_CENTER
#define FLAG_DEFEATED_MAGMA_SPACE_CENTER (HOENN_FLAGS_START + 0x025)
#undef  FLAG_DEFEATED_MAUVILLE_GYM
#define FLAG_DEFEATED_MAUVILLE_GYM (HOENN_FLAGS_START + 0x026)
#undef  FLAG_DEFEATED_METEOR_FALLS_STEVEN
#define FLAG_DEFEATED_METEOR_FALLS_STEVEN (HOENN_FLAGS_START + 0x027)
#undef  FLAG_DEFEATED_MOSSDEEP_GYM
#define FLAG_DEFEATED_MOSSDEEP_GYM (HOENN_FLAGS_START + 0x028)
#undef  FLAG_DEFEATED_PETALBURG_GYM
#define FLAG_DEFEATED_PETALBURG_GYM (HOENN_FLAGS_START + 0x029)
#undef  FLAG_DEFEATED_RAYQUAZA
#define FLAG_DEFEATED_RAYQUAZA (HOENN_FLAGS_START + 0x02A)
#undef  FLAG_DEFEATED_REGICE
#define FLAG_DEFEATED_REGICE (HOENN_FLAGS_START + 0x02B)
#undef  FLAG_DEFEATED_REGIROCK
#define FLAG_DEFEATED_REGIROCK (HOENN_FLAGS_START + 0x02C)
#undef  FLAG_DEFEATED_REGISTEEL
#define FLAG_DEFEATED_REGISTEEL (HOENN_FLAGS_START + 0x02D)
#undef  FLAG_DEFEATED_RIVAL_ROUTE103
#define FLAG_DEFEATED_RIVAL_ROUTE103 (HOENN_FLAGS_START + 0x02E)
#undef  FLAG_DEFEATED_RIVAL_ROUTE_104
#define FLAG_DEFEATED_RIVAL_ROUTE_104 (HOENN_FLAGS_START + 0x02F)
#undef  FLAG_DEFEATED_RIVAL_RUSTBORO
#define FLAG_DEFEATED_RIVAL_RUSTBORO (HOENN_FLAGS_START + 0x030)
#undef  FLAG_DEFEATED_RUSTBORO_GYM
#define FLAG_DEFEATED_RUSTBORO_GYM (HOENN_FLAGS_START + 0x031)
#undef  FLAG_DEFEATED_SEASHORE_HOUSE
#define FLAG_DEFEATED_SEASHORE_HOUSE (HOENN_FLAGS_START + 0x032)
#undef  FLAG_DEFEATED_SOOTOPOLIS_GYM
#define FLAG_DEFEATED_SOOTOPOLIS_GYM (HOENN_FLAGS_START + 0x033)
#undef  FLAG_DEFEATED_SS_TIDAL_TRAINERS
#define FLAG_DEFEATED_SS_TIDAL_TRAINERS (HOENN_FLAGS_START + 0x034)
#undef  FLAG_DEFEATED_VOLTORB_1_NEW_MAUVILLE
#define FLAG_DEFEATED_VOLTORB_1_NEW_MAUVILLE (HOENN_FLAGS_START + 0x035)
#undef  FLAG_DEFEATED_VOLTORB_2_NEW_MAUVILLE
#define FLAG_DEFEATED_VOLTORB_2_NEW_MAUVILLE (HOENN_FLAGS_START + 0x036)
#undef  FLAG_DEFEATED_VOLTORB_3_NEW_MAUVILLE
#define FLAG_DEFEATED_VOLTORB_3_NEW_MAUVILLE (HOENN_FLAGS_START + 0x037)
#undef  FLAG_DEFEATED_WALLY_MAUVILLE
#define FLAG_DEFEATED_WALLY_MAUVILLE (HOENN_FLAGS_START + 0x038)
#undef  FLAG_DEFEATED_WALLY_VICTORY_ROAD
#define FLAG_DEFEATED_WALLY_VICTORY_ROAD (HOENN_FLAGS_START + 0x039)
#undef  FLAG_DELIVERED_DEVON_GOODS
#define FLAG_DELIVERED_DEVON_GOODS (HOENN_FLAGS_START + 0x03A)
#undef  FLAG_DELIVERED_STEVEN_LETTER
#define FLAG_DELIVERED_STEVEN_LETTER (HOENN_FLAGS_START + 0x03B)
#undef  FLAG_DEVON_GOODS_STOLEN
#define FLAG_DEVON_GOODS_STOLEN (HOENN_FLAGS_START + 0x03C)
#undef  FLAG_DOCK_REJECTED_DEVON_GOODS
#define FLAG_DOCK_REJECTED_DEVON_GOODS (HOENN_FLAGS_START + 0x03D)
#undef  FLAG_ENABLE_BRAWLY_MATCH_CALL
#define FLAG_ENABLE_BRAWLY_MATCH_CALL (HOENN_FLAGS_START + 0x03E)
#undef  FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL
#define FLAG_ENABLE_FIRST_WALLY_POKENAV_CALL (HOENN_FLAGS_START + 0x03F)
#undef  FLAG_ENABLE_FLANNERY_MATCH_CALL
#define FLAG_ENABLE_FLANNERY_MATCH_CALL (HOENN_FLAGS_START + 0x040)
#undef  FLAG_ENABLE_JUAN_MATCH_CALL
#define FLAG_ENABLE_JUAN_MATCH_CALL (HOENN_FLAGS_START + 0x041)
#undef  FLAG_ENABLE_NORMAN_MATCH_CALL
#define FLAG_ENABLE_NORMAN_MATCH_CALL (HOENN_FLAGS_START + 0x042)
#undef  FLAG_ENABLE_RIVAL_MATCH_CALL
#define FLAG_ENABLE_RIVAL_MATCH_CALL (HOENN_FLAGS_START + 0x043)
#undef  FLAG_ENABLE_ROXANNE_FIRST_CALL
#define FLAG_ENABLE_ROXANNE_FIRST_CALL (HOENN_FLAGS_START + 0x044)
#undef  FLAG_ENABLE_ROXANNE_MATCH_CALL
#define FLAG_ENABLE_ROXANNE_MATCH_CALL (HOENN_FLAGS_START + 0x045)
#undef  FLAG_ENABLE_SCOTT_MATCH_CALL
#define FLAG_ENABLE_SCOTT_MATCH_CALL (HOENN_FLAGS_START + 0x046)
#undef  FLAG_ENABLE_SHIP_BIRTH_ISLAND
#define FLAG_ENABLE_SHIP_BIRTH_ISLAND (HOENN_FLAGS_START + 0x047)
#undef  FLAG_ENABLE_SHIP_FARAWAY_ISLAND
#define FLAG_ENABLE_SHIP_FARAWAY_ISLAND (HOENN_FLAGS_START + 0x048)
#undef  FLAG_ENABLE_SHIP_NAVEL_ROCK
#define FLAG_ENABLE_SHIP_NAVEL_ROCK (HOENN_FLAGS_START + 0x049)
#undef  FLAG_ENABLE_SHIP_SOUTHERN_ISLAND
#define FLAG_ENABLE_SHIP_SOUTHERN_ISLAND (HOENN_FLAGS_START + 0x04A)
#undef  FLAG_ENABLE_TATE_AND_LIZA_MATCH_CALL
#define FLAG_ENABLE_TATE_AND_LIZA_MATCH_CALL (HOENN_FLAGS_START + 0x04B)
#undef  FLAG_ENABLE_WALLY_MATCH_CALL
#define FLAG_ENABLE_WALLY_MATCH_CALL (HOENN_FLAGS_START + 0x04C)
#undef  FLAG_ENABLE_WATTSON_MATCH_CALL
#define FLAG_ENABLE_WATTSON_MATCH_CALL (HOENN_FLAGS_START + 0x04D)
#undef  FLAG_ENABLE_WINONA_MATCH_CALL
#define FLAG_ENABLE_WINONA_MATCH_CALL (HOENN_FLAGS_START + 0x04E)
#undef  FLAG_ENCOUNTERED_LATIAS_OR_LATIOS
#define FLAG_ENCOUNTERED_LATIAS_OR_LATIOS (HOENN_FLAGS_START + 0x04F)
#undef  FLAG_ENTERED_CONTEST
#define FLAG_ENTERED_CONTEST (HOENN_FLAGS_START + 0x050)
#undef  FLAG_ENTERED_ELITE_FOUR
#define FLAG_ENTERED_ELITE_FOUR (HOENN_FLAGS_START + 0x051)
#undef  FLAG_ENTERED_MIRAGE_TOWER
#define FLAG_ENTERED_MIRAGE_TOWER (HOENN_FLAGS_START + 0x052)
#undef  FLAG_EVIL_LEADER_PLEASE_STOP
#define FLAG_EVIL_LEADER_PLEASE_STOP (HOENN_FLAGS_START + 0x053)
#undef  FLAG_EVIL_TEAM_ESCAPED_STERN_SPOKE
#define FLAG_EVIL_TEAM_ESCAPED_STERN_SPOKE (HOENN_FLAGS_START + 0x054)
#undef  FLAG_EXCHANGED_SCANNER
#define FLAG_EXCHANGED_SCANNER (HOENN_FLAGS_START + 0x055)
#undef  FLAG_FAN_CLUB_STRENGTH_SHARED
#define FLAG_FAN_CLUB_STRENGTH_SHARED (HOENN_FLAGS_START + 0x056)
#undef  FLAG_FORCE_MIRAGE_TOWER_VISIBLE
#define FLAG_FORCE_MIRAGE_TOWER_VISIBLE (HOENN_FLAGS_START + 0x057)
#undef  FLAG_FORTREE_NPC_TRADE_COMPLETED
#define FLAG_FORTREE_NPC_TRADE_COMPLETED (HOENN_FLAGS_START + 0x058)
#undef  FLAG_GOT_BASEMENT_KEY_FROM_WATTSON
#define FLAG_GOT_BASEMENT_KEY_FROM_WATTSON (HOENN_FLAGS_START + 0x059)
#undef  FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON
#define FLAG_GOT_TM_THUNDERBOLT_FROM_WATTSON (HOENN_FLAGS_START + 0x05A)
#undef  FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT
#define FLAG_GROUDON_AWAKENED_MAGMA_HIDEOUT (HOENN_FLAGS_START + 0x05B)
#undef  FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_1_KEY
#define FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_1_KEY (HOENN_FLAGS_START + 0x05C)
#undef  FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_2_KEY
#define FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_2_KEY (HOENN_FLAGS_START + 0x05D)
#undef  FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_4_KEY
#define FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_4_KEY (HOENN_FLAGS_START + 0x05E)
#undef  FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_6_KEY
#define FLAG_HIDDEN_ITEM_ABANDONED_SHIP_RM_6_KEY (HOENN_FLAGS_START + 0x05F)
#undef  FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_CALCIUM
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_CALCIUM (HOENN_FLAGS_START + 0x060)
#undef  FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_IRON
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_IRON (HOENN_FLAGS_START + 0x061)
#undef  FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_PROTEIN
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_PROTEIN (HOENN_FLAGS_START + 0x062)
#undef  FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_ZINC
#define FLAG_HIDDEN_ITEM_ARTISAN_CAVE_B1F_ZINC (HOENN_FLAGS_START + 0x063)
#undef  FLAG_HIDDEN_ITEM_FALLARBOR_TOWN_NUGGET
#define FLAG_HIDDEN_ITEM_FALLARBOR_TOWN_NUGGET (HOENN_FLAGS_START + 0x064)
#undef  FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_1
#define FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_1 (HOENN_FLAGS_START + 0x065)
#undef  FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_2
#define FLAG_HIDDEN_ITEM_GRANITE_CAVE_B2F_EVERSTONE_2 (HOENN_FLAGS_START + 0x066)
#undef  FLAG_HIDDEN_ITEM_JAGGED_PASS_FULL_HEAL
#define FLAG_HIDDEN_ITEM_JAGGED_PASS_FULL_HEAL (HOENN_FLAGS_START + 0x067)
#undef  FLAG_HIDDEN_ITEM_JAGGED_PASS_GREAT_BALL
#define FLAG_HIDDEN_ITEM_JAGGED_PASS_GREAT_BALL (HOENN_FLAGS_START + 0x068)
#undef  FLAG_HIDDEN_ITEM_LAVARIDGE_TOWN_ICE_HEAL
#define FLAG_HIDDEN_ITEM_LAVARIDGE_TOWN_ICE_HEAL (HOENN_FLAGS_START + 0x069)
#undef  FLAG_HIDDEN_ITEM_LILYCOVE_CITY_HEART_SCALE
#define FLAG_HIDDEN_ITEM_LILYCOVE_CITY_HEART_SCALE (HOENN_FLAGS_START + 0x06A)
#undef  FLAG_HIDDEN_ITEM_LILYCOVE_CITY_POKE_BALL
#define FLAG_HIDDEN_ITEM_LILYCOVE_CITY_POKE_BALL (HOENN_FLAGS_START + 0x06B)
#undef  FLAG_HIDDEN_ITEM_LILYCOVE_CITY_PP_UP
#define FLAG_HIDDEN_ITEM_LILYCOVE_CITY_PP_UP (HOENN_FLAGS_START + 0x06C)
#undef  FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_MAX_ETHER
#define FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_MAX_ETHER (HOENN_FLAGS_START + 0x06D)
#undef  FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_MT_PYRE_EXTERIOR_ULTRA_BALL (HOENN_FLAGS_START + 0x06E)
#undef  FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_RARE_CANDY
#define FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_RARE_CANDY (HOENN_FLAGS_START + 0x06F)
#undef  FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_ZINC
#define FLAG_HIDDEN_ITEM_MT_PYRE_SUMMIT_ZINC (HOENN_FLAGS_START + 0x070)
#undef  FLAG_HIDDEN_ITEM_NAVEL_ROCK_TOP_SACRED_ASH
#define FLAG_HIDDEN_ITEM_NAVEL_ROCK_TOP_SACRED_ASH (HOENN_FLAGS_START + 0x071)
#undef  FLAG_HIDDEN_ITEM_PETALBURG_CITY_RARE_CANDY
#define FLAG_HIDDEN_ITEM_PETALBURG_CITY_RARE_CANDY (HOENN_FLAGS_START + 0x072)
#undef  FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POKE_BALL
#define FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POKE_BALL (HOENN_FLAGS_START + 0x073)
#undef  FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POTION
#define FLAG_HIDDEN_ITEM_PETALBURG_WOODS_POTION (HOENN_FLAGS_START + 0x074)
#undef  FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_1
#define FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_1 (HOENN_FLAGS_START + 0x075)
#undef  FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_2
#define FLAG_HIDDEN_ITEM_PETALBURG_WOODS_TINY_MUSHROOM_2 (HOENN_FLAGS_START + 0x076)
#undef  FLAG_HIDDEN_ITEM_ROUTE_104_ANTIDOTE
#define FLAG_HIDDEN_ITEM_ROUTE_104_ANTIDOTE (HOENN_FLAGS_START + 0x077)
#undef  FLAG_HIDDEN_ITEM_ROUTE_104_HEART_SCALE
#define FLAG_HIDDEN_ITEM_ROUTE_104_HEART_SCALE (HOENN_FLAGS_START + 0x078)
#undef  FLAG_HIDDEN_ITEM_ROUTE_104_POKE_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_104_POKE_BALL (HOENN_FLAGS_START + 0x079)
#undef  FLAG_HIDDEN_ITEM_ROUTE_104_POTION
#define FLAG_HIDDEN_ITEM_ROUTE_104_POTION (HOENN_FLAGS_START + 0x07A)
#undef  FLAG_HIDDEN_ITEM_ROUTE_104_SUPER_POTION
#define FLAG_HIDDEN_ITEM_ROUTE_104_SUPER_POTION (HOENN_FLAGS_START + 0x07B)
#undef  FLAG_HIDDEN_ITEM_ROUTE_105_BIG_PEARL
#define FLAG_HIDDEN_ITEM_ROUTE_105_BIG_PEARL (HOENN_FLAGS_START + 0x07C)
#undef  FLAG_HIDDEN_ITEM_ROUTE_105_HEART_SCALE
#define FLAG_HIDDEN_ITEM_ROUTE_105_HEART_SCALE (HOENN_FLAGS_START + 0x07D)
#undef  FLAG_HIDDEN_ITEM_ROUTE_106_HEART_SCALE
#define FLAG_HIDDEN_ITEM_ROUTE_106_HEART_SCALE (HOENN_FLAGS_START + 0x07E)
#undef  FLAG_HIDDEN_ITEM_ROUTE_106_POKE_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_106_POKE_BALL (HOENN_FLAGS_START + 0x07F)
#undef  FLAG_HIDDEN_ITEM_ROUTE_106_STARDUST
#define FLAG_HIDDEN_ITEM_ROUTE_106_STARDUST (HOENN_FLAGS_START + 0x080)
#undef  FLAG_HIDDEN_ITEM_ROUTE_108_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE_108_RARE_CANDY (HOENN_FLAGS_START + 0x081)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE_109_ETHER (HOENN_FLAGS_START + 0x082)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_GREAT_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_109_GREAT_BALL (HOENN_FLAGS_START + 0x083)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_1
#define FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_1 (HOENN_FLAGS_START + 0x084)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_2
#define FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_2 (HOENN_FLAGS_START + 0x085)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_3
#define FLAG_HIDDEN_ITEM_ROUTE_109_HEART_SCALE_3 (HOENN_FLAGS_START + 0x086)
#undef  FLAG_HIDDEN_ITEM_ROUTE_109_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_109_REVIVE (HOENN_FLAGS_START + 0x087)
#undef  FLAG_HIDDEN_ITEM_ROUTE_110_FULL_HEAL
#define FLAG_HIDDEN_ITEM_ROUTE_110_FULL_HEAL (HOENN_FLAGS_START + 0x088)
#undef  FLAG_HIDDEN_ITEM_ROUTE_110_GREAT_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_110_GREAT_BALL (HOENN_FLAGS_START + 0x089)
#undef  FLAG_HIDDEN_ITEM_ROUTE_110_POKE_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_110_POKE_BALL (HOENN_FLAGS_START + 0x08A)
#undef  FLAG_HIDDEN_ITEM_ROUTE_110_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_110_REVIVE (HOENN_FLAGS_START + 0x08B)
#undef  FLAG_HIDDEN_ITEM_ROUTE_111_PROTEIN
#define FLAG_HIDDEN_ITEM_ROUTE_111_PROTEIN (HOENN_FLAGS_START + 0x08C)
#undef  FLAG_HIDDEN_ITEM_ROUTE_111_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE_111_RARE_CANDY (HOENN_FLAGS_START + 0x08D)
#undef  FLAG_HIDDEN_ITEM_ROUTE_111_STARDUST
#define FLAG_HIDDEN_ITEM_ROUTE_111_STARDUST (HOENN_FLAGS_START + 0x08E)
#undef  FLAG_HIDDEN_ITEM_ROUTE_113_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE_113_ETHER (HOENN_FLAGS_START + 0x08F)
#undef  FLAG_HIDDEN_ITEM_ROUTE_113_NUGGET
#define FLAG_HIDDEN_ITEM_ROUTE_113_NUGGET (HOENN_FLAGS_START + 0x090)
#undef  FLAG_HIDDEN_ITEM_ROUTE_113_TM_DOUBLE_TEAM
#define FLAG_HIDDEN_ITEM_ROUTE_113_TM_DOUBLE_TEAM (HOENN_FLAGS_START + 0x091)
#undef  FLAG_HIDDEN_ITEM_ROUTE_114_CARBOS
#define FLAG_HIDDEN_ITEM_ROUTE_114_CARBOS (HOENN_FLAGS_START + 0x092)
#undef  FLAG_HIDDEN_ITEM_ROUTE_114_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_114_REVIVE (HOENN_FLAGS_START + 0x093)
#undef  FLAG_HIDDEN_ITEM_ROUTE_115_HEART_SCALE
#define FLAG_HIDDEN_ITEM_ROUTE_115_HEART_SCALE (HOENN_FLAGS_START + 0x094)
#undef  FLAG_HIDDEN_ITEM_ROUTE_116_BLACK_GLASSES
#define FLAG_HIDDEN_ITEM_ROUTE_116_BLACK_GLASSES (HOENN_FLAGS_START + 0x095)
#undef  FLAG_HIDDEN_ITEM_ROUTE_116_SUPER_POTION
#define FLAG_HIDDEN_ITEM_ROUTE_116_SUPER_POTION (HOENN_FLAGS_START + 0x096)
#undef  FLAG_HIDDEN_ITEM_ROUTE_117_REPEL
#define FLAG_HIDDEN_ITEM_ROUTE_117_REPEL (HOENN_FLAGS_START + 0x097)
#undef  FLAG_HIDDEN_ITEM_ROUTE_118_HEART_SCALE
#define FLAG_HIDDEN_ITEM_ROUTE_118_HEART_SCALE (HOENN_FLAGS_START + 0x098)
#undef  FLAG_HIDDEN_ITEM_ROUTE_118_IRON
#define FLAG_HIDDEN_ITEM_ROUTE_118_IRON (HOENN_FLAGS_START + 0x099)
#undef  FLAG_HIDDEN_ITEM_ROUTE_119_CALCIUM
#define FLAG_HIDDEN_ITEM_ROUTE_119_CALCIUM (HOENN_FLAGS_START + 0x09A)
#undef  FLAG_HIDDEN_ITEM_ROUTE_119_FULL_HEAL
#define FLAG_HIDDEN_ITEM_ROUTE_119_FULL_HEAL (HOENN_FLAGS_START + 0x09B)
#undef  FLAG_HIDDEN_ITEM_ROUTE_119_MAX_ETHER
#define FLAG_HIDDEN_ITEM_ROUTE_119_MAX_ETHER (HOENN_FLAGS_START + 0x09C)
#undef  FLAG_HIDDEN_ITEM_ROUTE_119_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_ROUTE_119_ULTRA_BALL (HOENN_FLAGS_START + 0x09D)
#undef  FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_1
#define FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_1 (HOENN_FLAGS_START + 0x09E)
#undef  FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_2
#define FLAG_HIDDEN_ITEM_ROUTE_120_RARE_CANDY_2 (HOENN_FLAGS_START + 0x09F)
#undef  FLAG_HIDDEN_ITEM_ROUTE_120_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_120_REVIVE (HOENN_FLAGS_START + 0x0A0)
#undef  FLAG_HIDDEN_ITEM_ROUTE_120_ZINC
#define FLAG_HIDDEN_ITEM_ROUTE_120_ZINC (HOENN_FLAGS_START + 0x0A1)
#undef  FLAG_HIDDEN_ITEM_ROUTE_121_FULL_HEAL
#define FLAG_HIDDEN_ITEM_ROUTE_121_FULL_HEAL (HOENN_FLAGS_START + 0x0A2)
#undef  FLAG_HIDDEN_ITEM_ROUTE_121_HP_UP
#define FLAG_HIDDEN_ITEM_ROUTE_121_HP_UP (HOENN_FLAGS_START + 0x0A3)
#undef  FLAG_HIDDEN_ITEM_ROUTE_121_MAX_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_121_MAX_REVIVE (HOENN_FLAGS_START + 0x0A4)
#undef  FLAG_HIDDEN_ITEM_ROUTE_121_NUGGET
#define FLAG_HIDDEN_ITEM_ROUTE_121_NUGGET (HOENN_FLAGS_START + 0x0A5)
#undef  FLAG_HIDDEN_ITEM_ROUTE_123_HYPER_POTION
#define FLAG_HIDDEN_ITEM_ROUTE_123_HYPER_POTION (HOENN_FLAGS_START + 0x0A6)
#undef  FLAG_HIDDEN_ITEM_ROUTE_123_PP_UP
#define FLAG_HIDDEN_ITEM_ROUTE_123_PP_UP (HOENN_FLAGS_START + 0x0A7)
#undef  FLAG_HIDDEN_ITEM_ROUTE_123_RARE_CANDY
#define FLAG_HIDDEN_ITEM_ROUTE_123_RARE_CANDY (HOENN_FLAGS_START + 0x0A8)
#undef  FLAG_HIDDEN_ITEM_ROUTE_123_REVIVE
#define FLAG_HIDDEN_ITEM_ROUTE_123_REVIVE (HOENN_FLAGS_START + 0x0A9)
#undef  FLAG_HIDDEN_ITEM_ROUTE_123_SUPER_REPEL
#define FLAG_HIDDEN_ITEM_ROUTE_123_SUPER_REPEL (HOENN_FLAGS_START + 0x0AA)
#undef  FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_1
#define FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_1 (HOENN_FLAGS_START + 0x0AB)
#undef  FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_2
#define FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_2 (HOENN_FLAGS_START + 0x0AC)
#undef  FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_3
#define FLAG_HIDDEN_ITEM_ROUTE_128_HEART_SCALE_3 (HOENN_FLAGS_START + 0x0AD)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_RARE_CANDY
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_RARE_CANDY (HOENN_FLAGS_START + 0x0AE)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_ZINC
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_NORTH_EAST_ZINC (HOENN_FLAGS_START + 0x0AF)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_FULL_RESTORE
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_FULL_RESTORE (HOENN_FLAGS_START + 0x0B0)
#undef  FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_PP_UP
#define FLAG_HIDDEN_ITEM_SAFARI_ZONE_SOUTH_EAST_PP_UP (HOENN_FLAGS_START + 0x0B1)
#undef  FLAG_HIDDEN_ITEM_SS_TIDAL_LOWER_DECK_LEFTOVERS
#define FLAG_HIDDEN_ITEM_SS_TIDAL_LOWER_DECK_LEFTOVERS (HOENN_FLAGS_START + 0x0B2)
#undef  FLAG_HIDDEN_ITEM_TRICK_HOUSE_NUGGET
#define FLAG_HIDDEN_ITEM_TRICK_HOUSE_NUGGET (HOENN_FLAGS_START + 0x0B3)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_BIG_PEARL
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_BIG_PEARL (HOENN_FLAGS_START + 0x0B4)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_CALCIUM
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_CALCIUM (HOENN_FLAGS_START + 0x0B5)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_CARBOS
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_CARBOS (HOENN_FLAGS_START + 0x0B6)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_GREEN_SHARD
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_GREEN_SHARD (HOENN_FLAGS_START + 0x0B7)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_1
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_1 (HOENN_FLAGS_START + 0x0B8)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_2
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_HEART_SCALE_2 (HOENN_FLAGS_START + 0x0B9)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_124_PEARL
#define FLAG_HIDDEN_ITEM_UNDERWATER_124_PEARL (HOENN_FLAGS_START + 0x0BA)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_BIG_PEARL
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_BIG_PEARL (HOENN_FLAGS_START + 0x0BB)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_BLUE_SHARD
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_BLUE_SHARD (HOENN_FLAGS_START + 0x0BC)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_HEART_SCALE
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_HEART_SCALE (HOENN_FLAGS_START + 0x0BD)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_IRON
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_IRON (HOENN_FLAGS_START + 0x0BE)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_PEARL
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_PEARL (HOENN_FLAGS_START + 0x0BF)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_STARDUST
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_STARDUST (HOENN_FLAGS_START + 0x0C0)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_ULTRA_BALL (HOENN_FLAGS_START + 0x0C1)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_126_YELLOW_SHARD
#define FLAG_HIDDEN_ITEM_UNDERWATER_126_YELLOW_SHARD (HOENN_FLAGS_START + 0x0C2)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_127_HEART_SCALE
#define FLAG_HIDDEN_ITEM_UNDERWATER_127_HEART_SCALE (HOENN_FLAGS_START + 0x0C3)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_127_HP_UP
#define FLAG_HIDDEN_ITEM_UNDERWATER_127_HP_UP (HOENN_FLAGS_START + 0x0C4)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_127_RED_SHARD
#define FLAG_HIDDEN_ITEM_UNDERWATER_127_RED_SHARD (HOENN_FLAGS_START + 0x0C5)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_127_STAR_PIECE
#define FLAG_HIDDEN_ITEM_UNDERWATER_127_STAR_PIECE (HOENN_FLAGS_START + 0x0C6)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_128_PEARL
#define FLAG_HIDDEN_ITEM_UNDERWATER_128_PEARL (HOENN_FLAGS_START + 0x0C7)
#undef  FLAG_HIDDEN_ITEM_UNDERWATER_128_PROTEIN
#define FLAG_HIDDEN_ITEM_UNDERWATER_128_PROTEIN (HOENN_FLAGS_START + 0x0C8)
#undef  FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL (HOENN_FLAGS_START + 0x0C9)
#undef  FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_ELIXIR
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_ELIXIR (HOENN_FLAGS_START + 0x0CA)
#undef  FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_MAX_REPEL
#define FLAG_HIDDEN_ITEM_VICTORY_ROAD_B2F_MAX_REPEL (HOENN_FLAGS_START + 0x0CB)
#undef  FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_1_BLOCKING_ENTRANCE
#define FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_1_BLOCKING_ENTRANCE (HOENN_FLAGS_START + 0x0CC)
#undef  FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_2_BLOCKING_ENTRANCE
#define FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_2_BLOCKING_ENTRANCE (HOENN_FLAGS_START + 0x0CD)
#undef  FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_1
#define FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_1 (HOENN_FLAGS_START + 0x0CE)
#undef  FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_2
#define FLAG_HIDE_AQUA_HIDEOUT_B1F_ELECTRODE_2 (HOENN_FLAGS_START + 0x0CF)
#undef  FLAG_HIDE_AQUA_HIDEOUT_GRUNTS
#define FLAG_HIDE_AQUA_HIDEOUT_GRUNTS (HOENN_FLAGS_START + 0x0D0)
#undef  FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY
#define FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY (HOENN_FLAGS_START + 0x0D1)
#undef  FLAG_HIDE_BRINEYS_HOUSE_PEEKO
#define FLAG_HIDE_BRINEYS_HOUSE_PEEKO (HOENN_FLAGS_START + 0x0D2)
#undef  FLAG_HIDE_CONTEST_POKE_BALL
#define FLAG_HIDE_CONTEST_POKE_BALL (HOENN_FLAGS_START + 0x0D3)
#undef  FLAG_HIDE_DESERT_UNDERPASS_FOSSIL
#define FLAG_HIDE_DESERT_UNDERPASS_FOSSIL (HOENN_FLAGS_START + 0x0D4)
#undef  FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN
#define FLAG_HIDE_DEWFORD_HALL_SLUDGE_BOMB_MAN (HOENN_FLAGS_START + 0x0D5)
#undef  FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT
#define FLAG_HIDE_EVER_GRANDE_POKEMON_CENTER_1F_SCOTT (HOENN_FLAGS_START + 0x0D6)
#undef  FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO
#define FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO (HOENN_FLAGS_START + 0x0D7)
#undef  FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT
#define FLAG_HIDE_FALLARBOR_TOWN_BATTLE_TENT_SCOTT (HOENN_FLAGS_START + 0x0D8)
#undef  FLAG_HIDE_FANCLUB_LADY
#define FLAG_HIDE_FANCLUB_LADY (HOENN_FLAGS_START + 0x0D9)
#undef  FLAG_HIDE_FANCLUB_LITTLE_BOY
#define FLAG_HIDE_FANCLUB_LITTLE_BOY (HOENN_FLAGS_START + 0x0DA)
#undef  FLAG_HIDE_FORTREE_CITY_HOUSE_4_WINGULL
#define FLAG_HIDE_FORTREE_CITY_HOUSE_4_WINGULL (HOENN_FLAGS_START + 0x0DB)
#undef  FLAG_HIDE_JAGGED_PASS_MAGMA_GUARD
#define FLAG_HIDE_JAGGED_PASS_MAGMA_GUARD (HOENN_FLAGS_START + 0x0DC)
#undef  FLAG_HIDE_LANETTES_HOUSE_LANETTE
#define FLAG_HIDE_LANETTES_HOUSE_LANETTE (HOENN_FLAGS_START + 0x0DD)
#undef  FLAG_HIDE_LAVARIDGE_TOWN_RIVAL
#define FLAG_HIDE_LAVARIDGE_TOWN_RIVAL (HOENN_FLAGS_START + 0x0DE)
#undef  FLAG_HIDE_LILYCOVE_CITY_AQUA_GRUNTS
#define FLAG_HIDE_LILYCOVE_CITY_AQUA_GRUNTS (HOENN_FLAGS_START + 0x0DF)
#undef  FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER
#define FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER (HOENN_FLAGS_START + 0x0E0)
#undef  FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER_REPLACEMENT
#define FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER_REPLACEMENT (HOENN_FLAGS_START + 0x0E1)
#undef  FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1
#define FLAG_HIDE_LILYCOVE_CONTEST_HALL_CONTEST_ATTENDANT_1 (HOENN_FLAGS_START + 0x0E2)
#undef  FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER
#define FLAG_HIDE_LILYCOVE_CONTEST_HALL_REPORTER (HOENN_FLAGS_START + 0x0E3)
#undef  FLAG_HIDE_LILYCOVE_DEPARTMENT_STORE_ROOFTOP_SALE_WOMAN
#define FLAG_HIDE_LILYCOVE_DEPARTMENT_STORE_ROOFTOP_SALE_WOMAN (HOENN_FLAGS_START + 0x0E4)
#undef  FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER
#define FLAG_HIDE_LILYCOVE_FAN_CLUB_INTERVIEWER (HOENN_FLAGS_START + 0x0E5)
#undef  FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER
#define FLAG_HIDE_LILYCOVE_HARBOR_EVENT_TICKET_TAKER (HOENN_FLAGS_START + 0x0E6)
#undef  FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR
#define FLAG_HIDE_LILYCOVE_HARBOR_FERRY_SAILOR (HOENN_FLAGS_START + 0x0E7)
#undef  FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL
#define FLAG_HIDE_LILYCOVE_HARBOR_SSTIDAL (HOENN_FLAGS_START + 0x0E8)
#undef  FLAG_HIDE_LILYCOVE_MOTEL_SCOTT
#define FLAG_HIDE_LILYCOVE_MOTEL_SCOTT (HOENN_FLAGS_START + 0x0E9)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_CURATOR
#define FLAG_HIDE_LILYCOVE_MUSEUM_CURATOR (HOENN_FLAGS_START + 0x0EA)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1
#define FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_1 (HOENN_FLAGS_START + 0x0EB)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2
#define FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_2 (HOENN_FLAGS_START + 0x0EC)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3
#define FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_3 (HOENN_FLAGS_START + 0x0ED)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4
#define FLAG_HIDE_LILYCOVE_MUSEUM_PATRON_4 (HOENN_FLAGS_START + 0x0EE)
#undef  FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS
#define FLAG_HIDE_LILYCOVE_MUSEUM_TOURISTS (HOENN_FLAGS_START + 0x0EF)
#undef  FLAG_HIDE_LILYCOVE_POKEMON_CENTER_CONTEST_LADY_MON
#define FLAG_HIDE_LILYCOVE_POKEMON_CENTER_CONTEST_LADY_MON (HOENN_FLAGS_START + 0x0F0)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCH
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCH (HOENN_FLAGS_START + 0x0F1)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_BIRCH (HOENN_FLAGS_START + 0x0F2)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CHIKORITA (HOENN_FLAGS_START + 0x0F3)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_CYNDAQUIL (HOENN_FLAGS_START + 0x0F4)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_POKEBALL_TOTODILE (HOENN_FLAGS_START + 0x0F5)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL
#define FLAG_HIDE_LITTLEROOT_TOWN_BIRCHS_LAB_RIVAL (HOENN_FLAGS_START + 0x0F6)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL (HOENN_FLAGS_START + 0x0F7)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_SWABLU_DOLL (HOENN_FLAGS_START + 0x0F8)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_BRENDAN (HOENN_FLAGS_START + 0x0F9)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_MOM (HOENN_FLAGS_START + 0x0FA)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM (HOENN_FLAGS_START + 0x0FB)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_MOM (HOENN_FLAGS_START + 0x0FC)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_SIBLING (HOENN_FLAGS_START + 0x0FD)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK
#define FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_TRUCK (HOENN_FLAGS_START + 0x0FE)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN
#define FLAG_HIDE_LITTLEROOT_TOWN_FAT_MAN (HOENN_FLAGS_START + 0x0FF)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_PICHU_DOLL (HOENN_FLAGS_START + 0x100)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_2F_POKE_BALL (HOENN_FLAGS_START + 0x101)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MAY (HOENN_FLAGS_START + 0x102)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_MOM (HOENN_FLAGS_START + 0x103)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_BEDROOM (HOENN_FLAGS_START + 0x104)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_MOM (HOENN_FLAGS_START + 0x105)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_RIVAL_SIBLING (HOENN_FLAGS_START + 0x106)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK
#define FLAG_HIDE_LITTLEROOT_TOWN_MAYS_HOUSE_TRUCK (HOENN_FLAGS_START + 0x107)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE
#define FLAG_HIDE_LITTLEROOT_TOWN_MOM_OUTSIDE (HOENN_FLAGS_START + 0x108)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM
#define FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_BEDROOM_MOM (HOENN_FLAGS_START + 0x109)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_1
#define FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_1 (HOENN_FLAGS_START + 0x10A)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_2
#define FLAG_HIDE_LITTLEROOT_TOWN_PLAYERS_HOUSE_VIGOROTH_2 (HOENN_FLAGS_START + 0x10B)
#undef  FLAG_HIDE_LITTLEROOT_TOWN_RIVAL
#define FLAG_HIDE_LITTLEROOT_TOWN_RIVAL (HOENN_FLAGS_START + 0x10C)
#undef  FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON
#define FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON (HOENN_FLAGS_START + 0x10D)
#undef  FLAG_HIDE_MAGMA_HIDEOUT_GRUNTS
#define FLAG_HIDE_MAGMA_HIDEOUT_GRUNTS (HOENN_FLAGS_START + 0x10E)
#undef  FLAG_HIDE_MAUVILLE_CITY_WATTSON
#define FLAG_HIDE_MAUVILLE_CITY_WATTSON (HOENN_FLAGS_START + 0x10F)
#undef  FLAG_HIDE_MAUVILLE_GYM_WATTSON
#define FLAG_HIDE_MAUVILLE_GYM_WATTSON (HOENN_FLAGS_START + 0x110)
#undef  FLAG_HIDE_METEOR_FALLS_1F_1R_COZMO
#define FLAG_HIDE_METEOR_FALLS_1F_1R_COZMO (HOENN_FLAGS_START + 0x111)
#undef  FLAG_HIDE_MEW
#define FLAG_HIDE_MEW (HOENN_FLAGS_START + 0x112)
#undef  FLAG_HIDE_MIRAGE_TOWER_CLAW_FOSSIL
#define FLAG_HIDE_MIRAGE_TOWER_CLAW_FOSSIL (HOENN_FLAGS_START + 0x113)
#undef  FLAG_HIDE_MIRAGE_TOWER_ROOT_FOSSIL
#define FLAG_HIDE_MIRAGE_TOWER_ROOT_FOSSIL (HOENN_FLAGS_START + 0x114)
#undef  FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL
#define FLAG_HIDE_MOSSDEEP_CITY_HOUSE_2_WINGULL (HOENN_FLAGS_START + 0x115)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SCOTT
#define FLAG_HIDE_MOSSDEEP_CITY_SCOTT (HOENN_FLAGS_START + 0x116)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_STEVEN
#define FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_STEVEN (HOENN_FLAGS_START + 0x117)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA
#define FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA (HOENN_FLAGS_START + 0x118)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN
#define FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN (HOENN_FLAGS_START + 0x119)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA
#define FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA (HOENN_FLAGS_START + 0x11A)
#undef  FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_MAGMA_NOTE
#define FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_MAGMA_NOTE (HOENN_FLAGS_START + 0x11B)
#undef  FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL
#define FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_BELDUM_POKEBALL (HOENN_FLAGS_START + 0x11C)
#undef  FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN
#define FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN (HOENN_FLAGS_START + 0x11D)
#undef  FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA
#define FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA (HOENN_FLAGS_START + 0x11E)
#undef  FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN
#define FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD_TOWN (HOENN_FLAGS_START + 0x11F)
#undef  FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN
#define FLAG_HIDE_MR_BRINEY_DEWFORD_TOWN (HOENN_FLAGS_START + 0x120)
#undef  FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY
#define FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY (HOENN_FLAGS_START + 0x121)
#undef  FLAG_HIDE_MT_CHIMNEY_TEAM_AQUA
#define FLAG_HIDE_MT_CHIMNEY_TEAM_AQUA (HOENN_FLAGS_START + 0x122)
#undef  FLAG_HIDE_MT_CHIMNEY_TEAM_MAGMA
#define FLAG_HIDE_MT_CHIMNEY_TEAM_MAGMA (HOENN_FLAGS_START + 0x123)
#undef  FLAG_HIDE_MT_CHIMNEY_TRAINERS
#define FLAG_HIDE_MT_CHIMNEY_TRAINERS (HOENN_FLAGS_START + 0x124)
#undef  FLAG_HIDE_MT_PYRE_SUMMIT_ARCHIE
#define FLAG_HIDE_MT_PYRE_SUMMIT_ARCHIE (HOENN_FLAGS_START + 0x125)
#undef  FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE
#define FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE (HOENN_FLAGS_START + 0x126)
#undef  FLAG_HIDE_MT_PYRE_SUMMIT_TEAM_AQUA
#define FLAG_HIDE_MT_PYRE_SUMMIT_TEAM_AQUA (HOENN_FLAGS_START + 0x127)
#undef  FLAG_HIDE_NEW_MAUVILLE_VOLTORB_1
#define FLAG_HIDE_NEW_MAUVILLE_VOLTORB_1 (HOENN_FLAGS_START + 0x128)
#undef  FLAG_HIDE_NEW_MAUVILLE_VOLTORB_2
#define FLAG_HIDE_NEW_MAUVILLE_VOLTORB_2 (HOENN_FLAGS_START + 0x129)
#undef  FLAG_HIDE_NEW_MAUVILLE_VOLTORB_3
#define FLAG_HIDE_NEW_MAUVILLE_VOLTORB_3 (HOENN_FLAGS_START + 0x12A)
#undef  FLAG_HIDE_OLDALE_TOWN_RIVAL
#define FLAG_HIDE_OLDALE_TOWN_RIVAL (HOENN_FLAGS_START + 0x12B)
#undef  FLAG_HIDE_PETALBURG_CITY_WALLY
#define FLAG_HIDE_PETALBURG_CITY_WALLY (HOENN_FLAGS_START + 0x12C)
#undef  FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD
#define FLAG_HIDE_PETALBURG_CITY_WALLYS_DAD (HOENN_FLAGS_START + 0x12D)
#undef  FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM
#define FLAG_HIDE_PETALBURG_CITY_WALLYS_MOM (HOENN_FLAGS_START + 0x12E)
#undef  FLAG_HIDE_PETALBURG_GYM_GREETER
#define FLAG_HIDE_PETALBURG_GYM_GREETER (HOENN_FLAGS_START + 0x12F)
#undef  FLAG_HIDE_PETALBURG_GYM_WALLY
#define FLAG_HIDE_PETALBURG_GYM_WALLY (HOENN_FLAGS_START + 0x130)
#undef  FLAG_HIDE_PLAYERS_HOUSE_DAD
#define FLAG_HIDE_PLAYERS_HOUSE_DAD (HOENN_FLAGS_START + 0x131)
#undef  FLAG_HIDE_REGICE
#define FLAG_HIDE_REGICE (HOENN_FLAGS_START + 0x132)
#undef  FLAG_HIDE_REGIROCK
#define FLAG_HIDE_REGIROCK (HOENN_FLAGS_START + 0x133)
#undef  FLAG_HIDE_REGISTEEL
#define FLAG_HIDE_REGISTEEL (HOENN_FLAGS_START + 0x134)
#undef  FLAG_HIDE_ROUTE_101_BIRCH
#define FLAG_HIDE_ROUTE_101_BIRCH (HOENN_FLAGS_START + 0x135)
#undef  FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG
#define FLAG_HIDE_ROUTE_101_BIRCH_STARTERS_BAG (HOENN_FLAGS_START + 0x136)
#undef  FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE
#define FLAG_HIDE_ROUTE_101_BIRCH_ZIGZAGOON_BATTLE (HOENN_FLAGS_START + 0x137)
#undef  FLAG_HIDE_ROUTE_101_BOY
#define FLAG_HIDE_ROUTE_101_BOY (HOENN_FLAGS_START + 0x138)
#undef  FLAG_HIDE_ROUTE_103_BIRCH
#define FLAG_HIDE_ROUTE_103_BIRCH (HOENN_FLAGS_START + 0x139)
#undef  FLAG_HIDE_ROUTE_103_RIVAL
#define FLAG_HIDE_ROUTE_103_RIVAL (HOENN_FLAGS_START + 0x13A)
#undef  FLAG_HIDE_ROUTE_104_MR_BRINEY
#define FLAG_HIDE_ROUTE_104_MR_BRINEY (HOENN_FLAGS_START + 0x13B)
#undef  FLAG_HIDE_ROUTE_104_MR_BRINEY_BOAT
#define FLAG_HIDE_ROUTE_104_MR_BRINEY_BOAT (HOENN_FLAGS_START + 0x13C)
#undef  FLAG_HIDE_ROUTE_104_RIVAL
#define FLAG_HIDE_ROUTE_104_RIVAL (HOENN_FLAGS_START + 0x13D)
#undef  FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST
#define FLAG_HIDE_ROUTE_104_WHITE_HERB_FLORIST (HOENN_FLAGS_START + 0x13E)
#undef  FLAG_HIDE_ROUTE_109_MR_BRINEY
#define FLAG_HIDE_ROUTE_109_MR_BRINEY (HOENN_FLAGS_START + 0x13F)
#undef  FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT
#define FLAG_HIDE_ROUTE_109_MR_BRINEY_BOAT (HOENN_FLAGS_START + 0x140)
#undef  FLAG_HIDE_ROUTE_110_BIRCH
#define FLAG_HIDE_ROUTE_110_BIRCH (HOENN_FLAGS_START + 0x141)
#undef  FLAG_HIDE_ROUTE_110_TEAM_AQUA
#define FLAG_HIDE_ROUTE_110_TEAM_AQUA (HOENN_FLAGS_START + 0x142)
#undef  FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2
#define FLAG_HIDE_ROUTE_111_GABBY_AND_TY_2 (HOENN_FLAGS_START + 0x143)
#undef  FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3
#define FLAG_HIDE_ROUTE_111_GABBY_AND_TY_3 (HOENN_FLAGS_START + 0x144)
#undef  FLAG_HIDE_ROUTE_111_ROCK_SMASH_TIP_GUY
#define FLAG_HIDE_ROUTE_111_ROCK_SMASH_TIP_GUY (HOENN_FLAGS_START + 0x145)
#undef  FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE
#define FLAG_HIDE_ROUTE_111_VICKY_WINSTRATE (HOENN_FLAGS_START + 0x146)
#undef  FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE
#define FLAG_HIDE_ROUTE_111_VICTORIA_WINSTRATE (HOENN_FLAGS_START + 0x147)
#undef  FLAG_HIDE_ROUTE_111_VICTOR_WINSTRATE
#define FLAG_HIDE_ROUTE_111_VICTOR_WINSTRATE (HOENN_FLAGS_START + 0x148)
#undef  FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE
#define FLAG_HIDE_ROUTE_111_VIVI_WINSTRATE (HOENN_FLAGS_START + 0x149)
#undef  FLAG_HIDE_ROUTE_112_TEAM_MAGMA
#define FLAG_HIDE_ROUTE_112_TEAM_MAGMA (HOENN_FLAGS_START + 0x14A)
#undef  FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE
#define FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE (HOENN_FLAGS_START + 0x14B)
#undef  FLAG_HIDE_ROUTE_116_MR_BRINEY
#define FLAG_HIDE_ROUTE_116_MR_BRINEY (HOENN_FLAGS_START + 0x14C)
#undef  FLAG_HIDE_ROUTE_116_WANDAS_BOYFRIEND
#define FLAG_HIDE_ROUTE_116_WANDAS_BOYFRIEND (HOENN_FLAGS_START + 0x14D)
#undef  FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1
#define FLAG_HIDE_ROUTE_118_GABBY_AND_TY_1 (HOENN_FLAGS_START + 0x14E)
#undef  FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2
#define FLAG_HIDE_ROUTE_118_GABBY_AND_TY_2 (HOENN_FLAGS_START + 0x14F)
#undef  FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3
#define FLAG_HIDE_ROUTE_118_GABBY_AND_TY_3 (HOENN_FLAGS_START + 0x150)
#undef  FLAG_HIDE_ROUTE_119_RIVAL
#define FLAG_HIDE_ROUTE_119_RIVAL (HOENN_FLAGS_START + 0x151)
#undef  FLAG_HIDE_ROUTE_119_SCOTT
#define FLAG_HIDE_ROUTE_119_SCOTT (HOENN_FLAGS_START + 0x152)
#undef  FLAG_HIDE_ROUTE_119_TEAM_AQUA
#define FLAG_HIDE_ROUTE_119_TEAM_AQUA (HOENN_FLAGS_START + 0x153)
#undef  FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1
#define FLAG_HIDE_ROUTE_120_GABBY_AND_TY_1 (HOENN_FLAGS_START + 0x154)
#undef  FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2
#define FLAG_HIDE_ROUTE_120_GABBY_AND_TY_2 (HOENN_FLAGS_START + 0x155)
#undef  FLAG_HIDE_ROUTE_128_ARCHIE
#define FLAG_HIDE_ROUTE_128_ARCHIE (HOENN_FLAGS_START + 0x156)
#undef  FLAG_HIDE_ROUTE_128_MAXIE
#define FLAG_HIDE_ROUTE_128_MAXIE (HOENN_FLAGS_START + 0x157)
#undef  FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT
#define FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT (HOENN_FLAGS_START + 0x158)
#undef  FLAG_HIDE_RUSTBORO_CITY_DEVON_CORP_3F_EMPLOYEE
#define FLAG_HIDE_RUSTBORO_CITY_DEVON_CORP_3F_EMPLOYEE (HOENN_FLAGS_START + 0x159)
#undef  FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1
#define FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1 (HOENN_FLAGS_START + 0x15A)
#undef  FLAG_HIDE_RUSTBORO_CITY_POKEMON_SCHOOL_SCOTT
#define FLAG_HIDE_RUSTBORO_CITY_POKEMON_SCHOOL_SCOTT (HOENN_FLAGS_START + 0x15B)
#undef  FLAG_HIDE_RUSTBORO_CITY_RIVAL
#define FLAG_HIDE_RUSTBORO_CITY_RIVAL (HOENN_FLAGS_START + 0x15C)
#undef  FLAG_HIDE_RUSTBORO_CITY_SCIENTIST
#define FLAG_HIDE_RUSTBORO_CITY_SCIENTIST (HOENN_FLAGS_START + 0x15D)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT
#define FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT (HOENN_FLAGS_START + 0x15E)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_BRINEY
#define FLAG_HIDE_RUSTURF_TUNNEL_BRINEY (HOENN_FLAGS_START + 0x15F)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_PEEKO
#define FLAG_HIDE_RUSTURF_TUNNEL_PEEKO (HOENN_FLAGS_START + 0x160)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_WANDA
#define FLAG_HIDE_RUSTURF_TUNNEL_WANDA (HOENN_FLAGS_START + 0x161)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND
#define FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND (HOENN_FLAGS_START + 0x162)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_AQUA_GRUNTS
#define FLAG_HIDE_SEAFLOOR_CAVERN_AQUA_GRUNTS (HOENN_FLAGS_START + 0x163)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ENTRANCE_AQUA_GRUNT
#define FLAG_HIDE_SEAFLOOR_CAVERN_ENTRANCE_AQUA_GRUNT (HOENN_FLAGS_START + 0x164)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE
#define FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE (HOENN_FLAGS_START + 0x165)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE
#define FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE (HOENN_FLAGS_START + 0x166)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS
#define FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS (HOENN_FLAGS_START + 0x167)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE
#define FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE (HOENN_FLAGS_START + 0x168)
#undef  FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL
#define FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA_STILL (HOENN_FLAGS_START + 0x169)
#undef  FLAG_HIDE_SKY_PILLAR_WALLACE
#define FLAG_HIDE_SKY_PILLAR_WALLACE (HOENN_FLAGS_START + 0x16A)
#undef  FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN
#define FLAG_HIDE_SLATEPORT_CITY_CAPTAIN_STERN (HOENN_FLAGS_START + 0x16B)
#undef  FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER
#define FLAG_HIDE_SLATEPORT_CITY_CONTEST_REPORTER (HOENN_FLAGS_START + 0x16C)
#undef  FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY
#define FLAG_HIDE_SLATEPORT_CITY_GABBY_AND_TY (HOENN_FLAGS_START + 0x16D)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT (HOENN_FLAGS_START + 0x16E)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE (HOENN_FLAGS_START + 0x16F)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN (HOENN_FLAGS_START + 0x170)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_PATRONS
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_PATRONS (HOENN_FLAGS_START + 0x171)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_SS_TIDAL (HOENN_FLAGS_START + 0x172)
#undef  FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW
#define FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW (HOENN_FLAGS_START + 0x173)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1 (HOENN_FLAGS_START + 0x174)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2 (HOENN_FLAGS_START + 0x175)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE (HOENN_FLAGS_START + 0x176)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_AQUA_GRUNTS
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_AQUA_GRUNTS (HOENN_FLAGS_START + 0x177)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_FAMILIAR_AQUA_GRUNT
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_FAMILIAR_AQUA_GRUNT (HOENN_FLAGS_START + 0x178)
#undef  FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY
#define FLAG_HIDE_SLATEPORT_CITY_STERNS_SHIPYARD_MR_BRINEY (HOENN_FLAGS_START + 0x179)
#undef  FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA
#define FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA (HOENN_FLAGS_START + 0x17A)
#undef  FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION
#define FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION (HOENN_FLAGS_START + 0x17B)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE
#define FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE (HOENN_FLAGS_START + 0x17C)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON
#define FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON (HOENN_FLAGS_START + 0x17D)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE
#define FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE (HOENN_FLAGS_START + 0x17E)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_MAN_1
#define FLAG_HIDE_SOOTOPOLIS_CITY_MAN_1 (HOENN_FLAGS_START + 0x17F)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE
#define FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE (HOENN_FLAGS_START + 0x180)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS
#define FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS (HOENN_FLAGS_START + 0x181)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN
#define FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN (HOENN_FLAGS_START + 0x182)
#undef  FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE
#define FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE (HOENN_FLAGS_START + 0x183)
#undef  FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE
#define FLAG_HIDE_SOUTHERN_ISLAND_EON_STONE (HOENN_FLAGS_START + 0x184)
#undef  FLAG_HIDE_SS_TIDAL_ROOMS_SNATCH_GIVER
#define FLAG_HIDE_SS_TIDAL_ROOMS_SNATCH_GIVER (HOENN_FLAGS_START + 0x185)
#undef  FLAG_HIDE_TERRA_CAVE_GROUDON
#define FLAG_HIDE_TERRA_CAVE_GROUDON (HOENN_FLAGS_START + 0x186)
#undef  FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN
#define FLAG_HIDE_TRICK_HOUSE_ENTRANCE_MAN (HOENN_FLAGS_START + 0x187)
#undef  FLAG_HIDE_UNDERWATER_SEA_FLOOR_CAVERN_STOLEN_SUBMARINE
#define FLAG_HIDE_UNDERWATER_SEA_FLOOR_CAVERN_STOLEN_SUBMARINE (HOENN_FLAGS_START + 0x188)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_1
#define FLAG_HIDE_UNION_ROOM_PLAYER_1 (HOENN_FLAGS_START + 0x189)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_2
#define FLAG_HIDE_UNION_ROOM_PLAYER_2 (HOENN_FLAGS_START + 0x18A)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_3
#define FLAG_HIDE_UNION_ROOM_PLAYER_3 (HOENN_FLAGS_START + 0x18B)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_4
#define FLAG_HIDE_UNION_ROOM_PLAYER_4 (HOENN_FLAGS_START + 0x18C)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_5
#define FLAG_HIDE_UNION_ROOM_PLAYER_5 (HOENN_FLAGS_START + 0x18D)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_6
#define FLAG_HIDE_UNION_ROOM_PLAYER_6 (HOENN_FLAGS_START + 0x18E)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_7
#define FLAG_HIDE_UNION_ROOM_PLAYER_7 (HOENN_FLAGS_START + 0x18F)
#undef  FLAG_HIDE_UNION_ROOM_PLAYER_8
#define FLAG_HIDE_UNION_ROOM_PLAYER_8 (HOENN_FLAGS_START + 0x190)
#undef  FLAG_HIDE_VERDANTURF_TOWN_SCOTT
#define FLAG_HIDE_VERDANTURF_TOWN_SCOTT (HOENN_FLAGS_START + 0x191)
#undef  FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY
#define FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLY (HOENN_FLAGS_START + 0x192)
#undef  FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE
#define FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WALLYS_UNCLE (HOENN_FLAGS_START + 0x193)
#undef  FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA
#define FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDA (HOENN_FLAGS_START + 0x194)
#undef  FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND
#define FLAG_HIDE_VERDANTURF_TOWN_WANDAS_HOUSE_WANDAS_BOYFRIEND (HOENN_FLAGS_START + 0x195)
#undef  FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY
#define FLAG_HIDE_VICTORY_ROAD_ENTRANCE_WALLY (HOENN_FLAGS_START + 0x196)
#undef  FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS
#define FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS (HOENN_FLAGS_START + 0x197)
#undef  FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M
#define FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M (HOENN_FLAGS_START + 0x198)
#undef  FLAG_HIDE_WEATHER_INSTITUTE_2F_WORKERS
#define FLAG_HIDE_WEATHER_INSTITUTE_2F_WORKERS (HOENN_FLAGS_START + 0x199)
#undef  FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN
#define FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN (HOENN_FLAGS_START + 0x19A)
#undef  FLAG_INTERACTED_WITH_STEVEN_SPACE_CENTER
#define FLAG_INTERACTED_WITH_STEVEN_SPACE_CENTER (HOENN_FLAGS_START + 0x19B)
#undef  FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_2_SCANNER
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_2_SCANNER (HOENN_FLAGS_START + 0x19C)
#undef  FLAG_ITEM_ROUTE_103_GUARD_SPEC
#define FLAG_ITEM_ROUTE_103_GUARD_SPEC (HOENN_FLAGS_START + 0x19D)
#undef  FLAG_ITEM_ROUTE_103_PP_UP
#define FLAG_ITEM_ROUTE_103_PP_UP (HOENN_FLAGS_START + 0x19E)
#undef  FLAG_KECLEON_FLED_FORTREE
#define FLAG_KECLEON_FLED_FORTREE (HOENN_FLAGS_START + 0x19F)
#undef  FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN
#define FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN (HOENN_FLAGS_START + 0x1A0)
#undef  FLAG_LANDMARK_ALTERING_CAVE
#define FLAG_LANDMARK_ALTERING_CAVE (HOENN_FLAGS_START + 0x1A1)
#undef  FLAG_LANDMARK_ARTISAN_CAVE
#define FLAG_LANDMARK_ARTISAN_CAVE (HOENN_FLAGS_START + 0x1A2)
#undef  FLAG_LANDMARK_BERRY_MASTERS_HOUSE
#define FLAG_LANDMARK_BERRY_MASTERS_HOUSE (HOENN_FLAGS_START + 0x1A3)
#undef  FLAG_LANDMARK_DESERT_RUINS
#define FLAG_LANDMARK_DESERT_RUINS (HOENN_FLAGS_START + 0x1A4)
#undef  FLAG_LANDMARK_DESERT_UNDERPASS
#define FLAG_LANDMARK_DESERT_UNDERPASS (HOENN_FLAGS_START + 0x1A5)
#undef  FLAG_LANDMARK_FIERY_PATH
#define FLAG_LANDMARK_FIERY_PATH (HOENN_FLAGS_START + 0x1A6)
#undef  FLAG_LANDMARK_FLOWER_SHOP
#define FLAG_LANDMARK_FLOWER_SHOP (HOENN_FLAGS_START + 0x1A7)
#undef  FLAG_LANDMARK_FOSSIL_MANIACS_HOUSE
#define FLAG_LANDMARK_FOSSIL_MANIACS_HOUSE (HOENN_FLAGS_START + 0x1A8)
#undef  FLAG_LANDMARK_GLASS_WORKSHOP
#define FLAG_LANDMARK_GLASS_WORKSHOP (HOENN_FLAGS_START + 0x1A9)
#undef  FLAG_LANDMARK_HUNTERS_HOUSE
#define FLAG_LANDMARK_HUNTERS_HOUSE (HOENN_FLAGS_START + 0x1AA)
#undef  FLAG_LANDMARK_ISLAND_CAVE
#define FLAG_LANDMARK_ISLAND_CAVE (HOENN_FLAGS_START + 0x1AB)
#undef  FLAG_LANDMARK_LANETTES_HOUSE
#define FLAG_LANDMARK_LANETTES_HOUSE (HOENN_FLAGS_START + 0x1AC)
#undef  FLAG_LANDMARK_MIRAGE_TOWER
#define FLAG_LANDMARK_MIRAGE_TOWER (HOENN_FLAGS_START + 0x1AD)
#undef  FLAG_LANDMARK_MR_BRINEY_HOUSE
#define FLAG_LANDMARK_MR_BRINEY_HOUSE (HOENN_FLAGS_START + 0x1AE)
#undef  FLAG_LANDMARK_NEW_MAUVILLE
#define FLAG_LANDMARK_NEW_MAUVILLE (HOENN_FLAGS_START + 0x1AF)
#undef  FLAG_LANDMARK_OLD_LADY_REST_SHOP
#define FLAG_LANDMARK_OLD_LADY_REST_SHOP (HOENN_FLAGS_START + 0x1B0)
#undef  FLAG_LANDMARK_POKEMON_DAYCARE
#define FLAG_LANDMARK_POKEMON_DAYCARE (HOENN_FLAGS_START + 0x1B1)
#undef  FLAG_LANDMARK_POKEMON_LEAGUE
#define FLAG_LANDMARK_POKEMON_LEAGUE (HOENN_FLAGS_START + 0x1B2)
#undef  FLAG_LANDMARK_SCORCHED_SLAB
#define FLAG_LANDMARK_SCORCHED_SLAB (HOENN_FLAGS_START + 0x1B3)
#undef  FLAG_LANDMARK_SEAFLOOR_CAVERN
#define FLAG_LANDMARK_SEAFLOOR_CAVERN (HOENN_FLAGS_START + 0x1B4)
#undef  FLAG_LANDMARK_SEALED_CHAMBER
#define FLAG_LANDMARK_SEALED_CHAMBER (HOENN_FLAGS_START + 0x1B5)
#undef  FLAG_LANDMARK_SEASHORE_HOUSE
#define FLAG_LANDMARK_SEASHORE_HOUSE (HOENN_FLAGS_START + 0x1B6)
#undef  FLAG_LANDMARK_SKY_PILLAR
#define FLAG_LANDMARK_SKY_PILLAR (HOENN_FLAGS_START + 0x1B7)
#undef  FLAG_LANDMARK_SOUTHERN_ISLAND
#define FLAG_LANDMARK_SOUTHERN_ISLAND (HOENN_FLAGS_START + 0x1B8)
#undef  FLAG_LANDMARK_TRICK_HOUSE
#define FLAG_LANDMARK_TRICK_HOUSE (HOENN_FLAGS_START + 0x1B9)
#undef  FLAG_LANDMARK_TUNNELERS_REST_HOUSE
#define FLAG_LANDMARK_TUNNELERS_REST_HOUSE (HOENN_FLAGS_START + 0x1BA)
#undef  FLAG_LANDMARK_WINSTRATE_FAMILY
#define FLAG_LANDMARK_WINSTRATE_FAMILY (HOENN_FLAGS_START + 0x1BB)
#undef  FLAG_LEGENDARIES_IN_SOOTOPOLIS
#define FLAG_LEGENDARIES_IN_SOOTOPOLIS (HOENN_FLAGS_START + 0x1BC)
#undef  FLAG_MAUVILLE_GYM_BARRIERS_STATE
#define FLAG_MAUVILLE_GYM_BARRIERS_STATE (HOENN_FLAGS_START + 0x1BD)
#undef  FLAG_MET_ARCHIE_METEOR_FALLS
#define FLAG_MET_ARCHIE_METEOR_FALLS (HOENN_FLAGS_START + 0x1BE)
#undef  FLAG_MET_ARCHIE_SOOTOPOLIS
#define FLAG_MET_ARCHIE_SOOTOPOLIS (HOENN_FLAGS_START + 0x1BF)
#undef  FLAG_MET_DEVON_EMPLOYEE
#define FLAG_MET_DEVON_EMPLOYEE (HOENN_FLAGS_START + 0x1C0)
#undef  FLAG_MET_DIVING_TREASURE_HUNTER
#define FLAG_MET_DIVING_TREASURE_HUNTER (HOENN_FLAGS_START + 0x1C1)
#undef  FLAG_MET_FANCLUB_YOUNGER_BROTHER
#define FLAG_MET_FANCLUB_YOUNGER_BROTHER (HOENN_FLAGS_START + 0x1C2)
#undef  FLAG_MET_HIDDEN_POWER_GIVER
#define FLAG_MET_HIDDEN_POWER_GIVER (HOENN_FLAGS_START + 0x1C3)
#undef  FLAG_MET_MAXIE_SOOTOPOLIS
#define FLAG_MET_MAXIE_SOOTOPOLIS (HOENN_FLAGS_START + 0x1C4)
#undef  FLAG_MET_PRETTY_PETAL_SHOP_OWNER
#define FLAG_MET_PRETTY_PETAL_SHOP_OWNER (HOENN_FLAGS_START + 0x1C5)
#undef  FLAG_MET_PROF_COZMO
#define FLAG_MET_PROF_COZMO (HOENN_FLAGS_START + 0x1C6)
#undef  FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE
#define FLAG_MET_RIVAL_IN_HOUSE_AFTER_LILYCOVE (HOENN_FLAGS_START + 0x1C7)
#undef  FLAG_MET_RIVAL_LILYCOVE
#define FLAG_MET_RIVAL_LILYCOVE (HOENN_FLAGS_START + 0x1C8)
#undef  FLAG_MET_RIVAL_MOM
#define FLAG_MET_RIVAL_MOM (HOENN_FLAGS_START + 0x1C9)
#undef  FLAG_MET_RIVAL_RUSTBORO
#define FLAG_MET_RIVAL_RUSTBORO (HOENN_FLAGS_START + 0x1CA)
#undef  FLAG_MET_SCOTT_AFTER_OBTAINING_STONE_BADGE
#define FLAG_MET_SCOTT_AFTER_OBTAINING_STONE_BADGE (HOENN_FLAGS_START + 0x1CB)
#undef  FLAG_MET_SCOTT_IN_EVERGRANDE
#define FLAG_MET_SCOTT_IN_EVERGRANDE (HOENN_FLAGS_START + 0x1CC)
#undef  FLAG_MET_SCOTT_IN_FALLARBOR
#define FLAG_MET_SCOTT_IN_FALLARBOR (HOENN_FLAGS_START + 0x1CD)
#undef  FLAG_MET_SCOTT_IN_LILYCOVE
#define FLAG_MET_SCOTT_IN_LILYCOVE (HOENN_FLAGS_START + 0x1CE)
#undef  FLAG_MET_SCOTT_IN_VERDANTURF
#define FLAG_MET_SCOTT_IN_VERDANTURF (HOENN_FLAGS_START + 0x1CF)
#undef  FLAG_MET_SCOTT_ON_SS_TIDAL
#define FLAG_MET_SCOTT_ON_SS_TIDAL (HOENN_FLAGS_START + 0x1D0)
#undef  FLAG_MET_SCOTT_RUSTBORO
#define FLAG_MET_SCOTT_RUSTBORO (HOENN_FLAGS_START + 0x1D1)
#undef  FLAG_MET_SLATEPORT_FANCLUB_CHAIRMAN
#define FLAG_MET_SLATEPORT_FANCLUB_CHAIRMAN (HOENN_FLAGS_START + 0x1D2)
#undef  FLAG_MET_TEAM_AQUA_HARBOR
#define FLAG_MET_TEAM_AQUA_HARBOR (HOENN_FLAGS_START + 0x1D3)
#undef  FLAG_MET_WAILMER_TRAINER
#define FLAG_MET_WAILMER_TRAINER (HOENN_FLAGS_START + 0x1D4)
#undef  FLAG_MIRAGE_TOWER_VISIBLE
#define FLAG_MIRAGE_TOWER_VISIBLE (HOENN_FLAGS_START + 0x1D5)
#undef  FLAG_MOSSDEEP_GYM_SWITCH_1
#define FLAG_MOSSDEEP_GYM_SWITCH_1 (HOENN_FLAGS_START + 0x1D6)
#undef  FLAG_MOSSDEEP_GYM_SWITCH_2
#define FLAG_MOSSDEEP_GYM_SWITCH_2 (HOENN_FLAGS_START + 0x1D7)
#undef  FLAG_MOSSDEEP_GYM_SWITCH_3
#define FLAG_MOSSDEEP_GYM_SWITCH_3 (HOENN_FLAGS_START + 0x1D8)
#undef  FLAG_MOSSDEEP_GYM_SWITCH_4
#define FLAG_MOSSDEEP_GYM_SWITCH_4 (HOENN_FLAGS_START + 0x1D9)
#undef  FLAG_MR_BRINEY_SAILING_INTRO
#define FLAG_MR_BRINEY_SAILING_INTRO (HOENN_FLAGS_START + 0x1DA)
#undef  FLAG_NOT_READY_FOR_BATTLE_ROUTE_120
#define FLAG_NOT_READY_FOR_BATTLE_ROUTE_120 (HOENN_FLAGS_START + 0x1DB)
#undef  FLAG_OMIT_DIVE_FROM_STEVEN_LETTER
#define FLAG_OMIT_DIVE_FROM_STEVEN_LETTER (HOENN_FLAGS_START + 0x1DC)
#undef  FLAG_PACIFIDLOG_NPC_TRADE_COMPLETED
#define FLAG_PACIFIDLOG_NPC_TRADE_COMPLETED (HOENN_FLAGS_START + 0x1DD)
#undef  FLAG_PETALBURG_MART_EXPANDED_ITEMS
#define FLAG_PETALBURG_MART_EXPANDED_ITEMS (HOENN_FLAGS_START + 0x1DE)
#undef  FLAG_RECEIVED_20_COINS
#define FLAG_RECEIVED_20_COINS (HOENN_FLAGS_START + 0x1DF)
#undef  FLAG_RECEIVED_6_SODA_POP
#define FLAG_RECEIVED_6_SODA_POP (HOENN_FLAGS_START + 0x1E0)
#undef  FLAG_RECEIVED_BELDUM
#define FLAG_RECEIVED_BELDUM (HOENN_FLAGS_START + 0x1E1)
#undef  FLAG_RECEIVED_BELUE_BERRY
#define FLAG_RECEIVED_BELUE_BERRY (HOENN_FLAGS_START + 0x1E2)
#undef  FLAG_RECEIVED_BLUE_SCARF
#define FLAG_RECEIVED_BLUE_SCARF (HOENN_FLAGS_START + 0x1E3)
#undef  FLAG_RECEIVED_CASTFORM
#define FLAG_RECEIVED_CASTFORM (HOENN_FLAGS_START + 0x1E4)
#undef  FLAG_RECEIVED_CHARCOAL
#define FLAG_RECEIVED_CHARCOAL (HOENN_FLAGS_START + 0x1E5)
#undef  FLAG_RECEIVED_CHESTO_BERRY_ROUTE_104
#define FLAG_RECEIVED_CHESTO_BERRY_ROUTE_104 (HOENN_FLAGS_START + 0x1E6)
#undef  FLAG_RECEIVED_CLEANSE_TAG
#define FLAG_RECEIVED_CLEANSE_TAG (HOENN_FLAGS_START + 0x1E7)
#undef  FLAG_RECEIVED_COIN_CASE
#define FLAG_RECEIVED_COIN_CASE (HOENN_FLAGS_START + 0x1E8)
#undef  FLAG_RECEIVED_DEVON_SCOPE
#define FLAG_RECEIVED_DEVON_SCOPE (HOENN_FLAGS_START + 0x1E9)
#undef  FLAG_RECEIVED_DOLL_LANETTE
#define FLAG_RECEIVED_DOLL_LANETTE (HOENN_FLAGS_START + 0x1EA)
#undef  FLAG_RECEIVED_DURIN_BERRY
#define FLAG_RECEIVED_DURIN_BERRY (HOENN_FLAGS_START + 0x1EB)
#undef  FLAG_RECEIVED_EXP_SHARE
#define FLAG_RECEIVED_EXP_SHARE (HOENN_FLAGS_START + 0x1EC)
#undef  FLAG_RECEIVED_FANCLUB_TM_THIS_WEEK
#define FLAG_RECEIVED_FANCLUB_TM_THIS_WEEK (HOENN_FLAGS_START + 0x1ED)
#undef  FLAG_RECEIVED_FOCUS_BAND
#define FLAG_RECEIVED_FOCUS_BAND (HOENN_FLAGS_START + 0x1EE)
#undef  FLAG_RECEIVED_GLASS_ORNAMENT
#define FLAG_RECEIVED_GLASS_ORNAMENT (HOENN_FLAGS_START + 0x1EF)
#undef  FLAG_RECEIVED_GOOD_ROD
#define FLAG_RECEIVED_GOOD_ROD (HOENN_FLAGS_START + 0x1F0)
#undef  FLAG_RECEIVED_GO_GOGGLES
#define FLAG_RECEIVED_GO_GOGGLES (HOENN_FLAGS_START + 0x1F1)
#undef  FLAG_RECEIVED_GREEN_SCARF
#define FLAG_RECEIVED_GREEN_SCARF (HOENN_FLAGS_START + 0x1F2)
#undef  FLAG_RECEIVED_HM_DIVE
#define FLAG_RECEIVED_HM_DIVE (HOENN_FLAGS_START + 0x1F3)
#undef  FLAG_RECEIVED_HM_FLY
#define FLAG_RECEIVED_HM_FLY (HOENN_FLAGS_START + 0x1F4)
#undef  FLAG_RECEIVED_HM_WATERFALL
#define FLAG_RECEIVED_HM_WATERFALL (HOENN_FLAGS_START + 0x1F5)
#undef  FLAG_RECEIVED_KINGS_ROCK
#define FLAG_RECEIVED_KINGS_ROCK (HOENN_FLAGS_START + 0x1F6)
#undef  FLAG_RECEIVED_LAVARIDGE_EGG
#define FLAG_RECEIVED_LAVARIDGE_EGG (HOENN_FLAGS_START + 0x1F7)
#undef  FLAG_RECEIVED_MACHO_BRACE
#define FLAG_RECEIVED_MACHO_BRACE (HOENN_FLAGS_START + 0x1F8)
#undef  FLAG_RECEIVED_MENTAL_HERB
#define FLAG_RECEIVED_MENTAL_HERB (HOENN_FLAGS_START + 0x1F9)
#undef  FLAG_RECEIVED_METEORITE
#define FLAG_RECEIVED_METEORITE (HOENN_FLAGS_START + 0x1FA)
#undef  FLAG_RECEIVED_MIRACLE_SEED
#define FLAG_RECEIVED_MIRACLE_SEED (HOENN_FLAGS_START + 0x1FB)
#undef  FLAG_RECEIVED_OLD_ROD
#define FLAG_RECEIVED_OLD_ROD (HOENN_FLAGS_START + 0x1FC)
#undef  FLAG_RECEIVED_PAMTRE_BERRY
#define FLAG_RECEIVED_PAMTRE_BERRY (HOENN_FLAGS_START + 0x1FD)
#undef  FLAG_RECEIVED_PINK_SCARF
#define FLAG_RECEIVED_PINK_SCARF (HOENN_FLAGS_START + 0x1FE)
#undef  FLAG_RECEIVED_POKEBLOCK_CASE
#define FLAG_RECEIVED_POKEBLOCK_CASE (HOENN_FLAGS_START + 0x1FF)
#undef  FLAG_RECEIVED_POTION_OLDALE
#define FLAG_RECEIVED_POTION_OLDALE (HOENN_FLAGS_START + 0x200)
#undef  FLAG_RECEIVED_POWDER_JAR
#define FLAG_RECEIVED_POWDER_JAR (HOENN_FLAGS_START + 0x201)
#undef  FLAG_RECEIVED_PREMIER_BALL_RUSTBORO
#define FLAG_RECEIVED_PREMIER_BALL_RUSTBORO (HOENN_FLAGS_START + 0x202)
#undef  FLAG_RECEIVED_QUICK_CLAW
#define FLAG_RECEIVED_QUICK_CLAW (HOENN_FLAGS_START + 0x203)
#undef  FLAG_RECEIVED_RED_OR_BLUE_ORB
#define FLAG_RECEIVED_RED_OR_BLUE_ORB (HOENN_FLAGS_START + 0x204)
#undef  FLAG_RECEIVED_RED_SCARF
#define FLAG_RECEIVED_RED_SCARF (HOENN_FLAGS_START + 0x205)
#undef  FLAG_RECEIVED_REPEAT_BALL
#define FLAG_RECEIVED_REPEAT_BALL (HOENN_FLAGS_START + 0x206)
#undef  FLAG_RECEIVED_SECRET_POWER
#define FLAG_RECEIVED_SECRET_POWER (HOENN_FLAGS_START + 0x207)
#undef  FLAG_SYS_PC_LANETTE
#define FLAG_SYS_PC_LANETTE (HOENN_FLAGS_START + 0x20A)
#undef  FLAG_WALLACE_GOES_TO_SKY_PILLAR
#define FLAG_WALLACE_GOES_TO_SKY_PILLAR (HOENN_FLAGS_START + 0x20B)
#undef  FLAG_WALLY_SPEECH
#define FLAG_WALLY_SPEECH (HOENN_FLAGS_START + 0x20C)
#undef  FLAG_WATTSON_REMATCH_AVAILABLE
#define FLAG_WATTSON_REMATCH_AVAILABLE (HOENN_FLAGS_START + 0x20D)
#undef  FLAG_WHITEOUT_TO_LAVARIDGE
#define FLAG_WHITEOUT_TO_LAVARIDGE (HOENN_FLAGS_START + 0x20E)
#undef  FLAG_WINGULL_DELIVERED_MAIL
#define FLAG_WINGULL_DELIVERED_MAIL (HOENN_FLAGS_START + 0x20F)
#undef  FLAG_WINGULL_SENT_ON_ERRAND
#define FLAG_WINGULL_SENT_ON_ERRAND (HOENN_FLAGS_START + 0x210)


// ---------------------------------------------------------------------
// Reaktivierte Null-Flags: flags_hns.h definiert diese Smaragd-Flags als 0
// (tote Stubs). removeobject/addobject persistieren aber ueber genau diese
// Flags - bei 0 ist das ein No-op, NPCs spawnen beim Wiederbetreten erneut
// (Playtest-Befund Bluetenburgwald). Hier erhalten alle Null-Flags mit
// echtem Bedarf (Objekt-Flag, Script-Lesen, aktive Engine) reale Slots;
// reine setflag/clearflag-No-ops und tote FRLG-Systeme bleiben bei 0.
// Hinweis: FLAG_DAILY_* liegen ausserhalb des taeglichen Reset-Bereichs
// (wirken einmalig statt taeglich - dokumentiert).
// ---------------------------------------------------------------------

#undef  FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
#define FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY (HOENN_FLAGS_START + 0x211)
#undef  FLAG_DAILY_SECRET_BASE
#define FLAG_DAILY_SECRET_BASE (HOENN_FLAGS_START + 0x212)
#undef  FLAG_DEFEATED_BROCK
#define FLAG_DEFEATED_BROCK (HOENN_FLAGS_START + 0x213)
#undef  FLAG_ENABLE_MOM_MATCH_CALL
#define FLAG_ENABLE_MOM_MATCH_CALL (HOENN_FLAGS_START + 0x214)
#undef  FLAG_ENABLE_MR_STONE_POKENAV
#define FLAG_ENABLE_MR_STONE_POKENAV (HOENN_FLAGS_START + 0x215)
#undef  FLAG_GOT_COIN_CASE
#define FLAG_GOT_COIN_CASE (HOENN_FLAGS_START + 0x216)
#undef  FLAG_GOT_POWDER_JAR
#define FLAG_GOT_POWDER_JAR (HOENN_FLAGS_START + 0x217)
#undef  FLAG_HIDE_AQUA_HIDEOUT_B2F_SUBMARINE_SHADOW
#define FLAG_HIDE_AQUA_HIDEOUT_B2F_SUBMARINE_SHADOW (HOENN_FLAGS_START + 0x218)
#undef  FLAG_HIDE_CAVE_OF_ORIGIN_B1F_WALLACE
#define FLAG_HIDE_CAVE_OF_ORIGIN_B1F_WALLACE (HOENN_FLAGS_START + 0x219)
#undef  FLAG_HIDE_FALLARBOR_AZURILL
#define FLAG_HIDE_FALLARBOR_AZURILL (HOENN_FLAGS_START + 0x21A)
#undef  FLAG_HIDE_FALLARBOR_POKEMON_CENTER_LANETTE
#define FLAG_HIDE_FALLARBOR_POKEMON_CENTER_LANETTE (HOENN_FLAGS_START + 0x21B)
#undef  FLAG_HIDE_FORTREE_CITY_KECLEON
#define FLAG_HIDE_FORTREE_CITY_KECLEON (HOENN_FLAGS_START + 0x21C)
#undef  FLAG_HIDE_GRANITE_CAVE_STEVEN
#define FLAG_HIDE_GRANITE_CAVE_STEVEN (HOENN_FLAGS_START + 0x21D)
#undef  FLAG_HIDE_LILYCOVE_CITY_RIVAL
#define FLAG_HIDE_LILYCOVE_CITY_RIVAL (HOENN_FLAGS_START + 0x21E)
#undef  FLAG_HIDE_LILYCOVE_HARBOR_FERRY_ATTENDANT
#define FLAG_HIDE_LILYCOVE_HARBOR_FERRY_ATTENDANT (HOENN_FLAGS_START + 0x21F)
#undef  FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_FEAROW_DOLL (HOENN_FLAGS_START + 0x220)
#undef  FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_LAPRAS_DOLL (HOENN_FLAGS_START + 0x221)
#undef  FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_F_DOLL (HOENN_FLAGS_START + 0x222)
#undef  FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_NIDORAN_M_DOLL (HOENN_FLAGS_START + 0x223)
#undef  FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL
#define FLAG_HIDE_LORELEIS_HOUSE_PIDGEOT_DOLL (HOENN_FLAGS_START + 0x224)
#undef  FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_CHANSEY_DOLL (HOENN_FLAGS_START + 0x225)
#undef  FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_JIGGLYPUFF_DOLL (HOENN_FLAGS_START + 0x226)
#undef  FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL
#define FLAG_HIDE_LORELEI_HOUSE_MEOWTH_DOLL (HOENN_FLAGS_START + 0x227)
#undef  FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_ASLEEP
#define FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_ASLEEP (HOENN_FLAGS_START + 0x228)
#undef  FLAG_HIDE_MAUVILLE_CITY_WALLY
#define FLAG_HIDE_MAUVILLE_CITY_WALLY (HOENN_FLAGS_START + 0x229)
#undef  FLAG_HIDE_MAUVILLE_CITY_WALLYS_UNCLE
#define FLAG_HIDE_MAUVILLE_CITY_WALLYS_UNCLE (HOENN_FLAGS_START + 0x22A)
#undef  FLAG_HIDE_METEOR_FALLS_TEAM_MAGMA
#define FLAG_HIDE_METEOR_FALLS_TEAM_MAGMA (HOENN_FLAGS_START + 0x22B)
#undef  FLAG_HIDE_PETALBURG_GYM_NORMAN
#define FLAG_HIDE_PETALBURG_GYM_NORMAN (HOENN_FLAGS_START + 0x22C)
#undef  FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT
#define FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT (HOENN_FLAGS_START + 0x22D)
#undef  FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE
#define FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE (HOENN_FLAGS_START + 0x22E)
#undef  FLAG_HIDE_ROUTE_110_RIVAL
#define FLAG_HIDE_ROUTE_110_RIVAL (HOENN_FLAGS_START + 0x22F)
#undef  FLAG_HIDE_ROUTE_111_GABBY_AND_TY_1
#define FLAG_HIDE_ROUTE_111_GABBY_AND_TY_1 (HOENN_FLAGS_START + 0x230)
#undef  FLAG_HIDE_ROUTE_111_SECRET_POWER_MAN
#define FLAG_HIDE_ROUTE_111_SECRET_POWER_MAN (HOENN_FLAGS_START + 0x231)
#undef  FLAG_HIDE_ROUTE_116_DROPPED_GLASSES_MAN
#define FLAG_HIDE_ROUTE_116_DROPPED_GLASSES_MAN (HOENN_FLAGS_START + 0x232)
#undef  FLAG_HIDE_ROUTE_118_STEVEN
#define FLAG_HIDE_ROUTE_118_STEVEN (HOENN_FLAGS_START + 0x233)
#undef  FLAG_HIDE_ROUTE_119_KECLEON_1
#define FLAG_HIDE_ROUTE_119_KECLEON_1 (HOENN_FLAGS_START + 0x234)
#undef  FLAG_HIDE_ROUTE_119_KECLEON_2
#define FLAG_HIDE_ROUTE_119_KECLEON_2 (HOENN_FLAGS_START + 0x235)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_1
#define FLAG_HIDE_ROUTE_120_KECLEON_1 (HOENN_FLAGS_START + 0x236)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_2
#define FLAG_HIDE_ROUTE_120_KECLEON_2 (HOENN_FLAGS_START + 0x237)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_3
#define FLAG_HIDE_ROUTE_120_KECLEON_3 (HOENN_FLAGS_START + 0x238)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_4
#define FLAG_HIDE_ROUTE_120_KECLEON_4 (HOENN_FLAGS_START + 0x239)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_5
#define FLAG_HIDE_ROUTE_120_KECLEON_5 (HOENN_FLAGS_START + 0x23A)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE
#define FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE (HOENN_FLAGS_START + 0x23B)
#undef  FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE_SHADOW
#define FLAG_HIDE_ROUTE_120_KECLEON_BRIDGE_SHADOW (HOENN_FLAGS_START + 0x23C)
#undef  FLAG_HIDE_ROUTE_120_STEVEN
#define FLAG_HIDE_ROUTE_120_STEVEN (HOENN_FLAGS_START + 0x23D)
#undef  FLAG_HIDE_ROUTE_121_TEAM_AQUA_GRUNTS
#define FLAG_HIDE_ROUTE_121_TEAM_AQUA_GRUNTS (HOENN_FLAGS_START + 0x23E)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_ROCK_1
#define FLAG_HIDE_RUSTURF_TUNNEL_ROCK_1 (HOENN_FLAGS_START + 0x23F)
#undef  FLAG_HIDE_RUSTURF_TUNNEL_ROCK_2
#define FLAG_HIDE_RUSTURF_TUNNEL_ROCK_2 (HOENN_FLAGS_START + 0x240)
#undef  FLAG_HIDE_SAFARI_ZONE_SOUTH_CONSTRUCTION_WORKERS
#define FLAG_HIDE_SAFARI_ZONE_SOUTH_CONSTRUCTION_WORKERS (HOENN_FLAGS_START + 0x241)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY (HOENN_FLAGS_START + 0x242)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT
#define FLAG_HIDE_SAFFRON_FAN_CLUB_BLACKBELT (HOENN_FLAGS_START + 0x243)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER
#define FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER (HOENN_FLAGS_START + 0x244)
#undef  FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN
#define FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN (HOENN_FLAGS_START + 0x245)
#undef  FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_ASLEEP
#define FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_ASLEEP (HOENN_FLAGS_START + 0x246)
#undef  FLAG_HIDE_SILPH_CO_5F_CARD_KEY
#define FLAG_HIDE_SILPH_CO_5F_CARD_KEY (HOENN_FLAGS_START + 0x247)
#undef  FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA
#define FLAG_HIDE_SKY_PILLAR_TOP_RAYQUAZA (HOENN_FLAGS_START + 0x248)
#undef  FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_CAPTAIN_STERN
#define FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_CAPTAIN_STERN (HOENN_FLAGS_START + 0x249)
#undef  FLAG_HIDE_SS_TIDAL_CORRIDOR_SCOTT
#define FLAG_HIDE_SS_TIDAL_CORRIDOR_SCOTT (HOENN_FLAGS_START + 0x24A)
#undef  FLAG_HIDE_TRICK_HOUSE_END_MAN
#define FLAG_HIDE_TRICK_HOUSE_END_MAN (HOENN_FLAGS_START + 0x24B)
#undef  FLAG_ITEM_ABANDONED_SHIP_CAPTAINS_OFFICE_STORAGE_KEY
#define FLAG_ITEM_ABANDONED_SHIP_CAPTAINS_OFFICE_STORAGE_KEY (HOENN_FLAGS_START + 0x24C)
#undef  FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_1_TM_RAIN_DANCE
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_1_TM_RAIN_DANCE (HOENN_FLAGS_START + 0x24D)
#undef  FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_3_WATER_STONE
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_3_WATER_STONE (HOENN_FLAGS_START + 0x24E)
#undef  FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_6_LUXURY_BALL
#define FLAG_ITEM_ABANDONED_SHIP_HIDDEN_FLOOR_ROOM_6_LUXURY_BALL (HOENN_FLAGS_START + 0x24F)
#undef  FLAG_ITEM_ABANDONED_SHIP_ROOMS_1F_HARBOR_MAIL
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_1F_HARBOR_MAIL (HOENN_FLAGS_START + 0x250)
#undef  FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_1F_REVIVE
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_1F_REVIVE (HOENN_FLAGS_START + 0x251)
#undef  FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_B1F_DIVE_BALL
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_2_B1F_DIVE_BALL (HOENN_FLAGS_START + 0x252)
#undef  FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_ESCAPE_ROPE
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_ESCAPE_ROPE (HOENN_FLAGS_START + 0x253)
#undef  FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_TM_ICE_BEAM
#define FLAG_ITEM_ABANDONED_SHIP_ROOMS_B1F_TM_ICE_BEAM (HOENN_FLAGS_START + 0x254)
#undef  FLAG_ITEM_AQUA_HIDEOUT_B1F_MASTER_BALL
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_MASTER_BALL (HOENN_FLAGS_START + 0x255)
#undef  FLAG_ITEM_AQUA_HIDEOUT_B1F_MAX_ELIXIR
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_MAX_ELIXIR (HOENN_FLAGS_START + 0x256)
#undef  FLAG_ITEM_AQUA_HIDEOUT_B1F_NUGGET
#define FLAG_ITEM_AQUA_HIDEOUT_B1F_NUGGET (HOENN_FLAGS_START + 0x257)
#undef  FLAG_ITEM_AQUA_HIDEOUT_B2F_NEST_BALL
#define FLAG_ITEM_AQUA_HIDEOUT_B2F_NEST_BALL (HOENN_FLAGS_START + 0x258)
#undef  FLAG_ITEM_ARTISAN_CAVE_1F_CARBOS
#define FLAG_ITEM_ARTISAN_CAVE_1F_CARBOS (HOENN_FLAGS_START + 0x259)
#undef  FLAG_ITEM_ARTISAN_CAVE_B1F_HP_UP
#define FLAG_ITEM_ARTISAN_CAVE_B1F_HP_UP (HOENN_FLAGS_START + 0x25A)
#undef  FLAG_ITEM_FIERY_PATH_FIRE_STONE
#define FLAG_ITEM_FIERY_PATH_FIRE_STONE (HOENN_FLAGS_START + 0x25B)
#undef  FLAG_ITEM_FIERY_PATH_TM_TOXIC
#define FLAG_ITEM_FIERY_PATH_TM_TOXIC (HOENN_FLAGS_START + 0x25C)
#undef  FLAG_ITEM_GRANITE_CAVE_1F_ESCAPE_ROPE
#define FLAG_ITEM_GRANITE_CAVE_1F_ESCAPE_ROPE (HOENN_FLAGS_START + 0x25D)
#undef  FLAG_ITEM_GRANITE_CAVE_B1F_POKE_BALL
#define FLAG_ITEM_GRANITE_CAVE_B1F_POKE_BALL (HOENN_FLAGS_START + 0x25E)
#undef  FLAG_ITEM_GRANITE_CAVE_B2F_RARE_CANDY
#define FLAG_ITEM_GRANITE_CAVE_B2F_RARE_CANDY (HOENN_FLAGS_START + 0x25F)
#undef  FLAG_ITEM_GRANITE_CAVE_B2F_REPEL
#define FLAG_ITEM_GRANITE_CAVE_B2F_REPEL (HOENN_FLAGS_START + 0x260)
#undef  FLAG_ITEM_JAGGED_PASS_BURN_HEAL
#define FLAG_ITEM_JAGGED_PASS_BURN_HEAL (HOENN_FLAGS_START + 0x261)
#undef  FLAG_ITEM_LILYCOVE_CITY_MAX_REPEL
#define FLAG_ITEM_LILYCOVE_CITY_MAX_REPEL (HOENN_FLAGS_START + 0x262)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_1F_RARE_CANDY
#define FLAG_ITEM_MAGMA_HIDEOUT_1F_RARE_CANDY (HOENN_FLAGS_START + 0x263)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_FULL_RESTORE
#define FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_FULL_RESTORE (HOENN_FLAGS_START + 0x264)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_MAX_ELIXIR
#define FLAG_ITEM_MAGMA_HIDEOUT_2F_2R_MAX_ELIXIR (HOENN_FLAGS_START + 0x265)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_3F_1R_NUGGET
#define FLAG_ITEM_MAGMA_HIDEOUT_3F_1R_NUGGET (HOENN_FLAGS_START + 0x266)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_3F_2R_PP_MAX
#define FLAG_ITEM_MAGMA_HIDEOUT_3F_2R_PP_MAX (HOENN_FLAGS_START + 0x267)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_3F_3R_ECAPE_ROPE
#define FLAG_ITEM_MAGMA_HIDEOUT_3F_3R_ECAPE_ROPE (HOENN_FLAGS_START + 0x268)
#undef  FLAG_ITEM_MAGMA_HIDEOUT_4F_MAX_REVIVE
#define FLAG_ITEM_MAGMA_HIDEOUT_4F_MAX_REVIVE (HOENN_FLAGS_START + 0x269)
#undef  FLAG_ITEM_MAUVILLE_CITY_X_SPEED
#define FLAG_ITEM_MAUVILLE_CITY_X_SPEED (HOENN_FLAGS_START + 0x26A)
#undef  FLAG_ITEM_METEOR_FALLS_1F_1R_FULL_HEAL
#define FLAG_ITEM_METEOR_FALLS_1F_1R_FULL_HEAL (HOENN_FLAGS_START + 0x26B)
#undef  FLAG_ITEM_METEOR_FALLS_1F_1R_MOON_STONE
#define FLAG_ITEM_METEOR_FALLS_1F_1R_MOON_STONE (HOENN_FLAGS_START + 0x26C)
#undef  FLAG_ITEM_METEOR_FALLS_1F_1R_PP_UP
#define FLAG_ITEM_METEOR_FALLS_1F_1R_PP_UP (HOENN_FLAGS_START + 0x26D)
#undef  FLAG_ITEM_METEOR_FALLS_1F_1R_TM_IRON_TAIL
#define FLAG_ITEM_METEOR_FALLS_1F_1R_TM_IRON_TAIL (HOENN_FLAGS_START + 0x26E)
#undef  FLAG_ITEM_METEOR_FALLS_B1F_2R_TM_DRAGON_CLAW
#define FLAG_ITEM_METEOR_FALLS_B1F_2R_TM_DRAGON_CLAW (HOENN_FLAGS_START + 0x26F)
#undef  FLAG_ITEM_MOSSDEEP_CITY_NET_BALL
#define FLAG_ITEM_MOSSDEEP_CITY_NET_BALL (HOENN_FLAGS_START + 0x270)
#undef  FLAG_ITEM_MT_PYRE_2F_ULTRA_BALL
#define FLAG_ITEM_MT_PYRE_2F_ULTRA_BALL (HOENN_FLAGS_START + 0x271)
#undef  FLAG_ITEM_MT_PYRE_3F_SUPER_REPEL
#define FLAG_ITEM_MT_PYRE_3F_SUPER_REPEL (HOENN_FLAGS_START + 0x272)
#undef  FLAG_ITEM_MT_PYRE_4F_SEA_INCENSE
#define FLAG_ITEM_MT_PYRE_4F_SEA_INCENSE (HOENN_FLAGS_START + 0x273)
#undef  FLAG_ITEM_MT_PYRE_5F_LAX_INCENSE
#define FLAG_ITEM_MT_PYRE_5F_LAX_INCENSE (HOENN_FLAGS_START + 0x274)
#undef  FLAG_ITEM_MT_PYRE_6F_TM_SHADOW_BALL
#define FLAG_ITEM_MT_PYRE_6F_TM_SHADOW_BALL (HOENN_FLAGS_START + 0x275)
#undef  FLAG_ITEM_MT_PYRE_EXTERIOR_MAX_POTION
#define FLAG_ITEM_MT_PYRE_EXTERIOR_MAX_POTION (HOENN_FLAGS_START + 0x276)
#undef  FLAG_ITEM_MT_PYRE_EXTERIOR_TM_SKILL_SWAP
#define FLAG_ITEM_MT_PYRE_EXTERIOR_TM_SKILL_SWAP (HOENN_FLAGS_START + 0x277)
#undef  FLAG_ITEM_NEW_MAUVILLE_ESCAPE_ROPE
#define FLAG_ITEM_NEW_MAUVILLE_ESCAPE_ROPE (HOENN_FLAGS_START + 0x278)
#undef  FLAG_ITEM_NEW_MAUVILLE_FULL_HEAL
#define FLAG_ITEM_NEW_MAUVILLE_FULL_HEAL (HOENN_FLAGS_START + 0x279)
#undef  FLAG_ITEM_NEW_MAUVILLE_PARALYZE_HEAL
#define FLAG_ITEM_NEW_MAUVILLE_PARALYZE_HEAL (HOENN_FLAGS_START + 0x27A)
#undef  FLAG_ITEM_NEW_MAUVILLE_THUNDER_STONE
#define FLAG_ITEM_NEW_MAUVILLE_THUNDER_STONE (HOENN_FLAGS_START + 0x27B)
#undef  FLAG_ITEM_NEW_MAUVILLE_ULTRA_BALL
#define FLAG_ITEM_NEW_MAUVILLE_ULTRA_BALL (HOENN_FLAGS_START + 0x27C)
#undef  FLAG_ITEM_PETALBURG_CITY_ETHER
#define FLAG_ITEM_PETALBURG_CITY_ETHER (HOENN_FLAGS_START + 0x27D)
#undef  FLAG_ITEM_PETALBURG_CITY_MAX_REVIVE
#define FLAG_ITEM_PETALBURG_CITY_MAX_REVIVE (HOENN_FLAGS_START + 0x27E)
#undef  FLAG_ITEM_PETALBURG_WOODS_ETHER
#define FLAG_ITEM_PETALBURG_WOODS_ETHER (HOENN_FLAGS_START + 0x27F)
#undef  FLAG_ITEM_PETALBURG_WOODS_GREAT_BALL
#define FLAG_ITEM_PETALBURG_WOODS_GREAT_BALL (HOENN_FLAGS_START + 0x280)
#undef  FLAG_ITEM_PETALBURG_WOODS_PARALYZE_HEAL
#define FLAG_ITEM_PETALBURG_WOODS_PARALYZE_HEAL (HOENN_FLAGS_START + 0x281)
#undef  FLAG_ITEM_PETALBURG_WOODS_X_ATTACK
#define FLAG_ITEM_PETALBURG_WOODS_X_ATTACK (HOENN_FLAGS_START + 0x282)
#undef  FLAG_ITEM_ROUTE_102_POTION
#define FLAG_ITEM_ROUTE_102_POTION (HOENN_FLAGS_START + 0x283)
#undef  FLAG_ITEM_ROUTE_104_POKE_BALL
#define FLAG_ITEM_ROUTE_104_POKE_BALL (HOENN_FLAGS_START + 0x284)
#undef  FLAG_ITEM_ROUTE_104_POTION
#define FLAG_ITEM_ROUTE_104_POTION (HOENN_FLAGS_START + 0x285)
#undef  FLAG_ITEM_ROUTE_104_PP_UP
#define FLAG_ITEM_ROUTE_104_PP_UP (HOENN_FLAGS_START + 0x286)
#undef  FLAG_ITEM_ROUTE_104_X_ACCURACY
#define FLAG_ITEM_ROUTE_104_X_ACCURACY (HOENN_FLAGS_START + 0x287)
#undef  FLAG_ITEM_ROUTE_105_IRON
#define FLAG_ITEM_ROUTE_105_IRON (HOENN_FLAGS_START + 0x288)
#undef  FLAG_ITEM_ROUTE_106_PROTEIN
#define FLAG_ITEM_ROUTE_106_PROTEIN (HOENN_FLAGS_START + 0x289)
#undef  FLAG_ITEM_ROUTE_108_STAR_PIECE
#define FLAG_ITEM_ROUTE_108_STAR_PIECE (HOENN_FLAGS_START + 0x28A)
#undef  FLAG_ITEM_ROUTE_109_POTION
#define FLAG_ITEM_ROUTE_109_POTION (HOENN_FLAGS_START + 0x28B)
#undef  FLAG_ITEM_ROUTE_109_PP_UP
#define FLAG_ITEM_ROUTE_109_PP_UP (HOENN_FLAGS_START + 0x28C)
#undef  FLAG_ITEM_ROUTE_110_DIRE_HIT
#define FLAG_ITEM_ROUTE_110_DIRE_HIT (HOENN_FLAGS_START + 0x28D)
#undef  FLAG_ITEM_ROUTE_110_ELIXIR
#define FLAG_ITEM_ROUTE_110_ELIXIR (HOENN_FLAGS_START + 0x28E)
#undef  FLAG_ITEM_ROUTE_110_RARE_CANDY
#define FLAG_ITEM_ROUTE_110_RARE_CANDY (HOENN_FLAGS_START + 0x28F)
#undef  FLAG_ITEM_ROUTE_111_ELIXIR
#define FLAG_ITEM_ROUTE_111_ELIXIR (HOENN_FLAGS_START + 0x290)
#undef  FLAG_ITEM_ROUTE_111_HP_UP
#define FLAG_ITEM_ROUTE_111_HP_UP (HOENN_FLAGS_START + 0x291)
#undef  FLAG_ITEM_ROUTE_111_STARDUST
#define FLAG_ITEM_ROUTE_111_STARDUST (HOENN_FLAGS_START + 0x292)
#undef  FLAG_ITEM_ROUTE_111_TM_SANDSTORM
#define FLAG_ITEM_ROUTE_111_TM_SANDSTORM (HOENN_FLAGS_START + 0x293)
#undef  FLAG_ITEM_ROUTE_112_NUGGET
#define FLAG_ITEM_ROUTE_112_NUGGET (HOENN_FLAGS_START + 0x294)
#undef  FLAG_ITEM_ROUTE_113_HYPER_POTION
#define FLAG_ITEM_ROUTE_113_HYPER_POTION (HOENN_FLAGS_START + 0x295)
#undef  FLAG_ITEM_ROUTE_113_MAX_ETHER
#define FLAG_ITEM_ROUTE_113_MAX_ETHER (HOENN_FLAGS_START + 0x296)
#undef  FLAG_ITEM_ROUTE_113_SUPER_REPEL
#define FLAG_ITEM_ROUTE_113_SUPER_REPEL (HOENN_FLAGS_START + 0x297)
#undef  FLAG_ITEM_ROUTE_114_ENERGY_POWDER
#define FLAG_ITEM_ROUTE_114_ENERGY_POWDER (HOENN_FLAGS_START + 0x298)
#undef  FLAG_ITEM_ROUTE_114_PROTEIN
#define FLAG_ITEM_ROUTE_114_PROTEIN (HOENN_FLAGS_START + 0x299)
#undef  FLAG_ITEM_ROUTE_114_RARE_CANDY
#define FLAG_ITEM_ROUTE_114_RARE_CANDY (HOENN_FLAGS_START + 0x29A)
#undef  FLAG_ITEM_ROUTE_115_GREAT_BALL
#define FLAG_ITEM_ROUTE_115_GREAT_BALL (HOENN_FLAGS_START + 0x29B)
#undef  FLAG_ITEM_ROUTE_115_HEAL_POWDER
#define FLAG_ITEM_ROUTE_115_HEAL_POWDER (HOENN_FLAGS_START + 0x29C)
#undef  FLAG_ITEM_ROUTE_115_IRON
#define FLAG_ITEM_ROUTE_115_IRON (HOENN_FLAGS_START + 0x29D)
#undef  FLAG_ITEM_ROUTE_115_PP_UP
#define FLAG_ITEM_ROUTE_115_PP_UP (HOENN_FLAGS_START + 0x29E)
#undef  FLAG_ITEM_ROUTE_115_SUPER_POTION
#define FLAG_ITEM_ROUTE_115_SUPER_POTION (HOENN_FLAGS_START + 0x29F)
#undef  FLAG_ITEM_ROUTE_115_TM_FOCUS_PUNCH
#define FLAG_ITEM_ROUTE_115_TM_FOCUS_PUNCH (HOENN_FLAGS_START + 0x2A0)
#undef  FLAG_ITEM_ROUTE_116_ETHER
#define FLAG_ITEM_ROUTE_116_ETHER (HOENN_FLAGS_START + 0x2A1)
#undef  FLAG_ITEM_ROUTE_116_HP_UP
#define FLAG_ITEM_ROUTE_116_HP_UP (HOENN_FLAGS_START + 0x2A2)
#undef  FLAG_ITEM_ROUTE_116_POTION
#define FLAG_ITEM_ROUTE_116_POTION (HOENN_FLAGS_START + 0x2A3)
#undef  FLAG_ITEM_ROUTE_116_REPEL
#define FLAG_ITEM_ROUTE_116_REPEL (HOENN_FLAGS_START + 0x2A4)
#undef  FLAG_ITEM_ROUTE_116_X_SPECIAL
#define FLAG_ITEM_ROUTE_116_X_SPECIAL (HOENN_FLAGS_START + 0x2A5)
#undef  FLAG_ITEM_ROUTE_117_GREAT_BALL
#define FLAG_ITEM_ROUTE_117_GREAT_BALL (HOENN_FLAGS_START + 0x2A6)
#undef  FLAG_ITEM_ROUTE_117_REVIVE
#define FLAG_ITEM_ROUTE_117_REVIVE (HOENN_FLAGS_START + 0x2A7)
#undef  FLAG_ITEM_ROUTE_118_HYPER_POTION
#define FLAG_ITEM_ROUTE_118_HYPER_POTION (HOENN_FLAGS_START + 0x2A8)
#undef  FLAG_ITEM_ROUTE_119_ELIXIR_1
#define FLAG_ITEM_ROUTE_119_ELIXIR_1 (HOENN_FLAGS_START + 0x2A9)
#undef  FLAG_ITEM_ROUTE_119_ELIXIR_2
#define FLAG_ITEM_ROUTE_119_ELIXIR_2 (HOENN_FLAGS_START + 0x2AA)
#undef  FLAG_ITEM_ROUTE_119_HYPER_POTION_1
#define FLAG_ITEM_ROUTE_119_HYPER_POTION_1 (HOENN_FLAGS_START + 0x2AB)
#undef  FLAG_ITEM_ROUTE_119_HYPER_POTION_2
#define FLAG_ITEM_ROUTE_119_HYPER_POTION_2 (HOENN_FLAGS_START + 0x2AC)
#undef  FLAG_ITEM_ROUTE_119_LEAF_STONE
#define FLAG_ITEM_ROUTE_119_LEAF_STONE (HOENN_FLAGS_START + 0x2AD)
#undef  FLAG_ITEM_ROUTE_119_NUGGET
#define FLAG_ITEM_ROUTE_119_NUGGET (HOENN_FLAGS_START + 0x2AE)
#undef  FLAG_ITEM_ROUTE_119_RARE_CANDY
#define FLAG_ITEM_ROUTE_119_RARE_CANDY (HOENN_FLAGS_START + 0x2AF)
#undef  FLAG_ITEM_ROUTE_119_SUPER_REPEL
#define FLAG_ITEM_ROUTE_119_SUPER_REPEL (HOENN_FLAGS_START + 0x2B0)
#undef  FLAG_ITEM_ROUTE_119_ZINC
#define FLAG_ITEM_ROUTE_119_ZINC (HOENN_FLAGS_START + 0x2B1)
#undef  FLAG_ITEM_ROUTE_120_FULL_HEAL
#define FLAG_ITEM_ROUTE_120_FULL_HEAL (HOENN_FLAGS_START + 0x2B2)
#undef  FLAG_ITEM_ROUTE_120_HYPER_POTION
#define FLAG_ITEM_ROUTE_120_HYPER_POTION (HOENN_FLAGS_START + 0x2B3)
#undef  FLAG_ITEM_ROUTE_120_NEST_BALL
#define FLAG_ITEM_ROUTE_120_NEST_BALL (HOENN_FLAGS_START + 0x2B4)
#undef  FLAG_ITEM_ROUTE_120_NUGGET
#define FLAG_ITEM_ROUTE_120_NUGGET (HOENN_FLAGS_START + 0x2B5)
#undef  FLAG_ITEM_ROUTE_120_REVIVE
#define FLAG_ITEM_ROUTE_120_REVIVE (HOENN_FLAGS_START + 0x2B6)
#undef  FLAG_ITEM_ROUTE_121_CARBOS
#define FLAG_ITEM_ROUTE_121_CARBOS (HOENN_FLAGS_START + 0x2B7)
#undef  FLAG_ITEM_ROUTE_121_REVIVE
#define FLAG_ITEM_ROUTE_121_REVIVE (HOENN_FLAGS_START + 0x2B8)
#undef  FLAG_ITEM_ROUTE_121_ZINC
#define FLAG_ITEM_ROUTE_121_ZINC (HOENN_FLAGS_START + 0x2B9)
#undef  FLAG_ITEM_ROUTE_123_CALCIUM
#define FLAG_ITEM_ROUTE_123_CALCIUM (HOENN_FLAGS_START + 0x2BA)
#undef  FLAG_ITEM_ROUTE_123_ELIXIR
#define FLAG_ITEM_ROUTE_123_ELIXIR (HOENN_FLAGS_START + 0x2BB)
#undef  FLAG_ITEM_ROUTE_123_PP_UP
#define FLAG_ITEM_ROUTE_123_PP_UP (HOENN_FLAGS_START + 0x2BC)
#undef  FLAG_ITEM_ROUTE_123_REVIVAL_HERB
#define FLAG_ITEM_ROUTE_123_REVIVAL_HERB (HOENN_FLAGS_START + 0x2BD)
#undef  FLAG_ITEM_ROUTE_123_ULTRA_BALL
#define FLAG_ITEM_ROUTE_123_ULTRA_BALL (HOENN_FLAGS_START + 0x2BE)
#undef  FLAG_ITEM_ROUTE_124_BLUE_SHARD
#define FLAG_ITEM_ROUTE_124_BLUE_SHARD (HOENN_FLAGS_START + 0x2BF)
#undef  FLAG_ITEM_ROUTE_124_RED_SHARD
#define FLAG_ITEM_ROUTE_124_RED_SHARD (HOENN_FLAGS_START + 0x2C0)
#undef  FLAG_ITEM_ROUTE_124_YELLOW_SHARD
#define FLAG_ITEM_ROUTE_124_YELLOW_SHARD (HOENN_FLAGS_START + 0x2C1)
#undef  FLAG_ITEM_ROUTE_125_BIG_PEARL
#define FLAG_ITEM_ROUTE_125_BIG_PEARL (HOENN_FLAGS_START + 0x2C2)
#undef  FLAG_ITEM_ROUTE_126_GREEN_SHARD
#define FLAG_ITEM_ROUTE_126_GREEN_SHARD (HOENN_FLAGS_START + 0x2C3)
#undef  FLAG_ITEM_ROUTE_127_CARBOS
#define FLAG_ITEM_ROUTE_127_CARBOS (HOENN_FLAGS_START + 0x2C4)
#undef  FLAG_ITEM_ROUTE_127_RARE_CANDY
#define FLAG_ITEM_ROUTE_127_RARE_CANDY (HOENN_FLAGS_START + 0x2C5)
#undef  FLAG_ITEM_ROUTE_127_ZINC
#define FLAG_ITEM_ROUTE_127_ZINC (HOENN_FLAGS_START + 0x2C6)
#undef  FLAG_ITEM_ROUTE_132_PROTEIN
#define FLAG_ITEM_ROUTE_132_PROTEIN (HOENN_FLAGS_START + 0x2C7)
#undef  FLAG_ITEM_ROUTE_132_RARE_CANDY
#define FLAG_ITEM_ROUTE_132_RARE_CANDY (HOENN_FLAGS_START + 0x2C8)
#undef  FLAG_ITEM_ROUTE_133_BIG_PEARL
#define FLAG_ITEM_ROUTE_133_BIG_PEARL (HOENN_FLAGS_START + 0x2C9)
#undef  FLAG_ITEM_ROUTE_133_MAX_REVIVE
#define FLAG_ITEM_ROUTE_133_MAX_REVIVE (HOENN_FLAGS_START + 0x2CA)
#undef  FLAG_ITEM_ROUTE_133_STAR_PIECE
#define FLAG_ITEM_ROUTE_133_STAR_PIECE (HOENN_FLAGS_START + 0x2CB)
#undef  FLAG_ITEM_ROUTE_134_CARBOS
#define FLAG_ITEM_ROUTE_134_CARBOS (HOENN_FLAGS_START + 0x2CC)
#undef  FLAG_ITEM_ROUTE_134_STAR_PIECE
#define FLAG_ITEM_ROUTE_134_STAR_PIECE (HOENN_FLAGS_START + 0x2CD)
#undef  FLAG_ITEM_RUSTBORO_CITY_X_DEFEND
#define FLAG_ITEM_RUSTBORO_CITY_X_DEFEND (HOENN_FLAGS_START + 0x2CE)
#undef  FLAG_ITEM_RUSTURF_TUNNEL_MAX_ETHER
#define FLAG_ITEM_RUSTURF_TUNNEL_MAX_ETHER (HOENN_FLAGS_START + 0x2CF)
#undef  FLAG_ITEM_RUSTURF_TUNNEL_POKE_BALL
#define FLAG_ITEM_RUSTURF_TUNNEL_POKE_BALL (HOENN_FLAGS_START + 0x2D0)
#undef  FLAG_ITEM_SAFARI_ZONE_NORTH_CALCIUM
#define FLAG_ITEM_SAFARI_ZONE_NORTH_CALCIUM (HOENN_FLAGS_START + 0x2D1)
#undef  FLAG_ITEM_SAFARI_ZONE_NORTH_EAST_NUGGET
#define FLAG_ITEM_SAFARI_ZONE_NORTH_EAST_NUGGET (HOENN_FLAGS_START + 0x2D2)
#undef  FLAG_ITEM_SAFARI_ZONE_NORTH_WEST_TM_SOLAR_BEAM
#define FLAG_ITEM_SAFARI_ZONE_NORTH_WEST_TM_SOLAR_BEAM (HOENN_FLAGS_START + 0x2D3)
#undef  FLAG_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL
#define FLAG_ITEM_SAFARI_ZONE_SOUTH_EAST_BIG_PEARL (HOENN_FLAGS_START + 0x2D4)
#undef  FLAG_ITEM_SAFARI_ZONE_SOUTH_WEST_MAX_REVIVE
#define FLAG_ITEM_SAFARI_ZONE_SOUTH_WEST_MAX_REVIVE (HOENN_FLAGS_START + 0x2D5)
#undef  FLAG_ITEM_SCORCHED_SLAB_TM_SUNNY_DAY
#define FLAG_ITEM_SCORCHED_SLAB_TM_SUNNY_DAY (HOENN_FLAGS_START + 0x2D6)
#undef  FLAG_ITEM_SEAFLOOR_CAVERN_ROOM_9_TM_EARTHQUAKE
#define FLAG_ITEM_SEAFLOOR_CAVERN_ROOM_9_TM_EARTHQUAKE (HOENN_FLAGS_START + 0x2D7)
#undef  FLAG_ITEM_SHOAL_CAVE_ENTRANCE_BIG_PEARL
#define FLAG_ITEM_SHOAL_CAVE_ENTRANCE_BIG_PEARL (HOENN_FLAGS_START + 0x2D8)
#undef  FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_NEVER_MELT_ICE
#define FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_NEVER_MELT_ICE (HOENN_FLAGS_START + 0x2D9)
#undef  FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_TM_HAIL
#define FLAG_ITEM_SHOAL_CAVE_ICE_ROOM_TM_HAIL (HOENN_FLAGS_START + 0x2DA)
#undef  FLAG_ITEM_SHOAL_CAVE_INNER_ROOM_RARE_CANDY
#define FLAG_ITEM_SHOAL_CAVE_INNER_ROOM_RARE_CANDY (HOENN_FLAGS_START + 0x2DB)
#undef  FLAG_ITEM_SHOAL_CAVE_STAIRS_ROOM_ICE_HEAL
#define FLAG_ITEM_SHOAL_CAVE_STAIRS_ROOM_ICE_HEAL (HOENN_FLAGS_START + 0x2DC)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_ORANGE_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_1_ORANGE_MAIL (HOENN_FLAGS_START + 0x2DD)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_HARBOR_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_HARBOR_MAIL (HOENN_FLAGS_START + 0x2DE)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_WAVE_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_2_WAVE_MAIL (HOENN_FLAGS_START + 0x2DF)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_SHADOW_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_SHADOW_MAIL (HOENN_FLAGS_START + 0x2E0)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_WOOD_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_3_WOOD_MAIL (HOENN_FLAGS_START + 0x2E1)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_MECH_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_4_MECH_MAIL (HOENN_FLAGS_START + 0x2E2)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_6_GLITTER_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_6_GLITTER_MAIL (HOENN_FLAGS_START + 0x2E3)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_7_TROPIC_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_7_TROPIC_MAIL (HOENN_FLAGS_START + 0x2E4)
#undef  FLAG_ITEM_TRICK_HOUSE_PUZZLE_8_BEAD_MAIL
#define FLAG_ITEM_TRICK_HOUSE_PUZZLE_8_BEAD_MAIL (HOENN_FLAGS_START + 0x2E5)
#undef  FLAG_ITEM_VICTORY_ROAD_1F_MAX_ELIXIR
#define FLAG_ITEM_VICTORY_ROAD_1F_MAX_ELIXIR (HOENN_FLAGS_START + 0x2E6)
#undef  FLAG_ITEM_VICTORY_ROAD_1F_PP_UP
#define FLAG_ITEM_VICTORY_ROAD_1F_PP_UP (HOENN_FLAGS_START + 0x2E7)
#undef  FLAG_ITEM_VICTORY_ROAD_B1F_FULL_RESTORE
#define FLAG_ITEM_VICTORY_ROAD_B1F_FULL_RESTORE (HOENN_FLAGS_START + 0x2E8)
#undef  FLAG_ITEM_VICTORY_ROAD_B1F_TM_PSYCHIC
#define FLAG_ITEM_VICTORY_ROAD_B1F_TM_PSYCHIC (HOENN_FLAGS_START + 0x2E9)
#undef  FLAG_ITEM_VICTORY_ROAD_B2F_FULL_HEAL
#define FLAG_ITEM_VICTORY_ROAD_B2F_FULL_HEAL (HOENN_FLAGS_START + 0x2EA)
#undef  FLAG_LEARNED_ALL_MOVES_AT_CAPE_BRINK
#define FLAG_LEARNED_ALL_MOVES_AT_CAPE_BRINK (HOENN_FLAGS_START + 0x2EB)
#undef  FLAG_MET_STICKER_MAN
#define FLAG_MET_STICKER_MAN (HOENN_FLAGS_START + 0x2EC)
#undef  FLAG_MYSTERY_GIFT_1
#define FLAG_MYSTERY_GIFT_1 (HOENN_FLAGS_START + 0x2ED)
#undef  FLAG_MYSTERY_GIFT_10
#define FLAG_MYSTERY_GIFT_10 (HOENN_FLAGS_START + 0x2EE)
#undef  FLAG_MYSTERY_GIFT_11
#define FLAG_MYSTERY_GIFT_11 (HOENN_FLAGS_START + 0x2EF)
#undef  FLAG_MYSTERY_GIFT_12
#define FLAG_MYSTERY_GIFT_12 (HOENN_FLAGS_START + 0x2F0)
#undef  FLAG_MYSTERY_GIFT_13
#define FLAG_MYSTERY_GIFT_13 (HOENN_FLAGS_START + 0x2F1)
#undef  FLAG_MYSTERY_GIFT_14
#define FLAG_MYSTERY_GIFT_14 (HOENN_FLAGS_START + 0x2F2)
#undef  FLAG_MYSTERY_GIFT_15
#define FLAG_MYSTERY_GIFT_15 (HOENN_FLAGS_START + 0x2F3)
#undef  FLAG_MYSTERY_GIFT_2
#define FLAG_MYSTERY_GIFT_2 (HOENN_FLAGS_START + 0x2F4)
#undef  FLAG_MYSTERY_GIFT_3
#define FLAG_MYSTERY_GIFT_3 (HOENN_FLAGS_START + 0x2F5)
#undef  FLAG_MYSTERY_GIFT_4
#define FLAG_MYSTERY_GIFT_4 (HOENN_FLAGS_START + 0x2F6)
#undef  FLAG_MYSTERY_GIFT_5
#define FLAG_MYSTERY_GIFT_5 (HOENN_FLAGS_START + 0x2F7)
#undef  FLAG_MYSTERY_GIFT_6
#define FLAG_MYSTERY_GIFT_6 (HOENN_FLAGS_START + 0x2F8)
#undef  FLAG_MYSTERY_GIFT_7
#define FLAG_MYSTERY_GIFT_7 (HOENN_FLAGS_START + 0x2F9)
#undef  FLAG_MYSTERY_GIFT_8
#define FLAG_MYSTERY_GIFT_8 (HOENN_FLAGS_START + 0x2FA)
#undef  FLAG_MYSTERY_GIFT_9
#define FLAG_MYSTERY_GIFT_9 (HOENN_FLAGS_START + 0x2FB)
#undef  FLAG_MYSTERY_GIFT_DONE
#define FLAG_MYSTERY_GIFT_DONE (HOENN_FLAGS_START + 0x2FC)
#undef  FLAG_NURSE_MENTIONS_GOLD_CARD
#define FLAG_NURSE_MENTIONS_GOLD_CARD (HOENN_FLAGS_START + 0x2FD)
#undef  FLAG_OAKS_RATING_IS_VIA_PC
#define FLAG_OAKS_RATING_IS_VIA_PC (HOENN_FLAGS_START + 0x2FE)
#undef  FLAG_OAK_SAW_DEX_COMPLETION
#define FLAG_OAK_SAW_DEX_COMPLETION (HOENN_FLAGS_START + 0x2FF)
#undef  FLAG_OCEANIC_MUSEUM_MET_REPORTER
#define FLAG_OCEANIC_MUSEUM_MET_REPORTER (HOENN_FLAGS_START + 0x300)
#undef  FLAG_OPENED_START_MENU
#define FLAG_OPENED_START_MENU (HOENN_FLAGS_START + 0x301)
#undef  FLAG_POKEMON_MANSION_SWITCH_STATE
#define FLAG_POKEMON_MANSION_SWITCH_STATE (HOENN_FLAGS_START + 0x302)
#undef  FLAG_RECEIVED_AMULET_COIN
#define FLAG_RECEIVED_AMULET_COIN (HOENN_FLAGS_START + 0x303)
#undef  FLAG_RECEIVED_AURORA_TICKET
#define FLAG_RECEIVED_AURORA_TICKET (HOENN_FLAGS_START + 0x304)
#undef  FLAG_RECEIVED_MYSTIC_TICKET
#define FLAG_RECEIVED_MYSTIC_TICKET (HOENN_FLAGS_START + 0x305)
#undef  FLAG_RECEIVED_OLD_SEA_MAP
#define FLAG_RECEIVED_OLD_SEA_MAP (HOENN_FLAGS_START + 0x306)
#undef  FLAG_RECEIVED_SS_TICKET
#define FLAG_RECEIVED_SS_TICKET (HOENN_FLAGS_START + 0x307)
#undef  FLAG_REGISTERED_DRAKE
#define FLAG_REGISTERED_DRAKE (HOENN_FLAGS_START + 0x308)
#undef  FLAG_REGISTERED_GLACIA
#define FLAG_REGISTERED_GLACIA (HOENN_FLAGS_START + 0x309)
#undef  FLAG_REGISTERED_PHOEBE
#define FLAG_REGISTERED_PHOEBE (HOENN_FLAGS_START + 0x30A)
#undef  FLAG_REGISTERED_SIDNEY
#define FLAG_REGISTERED_SIDNEY (HOENN_FLAGS_START + 0x30B)
#undef  FLAG_REGISTERED_WALLACE
#define FLAG_REGISTERED_WALLACE (HOENN_FLAGS_START + 0x30C)
#undef  FLAG_SECRET_BASE_REGISTRY_ENABLED
#define FLAG_SECRET_BASE_REGISTRY_ENABLED (HOENN_FLAGS_START + 0x30D)
#undef  FLAG_SILPH_10F_DOOR
#define FLAG_SILPH_10F_DOOR (HOENN_FLAGS_START + 0x30E)
#undef  FLAG_SILPH_11F_DOOR
#define FLAG_SILPH_11F_DOOR (HOENN_FLAGS_START + 0x30F)
#undef  FLAG_SILPH_2F_DOOR_1
#define FLAG_SILPH_2F_DOOR_1 (HOENN_FLAGS_START + 0x310)
#undef  FLAG_SILPH_2F_DOOR_2
#define FLAG_SILPH_2F_DOOR_2 (HOENN_FLAGS_START + 0x311)
#undef  FLAG_SILPH_3F_DOOR_1
#define FLAG_SILPH_3F_DOOR_1 (HOENN_FLAGS_START + 0x312)
#undef  FLAG_SILPH_3F_DOOR_2
#define FLAG_SILPH_3F_DOOR_2 (HOENN_FLAGS_START + 0x313)
#undef  FLAG_SILPH_4F_DOOR_1
#define FLAG_SILPH_4F_DOOR_1 (HOENN_FLAGS_START + 0x314)
#undef  FLAG_SILPH_4F_DOOR_2
#define FLAG_SILPH_4F_DOOR_2 (HOENN_FLAGS_START + 0x315)
#undef  FLAG_SILPH_5F_DOOR_1
#define FLAG_SILPH_5F_DOOR_1 (HOENN_FLAGS_START + 0x316)
#undef  FLAG_SILPH_5F_DOOR_2
#define FLAG_SILPH_5F_DOOR_2 (HOENN_FLAGS_START + 0x317)
#undef  FLAG_SILPH_5F_DOOR_3
#define FLAG_SILPH_5F_DOOR_3 (HOENN_FLAGS_START + 0x318)
#undef  FLAG_SILPH_6F_DOOR
#define FLAG_SILPH_6F_DOOR (HOENN_FLAGS_START + 0x319)
#undef  FLAG_SILPH_7F_DOOR_1
#define FLAG_SILPH_7F_DOOR_1 (HOENN_FLAGS_START + 0x31A)
#undef  FLAG_SILPH_7F_DOOR_2
#define FLAG_SILPH_7F_DOOR_2 (HOENN_FLAGS_START + 0x31B)
#undef  FLAG_SILPH_7F_DOOR_3
#define FLAG_SILPH_7F_DOOR_3 (HOENN_FLAGS_START + 0x31C)
#undef  FLAG_SILPH_8F_DOOR
#define FLAG_SILPH_8F_DOOR (HOENN_FLAGS_START + 0x31D)
#undef  FLAG_SILPH_9F_DOOR_1
#define FLAG_SILPH_9F_DOOR_1 (HOENN_FLAGS_START + 0x31E)
#undef  FLAG_SILPH_9F_DOOR_2
#define FLAG_SILPH_9F_DOOR_2 (HOENN_FLAGS_START + 0x31F)
#undef  FLAG_SILPH_9F_DOOR_3
#define FLAG_SILPH_9F_DOOR_3 (HOENN_FLAGS_START + 0x320)
#undef  FLAG_SILPH_9F_DOOR_4
#define FLAG_SILPH_9F_DOOR_4 (HOENN_FLAGS_START + 0x321)
#undef  FLAG_SYS_CHANGED_DEWFORD_TREND
#define FLAG_SYS_CHANGED_DEWFORD_TREND (HOENN_FLAGS_START + 0x322)
#undef  FLAG_SYS_CHAT_USED
#define FLAG_SYS_CHAT_USED (HOENN_FLAGS_START + 0x323)
#undef  FLAG_SYS_CRUISE_MODE
#define FLAG_SYS_CRUISE_MODE (HOENN_FLAGS_START + 0x324)
#undef  FLAG_SYS_MIX_RECORD
#define FLAG_SYS_MIX_RECORD (HOENN_FLAGS_START + 0x325)
#undef  FLAG_SYS_SET_TRAINER_CARD_PROFILE
#define FLAG_SYS_SET_TRAINER_CARD_PROFILE (HOENN_FLAGS_START + 0x326)
#undef  FLAG_SYS_TV_HOME
#define FLAG_SYS_TV_HOME (HOENN_FLAGS_START + 0x327)
#undef  FLAG_SYS_TV_LATIAS_LATIOS
#define FLAG_SYS_TV_LATIAS_LATIOS (HOENN_FLAGS_START + 0x328)
#undef  FLAG_SYS_TV_WATCH
#define FLAG_SYS_TV_WATCH (HOENN_FLAGS_START + 0x329)
#undef  FLAG_TUTOR_BLAST_BURN
#define FLAG_TUTOR_BLAST_BURN (HOENN_FLAGS_START + 0x32A)
#undef  FLAG_TUTOR_BODY_SLAM
#define FLAG_TUTOR_BODY_SLAM (HOENN_FLAGS_START + 0x32B)
#undef  FLAG_TUTOR_COUNTER
#define FLAG_TUTOR_COUNTER (HOENN_FLAGS_START + 0x32C)
#undef  FLAG_TUTOR_DOUBLE_EDGE
#define FLAG_TUTOR_DOUBLE_EDGE (HOENN_FLAGS_START + 0x32D)
#undef  FLAG_TUTOR_DREAM_EATER
#define FLAG_TUTOR_DREAM_EATER (HOENN_FLAGS_START + 0x32E)
#undef  FLAG_TUTOR_EXPLOSION
#define FLAG_TUTOR_EXPLOSION (HOENN_FLAGS_START + 0x32F)
#undef  FLAG_TUTOR_FRENZY_PLANT
#define FLAG_TUTOR_FRENZY_PLANT (HOENN_FLAGS_START + 0x330)
#undef  FLAG_TUTOR_HYDRO_CANNON
#define FLAG_TUTOR_HYDRO_CANNON (HOENN_FLAGS_START + 0x331)
#undef  FLAG_TUTOR_MEGA_KICK
#define FLAG_TUTOR_MEGA_KICK (HOENN_FLAGS_START + 0x332)
#undef  FLAG_TUTOR_MEGA_PUNCH
#define FLAG_TUTOR_MEGA_PUNCH (HOENN_FLAGS_START + 0x333)
#undef  FLAG_TUTOR_METRONOME
#define FLAG_TUTOR_METRONOME (HOENN_FLAGS_START + 0x334)
#undef  FLAG_TUTOR_MIMIC
#define FLAG_TUTOR_MIMIC (HOENN_FLAGS_START + 0x335)
#undef  FLAG_TUTOR_ROCK_SLIDE
#define FLAG_TUTOR_ROCK_SLIDE (HOENN_FLAGS_START + 0x336)
#undef  FLAG_TUTOR_SEISMIC_TOSS
#define FLAG_TUTOR_SEISMIC_TOSS (HOENN_FLAGS_START + 0x337)
#undef  FLAG_TUTOR_SOFT_BOILED
#define FLAG_TUTOR_SOFT_BOILED (HOENN_FLAGS_START + 0x338)
#undef  FLAG_TUTOR_SUBSTITUTE
#define FLAG_TUTOR_SUBSTITUTE (HOENN_FLAGS_START + 0x339)
#undef  FLAG_TUTOR_SWORDS_DANCE
#define FLAG_TUTOR_SWORDS_DANCE (HOENN_FLAGS_START + 0x33A)
#undef  FLAG_TUTOR_THUNDER_WAVE
#define FLAG_TUTOR_THUNDER_WAVE (HOENN_FLAGS_START + 0x33B)
#undef  FLAG_UNLOCKED_TRENDY_SAYINGS
#define FLAG_UNLOCKED_TRENDY_SAYINGS (HOENN_FLAGS_START + 0x33C)
#undef  FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE
#define FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE (HOENN_FLAGS_START + 0x33D)
#undef  FLAG_WORLD_MAP_CELADON_CITY
#define FLAG_WORLD_MAP_CELADON_CITY (HOENN_FLAGS_START + 0x33E)
#undef  FLAG_WORLD_MAP_CERULEAN_CAVE_1F
#define FLAG_WORLD_MAP_CERULEAN_CAVE_1F (HOENN_FLAGS_START + 0x33F)
#undef  FLAG_WORLD_MAP_CERULEAN_CITY
#define FLAG_WORLD_MAP_CERULEAN_CITY (HOENN_FLAGS_START + 0x340)
#undef  FLAG_WORLD_MAP_CINNABAR_ISLAND
#define FLAG_WORLD_MAP_CINNABAR_ISLAND (HOENN_FLAGS_START + 0x341)
#undef  FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F
#define FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F (HOENN_FLAGS_START + 0x342)
#undef  FLAG_WORLD_MAP_FIVE_ISLAND
#define FLAG_WORLD_MAP_FIVE_ISLAND (HOENN_FLAGS_START + 0x343)
#undef  FLAG_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE
#define FLAG_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE (HOENN_FLAGS_START + 0x344)
#undef  FLAG_WORLD_MAP_FOUR_ISLAND
#define FLAG_WORLD_MAP_FOUR_ISLAND (HOENN_FLAGS_START + 0x345)
#undef  FLAG_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE
#define FLAG_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE (HOENN_FLAGS_START + 0x346)
#undef  FLAG_WORLD_MAP_FUCHSIA_CITY
#define FLAG_WORLD_MAP_FUCHSIA_CITY (HOENN_FLAGS_START + 0x347)
#undef  FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR
#define FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR (HOENN_FLAGS_START + 0x348)
#undef  FLAG_WORLD_MAP_LAVENDER_TOWN
#define FLAG_WORLD_MAP_LAVENDER_TOWN (HOENN_FLAGS_START + 0x349)
#undef  FLAG_WORLD_MAP_MT_EMBER_EXTERIOR
#define FLAG_WORLD_MAP_MT_EMBER_EXTERIOR (HOENN_FLAGS_START + 0x34A)
#undef  FLAG_WORLD_MAP_MT_MOON_1F
#define FLAG_WORLD_MAP_MT_MOON_1F (HOENN_FLAGS_START + 0x34B)
#undef  FLAG_WORLD_MAP_ONE_ISLAND
#define FLAG_WORLD_MAP_ONE_ISLAND (HOENN_FLAGS_START + 0x34C)
#undef  FLAG_WORLD_MAP_PALLET_TOWN
#define FLAG_WORLD_MAP_PALLET_TOWN (HOENN_FLAGS_START + 0x34D)
#undef  FLAG_WORLD_MAP_PEWTER_CITY
#define FLAG_WORLD_MAP_PEWTER_CITY (HOENN_FLAGS_START + 0x34E)
#undef  FLAG_WORLD_MAP_POKEMON_MANSION_1F
#define FLAG_WORLD_MAP_POKEMON_MANSION_1F (HOENN_FLAGS_START + 0x34F)
#undef  FLAG_WORLD_MAP_POKEMON_TOWER_1F
#define FLAG_WORLD_MAP_POKEMON_TOWER_1F (HOENN_FLAGS_START + 0x350)
#undef  FLAG_WORLD_MAP_POWER_PLANT
#define FLAG_WORLD_MAP_POWER_PLANT (HOENN_FLAGS_START + 0x351)
#undef  FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F
#define FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F (HOENN_FLAGS_START + 0x352)
#undef  FLAG_WORLD_MAP_ROCK_TUNNEL_1F
#define FLAG_WORLD_MAP_ROCK_TUNNEL_1F (HOENN_FLAGS_START + 0x353)
#undef  FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F
#define FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F (HOENN_FLAGS_START + 0x354)
#undef  FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F
#define FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F (HOENN_FLAGS_START + 0x355)
#undef  FLAG_WORLD_MAP_SAFARI_ZONE_CENTER
#define FLAG_WORLD_MAP_SAFARI_ZONE_CENTER (HOENN_FLAGS_START + 0x356)
#undef  FLAG_WORLD_MAP_SAFFRON_CITY
#define FLAG_WORLD_MAP_SAFFRON_CITY (HOENN_FLAGS_START + 0x357)
#undef  FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F
#define FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F (HOENN_FLAGS_START + 0x358)
#undef  FLAG_WORLD_MAP_SEVEN_ISLAND
#define FLAG_WORLD_MAP_SEVEN_ISLAND (HOENN_FLAGS_START + 0x359)
#undef  FLAG_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER
#define FLAG_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER (HOENN_FLAGS_START + 0x35A)
#undef  FLAG_WORLD_MAP_SILPH_CO_1F
#define FLAG_WORLD_MAP_SILPH_CO_1F (HOENN_FLAGS_START + 0x35B)
#undef  FLAG_WORLD_MAP_SIX_ISLAND
#define FLAG_WORLD_MAP_SIX_ISLAND (HOENN_FLAGS_START + 0x35C)
#undef  FLAG_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE
#define FLAG_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE (HOENN_FLAGS_START + 0x35D)
#undef  FLAG_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F
#define FLAG_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F (HOENN_FLAGS_START + 0x35E)
#undef  FLAG_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH
#define FLAG_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH (HOENN_FLAGS_START + 0x35F)
#undef  FLAG_WORLD_MAP_THREE_ISLAND
#define FLAG_WORLD_MAP_THREE_ISLAND (HOENN_FLAGS_START + 0x360)
#undef  FLAG_WORLD_MAP_THREE_ISLAND_BERRY_FOREST
#define FLAG_WORLD_MAP_THREE_ISLAND_BERRY_FOREST (HOENN_FLAGS_START + 0x361)
#undef  FLAG_WORLD_MAP_TWO_ISLAND
#define FLAG_WORLD_MAP_TWO_ISLAND (HOENN_FLAGS_START + 0x362)
#undef  FLAG_WORLD_MAP_VERMILION_CITY
#define FLAG_WORLD_MAP_VERMILION_CITY (HOENN_FLAGS_START + 0x363)
#undef  FLAG_WORLD_MAP_VICTORY_ROAD_1F
#define FLAG_WORLD_MAP_VICTORY_ROAD_1F (HOENN_FLAGS_START + 0x364)
#undef  FLAG_WORLD_MAP_VIRIDIAN_CITY
#define FLAG_WORLD_MAP_VIRIDIAN_CITY (HOENN_FLAGS_START + 0x365)
#undef  FLAG_WORLD_MAP_VIRIDIAN_FOREST
#define FLAG_WORLD_MAP_VIRIDIAN_FOREST (HOENN_FLAGS_START + 0x366)

// Hoenn-Trainerkarte erhalten (Birk uebergibt sie mit dem Dex-Upgrade);
// schaltet das Umschalten der Kartenvariante per SELECT frei.
#define FLAG_RECEIVED_PASS_BINDER (HOENN_FLAGS_START + 0x367)

#define HOENN_FLAGS_END (HOENN_FLAGS_START + 0x367)

#endif // GUARD_CONSTANTS_FLAGS_HOENN_DE_H
