FallarborTown_BattleTentCorridor_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentCorridor_OnFrame
	.byte 0

FallarborTown_BattleTentCorridor_OnFrame:
	map_script_2 VAR_TEMP_0, 0, FallarborTown_BattleTentCorridor_EventScript_EnterCorridor
	.2byte 0

FallarborTown_BattleTentCorridor_EventScript_EnterCorridor::
	lockall
	setvar VAR_TEMP_0, 1
	applymovement LOCALID_FALLARBOR_TENT_CORRIDOR_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	applymovement LOCALID_PLAYER, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	waitmovement 0
	opendoor 2, 1
	waitdooranim
	applymovement LOCALID_FALLARBOR_TENT_CORRIDOR_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor
	applymovement LOCALID_PLAYER, FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor
	waitmovement 0
	closedoor 2, 1
	waitdooranim
	setvar VAR_0x8006, 0
	warp MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM, 4, 4
	waitstate
	releaseall
	end

FallarborTown_BattleTentCorridor_Movement_WalkToDoor:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor:
	walk_up
FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor:
	walk_up
	set_invisible
	step_end

@ Leftover text from when this was a Contest Hall in R/S
@ Unused
FallarborTown_ContestHall_Text_DoAllRightInPreliminary:
#if GERMAN
	.string "Im ersten Durchlauf schlagen wir uns\n"
	.string "ganz gut, aber beim Ausdruck gewinnen\l"
	.string "wir nie…\p"
	.string "Vielleicht muss ich mehr darauf achten,\n"
	.string "was die anderen Teilnehmer machen…$"
#else
	.string "We do all right in the preliminary round,\n"
	.string "but we can never win the appeals…\p"
	.string "Maybe it means I have to watch what\n"
	.string "other contestants are doing…$"
#endif

@ Unused
FallarborTown_ContestHall_Text_MonAllTheseRibbons:
#if GERMAN
	.string "Sieh nur!\n"
	.string "Mein Pokémon hat all diese Bänder\l"
	.string "gewonnen!\p"
	.string "Hat dein Pokémon schon Bänder\n"
	.string "bekommen? Im Pokénav kannst du\l"
	.string "nachsehen.$"
#else
	.string "See!\n"
	.string "My POKéMON won all these RIBBONS!\p"
	.string "Have your POKéMON earned any RIBBONS?\n"
	.string "You can check them on your POKéNAV.$"
#endif

@ Unused
FallarborTown_ContestHall_Text_CantWinEverywhere:
#if GERMAN
	.string "Ich kann keine Arenaleiter besiegen…\p"
	.string "Ich kann keinen Wettbewerb gewinnen…\p"
	.string "Ich war schon überall und nirgendwo,\n"
	.string "und alles war vergebens…$"
#else
	.string "I can't beat GYM LEADERS…\p"
	.string "I can't win any CONTESTS…\p"
	.string "I've been here, there, and everywhere,\n"
	.string "and it's all for naught…$"
#endif

@ Unused
FallarborTown_ContestHall_Text_SuperRankStage:
#if GERMAN
	.string "Pokémon Contests\n"
	.string "Super Rank Stage!$"
#else
	.string "POKéMON CONTESTS\n"
	.string "SUPER RANK STAGE!$"
#endif

