Route8_Frlg_MapScripts::
	.byte 0

Route8_EventScript_UndergroundPathSign::
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route8_Text_AidanIntro::
#if GERMAN
	.string "Du weißt viel über Pokémon!\n"
	.string "Doch wie sieht es mit Chemie aus?$"
#else
	.string "You look good at POKéMON, but how\n"
	.string "is your chemistry grade?$"
#endif

Route8_Text_AidanDefeat::
#if GERMAN
	.string "Au!\n"
	.string "Eine Kernschmelze!$"
#else
	.string "Ow!\n"
	.string "Meltdown!$"
#endif

Route8_Text_AidanPostBattle::
#if GERMAN
	.string "Meine schulischen Leistungen sind\n"
	.string "besser!$"
#else
	.string "I am better at school than this!$"
#endif

Route8_Text_StanIntro::
#if GERMAN
	.string "O.k.!\n"
	.string "Die Spiele mögen beginnen!$"
#else
	.string "All right!\n"
	.string "Let's play a game!$"
#endif

Route8_Text_StanDefeat::
#if GERMAN
	.string "Knapp vorbei ist auch daneben!$"
#else
	.string "Drat!\n"
	.string "Came up short!$"
#endif

Route8_Text_StanPostBattle::
#if GERMAN
	.string "Man kann nicht immer gewinnen!$"
#else
	.string "Things didn't work today.$"
#endif

Route8_Text_GlennIntro::
#if GERMAN
	.string "Um zu gewinnen, benötigst du eine\n"
	.string "gute Strategie!$"
#else
	.string "You should be informed.\n"
	.string "You need strategy to win at this!$"
#endif

Route8_Text_GlennDefeat::
#if GERMAN
	.string "Ich habe verloren!\n"
	.string "Das ist nicht logisch!$"
#else
	.string "It's not logical!$"
#endif

Route8_Text_GlennPostBattle::
#if GERMAN
	.string "Sleima kämpft als Erstes... und...\n"
	.string "und... dann...$"
#else
	.string "Go with GRIMER first…and…\n"
	.string "…and…then…$"
#endif

Route8_Text_PaigeIntro::
#if GERMAN
	.string "Ich mag alle Nidoran sehr gerne!\n"
	.string "Deshalb sammle ich sie!$"
#else
	.string "I like NIDORAN, so I collect them!$"
#endif

Route8_Text_PaigeDefeat::
#if GERMAN
	.string "Warum?\n"
	.string "Warum nur?$"
#else
	.string "Why?\n"
	.string "Why??$"
#endif

Route8_Text_PaigePostBattle::
#if GERMAN
	.string "Wenn Pokémon sich entwickeln, werden\n"
	.string "sie groß und hässlich! Sie sollten klein\l"
	.string "und goldig bleiben!$"
#else
	.string "When POKéMON grow up, they get\n"
	.string "ugly! They shouldn't evolve.$"
#endif

Route8_Text_LeslieIntro::
#if GERMAN
	.string "Die Schule macht Spaß! Pokémon zu\n"
	.string "trainieren aber auch!$"
#else
	.string "School is fun, but so are POKéMON.$"
#endif

Route8_Text_LeslieDefeat::
#if GERMAN
	.string "O.k., ich gehe lieber zur Schule!$"
#else
	.string "You made it clear to me that\n"
	.string "I should stick with school.$"
#endif

Route8_Text_LesliePostBattle::
#if GERMAN
	.string "Wir sitzen hier fest, weil\n"
	.string "Saffronia City abgeriegelt wird.$"
#else
	.string "I was planning on getting some\n"
	.string "fresh air for a change, but…\p"
	.string "We're stuck here because of the\n"
	.string "gates at SAFFRON.$"
#endif

Route8_Text_AndreaIntro::
#if GERMAN
	.string "Mauzi ist so süß!\n"
	.string "Miau, miauz!$"
#else
	.string "MEOWTH is so cute, meow, meow,\n"
	.string "meow!$"
#endif

Route8_Text_AndreaDefeat::
#if GERMAN
	.string "Miauz!$"
#else
	.string "Meeeeyow!$"
#endif

Route8_Text_AndreaPostBattle::
#if GERMAN
	.string "Aber Taubsi und Rattfratz sind\n"
	.string "auch niedlich!$"
#else
	.string "I think PIDGEY and RATTATA are\n"
	.string "cute, too!$"
#endif

Route8_Text_MeganIntro::
#if GERMAN
	.string "Es muss ziemlich blöd aussehen, wie\n"
	.string "wir hier herumstehen!$"
#else
	.string "We must look silly standing here\n"
	.string "like this.$"
#endif

Route8_Text_MeganDefeat::
#if GERMAN
	.string "Schau was du getan hast!$"
#else
	.string "Look what you did to my poor, cute\n"
	.string "POKéMON!$"
#endif

Route8_Text_MeganPostBattle::
#if GERMAN
	.string "Der Wachtposten von Saffronia\n"
	.string "City ist so gemein!\p"
	.string "Er lässt uns nicht in die Stadt!$"
#else
	.string "SAFFRON's gatekeeper won't let us\n"
	.string "go through.\p"
	.string "I know he's doing his job, but I\n"
	.string "think he's mean.$"
#endif

Route8_Text_RichIntro::
#if GERMAN
	.string "Ich bin ein weit herumgekommener\n"
	.string "Glücksspieler!$"
#else
	.string "I'm a rambling, gaming dude!$"
#endif

Route8_Text_RichDefeat::
#if GERMAN
	.string "Den Jackpot habe ich noch nicht\n"
	.string "geknackt...$"
#else
	.string "Missed the big chance!$"
#endif

Route8_Text_RichPostBattle::
#if GERMAN
	.string "Glücksspiele und Pokémon haben eines\n"
	.string "gemeinsam: Man kann nicht damit\l"
	.string "aufhören!$"
#else
	.string "Playing games and POKéMON are like\n"
	.string "eating peanuts! I just can't stop!$"
#endif

Route8_Text_JuliaIntro::
#if GERMAN
	.string "Welches Pokémon ist süß, pummelig\n"
	.string "und kuschlig?$"
#else
	.string "What's a cute, round, and fluffy\n"
	.string "POKéMON?$"
#endif

Route8_Text_JuliaDefeat::
#if GERMAN
	.string "Hör auf!\p"
	.string "Sei nicht so gemein zu Piepi!$"
#else
	.string "Stop!\p"
	.string "Don't be so mean to my CLEFAIRY!$"
#endif

Route8_Text_JuliaPostBattle::
#if GERMAN
	.string "Ich habe gehört, Piepi entwickelt sich,\n"
	.string "wenn man ihm einen Mondstein gibt.$"
#else
	.string "I read that CLEFAIRY evolves when\n"
	.string "it's exposed to a MOON STONE.\p"
	.string "I read that in a POKéMON JOURNAL.\n"
	.string "I wonder if it's true?$"
#endif

Route8_Text_UndergroundPathSign::
#if GERMAN
	.string "Tunnelpfad\n"
	.string "Prismania City - Lavandia$"
#else
	.string "UNDERGROUND PATH\n"
	.string "CELADON CITY - LAVENDER TOWN$"
#endif

Route8_Text_EliIntro::
#if GERMAN
	.string "Nora: Die Kraft von Zwillingen ist\n"
	.string "fantastisch. Wusstest du das?$"
#else
	.string "ELI: Twin power is fantastic.\n"
	.string "Did you know?$"
#endif

Route8_Text_EliDefeat::
#if GERMAN
	.string "Nora: Aber…\n"
	.string "Wir nutzten unsere Zwillings-Kraft.$"
#else
	.string "ELI: But…\n"
	.string "We used our twin power…$"
#endif

Route8_Text_EliPostBattle::
#if GERMAN
	.string "Nora: Ich habe mein Pokémon mit\n"
	.string "Jo gefangen!$"
#else
	.string "ELI: I caught my POKéMON with\n"
	.string "ANNE!$"
#endif

Route8_Text_EliNotEnoughMons::
#if GERMAN
	.string "Nora: Wir können nicht kämpfen,\n"
	.string "wenn du keine zwei Pokémon hast.$"
#else
	.string "ELI: We can't battle if you don't\n"
	.string "have two POKéMON.$"
#endif

Route8_Text_AnneIntro::
#if GERMAN
	.string "Jo: Wir überrumpeln dich mit\n"
	.string "unserer Zwillings-Kraft.$"
#else
	.string "ANNE: We'll shock you with our twin\n"
	.string "power!$"
#endif

Route8_Text_AnneDefeat::
#if GERMAN
	.string "Jo: Unsere Zwillings-Kraft…$"
#else
	.string "ANNE: Our twin power…$"
#endif

Route8_Text_AnnePostBattle::
#if GERMAN
	.string "Jo: Ich trainiere Pokémon mit\n"
	.string "Nora!$"
#else
	.string "ANNE: I'm raising POKéMON with\n"
	.string "ELI.$"
#endif

Route8_Text_AnneNotEnoughMons::
#if GERMAN
	.string "Jo: Hallo! Lass uns kämpfen!\n"
	.string "Aber bring zwei Pokémon mit!$"
#else
	.string "ANNE: Hi, hi! Let's battle!\n"
	.string "But bring two POKéMON.$"
#endif

Route8_Text_RicardoIntro::
#if GERMAN
	.string "Mein Motorrad spielt verrückt!$"
#else
	.string "My bike's acting up, man.$"
#endif

Route8_Text_RicardoDefeat::
#if GERMAN
	.string "Argh!\n"
	.string "Das kann ich einfach nicht!$"
#else
	.string "Aww, man.\n"
	.string "I'm not into this.$"
#endif

Route8_Text_RicardoPostBattle::
#if GERMAN
	.string "Mir ist Gras in die Speichen\n"
	.string "gekommen.$"
#else
	.string "I got grass caught up in my\n"
	.string "spokes, man.$"
#endif

Route8_Text_JarenIntro::
#if GERMAN
	.string "Mach den Weg frei oder ich über-\n"
	.string "fahre dich!$"
#else
	.string "Clear the way, or I'll run you\n"
	.string "down!$"
#endif

Route8_Text_JarenDefeat::
#if GERMAN
	.string "Du hast es drauf, Kiddie!$"
#else
	.string "You for real, kid?$"
#endif

Route8_Text_JarenPostBattle::
#if GERMAN
	.string "Denk bloß nicht, dass du etwas\n"
	.string "Besonderes bist, nur weil du gewonnen\l"
	.string "hast.$"
#else
	.string "Don't think you're all special and\n"
	.string "all just because of this.$"
#endif
