Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
#if GERMAN
	.string "Versuche dein Glück gegen mich!$"
#else
	.string "Win, lose, or draw!$"
#endif

Route11_Text_HugoDefeat::
#if GERMAN
	.string "Das Glück hat mich verlassen!$"
#else
	.string "Atcha!\n"
	.string "Didn't go my way!$"
#endif

Route11_Text_HugoPostBattle::
#if GERMAN
	.string "Das ganze Leben ist ein Glücksspiel!$"
#else
	.string "POKéMON is life!\n"
	.string "And to live is to play games!$"
#endif

Route11_Text_JasperIntro::
#if GERMAN
	.string "Wettkämpfe!\n"
	.string "Ich kann ihnen nicht widerstehen!$"
#else
	.string "Competition!\n"
	.string "I can't get enough!$"
#endif

Route11_Text_JasperDefeat::
#if GERMAN
	.string "Immerhin hatte ich eine Chance!$"
#else
	.string "I had a chance!$"
#endif

Route11_Text_JasperPostBattle::
#if GERMAN
	.string "Feiglinge haben in der Welt der\n"
	.string "Pokémon keine Chance!$"
#else
	.string "You can't be a coward in the world\n"
	.string "of POKéMON!$"
#endif

Route11_Text_EddieIntro::
#if GERMAN
	.string "Hast du Lust mit mir zu kämpfen?$"
#else
	.string "Let's go, but don't cheat!$"
#endif

Route11_Text_EddieDefeat::
#if GERMAN
	.string "Hä?\n"
	.string "Das ist gemein!$"
#else
	.string "Huh?\n"
	.string "That's not right!$"
#endif

Route11_Text_EddiePostBattle::
#if GERMAN
	.string "Immerhin habe ich es versucht!\n"
	.string "Ich schäme mich nicht!$"
#else
	.string "I did my best.\n"
	.string "I have no regrets.$"
#endif

Route11_Text_BraxtonIntro::
#if GERMAN
	.string "Vorsicht!\n"
	.string "Ich verlege hier gerade Kabel!$"
#else
	.string "Careful!\n"
	.string "I'm laying down some cables!$"
#endif

Route11_Text_BraxtonDefeat::
#if GERMAN
	.string "Das war ein Stromschlag!$"
#else
	.string "That was electric!$"
#endif

Route11_Text_BraxtonPostBattle::
#if GERMAN
	.string "Schone die Umwelt und spare Energie!$"
#else
	.string "Spread the word to save energy!$"
#endif

Route11_Text_DillonIntro::
#if GERMAN
	.string "Ich habe gerade erst angefangen,\n"
	.string "Pokémon zu trainieren!$"
#else
	.string "I just became a TRAINER.\n"
	.string "But, I think I can win.$"
#endif

Route11_Text_DillonDefeat::
#if GERMAN
	.string "Mist!\n"
	.string "Ich hasse schwache Pokémon!$"
#else
	.string "My POKéMON couldn't win…\n"
	.string "Haven't they grown enough?$"
#endif

Route11_Text_DillonPostBattle::
#if GERMAN
	.string "Was willst du noch?\n"
	.string "Lass mich endlich allein!$"
#else
	.string "What now?\n"
	.string "Leave me alone!$"
#endif

Route11_Text_DirkIntro::
#if GERMAN
	.string "Haha!\n"
	.string "Bisher habe ich noch nie verloren!$"
#else
	.string "Fwahaha!\n"
	.string "I have never lost!$"
#endif

Route11_Text_DirkDefeat::
#if GERMAN
	.string "Es gibt immer ein erstes Mal...$"
#else
	.string "My first loss!$"
#endif

Route11_Text_DirkPostBattle::
#if GERMAN
	.string "Das war purer Zufall!\n"
	.string "Nichts als Glück!$"
#else
	.string "You were just lucky, that's all.$"
#endif

Route11_Text_DarianIntro::
#if GERMAN
	.string "Ich habe noch nie gewonnen...$"
#else
	.string "I have never won before…$"
#endif

Route11_Text_DarianDefeat::
#if GERMAN
	.string "Das habe ich kommen sehen!$"
#else
	.string "I saw this coming…$"
#endif

Route11_Text_DarianPostBattle::
#if GERMAN
	.string "Das war nichts als Glück.\n"
	.string "Purer Zufall!$"
#else
	.string "I was unlucky, as always.$"
#endif

Route11_Text_YasuIntro::
#if GERMAN
	.string "In meiner Klasse bin ich der Beste!$"
#else
	.string "I'm the best in my class.\n"
	.string "I train every morning.$"
#endif

Route11_Text_YasuDefeat::
#if GERMAN
	.string "Ich muss meine Pokémon mehr trainieren!$"
#else
	.string "Darn!\n"
	.string "My POKéMON need to be stronger!$"
#endif

Route11_Text_YasuPostBattle::
#if GERMAN
	.string "Aus den Bergen steigt manchmal ein\n"
	.string "dickes Pokémon herab.\p"
	.string "Es ist sehr stark!\n"
	.string "Versuche es zu fangen!$"
#else
	.string "There's a fat POKéMON that comes\n"
	.string "down from the mountains.\p"
	.string "I bet it'd be strong if you can\n"
	.string "catch it.$"
#endif

Route11_Text_BernieIntro::
#if GERMAN
	.string "Nimm dich vor Hochspannung in\n"
	.string "Acht!$"
#else
	.string "Watch out for live wires!$"
#endif

Route11_Text_BernieDefeat::
#if GERMAN
	.string "Au!\n"
	.string "Der Funke ist übergesprungen!$"
#else
	.string "Whoa!\n"
	.string "You spark plug!$"
#endif

Route11_Text_BerniePostBattle::
#if GERMAN
	.string "Ich mache mich besser wieder an\n"
	.string "die Arbeit.$"
#else
	.string "Well, better get back to work.$"
#endif

Route11_Text_DaveIntro::
#if GERMAN
	.string "Meine Pokémon müssten bereit sein!$"
#else
	.string "I raised my POKéMON carefully.\n"
	.string "They should be ready by now!$"
#endif

Route11_Text_DaveDefeat::
#if GERMAN
	.string "Das war schwach!$"
#else
	.string "Bye-bye!\n"
	.string "Thank you, and good-bye!$"
#endif

Route11_Text_DavePostBattle::
#if GERMAN
	.string "Ich muss ein paar stärkere fangen!$"
#else
	.string "Tch…\n"
	.string "I better go find stronger ones!$"
#endif

Route11_Text_DiglettsCave::
#if GERMAN
	.string "Digdas Höhle$"
#else
	.string "DIGLETT'S CAVE$"
#endif

