gText_ApprenticeChallenge0::
#if GERMAN
	.string "Äh, ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Schnief… Die Spannung zerrt an mir…$"
#else
	.string "Um, I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Snivel… This tension is getting to me…$"
#endif

gText_ApprenticeChallenge1::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Jetzt komme ich!$"
#else
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Here we come!$"
#endif

gText_ApprenticeChallenge2::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Stell dich meiner Herausforderung!$"
#else
	.string "I'm the no. {STR_VAR_2} apprentice of {STR_VAR_1}!\n"
	.string "Accept my challenge!$"
#endif

gText_ApprenticeChallenge3::
#if GERMAN
	.string "Äh, ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Meinst du, ich kann gewinnen?$"
#else
	.string "Um… I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice…\n"
	.string "Do you think someone like me can win?$"
#endif

gText_ApprenticeChallenge4::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ich fordere dich heraus!$"
#else
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "I'll let you challenge me!$"
#endif

gText_ApprenticeChallenge5::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1} und\n"
	.string "außerdem schwer beschäftigt!$"
#else
	.string "I'm horribly busy, but I also happen\n"
	.string "to be {STR_VAR_1}'s no. {STR_VAR_2} apprentice.$"
#endif

gText_ApprenticeChallenge6::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Freut mich, dich kennen zu lernen!$"
#else
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Glad to meet you!$"
#endif

gText_ApprenticeChallenge7::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Darf ich anfangen?$"
#else
	.string "I serve as {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "May I begin?$"
#endif

gText_ApprenticeChallenge8::
#if GERMAN
	.string "Hiii! Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ich werde mein Bestes geben!$"
#else
	.string "Eek! I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "I'll do my best!$"
#endif

gText_ApprenticeChallenge9::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Hiiyaa! Los geht’s!$"
#else
	.string "Yeehaw! I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Put 'em up!$"
#endif

gText_ApprenticeChallenge10::
#if GERMAN
	.string "Ich bin der 1.000ste Schüler von\n"
	.string "{STR_VAR_1}. Äh, der {STR_VAR_2}. Schüler! Los jetzt!$"
#else
	.string "I'm {STR_VAR_1}'s 1,000th apprentice!\n"
	.string "Actually, I'm no. {STR_VAR_2}! Here goes!$"
#endif

gText_ApprenticeChallenge11::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Auf geht’s! Lass die Erde beben!$"
#else
	.string "Yeah, I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice!\n"
	.string "Let's get rockin' and a-rollin'!$"
#endif

gText_ApprenticeChallenge12::
#if GERMAN
	.string "Man nennt mich Schüler Nr. {STR_VAR_2}\n"
	.string "von {STR_VAR_1}. Yeah!$"
#else
	.string "Yippee-yahoo! I'm what you call\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} apprentice!$"
#endif

gText_ApprenticeChallenge13::
#if GERMAN
	.string "Hust! Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Nett, dich kennen zu lernen! Hust!$"
#else
	.string "Cough! I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Good to meet you! Cough!$"
#endif

gText_ApprenticeChallenge14::
#if GERMAN
	.string "Ist das alles Nerven zerreißend…\n"
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.$"
#else
	.string "This is nerve-racking…\n"
	.string "I'm the no. {STR_VAR_2} apprentice of {STR_VAR_1}.$"
#endif

gText_ApprenticeChallenge15::
#if GERMAN
	.string "Ich bin Schüler Nr. {STR_VAR_2} von {STR_VAR_1}.\n"
	.string "Ehrlich wahr und nicht gelogen!$"
#else
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} apprentice,\n"
	.string "and that's no lie.$"
#endif

gText_ApprenticePleaseTeach0::
#if GERMAN
	.string "Waaahaaa… Bist du es, {PLAYER}?!?\n"
	.string "Oooh… Heul… Jammer… Schnief…\p"
	.string "Tu-tut mir L-Leid…\n"
	.string "Ich bin so nervös, da muss ich einfach\l"
	.string "weinen… Heul…\p"
	.string "Ich bin {STR_VAR_1} und du bist mein\n"
	.string "großes Vorbild, {PLAYER}… Jammer…\p"
	.string "Ich hatte diesen Traum - dass ich dich\n"
	.string "eines Tages etwas über Pokémon fragen\l"
	.string "würde… Schnief…\p"
	.string "Bitte, bitte, {PLAYER}!\n"
	.string "Bring mir etwas über Pokémon bei!$"
#else
	.string "Are you… {PLAYER}?\n"
	.string "Oh! Sniff…sob…\p"
	.string "Oh! S-sorry…\n"
	.string "I'm so nervous, I can't help crying…\p"
	.string "I'm {STR_VAR_1}, and I really look up\n"
	.string "to you, {PLAYER}.\p"
	.string "I… I had this dream of one day meeting\n"
	.string "you and asking you about POKéMON.\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Please teach me about POKéMON!$"
#endif

gText_ApprenticeRejectTeaching0::
#if GERMAN
	.string "Oh… Ab-ber, ab-ber…\n"
	.string "Heul… Waaaaaahaaaaaa…\p"
	.string "Bitte!\n"
	.string "Ich flehe dich an… Jammer…$"
#else
	.string "Oh… B-but…\n"
	.string "Snivel… Waaaaaaah!\p"
	.string "Please!\n"
	.string "I'm begging you, please!$"
#endif

gText_ApprenticeWhichLevelMode0::
#if GERMAN
	.string "Echt? Ganz wirklich?!?\n"
	.string "Unglaublich! Fantastisch! Juhuuuuuu…\p"
	.string "Oh… Entschuldige…\n"
	.string "Ich freue mich so sehr, ich könnte glatt\l"
	.string "wieder weinen…\p"
	.string "Äh… Also, dann erzähl mir bitte\n"
	.string "etwas über den Duellturm.\p"
	.string "Soll ich an den Level 50 oder den \n"
	.string "Offenen Kämpfen teilnehmen?$"
#else
	.string "Oh, really? You will?\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Um… Then please tell me!\n"
	.string "It's about the BATTLE TOWER.\p"
	.string "Which would be better for me: Level 50\n"
	.string "or the Open Level?$"
#endif

gText_ApprenticeLevelModeThanks0::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Waaaaahaaaaaaa…\p"
	.string "Oh, tut mir Leid! Aber du hast mich\n"
	.string "so glücklich gemacht, da muss ich\l"
	.string "einfach weinen… Heul…\p"
	.string "Schnüff…\n"
	.string "Vielen, vielen Dank! Ich hoffe, du\l"
	.string "hilfst mir bald wieder… Heul…$"
#else
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "the level for me, and it's made me cry…\p"
	.string "Snivel…\n"
	.string "Thank you so much!\l"
	.string "Please talk with me again!$"
#endif

gText_ApprenticePleaseTeach1::
#if GERMAN
	.string "Wuhuuu! Du bist doch {PLAYER},\n"
	.string "oder? Du bist sehr stark, oder?\p"
	.string "Ich bin {STR_VAR_1}!\n"
	.string "Ich bin gerade erst ein Trainer\l"
	.string "geworden!\p"
	.string "{PLAYER}, bitte! Du kannst mir nicht\n"
	.string "etwas über Trainer beibringen, oder?$"
#else
	.string "Wowee! You're {PLAYER}, aren't you?\n"
	.string "You're awesomely strong, aren't you?\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I just became a TRAINER!\p"
	.string "Please, {PLAYER}!\n"
	.string "Can you be my teacher and tell me\l"
	.string "lots about being a TRAINER?$"
#endif

gText_ApprenticeRejectTeaching1::
#if GERMAN
	.string "Oooh, warum nicht?\n"
	.string "Bitte?Ja? Bitte, bitte, bitte, bitte…\l"
	.string "Bitte, werde mein Lehrer, bitte, bitte…$"
#else
	.string "Aww, why?\n"
	.string "Oh, please? Pretty please?\l"
	.string "Please be my teacher, please!$"
#endif

gText_ApprenticeWhichLevelMode1::
#if GERMAN
	.string "Juhuuu! Super!\p"
	.string "Ich möchte dich gerne etwas über den\n"
	.string "Duellturm fragen.\p"
	.string "Level 50 oder Offene Kämpfe…\n"
	.string "Was würdest du mir empfehlen?$"
#else
	.string "Yay! Great!\p"
	.string "The first thing I wanted to ask you is\n"
	.string "about the BATTLE TOWER!\p"
	.string "The Level 50 and Open Level Rooms…\n"
	.string "Which would be perfect for me?$"
#endif

gText_ApprenticeLevelModeThanks1::
#if GERMAN
	.string "{STR_VAR_1}? Jawohl!\n"
	.string "Ich werde mein Bestes geben!\p"
	.string "Du bringst mir doch noch mehr bei, wenn\n"
	.string "wir uns wiedersehen, oder?$"
#else
	.string "{STR_VAR_1}, huh? That's true!\n"
	.string "I'll do my best there!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, teacher!$"
#endif

gText_ApprenticePleaseTeach2::
#if GERMAN
	.string "Äh… Du bist {PLAYER}?\n"
	.string "Ich bin {STR_VAR_1}.\p"
	.string "Ich möchte gerne ein Trainer werden,\n"
	.string "aber ich weiß nicht wie…\p"
	.string "Und da dachte ich mir, dass du mir\n"
	.string "weiterhelfen könntest. Du bist doch\l"
	.string "berühmt für dein Talent.\p"
	.string "{PLAYER}, hilfst du mir?$"
#else
	.string "Um… Are you {PLAYER}?\n"
	.string "My name is {STR_VAR_1}.\p"
	.string "I want to become a POKéMON TRAINER,\n"
	.string "but I don't know what to do…\p"
	.string "So I thought maybe I could ask you for\n"
	.string "advice because you're so famous.\p"
	.string "{PLAYER}, could you give me advice?$"
#endif

gText_ApprenticeRejectTeaching2::
#if GERMAN
	.string "Aber…\p"
	.string "Ich würde doch so gerne ein Trainer\n"
	.string "werden!\p"
	.string "Bitte, gib mir doch ein paar Tipps, ja?$"
#else
	.string "Oh, but…\p"
	.string "I sincerely want to become a POKéMON\n"
	.string "TRAINER!\p"
	.string "Please, can you answer my questions?$"
#endif

gText_ApprenticeWhichLevelMode2::
#if GERMAN
	.string "Vielen Dank!\n"
	.string "Und hier kommt auch schon meine erste\l"
	.string "Frage!\p"
	.string "Der Duellturm bietet Level 50\n"
	.string "und Offene Kämpfe an.\p"
	.string "An welchen Kämpfen soll ich teilnehmen?$"
#else
	.string "Thank you!\n"
	.string "Here's my first question right away!\p"
	.string "The BATTLE TOWER has two levels,\n"
	.string "Level 50 and Open Level, right?\p"
	.string "Which level do you think is more\n"
	.string "suitable for me?$"
#endif

gText_ApprenticeLevelModeThanks2::
#if GERMAN
	.string "Ach, {STR_VAR_1}?\n"
	.string "Ja, abgemacht!\p"
	.string "Und wenn ich noch mehr Fragen habe,\n"
	.string "dann warte ich hier auf deinen Rat.$"
#else
	.string "Oh, the {STR_VAR_1} challenge?\n"
	.string "Understood!\p"
	.string "If I have another question, I'll come\n"
	.string "back here for your advice!$"
#endif

gText_ApprenticePleaseTeach3::
#if GERMAN
	.string "Wie? Du bist…\n"
	.string "Nein, das kann einfach nicht sein!\p"
	.string "Jemand wie ich kann doch nicht das\n"
	.string "Glück haben, {PLAYER} zu treffen.\p"
	.string "Du bist wirklich… {PLAYER}?\n"
	.string "Ich fass es nicht! Ich spreche\l"
	.string "mit {PLAYER}!\p"
	.string "Bei so viel Glück wird mir bestimmt\n"
	.string "etwas Schreckliches passieren!\l"
	.string "Das weiß ich ganz genau…\p"
	.string "Tut mir Leid…\n"
	.string "Ich heiße… {STR_VAR_1}…\p"
	.string "Nun, ich habe nichts, auf das ich stolz\n"
	.string "sein müsste…\p"
	.string "Und du wirst meinen Namen bestimmt\n"
	.string "ganz schnell wieder vergessen…\p"
	.string "Ich hatte diesen Traum! Dass ich dich,\n"
	.string "sollte ich dich jemals treffen,\l"
	.string "{PLAYER}… Um Rat fragen würde!\p"
	.string "Dich, als Trainer! Aber das würdest\n"
	.string "du bestimmt ablehnen…\p"
	.string "Oder bist du so nett und verrätst mir\n"
	.string "ein paar Geheimnisse?$"
#else
	.string "Oh? Huh? You're…\n"
	.string "No, that can't be true.\p"
	.string "There isn't any way that someone\n"
	.string "like me could meet {PLAYER}.\p"
	.string "…You really are {PLAYER}?\n"
	.string "I can't believe I'm talking to you!\p"
	.string "When something this good happens,\n"
	.string "only terrible things will happen to me\l"
	.string "now, I just know it…\p"
	.string "…I'm sorry…\n"
	.string "I'm… {STR_VAR_1}…\p"
	.string "There isn't anything special about\n"
	.string "me that I can be proud of…\p"
	.string "I shouldn't even say anything about\n"
	.string "myself because you'll forget…\p"
	.string "I had this dream that if I ever met\n"
	.string "you, {PLAYER}, that maybe I could ask\l"
	.string "you for advice as a TRAINER.\p"
	.string "But I don't think you would agree\n"
	.string "to that.\p"
	.string "…Or will you be so kind as to give\n"
	.string "me advice?$"
#endif

gText_ApprenticeRejectTeaching3::
#if GERMAN
	.string "Ich wusste es…\p"
	.string "Da ich ein langweiliger Niemand bin…\p"
	.string "Aber ich hatte doch gehofft…\n"
	.string "Du würdest es dir nicht noch einmal\l"
	.string "überlegen, oder?\p"
	.string "Ich kann dich doch jetzt nicht einfach\n"
	.string "so gehen lassen!\p"
	.string "Wo ich doch ausnahmsweise mal Glück\n"
	.string "habe und dich traf.\p"
	.string "Könntest du mir nicht doch einen Rat\n"
	.string "geben?$"
#else
	.string "I knew it…\p"
	.string "It had to happen because I'm such\n"
	.string "a really boring nobody…\p"
	.string "But I thought just maybe…\n"
	.string "You won't reconsider, will you?\p"
	.string "But I can't give up just like that.\n"
	.string "I'll ask you while I'm still lucky!\p"
	.string "Please, will you be so kind as to give\n"
	.string "me advice?$"
#endif

gText_ApprenticeWhichLevelMode3::
#if GERMAN
	.string "Wirklich?!? Ich kann es kaum glauben!!!\n"
	.string "Ich kann es nicht glauben, dass du mir\l"
	.string "einen Rat geben wirst!\p"
	.string "Ich… bin sooooo froh…\p"
	.string "Meine Frage ist eigentlich recht dumm,\n"
	.string "aber ich kann mich nicht entscheiden…\p"
	.string "Im Duellturm kannst du an Level 50\n"
	.string "und Offenen Kämpfen teilnehmen.\p"
	.string "Welche Kämpfe kommen für mich wohl\n"
	.string "in Frage?!?$"
#else
	.string "Really? I can't believe it!\n"
	.string "I can't believe you'll advise me!\l"
	.string "I… I'm so happy…\p"
	.string "What I want to ask you is really\n"
	.string "trivial, but I can't decide…\p"
	.string "At the BATTLE TOWER, they let you\n"
	.string "choose Level 50 or Open Level.\p"
	.string "Which course do you think even I may\n"
	.string "have a chance at?$"
#endif

gText_ApprenticeLevelModeThanks3::
#if GERMAN
	.string "{STR_VAR_1}? Ja!\n"
	.string "Aber glaubst du wirklich, jemand wie\l"
	.string "ich hat da überhaupt eine Chance?\p"
	.string "Ich werde mein Bestes geben, auch wenn\n"
	.string "ich weiß, dass das nichts nützt.\p"
	.string "Vielen Dank, dass du deine kostbare\n"
	.string "Zeit jemandem wie mir gewidmet hast.$"
#else
	.string "{STR_VAR_1}? Okay!\n"
	.string "But do you really think someone like\l"
	.string "me would have a chance?\p"
	.string "I'll do my best, even though I don't\n"
	.string "think it will work.\p"
	.string "Thank you very much for spending\n"
	.string "time with someone like me.$"
#endif

gText_ApprenticePleaseTeach4::
#if GERMAN
	.string "Hi! Du bist {PLAYER}{KUN}?\p"
	.string "Ich habe gehört, du bist talentiert im\n"
	.string "Umgang mit Pokémon!\p"
	.string "Ich bin {STR_VAR_1}.\n"
	.string "Wir werden bestimmt gute Freunde\l"
	.string "werden.\p"
	.string "Weißt du was?\p"
	.string "Du kannst in der Kampfzone nicht\n"
	.string "gewinnen, wenn du dich auf das\p"
	.string "verlässt, was du in der Trainerschule\n"
	.string "gelernt hast…\p"
	.string "Daher würde ich auch gerne etwas von\n"
	.string "dir lernen. Bist du einverstanden?$"
#else
	.string "Oh! You're {PLAYER}{KUN}, aren't you?\p"
	.string "I've heard that you're tough at\n"
	.string "POKéMON!\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I'll be your friend!\p"
	.string "Did you know?\p"
	.string "You can't win at the BATTLE FRONTIER\n"
	.string "if all you know is what they teach at\l"
	.string "the TRAINER'S SCHOOL.\p"
	.string "I'm willing to listen to your advice.\n"
	.string "You'll agree, of course?$"
#endif

gText_ApprenticeRejectTeaching4::
#if GERMAN
	.string "Was? Warum lehnst du ab?\n"
	.string "Ich bin’s doch!\l"
	.string "Überleg dir das noch einmal!$"
#else
	.string "Huh? Why are you refusing me?\n"
	.string "It's me who's asking you!\l"
	.string "You have to reconsider!$"
#endif

gText_ApprenticeWhichLevelMode4::
#if GERMAN
	.string "Na, das hört sich doch gut an. Ich\n"
	.string "möchte, dass du mir bei einer\l"
	.string "Entscheidung hilfst.\p"
	.string "Im Duellturm gibt es doch die Level 50\n"
	.string "und die Offenen Kämpfe.\p"
	.string "An welchen soll ich teilnehmen,\n"
	.string "{PLAYER}{KUN}?$"
#else
	.string "Okay, so there is this something.\n"
	.string "I want you to decide it for me.\p"
	.string "You know that the BATTLE TOWER has\n"
	.string "Level 50 and Open Level Rooms?\p"
	.string "Which do you think would be good\n"
	.string "for me, {PLAYER}{KUN}?$"
#endif

gText_ApprenticeLevelModeThanks4::
#if GERMAN
	.string "{STR_VAR_1} kommt also für mich in\n"
	.string "Frage? Vielen Dank!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "Okay, {STR_VAR_1} is suitable for me?\n"
	.string "Thank you!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticePleaseTeach5::
#if GERMAN
	.string "Hallo! {PLAYER}{KUN}! Ich kenne dich!\n"
	.string "Du bist ja berühmt! Ich bin {STR_VAR_1}!\l"
	.string "Schön, dich kennen zu lernen!\p"
	.string "Ich bin ein Triathlet. Ich halte mich\n"
	.string "fit und ziehe nebenbei noch Pokémon\l"
	.string "auf.\p"
	.string "Ich arbeite, schlafe, tanze und habe \n"
	.string "noch viele andere Dinge zu tun…\p"
	.string "Und da ich so beschäftigt bin, ist es\n"
	.string "nicht leicht für mich, ein ordentlicher\l"
	.string "Trainer zu werden.\p"
	.string "Mir kommt da gerade eine Idee!\p"
	.string "Es kann kein Zufall sein, dass wir uns\n"
	.string "begegnet sind. {PLAYER}{KUN}, darf ich an\l"
	.string "deinem Wissen teilhaben?$"
#else
	.string "Oh, hi, there! {PLAYER}{KUN}!\n"
	.string "I know you because you're famous!\l"
	.string "Call me {STR_VAR_1}! Glad to meet you!\p"
	.string "I'm a TRIATHLETE, so I keep myself\n"
	.string "fit even while I raise POKéMON.\p"
	.string "I'm also involved with other things\n"
	.string "like work, napping, ballroom dancing…\p"
	.string "Being this busy, it's not so easy for\n"
	.string "me to become a decent TRAINER.\p"
	.string "So, I have a proposition!\p"
	.string "There must be a reason why we met.\n"
	.string "So, {PLAYER}{KUN}, how about sharing your\l"
	.string "wisdom with me every so often?$"
#endif

gText_ApprenticeRejectTeaching5::
#if GERMAN
	.string "Ach, komm schon. Bitte?\n"
	.string "Ich kann einen Lehrer wie dich gut\l"
	.string "gebrauchen, {PLAYER}{KUN}!\p"
	.string "Ich brauche wirklich ganz dringend\n"
	.string "deinen Rat.$"
#else
	.string "Oh, but, please?\n"
	.string "A guy like me needs someone like\l"
	.string "you, {PLAYER}{KUN}!\p"
	.string "Honestly, I need your advice!$"
#endif

gText_ApprenticeWhichLevelMode5::
#if GERMAN
	.string "Danke! Das hört sich doch schon viel\n"
	.string "besser an! Also, hier ist eine einfache\l"
	.string "Frage!\p"
	.string "Im Duellturm kann man an Level 50\n"
	.string "oder Offenen Kämpfen teilnehmen.\p"
	.string "An welchen sollte ein beschäftigter Typ\n"
	.string "wie ich teilnehmen?$"
#else
	.string "Thank you! That's more like it!\n"
	.string "So, let's start with an easy one!\p"
	.string "You know about the BATTLE TOWER's\n"
	.string "two courses, right?\l"
	.string "You know, Level 50 and Open Level.\p"
	.string "Me being a busy guy, which one should\n"
	.string "I gear up for?$"
#endif

gText_ApprenticeLevelModeThanks5::
#if GERMAN
	.string "{STR_VAR_1}? Fein. Ich werde\n"
	.string "irgendwie die Zeit dafür finden und\l"
	.string "daran teilnehmen.\p"
	.string "Jetzt muss ich aber wirklich wieder an\n"
	.string "die Arbeit…\l"
	.string "Vielen Dank! Man sieht sich!$"
#else
	.string "{STR_VAR_1}, huh? Okay, gotcha.\n"
	.string "I'll find time somehow and give it a go!\p"
	.string "…Whoops, I'd better go to work!\n"
	.string "Thanks! See you around!$"
#endif

gText_ApprenticePleaseTeach6::
#if GERMAN
	.string "Das gibt’s ja gar nicht!!!\n"
	.string "Bist du es wirklich, {PLAYER}?\p"
	.string "Ahah! Fantastisch! Ich bin {STR_VAR_1}.\n"
	.string "Toll, dass ich dich mal kennen lerne!\p"
	.string "Du bist wirklich stark und talentiert,\n"
	.string "nicht wahr, {PLAYER}?\p"
	.string "Alle sprechen über dich!\p"
	.string "Mir kommt da eine großartige Idee!!!\n"
	.string "Du gibst mir einen Rat, {PLAYER}!\l"
	.string "Dadurch werde ich bestimmt stärker!\p"
	.string "Ist das nicht eine Superidee?\n"
	.string "Bitte, ich muss an deiner Klugheit\l"
	.string "teilhaben. Ja?$"
#else
	.string "No way! Uh-uh!\n"
	.string "Are you maybe the real {PLAYER}?\p"
	.string "A-hah! Awesome! I'm {STR_VAR_1},\n"
	.string "so pleased to meet you!\p"
	.string "{PLAYER}, you're very strong,\n"
	.string "aren't you?\p"
	.string "Everyone's talking about you!\p"
	.string "Oh! I just had this great idea!\n"
	.string "I'll get advice off you, {PLAYER}!\l"
	.string "I'm sure it will make me tougher!\p"
	.string "Isn't it a great idea?\n"
	.string "Please, I want your advice!$"
#endif

gText_ApprenticeRejectTeaching6::
#if GERMAN
	.string "Hahahaha, du tust doch nur so, als ob du\n"
	.string "gemein seist. Du kannst mich nicht an\l"
	.string "der Nase herumführen! Du hilfst mir?$"
#else
	.string "Ahahaha, you can pretend to be mean,\n"
	.string "but you can't fool me!\l"
	.string "You really mean okay, don't you?$"
#endif

gText_ApprenticeWhichLevelMode6::
#if GERMAN
	.string "Siehst du! Ich wusste doch, du hast ein\n"
	.string "gutes Herz, {PLAYER}!\p"
	.string "Mh, was frage ich dich jetzt als Erstes?\n"
	.string "Mal sehen… Hah, ich weiß!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Meine Frage lautet…\p"
	.string "An welchen Kämpfen soll ich im\n"
	.string "Duellturm teilnehmen?\p"
	.string "Level 50 oder Offene Kämpfe?\n"
	.string "Welche passen zu mir?$"
#else
	.string "Yay! I knew you'd have a big heart,\n"
	.string "{PLAYER}!\p"
	.string "What should I ask you first?\n"
	.string "…Oh, I thought of something!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I were to take a BATTLE TOWER\n"
	.string "challenge, which way should I go?\p"
	.string "Level 50 or Open Level?\n"
	.string "Which suits me more?$"
#endif

gText_ApprenticeLevelModeThanks6::
#if GERMAN
	.string "Ooooh, wow!\n"
	.string "{STR_VAR_1}, meinst du?!?\l"
	.string "Eine coole Antwort. Danke!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"
#else
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thank you for a totally cool reply!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticePleaseTeach7::
#if GERMAN
	.string "Ich bitte vielmals um Verzeihung, aber…\n"
	.string "Bist du {PLAYER}?\p"
	.string "Ich bin {STR_VAR_1}.\n"
	.string "Schön, dich kennen zu lernen!\p"
	.string "Ich bewundere dich schon lange…\p"
	.string "… … … … …\n"
	.string "…\p"
	.string "Wenn es dir nicht zu viel ausmacht,\n"
	.string "würde ich dich gerne um etwas bitten…\p"
	.string "Darf ich deine Schülerin\n"
	.string "werden, {PLAYER}?$"
#else
	.string "I beg your pardon, but…\n"
	.string "Are you {PLAYER}?\p"
	.string "I'm {STR_VAR_1}, and I am delighted to\n"
	.string "make your acquaintance.\p"
	.string "I have long been an admirer\n"
	.string "of yours…\p"
	.string "… … … … … …\p"
	.string "Um… I hope you don't find this\n"
	.string "request too much of a burden, but…\p"
	.string "May I become your apprentice,\n"
	.string "{PLAYER}?$"
#endif

gText_ApprenticeRejectTeaching7::
#if GERMAN
	.string "Oh…\p"
	.string "… … … … … \n"
	.string "…\l"
	.string "… … … … …\l"
	.string "…\p"
	.string "Ich muss vor Schreck in Ohnmacht\n"
	.string "gefallen sein… Ich habe dich\l"
	.string "bestimmt falsch verstanden!\p"
	.string "Bitte! Nimm mich als deine Schülerin\n"
	.string "an. Ja?$"
#else
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…I must have fainted from shock.\n"
	.string "I'm sorry, I must have misheard you.\p"
	.string "Please! Please say that you will\n"
	.string "accept me as your apprentice!$"
#endif

gText_ApprenticeWhichLevelMode7::
#if GERMAN
	.string "Oh… Das freut mich!!!\p"
	.string "Ich möchte deine Zeit nicht übermäßig\n"
	.string "in Anspruch nehmen, daher stelle ich dir\l"
	.string "eine einzige Frage.\p"
	.string "Ich möchte gern im Duellturm antreten.\p"
	.string "Aber zu welchen Kämpfen soll ich\n"
	.string "mich anmelden?\p"
	.string "Level 50 oder Offene Kämpfe?\n"
	.string "Welche kommen für mich in Frage?$"
#else
	.string "Oh… I'm delighted!\p"
	.string "I don't wish to waste your time,\n"
	.string "so please advise me on this.\p"
	.string "I plan to take a BATTLE TOWER\n"
	.string "challenge soon.\p"
	.string "However, there are two levels…\p"
	.string "Which would be most suitable for me?\n"
	.string "Level 50 or Open Level?$"
#endif

gText_ApprenticeLevelModeThanks7::
#if GERMAN
	.string "{STR_VAR_1}, sagst du?\n"
	.string "Ja! Ich werde mein Bestes geben!\l"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "{STR_VAR_1} is your choice!\n"
	.string "I see. I will do my best!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticePleaseTeach8::
#if GERMAN
	.string "Iiihiii! {PLAYER}!\n"
	.string "Du hast mich angesprochen!!!\l"
	.string "Ich… kann mein Glück kaum fassen!\p"
	.string "Ich? Ich bin {STR_VAR_1}!\n"
	.string "Ich bin gerade erst Trainer geworden.\p"
	.string "Ich freue mich, dich getroffen zu\n"
	.string "haben, {PLAYER}. Du bist eine\l"
	.string "Berühmtheit in Pokémon-Kreisen!\p"
	.string "Diese Gelegenheit möchte ich nutzen!\n"
	.string "Darf ich dich um einen Riesengefallen\l"
	.string "bitten, {PLAYER}?\p"
	.string "Bitte nimm mich als deine Schülerin an!\n"
	.string "Ich möchte so gerne von dir lernen!$"
#else
	.string "Eek! Eek! {PLAYER}!\n"
	.string "You spoke to me!\l"
	.string "I… I'm overjoyed!\p"
	.string "Me! My name is {STR_VAR_1}!\n"
	.string "I just became a TRAINER!\p"
	.string "I'm delighted I met you, {PLAYER},\n"
	.string "the big name in POKéMON circles!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "May I ask a huge favor, {PLAYER}?\p"
	.string "Please take me in as your apprentice!\n"
	.string "I want to learn from you!$"
#endif

gText_ApprenticeRejectTeaching8::
#if GERMAN
	.string "Waaaaahaaaa! {PLAYER} hat mich\n"
	.string "abgelehnt… Und dabei wäre\l"
	.string "es eine unbezahlbare Erfahrung!\p"
	.string "Bitte, {PLAYER}! Ich würde so gerne ein\n"
	.string "Ja von dir hören!\p"
	.string "Ich bitte dich! Bitte, ja?$"
#else
	.string "Waaaah!\n"
	.string "{PLAYER} turned me down…\l"
	.string "It… It's an invaluable experience!\p"
	.string "{PLAYER}, please! I want to hear\n"
	.string "an affirmative answer this time!\p"
	.string "I beg you for your guidance!$"
#endif

gText_ApprenticeWhichLevelMode8::
#if GERMAN
	.string "Hiiihiii! {PLAYER} hat Ja gesagt!\n"
	.string "{PLAYER} hat Ja gesagt!\p"
	.string "Heute Nacht werde ich mit Sicherheit\n"
	.string "nicht schlafen können…\p"
	.string "Und hier ist meine Frage!\p"
	.string "Soll ich im Duellturm in Level 50 oder\n"
	.string "an den Offenen Kämpfen teilnehmen?$"
#else
	.string "Hieeeeh! {PLAYER} said yes!\n"
	.string "{PLAYER} said yes!\p"
	.string "I won't be able to sleep tonight…\n"
	.string "Thank you ever so much!\p"
	.string "Then, here's my question!\p"
	.string "At the BATTLE TOWER, what is right\n"
	.string "for me, Level 50 or Open Level?$"
#endif

gText_ApprenticeLevelModeThanks8::
#if GERMAN
	.string "{STR_VAR_1}! Superfein!\n"
	.string "Ich freu mich so sehr! Mir ist\l"
	.string "richtig schwindelig vor Glück!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"
#else
	.string "{STR_VAR_1}! Perfectly understood!\n"
	.string "I understand perfectly!\l"
	.string "I'm deliriously delighted!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
#endif

gText_ApprenticePleaseTeach9::
#if GERMAN
	.string "Whoa! Das kann nicht sein…\n"
	.string "Bist du eventuell… {PLAYER}{KUN}?!?\l"
	.string "Dieser starke und berühmte Trainer?\p"
	.string "Ich muss ein Glückzilp… Äh… Glückspilz\n"
	.string "sein! Ich heiße {STR_VAR_1}!\p"
	.string "Ich bin auf der Suche nach einem\n"
	.string "Pokémon-Lehrer!\p"
	.string "So etwas nenn ich perfektes Timing,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Bitte nimm mich unter deine Eittichf…\n"
	.string "Äh… Fittiche!$"
#else
	.string "Whoa! Could you be…\n"
	.string "Might you be… {PLAYER}{KUN}?!\l"
	.string "That strong and famous TRAINER?\l"
	.string "Well, hello, aren't I just the luckiest!\p"
	.string "Hello, the name's {STR_VAR_1}!\p"
	.string "I've been on the lookout for\n"
	.string "a POKéMON teacher.\p"
	.string "And with impeccably good timing,\n"
	.string "along came you, {PLAYER}{KUN}!\p"
	.string "So, there you have it, {PLAYER}{KUN}!\n"
	.string "Let me apprentice under you!$"
#endif

gText_ApprenticeRejectTeaching9::
#if GERMAN
	.string "Guaaaah!\n"
	.string "Du bist so cool und abgebrüht…\p"
	.string "Komm sei nicht so!\n"
	.string "Ich bitte chid… Äh… dich!$"
#else
	.string "Gwaaaah!\n"
	.string "You're quite cool and tough…\p"
	.string "Don't be that way, please.\n"
	.string "I'm asking you!$"
#endif

gText_ApprenticeWhichLevelMode9::
#if GERMAN
	.string "Nun, mit der Antwort kann ich was\n"
	.string "anfangen! Eine exzellente Antwort!\p"
	.string "Wie wäre es, wenn du mir einen Rat\n"
	.string "zu dem Duellturm geben würdest?\p"
	.string "Level 50 oder Offene Kämpfe? An\n"
	.string "was soll ich teilnehmen?$"
#else
	.string "Oh, yeah! That's a solid reply!\n"
	.string "Excellent, I might add!\p"
	.string "So how about a first piece of advice\n"
	.string "on the BATTLE TOWER?\p"
	.string "If I were to go, what would be better?\n"
	.string "Level 50 or Open Level?$"
#endif

gText_ApprenticeLevelModeThanks9::
#if GERMAN
	.string "Ha, {STR_VAR_1} also!\n"
	.string "Nief… Äh… Fein!\l"
	.string "Ich werde mein Bestes geben!\p"
	.string "Und du bist ab sofort mein Lehrer!\n"
	.string "Bis bald nand… Äh… dann!$"
#else
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll go show my mettle, like, jam!\p"
	.string "All right, I'll look to you as my mentor!\n"
	.string "Adios!$"
#endif

gText_ApprenticePleaseTeach10::
#if GERMAN
	.string "Hey, du bist doch {PLAYER}{KUN}, oder?\n"
	.string "Die Polizei sucht dich!!!\p"
	.string "… … … …\n"
	.string "Hahaha, ich hab dich auf den Arm\l"
	.string "genommen! Dein blödes Gesicht…\p"
	.string "Ich bin {STR_VAR_1}. Ich sehe vielleicht\n"
	.string "nicht so aus, aber du stehst vor dem\l"
	.string "Pokémon-Champ! Jawohl!\p"
	.string "Haha! Ich habe dich schon wieder auf\n"
	.string "den Arm genommen!\p"
	.string "Ich bin kein talentierter Kämpfer.\n"
	.string "Und diesmal sag ich die Wahrheit!\p"
	.string "Wie wäre es, wenn du mich als deinen\n"
	.string "Schüler annimmst?$"
#else
	.string "Oh, hey, {PLAYER}{KUN}, right?\n"
	.string "The police were looking for you!\p"
	.string "… … …\n"
	.string "Of course I'm lying!\p"
	.string "Me, I'm {STR_VAR_1}. Despite the way\n"
	.string "I look, I'm the POKéMON CHAMPION!\l"
	.string "…That's a lie, too!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at battling.\p"
	.string "So, how about you becoming my master\n"
	.string "about all things POKéMON?$"
#endif

gText_ApprenticeRejectTeaching10::
#if GERMAN
	.string "Ich werde dir zeigen, wie ich auf so eine\n"
	.string "rüde Abfuhr reagiere!\p"
	.string "Waaaah! Heul! Jammer! Klag!\n"
	.string "Hick…\p"
	.string "Hahaha! Das waren meine Trugtränen!\n"
	.string "Reingelegt!\p"
	.string "Komm, bitte nimm mich als deinen\n"
	.string "Schüler!$"
#else
	.string "If you're going to act cold like that,\n"
	.string "I'll show you what I'll do!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Hiccup!\p"
	.string "Hahaha, that was my FAKE TEARS!\p"
	.string "Come on, will you please be\n"
	.string "my POKéMON master?$"
#endif

gText_ApprenticeWhichLevelMode10::
#if GERMAN
	.string "Jipiii!\n"
	.string "Dafür schenke ich dir ein großes Boot!\p"
	.string "Nee, ich nehme dich schon wieder hoch!\n"
	.string "Aber… Ich danke dir!\p"
	.string "Im Duellturm kann man doch an\n"
	.string "Level 50 und Offenen Kämpfen\l"
	.string "teilnehmen.\p"
	.string "Ich kann mich nicht entscheiden, an\n"
	.string "welchen Kämpfen ich teilnehmen soll…\p"
	.string "Kannst du das für mich entscheiden,\n"
	.string "mein Lehrer?$"
#else
	.string "Yippee!\n"
	.string "I'll buy you a boat for that!\p"
	.string "Of course I'm lying again!\n"
	.string "But… Thank you, master!\p"
	.string "You know how there's Level 50 and\n"
	.string "Open Level at the BATTLE TOWER?\p"
	.string "I'm having trouble deciding which\n"
	.string "level I should challenge…\p"
	.string "Can you decide for me, master?$"
#endif

gText_ApprenticeLevelModeThanks10::
#if GERMAN
	.string "Aha! {STR_VAR_1}.\n"
	.string "Dann werde ich an den anderen Kämpfen\l"
	.string "teilnehmen, das ist klar!\p"
	.string "Haha! Das war ein Witz! Ich werde\n"
	.string "natürlich auf deinen Rat hören, Lehrer!\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so {STR_VAR_1} is better!\n"
	.string "I'll go to the other level, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticePleaseTeach11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi und Hallo!\p"
	.string "Ich bin der Matrose {STR_VAR_1}!\p"
	.string "Du bist dran!\n"
	.string "Nenn mir deinen Namen, Mann!\p"
	.string "Aha, aha!\n"
	.string "{PLAYER}{KUN} bist du,\l"
	.string "und Pokémon gehören auch dazu.\p"
	.string "Wird die Welt dir zur Bühne,\n"
	.string "musst du sein der starke Kühne.\p"
	.string "Was ich dir damit eigentlich sage,\n"
	.string "du bist der zehnte Trainer, den ich\l"
	.string "heut frage.\p"
	.string "Lass mich nicht im Regen stehn,\n"
	.string "möchte dich als meinen Lehrer sehn.$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy, and it means hi!\p"
	.string "I'm {STR_VAR_1}, the rappin' SAILOR\n"
	.string "am I!\p"
	.string "Your turn now, tell me a little about\n"
	.string "yourself, give it a try!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN}'s your name,\l"
	.string "and POKéMON's your game!\p"
	.string "And you're at a delicate age\n"
	.string "when all the world's your stage!\p"
	.string "Anyway, I just want to say,\n"
	.string "that you're the tenth TRAINER\l"
	.string "I've spoken to today.\p"
	.string "Let's make that a celebration!\n"
	.string "Become my mentor for commemoration!$"
#endif

gText_ApprenticeRejectTeaching11::
#if GERMAN
	.string "Aber!\n"
	.string "Du musst mich als Schüler annehmen!\p"
	.string "Sei doch nicht so gemein!\n"
	.string "Lass mich bitte dein Schüler sein!$"
#else
	.string "But!\n"
	.string "You have to work with me!\p"
	.string "Don't be such a tease!\n"
	.string "Become my mentor, please!$"
#endif

gText_ApprenticeWhichLevelMode11::
#if GERMAN
	.string "{PLAYER}, das ist die richtige\n"
	.string "Einstellung!\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "Der Duellturm, da komm ich mir\n"
	.string "vor wie ein Wurm.\p"
	.string "Level 50 oder Offene Kämpfe,\n"
	.string "was soll ich wählen? Ich muss auf deine\l"
	.string "Entscheidung zählen.$"
#else
	.string "That's it!\n"
	.string "{PLAYER}, you've got the spirit!\p"
	.string "So here's my first question\n"
	.string "that begs your suggestion!\p"
	.string "It's about the BATTLE TOWER,\n"
	.string "and it hinges on my power!\p"
	.string "Level 50 and Open Level there be,\n"
	.string "which is the one that's good for me?$"
#endif

gText_ApprenticeLevelModeThanks11::
#if GERMAN
	.string "{STR_VAR_1} sagst du?\n"
	.string "Gut, ich hörte dir zu.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "Okay, {STR_VAR_1} it is, you say!\n"
	.string "I'll go and take it on my way!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticePleaseTeach12::
#if GERMAN
	.string "Sag, bist du nicht {PLAYER}? Was mache\n"
	.string "ich jetzt nur? Mit dir reden? Warum\l"
	.string "nicht? Ich rede ja eh schon mir dir.\p"
	.string "{PLAYER}, habe ich dich überrascht?\n"
	.string "Ich sage dir besser, mit wem du es zu\l"
	.string "tun hast!\p"
	.string "Du darfst mich {STR_VAR_1} nennen. Ich\n"
	.string "bin der beste Gitarrist, den es gibt! Ja,\l"
	.string "das sage ich in aller Bescheidenheit!\p"
	.string "Nimmst du mir das ab?\n"
	.string "Du nimmst es mir ab!\p"
	.string "Da ich so viel Glück habe, werde ich dies\n"
	.string "weiter auf die Probe stellen.\l"
	.string "Ich habe eine Bitte an dich!\p"
	.string "{PLAYER}, bitte nimm mich als deinen\n"
	.string "Schüler an! Ich möchte alles von\l"
	.string "dir lernen!$"
#else
	.string "Say, hey, aren't you {PLAYER}?\n"
	.string "What should I do? Talk to you?\l"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised at me?\n"
	.string "I'd better tell you who I happen to be!\p"
	.string "{STR_VAR_1} is what you can call me.\n"
	.string "The brightest star in guitardom,\l"
	.string "that's me!\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My luck's at its best,\n"
	.string "I'll hit you with a request!\p"
	.string "{PLAYER}, let me be your underling!\n"
	.string "I want you to teach me everything!$"
#endif

gText_ApprenticeRejectTeaching12::
#if GERMAN
	.string "Du lehnst mich also ab, was?\n"
	.string "Dann werde ich dich einfach nochmal\l"
	.string "fragen.\p"
	.string "{PLAYER}, nimmst du mich als deinen\n"
	.string "Schüler an? Ich möchte alles von\l"
	.string "dir lernen!$"
#else
	.string "You're turning me down, then?\n"
	.string "I'll just have to ask you again!\p"
	.string "{PLAYER}, I beg to be your underling!\n"
	.string "I need you to teach me everything!$"
#endif

gText_ApprenticeWhichLevelMode12::
#if GERMAN
	.string "Ich bade im Glück, hähähä!\n"
	.string "Und schon habe ich eine Frage!\p"
	.string "Da wir hier im Duellturm\n"
	.string "sind, drängt sich mir diese Frage auf!\p"
	.string "Welche Kämpfe soll ich hier bestreiten?$"
#else
	.string "Lucky, yeah, woohoo!\n"
	.string "Should I pop a question to you?\p"
	.string "Since we're near the BATTLE TOWER,\n"
	.string "how about a question about its power?\p"
	.string "Of the choices you see,\n"
	.string "which is the right one for me?$"
#endif

gText_ApprenticeLevelModeThanks12::
#if GERMAN
	.string "Du meinst also {STR_VAR_1}?\n"
	.string "Das wird dann wohl das Beste sein!\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "If {STR_VAR_1} is what you suggest,\n"
	.string "it must be the very best!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticePleaseTeach13::
#if GERMAN
	.string "Oh, hallo! Du da! Dich meine ich!\n"
	.string "Kannst du mir nicht meine Schultern\l"
	.string "massieren?\p"
	.string "Ja… Genau da! Oh, ja!\n"
	.string "Auaaa! Au! Das tut gut!\p"
	.string "Ich heiße {STR_VAR_1}!\n"
	.string "Ich trainiere Karate, aber mein Körper\l"
	.string "mag das gar nicht leiden…\p"
	.string "Daher überlege ich, ob ich nicht an\n"
	.string "Pokémon-Kämpfen teilnehmen soll, um\l"
	.string "meine Muskeln aufzubauen.\p"
	.string "Du bist {PLAYER}{KUN}, stimmt’s?\n"
	.string "Der Champ der Pokémon Liga?\p"
	.string "Kannst du mir nicht mit Rat und Tat zur\n"
	.string "Seite stehen?$"
#else
	.string "Oh, hi! You there!\n"
	.string "Can I get you to massage my shoulder?\p"
	.string "…Yes, there! That's it!\n"
	.string "Ouch, ouch! Oooh, that feels great!\p"
	.string "My name's {STR_VAR_1}.\n"
	.string "I take karate training, but my body's\l"
	.string "not built to take the abuse…\p"
	.string "I decided I'll battle POKéMON and\n"
	.string "toughen myself up.\p"
	.string "You're {PLAYER}{KUN}, aren't you?\n"
	.string "The POKéMON LEAGUE CHAMP?\p"
	.string "Listen, can I get you to give me\n"
	.string "advice?$"
#endif

gText_ApprenticeRejectTeaching13::
#if GERMAN
	.string "Oh, warum nicht?\p"
	.string "Ich werde dich auch nicht nerven!\n"
	.string "Ehrlich nicht! Komm schon, ja?$"
#else
	.string "Oh, why?\p"
	.string "I won't be a big bother, I promise!\n"
	.string "Please?$"
#endif

gText_ApprenticeWhichLevelMode13::
#if GERMAN
	.string "Vielen Dank! Das ist megacool von dir!\n"
	.string "Hust… Hust…\p"
	.string "Röchel… Ich muss mich wirklich\n"
	.string "sportlich betätigen…\p"
	.string "Ich kämpfe sofort hier weiter!!\n"
	.string "Aber soll ich an Level 50 oder den\l"
	.string "Offenen Kämpfen teilnehmen?$"
#else
	.string "Thank you. Mighty good of you!\n"
	.string "…Cough! Cough!\p"
	.string "Oogh, I have to toughen up quick…\p"
	.string "I'll be heading off to the BATTLE TOWER\n"
	.string "right away, but what would be better\l"
	.string "for me? Level 50 or Open Level?$"
#endif

gText_ApprenticeLevelModeThanks13::
#if GERMAN
	.string "Hm, gut. {STR_VAR_1}.\n"
	.string "Ich mache mich sofort auf den Weg!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"
#else
	.string "Hm, all right. That's {STR_VAR_1}.\n"
	.string "I'll go there right away.\p"
	.string "I hope I can keep hitting you up for\n"
	.string "help--after all, you're my mentor!$"
#endif

gText_ApprenticePleaseTeach14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Oh, schau mich nicht so an. Du machst\n"
	.string "mich ganz verlegen!\p"
	.string "Ich… Ich bin {STR_VAR_1}.\p"
	.string "Es ist mir ja schrecklich peinlich\n"
	.string "es zuzugeben, aber ich untersuche\l"
	.string "alte Ruinen und so was.\p"
	.string "Und es ist noch peinlicher, dass ich\n"
	.string "Interesse an der Kampfzone habe.\p"
	.string "Du hast den Ruf eines starken\n"
	.string "Trainers, {PLAYER}{KUN}…\p"
	.string "Es fällt mir schwer, das zu sagen, aber\n"
	.string "ich möchte dich etwas fragen.\p"
	.string "Kannst du nicht mein Lehrer werden\n"
	.string "und mir mit Rat und Tat zur Seite\l"
	.string "stehen?$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all self-conscious.\p"
	.string "I… I'm {STR_VAR_1}.\p"
	.string "I'm really embarrassed to say this,\n"
	.string "but I explore ancient ruins and such.\p"
	.string "I'm even more embarrassed to admit\n"
	.string "I'm interested in the BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, you have a reputation as\n"
	.string "a tough TRAINER…\p"
	.string "It's hard for me to say this,\n"
	.string "but I want to ask something.\p"
	.string "Could you become my teacher and\n"
	.string "give me advice?$"
#endif

gText_ApprenticeRejectTeaching14::
#if GERMAN
	.string "Bitte, weis mich nicht so einfach ab!\n"
	.string "Ich kann mit dieser Peinlichkeit\l"
	.string "nicht leben!\p"
	.string "Bitte, werde mein Lehrer!\n"
	.string "Ich brauche deine Weisheit!$"
#else
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Please become my teacher!\n"
	.string "I need your advice!$"
#endif

gText_ApprenticeWhichLevelMode14::
#if GERMAN
	.string "Da-Danke…\p"
	.string "Schau mich nicht so an!\n"
	.string "Ich werde ja ganz rot.\p"
	.string "Bitte antworte mir, ohne mir in die\n"
	.string "Augen zu schauen.\p"
	.string "Im Duellturm… An welchen Kämpfen\n"
	.string "soll ich da teilnehmen?$"
#else
	.string "Th-thank you…\p"
	.string "But please don't look at me like that.\n"
	.string "It makes me all flustered.\p"
	.string "Please, answer me without looking\n"
	.string "at my eyes.\p"
	.string "At the BATTLE TOWER…\n"
	.string "Which level should I attempt?$"
#endif

gText_ApprenticeLevelModeThanks14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Ich werde mich gewiss anstrengen.\p"
	.string "Ich hoffe, ich werde mich nicht allzu\n"
	.string "sehr blamieren, wenn ich mich da\l"
	.string "versuche…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll try my hand at that.\p"
	.string "I hope I can make a valiant challenge\n"
	.string "without getting all flustered…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticePleaseTeach15::
#if GERMAN
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du wirklich du?\p"
	.string "Du kannst mich {STR_VAR_1} nennen.\p"
	.string "Ich überlege gerade, ob ich mir nicht\n"
	.string "einen starken Trainer als Lehrer\l"
	.string "suchen soll.\p"
	.string "Da habe ich Glück, dass du hier\n"
	.string "vorbeigekommen bist.\l"
	.string "Du bist doch {PLAYER}{KUN}, oder?\p"
	.string "Also, wenn du echt bist, ist alles in\n"
	.string "Ordnung. Ich möchte nur, dass du mich\l"
	.string "als deinen Schüler annimmst.$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "You may call me {STR_VAR_1}.\p"
	.string "I have been toying with the idea of\n"
	.string "apprenticing under a strong TRAINER.\p"
	.string "So, I must say I'm lucky you came along!\n"
	.string "…You really are {PLAYER}{KUN}, yes?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "I merely want you to recognize me\l"
	.string "as your apprentice.$"
#endif

gText_ApprenticeRejectTeaching15::
#if GERMAN
	.string "Oh? Warum lehnst du mich ab?\p"
	.string "Ich entschuldige mich, dass ich an\n"
	.string "deiner Identität gezweifelt habe.\p"
	.string "Nimm meine Entschuldigung und mich\n"
	.string "als deinen Schüler an. Bitte.$"
#else
	.string "Oh?\n"
	.string "But what would compel you to refuse?\p"
	.string "I apologize for being skeptical about\n"
	.string "your identity.\p"
	.string "Please accept my apology and\n"
	.string "accept me as your apprentice.$"
#endif

gText_ApprenticeWhichLevelMode15::
#if GERMAN
	.string "Du nimmst mich wirklich an?\n"
	.string "Ich möchte auf keinen Fall unreif\l"
	.string "erscheinen.\p"
	.string "Wenn das wahr ist, dann entschuldige\n"
	.string "ich mich, dass ich an deiner Identität\l"
	.string "gezweifelt habe.\p"
	.string "Ich möchte im Duellturm antreten.\n"
	.string "Soll ich an Level 50 oder Offenen\l"
	.string "Kämpfen teilnehmen?$"
#else
	.string "You really are accepting me?\n"
	.string "I don't wish to celebrate prematurely.\p"
	.string "If it is true, I apologize.\n"
	.string "But now, I need your advice.\p"
	.string "If I were to enter the BATTLE TOWER,\n"
	.string "what would be worthy of me?\l"
	.string "Level 50 or Open Level?$"
#endif

gText_ApprenticeLevelModeThanks15::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Bist du dir da ganz sicher?\p"
	.string "Verstehe. In dem Fall danke ich dir,\n"
	.string "dass du dir Zeit für mich genommen hast.\p"
	.string "Ich weiß, manchmal nerve ich. Umso mehr\n"
	.string "freut es mich, dass du mich angenommen\l"
	.string "hast.\p"
	.string "Bis bald mal!$"
#else
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I realize I can annoy, but it delights\n"
	.string "me that you have accepted me.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticeWhatHeldItem0::
#if GERMAN
	.string "Seufz… Jammer…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Ich habe ein Problem, bei dem ich zu\n"
	.string "keiner Lösung komme.\p"
	.string "Ich kann mich nicht entscheiden,\n"
	.string "welches Item mein {STR_VAR_1} tragen\l"
	.string "soll.\p"
	.string "Sag du es mir, {PLAYER}.\n"
	.string "Welches Item soll ich ihm geben?$"
#else
	.string "Sigh… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "I'm all tangled up in a dilemma\n"
	.string "that I can't decide.\p"
	.string "I can't decide what I should make\n"
	.string "my {STR_VAR_1} hold.\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "What item should I make it hold?$"
#endif

gText_ApprenticeHoldNothing0::
#if GERMAN
	.string "Oh? Ich soll meinem {STR_VAR_1} nichts\n"
	.string "geben?!?$"
#else
	.string "Oh, really? I shouldn't make\n"
	.string "my {STR_VAR_1} hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem0::
#if GERMAN
	.string "Oh, okay! Gut, dass wir das Problem\n"
	.string "gelöst haben. Herrlich! Juhuu!\p"
	.string "Vielen, vielen Dank!$"
#else
	.string "Oh, okay! I'm delighted it's settled!\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Thank you so much!$"
#endif

gText_ApprenticeThanksHeldItem0::
#if GERMAN
	.string "Oh, da bin ich aber froh…\n"
	.string "Ich müsste sogar {STR_VAR_1} haben.\p"
	.string "Bin ich froh, dass wir das Problem\n"
	.string "gelöst haben! Herrlich! Juhuu!\p"
	.string "Vielen, vielen Dank!$"
#else
	.string "Oh, I'm so glad…\n"
	.string "I think I have that {STR_VAR_1}, too.\p"
	.string "I'm delighted it's settled!\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Thank you so much!$"
#endif

gText_ApprenticeItemAlreadyRecommended0::
#if GERMAN
	.string "Waaahaaa! Das ist sooo gemein!\p"
	.string "{STR_VAR_1} wurde mir vorher auch\n"
	.string "schon mal vorgeschlagen… Schnief…\p"
	.string "Oder meinst du, mein {STR_VAR_2} sollte\n"
	.string "besser gar nichts tragen?$"
#else
	.string "Waaaah! Please don't be mean!\p"
	.string "That item {STR_VAR_1} was already\n"
	.string "recommended to me before, sob…\p"
	.string "Or do you mean I shouldn't make\n"
	.string "my {STR_VAR_2} hold anything?$"
#endif

gText_ApprenticeWhatHeldItem1::
#if GERMAN
	.string "Hey! Du bist es, {PLAYER}! Sehr gut!\n"
	.string "Ich wollte dich nämlich was fragen!\p"
	.string "Halten deine Pokémon Items? Ich\n"
	.string "möchte meinen auch Items geben, aber…\p"
	.string "Welches Item soll mein {STR_VAR_1}\n"
	.string "nur tragen? Ich weiß es einfach nicht…\p"
	.string "Was meinst du?$"
#else
	.string "Yay! It's {PLAYER}!\n"
	.string "Great! I wanted to ask you something!\p"
	.string "Do you make your POKéMON hold items?\n"
	.string "I want to make mine hold items, but…\p"
	.string "What item would be good for\n"
	.string "{STR_VAR_1} to hold?\p"
	.string "What do you think?$"
#endif

gText_ApprenticeHoldNothing1::
#if GERMAN
	.string "Wie? Du meinst, {STR_VAR_1} braucht\n"
	.string "kein Item?$"
#else
	.string "Huh? You mean my {STR_VAR_1} doesn't\n"
	.string "have to hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem1::
#if GERMAN
	.string "Oh, verstehe! Das mache ich! Genau!\n"
	.string "Vielen Dank für deine Hilfe!$"
#else
	.string "Oh, I get it! I'll do that!\n"
	.string "Thanks for teaching me!$"
#endif

gText_ApprenticeThanksHeldItem1::
#if GERMAN
	.string "Oh, wow! {STR_VAR_1}?!?\n"
	.string "Okay, das gebe ich ihm.\p"
	.string "Vielen Dank für deinen Rat!$"
#else
	.string "Oh, wow! One {STR_VAR_1}, huh?\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"
#endif

gText_ApprenticeItemAlreadyRecommended1::
#if GERMAN
	.string "Oh, so habe ich das aber gar nicht\n"
	.string "gemeint! Ich wollte wissen, wie sich die\l"
	.string "Items unterscheiden.\p"
	.string "Manche kenne ich, manche eben nicht.\n"
	.string "Oder meinst du, mein Pokémon benötigt\l"
	.string "kein Item?$"
#else
	.string "Oh, uh, no, that's not what I meant.\n"
	.string "I want to know about a different item\l"
	.string "than the ones I already know.\p"
	.string "Or do you mean that my POKéMON doesn't\n"
	.string "have to hold anything this time?$"
#endif

gText_ApprenticeWhatHeldItem2::
#if GERMAN
	.string "Hallo {PLAYER}!\n"
	.string "Es geht um mein {STR_VAR_1}…\p"
	.string "Ich würde ihm gerne ein gutes Item zum\n"
	.string "Tragen geben. Aber welches?$"
#else
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}…\p"
	.string "I want to make it hold a good item.\n"
	.string "What would be good for it?$"
#endif

gText_ApprenticeHoldNothing2::
#if GERMAN
	.string "Oh, mein {STR_VAR_1} benötigt kein\n"
	.string "Item?$"
#else
	.string "Oh, then my {STR_VAR_1} doesn't have\n"
	.string "to hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem2::
#if GERMAN
	.string "Oh, verstehe!\n"
	.string "Bis später dann!$"
#else
	.string "Okay, I got it!\n"
	.string "See you again!$"
#endif

gText_ApprenticeThanksHeldItem2::
#if GERMAN
	.string "Oh, {STR_VAR_1}?\n"
	.string "Klar!\p"
	.string "Ich werde mir Mühe geben, das Item zu\n"
	.string "finden. Bis später dann!$"
#else
	.string "Oh, the item {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I'll do my best to find one!\n"
	.string "See you again!$"
#endif

gText_ApprenticeItemAlreadyRecommended2::
#if GERMAN
	.string "Jemand hat mir bereits zu {STR_VAR_1}\n"
	.string "geraten.\p"
	.string "Aber ich möchte meinem Pokémon ein\n"
	.string "anderes Item zum Tragen geben.\p"
	.string "Oder meinst du, mein {STR_VAR_2}\n"
	.string "benötigt kein Item?$"
#else
	.string "Somebody taught me about\n"
	.string "the {STR_VAR_1} already.\p"
	.string "I want my POKéMON to hold a different\n"
	.string "kind of item.\p"
	.string "Or do you think {STR_VAR_2} doesn't\n"
	.string "have to hold anything?$"
#endif

gText_ApprenticeWhatHeldItem3::
#if GERMAN
	.string "Hallo, {PLAYER}…\n"
	.string "Ich muss dich noch mal belästigen. Ich\l"
	.string "habe eine wichtige Frage.\p"
	.string "Ich glaube nicht, dass ich gut genug\n"
	.string "bin, um einen Kampf zu gewinnen. Daher\l"
	.string "überlege ich, meinem {STR_VAR_1} ein\p"
	.string "Item zum Tragen zu geben.\n"
	.string "Aber ich weiß nicht, welches.\p"
	.string "{PLAYER}, kannst du das nicht für mich\n"
	.string "entscheiden?$"
#else
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to disturb you, but I have\l"
	.string "something else I wanted to ask you.\p"
	.string "I don't think I'm good enough to win\n"
	.string "matches on my own, so I'm thinking of\l"
	.string "making my {STR_VAR_1} hold an item.\p"
	.string "But I don't know what would be good.\p"
	.string "{PLAYER}, please, could you decide\n"
	.string "for me?$"
#endif

gText_ApprenticeHoldNothing3::
#if GERMAN
	.string "Ein Pokémon, das zu jemandem wie mir\n"
	.string "gehört, benötigt kein Item?$"
#else
	.string "A POKéMON belonging to someone like me\n"
	.string "would be better off without an item?$"
#endif

gText_ApprenticeThanksNoHeldItem3::
#if GERMAN
	.string "Ah, ich verstehe…\n"
	.string "Du sagst, ich soll mich nicht nur auf\l"
	.string "Items verlasen.\p"
	.string "Ich werde mein Bestes geben!\n"
	.string "Vielen, vielen Dank!$"
#else
	.string "I understand…\n"
	.string "You're saying I shouldn't rely on items.\l"
	.string "I'll do my best not to!\p"
	.string "Thank you very much!$"
#endif

gText_ApprenticeThanksHeldItem3::
#if GERMAN
	.string "{STR_VAR_1}? Okay!\n"
	.string "Ich bin nicht sicher, ob ich dieses Item\l"
	.string "besorgen kann… Aber ich versuche es.\p"
	.string "Vielen, vielen Dank!$"
#else
	.string "The item {STR_VAR_1}, okay.\n"
	.string "I'm not sure if I can get one…\l"
	.string "No! I'll do my best to get it.\p"
	.string "Thank you very much!$"
#endif

gText_ApprenticeItemAlreadyRecommended3::
#if GERMAN
	.string "Oh, aber…\n"
	.string "Ich glaube, das habe ich schon mal\l"
	.string "gehört…\p"
	.string "Vielleicht, weil ich mit {STR_VAR_1}\n"
	.string "nicht geschickt genug umgegangen bin?\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} gar kein Item benötigt?$"
#else
	.string "Oh, but…\n"
	.string "I think I've heard about that before…\p"
	.string "Is it maybe because I haven't handled\n"
	.string "the item {STR_VAR_1} very well?\p"
	.string "Or do you mean I shouldn't make\n"
	.string "my {STR_VAR_2} hold anything?$"
#endif

gText_ApprenticeWhatHeldItem4::
#if GERMAN
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Ich muss dich unbedingt etwas fragen!\p"
	.string "Du hast mir geraten, welches Pokémon\n"
	.string "ich einsetzen soll.\p"
	.string "Aber ich habe dich nicht gefragt,\n"
	.string "welches Item es tragen soll.\p"
	.string "Du hast mir schon einmal einen tollen\n"
	.string "Rat gegeben. Kannst du mir wieder\l"
	.string "helfen?\p"
	.string "Welches Item wäre gut? Ich möchte\n"
	.string "meinem {STR_VAR_1} etwas geben.$"
#else
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I wanted to ask you.\p"
	.string "You know how you decided which\n"
	.string "POKéMON I should have for me?\p"
	.string "But I never asked you what item\n"
	.string "it should be holding.\p"
	.string "Since you already gave me advice,\n"
	.string "how about seeing this to the end?\p"
	.string "What would be good? I want to make\n"
	.string "my {STR_VAR_1} hold something.$"
#endif

gText_ApprenticeHoldNothing4::
#if GERMAN
	.string "Oh, mein {STR_VAR_1} soll also mit\n"
	.string "leeren Händen dastehen?$"
#else
	.string "Oh! So my {STR_VAR_1} should do\n"
	.string "the best it can empty-handed?$"
#endif

gText_ApprenticeThanksNoHeldItem4::
#if GERMAN
	.string "Wenn du das für das Beste hältst, werde\n"
	.string "ich mich an deinen Rat halten.\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "If you think that's best, I'll do that.\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticeThanksHeldItem4::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Klingt gut. Ich werde es probieren.\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "The item {STR_VAR_1}, huh?\n"
	.string "Not bad. I'll use it!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticeItemAlreadyRecommended4::
#if GERMAN
	.string "Bitte? Was sagst du denn da? Du hast\n"
	.string "mir doch schon einmal zu dem Item\l"
	.string "{STR_VAR_1} geraten.\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item benötigt?$"
#else
	.string "Huh? What are you saying?\n"
	.string "You told me about the {STR_VAR_1}\l"
	.string "already before.\p"
	.string "Or do you mean my {STR_VAR_2} should\n"
	.string "do the best it can empty-handed?$"
#endif

gText_ApprenticeWhatHeldItem5::
#if GERMAN
	.string "Hi, {PLAYER}{KUN}!\p"
	.string "Wir sind ja beide schwer beschäftigt\n"
	.string "und laufen uns doch ständig über den\l"
	.string "Weg.\p"
	.string "Heute betätige ich mich beim Hausputz\n"
	.string "sportlich.\p"
	.string "Ich hatte bisher keine Zeit, meinem\n"
	.string "{STR_VAR_1} etwas zu kaufen.\p"
	.string "Da ich kaum Zeit zum Suchen habe, frage\n"
	.string "ich dich, welches Item zum Tragen\l"
	.string "wohl für mein {STR_VAR_1} geeignet ist.$"
#else
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "We're both busy, but we seem to run\n"
	.string "into each other often anyway!\p"
	.string "Today I have to do some walking,\n"
	.string "cleaning, and brushing.\p"
	.string "I haven't even had the time to buy\n"
	.string "my precious {STR_VAR_1} anything.\p"
	.string "I don't have any time, so how about\n"
	.string "giving me advice on what I should make\l"
	.string "my {STR_VAR_1} hold?$"
#endif

gText_ApprenticeHoldNothing5::
#if GERMAN
	.string "Oh, du meinst, mein {STR_VAR_1} benötigt\n"
	.string "kein Item?$"
#else
	.string "Oh, so me being a busy guy, you say\n"
	.string "my {STR_VAR_1} doesn't need anything?$"
#endif

gText_ApprenticeThanksNoHeldItem5::
#if GERMAN
	.string "Sehr schön. Dann brauche ich\n"
	.string "mich damit auch nicht weiter\l"
	.string "aufzuhalten.\p"
	.string "Vielen Dank! Man sieht sich!$"
#else
	.string "Okay, gotcha.\n"
	.string "I won't need any time for that.\p"
	.string "Thanks today!\n"
	.string "See you around!$"
#endif

gText_ApprenticeThanksHeldItem5::
#if GERMAN
	.string "Okay, dann werde ich mir die Zeit nehmen\n"
	.string "und das Item {STR_VAR_1} besorgen.\p"
	.string "Ich bin froh, dass ich dich als Mentor\n"
	.string "gefunden habe! Danke! Man sieht sich!$"
#else
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and find\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"
#endif

gText_ApprenticeItemAlreadyRecommended5::
#if GERMAN
	.string "Bitte? Aber das mit dem {STR_VAR_1}\n"
	.string "weiß ich doch schon längst.\p"
	.string "Ach, jetzt verstehe ich! Du meinst\n"
	.string "damit, dass mein {STR_VAR_2} gar kein\l"
	.string "Item benötigt?$"
#else
	.string "Huh? I already know about\n"
	.string "that {STR_VAR_1}.\p"
	.string "Oh, right, I get it.\n"
	.string "So me being a busy guy, you say\l"
	.string "my {STR_VAR_2} doesn't need anything?$"
#endif

gText_ApprenticeWhatHeldItem6::
#if GERMAN
	.string "Hiya {PLAYER}! Ich bin’s! Ich brauche\n"
	.string "wieder dein Gehirnschmalz…\l"
	.string "Äh, deinen Rat!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Ich habe folgende Frage…\p"
	.string "Welches Item soll ich meinem\n"
	.string "{STR_VAR_1} zum Tragen geben?$"
#else
	.string "Hiya, {PLAYER}! It's me!\n"
	.string "I need to tap your mind again today.\l"
	.string "Please, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I want to make my {STR_VAR_1} hold\n"
	.string "an item, what should it be?$"
#endif

gText_ApprenticeHoldNothing6::
#if GERMAN
	.string "Echt? Mein {STR_VAR_1} benötigt gar\n"
	.string "kein Item zum Tragen?$"
#else
	.string "Is that right? My {STR_VAR_1} doesn't\n"
	.string "need to hold an item, you're saying.$"
#endif

gText_ApprenticeThanksNoHeldItem6::
#if GERMAN
	.string "Oh, genau das werde ich machen!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"
#else
	.string "Okay, that's what I'll do!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticeThanksHeldItem6::
#if GERMAN
	.string "Oh hoooh! {STR_VAR_1}…\n"
	.string "Das ist echt cool!\l"
	.string "Das werde ich sofort ausprobieren!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"
#else
	.string "Uh-huh! One {STR_VAR_1}.\n"
	.string "What a cool choice!\l"
	.string "I'll definitely try that!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticeItemAlreadyRecommended6::
#if GERMAN
	.string "Ahahahaha! Das ist ja witzig!\n"
	.string "Du hast mir bereits schon einmal zu\l"
	.string "{STR_VAR_1} geraten!\p"
	.string "Geht es dir auch wirklich gut, {PLAYER}?\p"
	.string "Ach, jetzt verstehe ich!!! Mein\n"
	.string "{STR_VAR_2} benötigt kein Item.\l"
	.string "Meinst du das damit?!?$"
#else
	.string "Ahahah! That's silly!\n"
	.string "You already told me about that\l"
	.string "{STR_VAR_1} before!\p"
	.string "Are you feeling okay, {PLAYER}?\p"
	.string "Oh, wait! My {STR_VAR_2} doesn't\n"
	.string "need to hold an item, you're saying.$"
#endif

gText_ApprenticeWhatHeldItem7::
#if GERMAN
	.string "Hallo, {PLAYER}. Ich hoffe, dir geht es\n"
	.string "gut!\p"
	.string "Darf ich dich um einen Rat bitten?\p"
	.string "In den letzten Kämpfen hatten meine\n"
	.string "Gegner ihren Pokémon immer Items\l"
	.string "gegeben, die diese dann hielten.\p"
	.string "Und deshalb wurde ich immer besiegt…\p"
	.string "Ich möchte auch mal siegen!\n"
	.string "Ich möchte meinem {STR_VAR_1} auch\l"
	.string "ein Item zum Tragen geben.\p"
	.string "Du würdest mir echt eine Freude machen,\n"
	.string "wenn du mir da einen Rat geben\l"
	.string "könntest. Welches Item ist richtig?$"
#else
	.string "Hello, {PLAYER}. I hope you've been\n"
	.string "keeping well.\p"
	.string "May I approach you for advice?\p"
	.string "In a recent battle, my opponent\n"
	.string "seemed to have given his POKéMON\l"
	.string "an item to hold.\p"
	.string "As a result, I was defeated…\p"
	.string "I don't wish to be left behind.\n"
	.string "I would like to make my {STR_VAR_1}\l"
	.string "hold an item, too.\p"
	.string "It would please me if you could decide\n"
	.string "what would be right for my POKéMON…$"
#endif

gText_ApprenticeHoldNothing7::
#if GERMAN
	.string "Mit anderen Worten… Mein Pokémon\n"
	.string "benötigt gar kein Item?$"
#else
	.string "In other words… My POKéMON has\n"
	.string "no need to hold an item?$"
#endif

gText_ApprenticeThanksNoHeldItem7::
#if GERMAN
	.string "Jetzt wird es mir klar wie Kloßbrühe!\n"
	.string "Das werde ich ausprobieren!\p"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "I understand clearly now!\n"
	.string "I will keep trying like this.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticeThanksHeldItem7::
#if GERMAN
	.string "Dann soll es also {STR_VAR_1} sein!\n"
	.string "Ich werde das Item gleich bestellen!\p"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "One {STR_VAR_1} it is!\n"
	.string "I will order it right away.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticeItemAlreadyRecommended7::
#if GERMAN
	.string "Du hast mir doch schon dazu geraten\n"
	.string "und ich habe das Item auch sofort\l"
	.string "besorgt.\p"
	.string "Oder meinst du damit… Mein Pokémon\n"
	.string "benötigt gar kein Item?$"
#else
	.string "You've already told me about that,\n"
	.string "and I already have it.\p"
	.string "Or are you saying… My POKéMON has\n"
	.string "no need to hold an item?$"
#endif

gText_ApprenticeWhatHeldItem8::
#if GERMAN
	.string "Iiihiii! {PLAYER}!!!\n"
	.string "Ich… Ich freu mich soooo sehr, dich\l"
	.string "wiederzusehen!\p"
	.string "Oh! Und ich muss dich unbedingt etwas\n"
	.string "Wichtiges fragen, {PLAYER}!\p"
	.string "Was soll ich meinem {STR_VAR_1} zum\n"
	.string "Tragen geben?$"
#else
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you, {PLAYER}!\p"
	.string "Please decide what my {STR_VAR_1}\n"
	.string "should be holding!$"
#endif

gText_ApprenticeHoldNothing8::
#if GERMAN
	.string "Oh! Diese Antwort hatte ich nicht\n"
	.string "erwartet! Ein Item ist also nicht nötig?$"
#else
	.string "Oh, wow! I didn't expect that answer!\n"
	.string "So, a hold item isn't necessary?$"
#endif

gText_ApprenticeThanksNoHeldItem8::
#if GERMAN
	.string "Alles klar! Dann werde ich ihm kein Item\n"
	.string "geben!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"
#else
	.string "Perfectly understood!\n"
	.string "I'll keep at this without an item!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
#endif

gText_ApprenticeThanksHeldItem8::
#if GERMAN
	.string "{STR_VAR_1}! Genau das nehme ich!\p"
	.string "Äh… {PLAYER}, kann es sein, dass deine\n"
	.string "Pokémon auch Items tragen?\p"
	.string "Ich werde mir das Item sofort besorgen.\n"
	.string "Ich hoffe, ich darf dich auch in\l"
	.string "Zukunft um Rat fragen.$"
#else
	.string "{STR_VAR_1}! I'll use that!\p"
	.string "Um… Could it be, {PLAYER}, you also\n"
	.string "make your POKéMON hold that item?\p"
	.string "I'll be sure to get it!\n"
	.string "I hope you'll be willing to teach me\l"
	.string "some more another time.$"
#endif

gText_ApprenticeItemAlreadyRecommended8::
#if GERMAN
	.string "Ach? Aber zu {STR_VAR_1} hast du mir\n"
	.string "schon einmal geraten.\p"
	.string "Ist das das beste Item zum Tragen?\n"
	.string "Oder meinst du damit, dass mein\l"
	.string "{STR_VAR_2} gar kein Item benötigt?$"
#else
	.string "Oh? You recommended that\n"
	.string "{STR_VAR_1} before, too.\p"
	.string "Or is it the best thing to hold?\n"
	.string "Or do you mean that my {STR_VAR_2}\l"
	.string "doesn't need anything to hold?$"
#endif

gText_ApprenticeWhatHeldItem9::
#if GERMAN
	.string "Holla… Äh… Hallo!\n"
	.string "Meister {PLAYER}{KUN}!\p"
	.string "Ich muss dich in einer dringenden\n"
	.string "Pokémon-Angelegenheit um Rat fragen.\p"
	.string "Was meinst du? Welches Item soll ich\n"
	.string "meinem {STR_VAR_1} zum Tragen geben?\p"
	.string "Sei ruhig ehrlich!\n"
	.string "Spuck’s einfach aus!$"
#else
	.string "Hola!\n"
	.string "My maestro, {PLAYER}{KUN}!\p"
	.string "I want to hit you up for advice on\n"
	.string "POKéMON tools.\p"
	.string "What do you think would be good for\n"
	.string "my {STR_VAR_1} to hold?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"
#endif

gText_ApprenticeHoldNothing9::
#if GERMAN
	.string "Echt? Du meinst, mein {STR_VAR_1} kann,\n"
	.string "auch ohne ein Item zu tragen, gewinnen?$"
#else
	.string "Oh? So, you're saying my {STR_VAR_1}\n"
	.string "can win without holding any item?$"
#endif

gText_ApprenticeThanksNoHeldItem9::
#if GERMAN
	.string "Genua… Äh… Genau!\n"
	.string "Ich werde mein Bestes geben! Ohne Item.\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Mach’s tug… Äh… gut!$"
#else
	.string "Si, bueno!\n"
	.string "I'll give it my best shot, like, slam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
#endif

gText_ApprenticeThanksHeldItem9::
#if GERMAN
	.string "Ho… Äh… Oh! {STR_VAR_1}?\n"
	.string "Ich werde mir sofort dieses Item\l"
	.string "besorgen!\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Mach’s tug… Äh… gut!$"
#else
	.string "Uh-huh, that's one {STR_VAR_1}?\n"
	.string "Si, bueno!\l"
	.string "I'll go find me one, like, bam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
#endif

gText_ApprenticeItemAlreadyRecommended9::
#if GERMAN
	.string "Nein, nein, nein! Zu {STR_VAR_1} hast\n"
	.string "du mir doch schon geraten!\p"
	.string "Ach, jetzt warte mal eine Sekunde…\n"
	.string "Du meinst, mein {STR_VAR_2} kann, auch\l"
	.string "ohne ein Item zu tragen, gewinnen?$"
#else
	.string "No, no! You already told me about\n"
	.string "that {STR_VAR_1} thing before.\p"
	.string "Oh, now wait just one minute here…\n"
	.string "So, you're saying my {STR_VAR_2}\l"
	.string "can win without holding any item?$"
#endif

gText_ApprenticeWhatHeldItem10::
#if GERMAN
	.string "{PLAYER}{KUN}, das wirst du nicht glauben!\n"
	.string "Etwas Unglaubliches ist passiert!!!\p"
	.string "Als ich morgens aufwachte, hatte mein\n"
	.string "Pokémon 10 Nuggets!\p"
	.string "Natüüürlich ist das eine Lüge!!!\n"
	.string "Muahahahahaha!\p"
	.string "Ich denke darüber nach, welche Items\n"
	.string "meine Pokémon tragen sollen.\l"
	.string "Und das ist keine Lüge!\p"
	.string "Nun, dann entscheide du doch mal für\n"
	.string "mich, welches Item mein {STR_VAR_1}\l"
	.string "tragen soll.$"
#else
	.string "{PLAYER}{KUN}, something unbelievable\n"
	.string "has happened!\p"
	.string "I woke up this morning, and my POKéMON\n"
	.string "had 10 NUGGETS!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "what items POKéMON should hold.\p"
	.string "So, how about deciding for me what\n"
	.string "my {STR_VAR_1} should hold, master?$"
#endif

gText_ApprenticeHoldNothing10::
#if GERMAN
	.string "Was soll das denn heißen?\n"
	.string "Ich soll ihm gar nichts geben?$"
#else
	.string "What's that mean?\n"
	.string "Don't make it hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem10::
#if GERMAN
	.string "Okay, es soll also nichts tragen. Na,\n"
	.string "dann besorge ich das doch gleich mal!\p"
	.string "Ha ha! Das war ein Witz!\n"
	.string "Ich werde deinem weisen Rat folgen,\l"
	.string "oh großer Leerer.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so it shouldn't hold anything.\n"
	.string "Then, I'd better get something for it!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticeThanksHeldItem10::
#if GERMAN
	.string "Okay, es soll also {STR_VAR_1} tragen.\n"
	.string "Na, dann werde ich das besser mal\l"
	.string "nicht kaufen!\p"
	.string "Ha ha! Das war ein Witz!\n"
	.string "Ich werde deinem weisen Rat folgen,\l"
	.string "oh großer Lehrer.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so it's one {STR_VAR_1}!\n"
	.string "I'll make it hold anything but that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticeItemAlreadyRecommended10::
#if GERMAN
	.string "Äh… Dazu hast du mir schon einmal\n"
	.string "geraten, oder nicht?\p"
	.string "Gibt es denn kein anderes Item?\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item tragen soll?$"
#else
	.string "Um, you told me about that before,\n"
	.string "didn't you?\p"
	.string "Isn't there something else?\p"
	.string "Or do you mean, don't make\n"
	.string "my {STR_VAR_2} hold anything?$"
#endif

gText_ApprenticeWhatHeldItem11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein Matrose!\n"
	.string "Ich habe eine Frage, die\l"
	.string "wird dir zur Plage!\p"
	.string "Ein Problem mit einem Item,\n"
	.string "die Lösung kenn ich nicht bei weitem.\p"
	.string "Mein {STR_VAR_1} braucht etwas zu\n"
	.string "tragen, daher muss ich dich jetzt\l"
	.string "fragen.$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's an item question\n"
	.string "that begs your suggestion!\p"
	.string "My {STR_VAR_1} needs an item to hold,\n"
	.string "What should it be, if I may be bold?$"
#endif

gText_ApprenticeHoldNothing11::
#if GERMAN
	.string "Ist das denn auch richtig? Für mein\n"
	.string "{STR_VAR_1} sind Items nicht wichtig?$"
#else
	.string "Is that right?\n"
	.string "My {STR_VAR_1} doesn't need to be\l"
	.string "holding anything tight?$"
#endif

gText_ApprenticeThanksNoHeldItem11::
#if GERMAN
	.string "Verstanden, verstanden! Mein Pokémon\n"
	.string "wird auch so einen Sieg landen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "Okay, I hear you, sure I do!\n"
	.string "My POKéMON will go empty-handed, too!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticeThanksHeldItem11::
#if GERMAN
	.string "Okay! {STR_VAR_1}!\n"
	.string "Das setze ich ein, das ist fein!\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "Okay, one {STR_VAR_1},\n"
	.string "that's what I'll use.\l"
	.string "I was right to make you choose!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticeItemAlreadyRecommended11::
#if GERMAN
	.string "Okay! {STR_VAR_1}!\n"
	.string "Das hast du schon mal gesagt,\l"
	.string "keine neue Idee an dir nagt?\p"
	.string "Ist das denn auch richtig? Für mein\n"
	.string "Pokémon sind Items nicht wichtig?$"
#else
	.string "Okay, one {STR_VAR_1}, you say?\n"
	.string "You told me that the other day.\l"
	.string "I need a new idea, a brand new way.\p"
	.string "Or, what, is that right?\n"
	.string "My POKéMON doesn't need to hold\l"
	.string "anything tight?$"
#endif

gText_ApprenticeWhatHeldItem12::
#if GERMAN
	.string "Hey, du da! {PLAYER}!\n"
	.string "So sieht man sich also wieder!\p"
	.string "Und was soll ich jetzt machen? Na, da\n"
	.string "ich bereits mit dir rede, kann ich dich\l"
	.string "auch um einen Rat bitten.\p"
	.string "{PLAYER}, du bist doch nicht angenervt\n"
	.string "von mir? Neeee, das kann nicht sein…\p"
	.string "Also, darf ich dich was fragen?\n"
	.string "Ich brauche wirklich deinen Rat.\p"
	.string "Welches Item soll mein {STR_VAR_1}\n"
	.string "tragen?$"
#else
	.string "Say, hey, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you getting sick of me?\n"
	.string "Nah, no way, that can't be.\p"
	.string "Will you hear me out?\n"
	.string "I'm looking for advice--that's what\l"
	.string "I'm talking about.\p"
	.string "It's about a hold item for\n"
	.string "my {STR_VAR_1} that'd be good.\l"
	.string "My indecision is making me brood.$"
#endif

gText_ApprenticeHoldNothing12::
#if GERMAN
	.string "Mein {STR_VAR_1} braucht kein Item?\n"
	.string "Gar keins?$"
#else
	.string "My {STR_VAR_1} needs nothing?\n"
	.string "Doesn't need to hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem12::
#if GERMAN
	.string "Wenn du meinst, dass es kein Item\n"
	.string "benötigt, werde ich mich daran halten.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "If holding nothing is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticeThanksHeldItem12::
#if GERMAN
	.string "{STR_VAR_1} ist also dein Rat? Gut,\n"
	.string "dann werde ich mich daran halten.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "If holding that {STR_VAR_1} is\n"
	.string "the best, I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticeItemAlreadyRecommended12::
#if GERMAN
	.string "Hast du mir nicht vor kurzem auch zu\n"
	.string "{STR_VAR_1} geraten?\l"
	.string "Ich bin mir ziemlich sicher…\p"
	.string "Ich brauche aber etwas Neues!\n"
	.string "Oder braucht mein {STR_VAR_2} kein\l"
	.string "Item?$"
#else
	.string "Haven't I heard about that\n"
	.string "{STR_VAR_1} before?\l"
	.string "I'm certain I have, that's for sure!\p"
	.string "I need a new something!\n"
	.string "Or, my {STR_VAR_2} needs nothing?\l"
	.string "Doesn't need to hold anything?$"
#endif

gText_ApprenticeWhatHeldItem13::
#if GERMAN
	.string "Auaaaa au au au! {PLAYER}{KUN}, mein Arm\n"
	.string "ist gebrochen! Nicht anfassen, bitte!\p"
	.string "Ich muss ihn mir gebrochen haben, als\n"
	.string "ich verschiedene Items ausprobierte,\l"
	.string "um sie meinen Pokémon zum Tragen \p"
	.string "zu geben. Das ist ein Notfall! Kannst\n"
	.string "du bitte für mich eine Entscheidung\l"
	.string "fällen?\p"
	.string "Welches Item könnte mein {STR_VAR_1}\n"
	.string "tragen, {PLAYER}{KUN}?$"
#else
	.string "Gwah! Ouch! {PLAYER}{KUN}, my arm's broken!\n"
	.string "Don't touch it, please!\p"
	.string "I must've broken it while I was trying\n"
	.string "out different hold items with my posse\l"
	.string "of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, what do you think would be\n"
	.string "good for my {STR_VAR_1} to hold?$"
#endif

gText_ApprenticeHoldNothing13::
#if GERMAN
	.string "Auaaaa…\p"
	.string "Du bist überzeugt, mein {STR_VAR_1}\n"
	.string "benötigt kein Item?$"
#else
	.string "Ouch…\p"
	.string "So your suggestion is my {STR_VAR_1}\n"
	.string "doesn't have to hold anything?$"
#endif

gText_ApprenticeThanksNoHeldItem13::
#if GERMAN
	.string "Oh, das erleichtert mir einiges. Das ist\n"
	.string "in der momentanen Situation echt gut.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"
#else
	.string "Hm, all right. That would be easier\n"
	.string "for me, the way things are now.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
#endif

gText_ApprenticeThanksHeldItem13::
#if GERMAN
	.string "Gut. {STR_VAR_1}. Der Arm meines\n"
	.string "Pokémon ist gesund, da kann ich das\l"
	.string "Item gleich meinem Pokémon geben.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"
#else
	.string "Hm, all right. That's one {STR_VAR_1}.\n"
	.string "My POKéMON's arm is fine, so I'll make\l"
	.string "it hold that item right away.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
#endif

gText_ApprenticeItemAlreadyRecommended13::
#if GERMAN
	.string "Oh, aber du hast mir doch früher schon\n"
	.string "mal etwas über {STR_VAR_1} gesagt,\l"
	.string "erinnerst du dich?\p"
	.string "Hast du keinen besseren Vorschlag für\n"
	.string "mich?\p"
	.string "Jetzt warte mal. Das soll doch nicht\n"
	.string "heißen, dass mein {STR_VAR_2} gar kein\l"
	.string "Item tragen soll, oder?$"
#else
	.string "No, no, you told me about that\n"
	.string "{STR_VAR_1} before, remember?\p"
	.string "How about telling me something\n"
	.string "even better?\p"
	.string "Oh, wait a second.\n"
	.string "So your suggestion is my {STR_VAR_2}\l"
	.string "doesn't have to hold anything?$"
#endif

gText_ApprenticeWhatHeldItem14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Schau mich bitte nicht so an!\n"
	.string "Meine Pokémon haben keine Items.\p"
	.string "Das ist mir ja auch echt peinlich…\n"
	.string "Aber ich brauche dabei deinen Rat.\p"
	.string "Ich weiß nicht, welches Item ich meinem\n"
	.string "{STR_VAR_1} zum Tragen geben soll,\l"
	.string "damit es stark wird.\p"
	.string "Du weißt das doch bestimmt, oder,\n"
	.string "{PLAYER}{KUN}?$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "My POKéMON don't have anything.\p"
	.string "I… I'm really embarrassed about this,\n"
	.string "but I really need your advice.\p"
	.string "I can't decide what hold item would\n"
	.string "make my {STR_VAR_1} strong.\p"
	.string "{PLAYER}{KUN}, what do you think would\n"
	.string "be good?$"
#endif

gText_ApprenticeHoldNothing14::
#if GERMAN
	.string "Oh… Du meinst, mein {STR_VAR_1}\n"
	.string "braucht kein Item zu tragen?$"
#else
	.string "Oh… Then, you think it would be better\n"
	.string "if my {STR_VAR_1} didn't have an item?$"
#endif

gText_ApprenticeThanksNoHeldItem14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Dann gebe ich ihm keines!\p"
	.string "Das ist dann aber echt Nerven\n"
	.string "zerreißend! Aber auch total cool!\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll go without an item.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticeThanksHeldItem14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Ich gebe ihm {STR_VAR_1}.\p"
	.string "Das ist dann aber echt Nerven\n"
	.string "zerreißend! Aber auch total cool!\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticeItemAlreadyRecommended14::
#if GERMAN
	.string "A-aber das hast du mir doch schon mal\n"
	.string "gesagt.\p"
	.string "Bitte, speis mich nicht einfach so ab!\n"
	.string "Ich kann mit dieser Peinlichkeit nicht\l"
	.string "leben!\p"
	.string "Oh… Jetzt verstehe ich dich!\n"
	.string "Du meinst damit, dass mein {STR_VAR_2}\l"
	.string "gar kein Item benötigt?$"
#else
	.string "B-but I already heard about that.\p"
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Oh… Am I jumping to conclusions?\n"
	.string "Do you think it would be better if\l"
	.string "my {STR_VAR_2} didn't have an item?$"
#endif

gText_ApprenticeWhatHeldItem15::
#if GERMAN
	.string "Hm… Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du es wirklich?\l"
	.string "Oder bist du ein Zwilling?\p"
	.string "Nein, nein, nein! Keine Angst!\n"
	.string "Wenn du wirklich {PLAYER} bist, dann\l"
	.string "verzeih bitte meine Ungehobeltheit!\p"
	.string "Ich würde dich gerne um einen Rat\n"
	.string "bitten.\p"
	.string "Ich habe hier mein {STR_VAR_1} und\n"
	.string "würde ihm gerne ein Item zum Tragen\l"
	.string "geben.\p"
	.string "Aber welches soll ich ihm bloß geben?$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a twin?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is some more of\n"
	.string "your fine advice.\p"
	.string "I have here my {STR_VAR_1} that I wish\n"
	.string "to make hold a convenient item.\p"
	.string "What would be worthy of it?$"
#endif

gText_ApprenticeHoldNothing15::
#if GERMAN
	.string "Es ist besser, wenn es kein Item trägt?\n"
	.string "Bist du dir da sicher?$"
#else
	.string "It's better if it held nothing?\n"
	.string "Are you certain?$"
#endif

gText_ApprenticeThanksNoHeldItem15::
#if GERMAN
	.string "Na, dann werde ich einfach deinem Rat\n"
	.string "folgen.\p"
	.string "Danke! Bis bald mal!$"
#else
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticeThanksHeldItem15::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Bist du sicher?\p"
	.string "Na, dann werde ich deinem Rat folgen.\n"
	.string "Ich danke dir für deine Zeit.\p"
	.string "Ich hoffe, mein Pokémon wird es gut\n"
	.string "zu nutzen wissen.\p"
	.string "Bis bald mal!$"
#else
	.string "One {STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope my POKéMON will be able to\n"
	.string "put it to good use.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticeItemAlreadyRecommended15::
#if GERMAN
	.string "Nein, jetzt warte mal! Das hast du\n"
	.string "mir letztes Mal doch schon geraten!\p"
	.string "Ich möchte dich bitten, mir zu etwas\n"
	.string "anderem zu raten.\p"
	.string "Oder meinst du damit, dass mein\n"
	.string "{STR_VAR_2} kein Item benötigt?\l"
	.string "Bist du sicher?$"
#else
	.string "No, no, wait a minute.\n"
	.string "I believe you taught me that before.\p"
	.string "I would like you to recommend\n"
	.string "something different this time.\p"
	.string "Perhaps you're suggesting that\n"
	.string "my {STR_VAR_2} should hold nothing?\l"
	.string "Are you certain?$"
#endif

gText_ApprenticeWhichMonFirst0::
#if GERMAN
	.string "Waaahaaa, {PLAYER}!\n"
	.string "Ich habe ein Problem… Heul, Jammer…\p"
	.string "Ich würde so gerne an Kämpfen\n"
	.string "teilnehmen, aber ich weiß nicht, was\l"
	.string "ich tun soll.\p"
	.string "In welcher Reihenfolge sollen meine\n"
	.string "Pokémon stehen, damit sie richtig\l"
	.string "stark sind?\p"
	.string "Bitte, hilf mir, {PLAYER}!\n"
	.string "Welches dieser Pokémon würdest du\l"
	.string "an die erste Stelle setzen?$"
#else
	.string "Waah, {PLAYER}!\n"
	.string "I have a dilemma, sob…\p"
	.string "I want to begin battling other people,\n"
	.string "but I don't know what to do.\p"
	.string "How should I line up my POKéMON\n"
	.string "so they'll be at their strongest?\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "If you were me, which of these POKéMON\l"
	.string "would you send out first?$"
#endif

gText_ApprenticeMonFirstThanks0::
#if GERMAN
	.string "Mein {STR_VAR_1} soll als erstes in den\n"
	.string "Kampf? Waaaahaaa… Schnüff…\p"
	.string "Oh, tut mir Leid!\n"
	.string "Du machst mich glücklich, weil du das\l"
	.string "erste Pokémon bestimmt hast. Heul…\p"
	.string "Vielen Dank! Schnüff… Heul…$"
#else
	.string "My {STR_VAR_1} should go first?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "my first POKéMON, and it's made me cry…\p"
	.string "Thank you so much!$"
#endif

gText_ApprenticeWhichMonFirst1::
#if GERMAN
	.string "Hey! Du bist es, {PLAYER}! Sehr gut!\n"
	.string "Ich wollte dich nämlich was fragen!\p"
	.string "Welches meiner Pokémon soll als\n"
	.string "Erstes in den Kampf gehen?$"
#else
	.string "Yay! It's {PLAYER}!\n"
	.string "Great! I wanted to ask you something!\p"
	.string "Um, of my POKéMON, which do you\n"
	.string "think should go out first?$"
#endif

gText_ApprenticeMonFirstThanks1::
#if GERMAN
	.string "Mein {STR_VAR_1}?!? Wirklich?\n"
	.string "Okay, dann machen wir das so!\p"
	.string "Vielen Dank für deine Hilfe!$"
#else
	.string "My {STR_VAR_1}? That's true.\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"
#endif

gText_ApprenticeWhichMonFirst2::
#if GERMAN
	.string "Hallo {PLAYER}!\p"
	.string "Ich finde, es ist wichtig, welches\n"
	.string "Pokémon im Kampf als Erstes antritt.\p"
	.string "Welches von meinen Pokémon soll\n"
	.string "ich als Erstes einsetzen?$"
#else
	.string "{PLAYER}, hello!\p"
	.string "I think, in a battle, it's very important\n"
	.string "which POKéMON comes out first.\p"
	.string "Out of the POKéMON that I have,\n"
	.string "which would be good to send out first?$"
#endif

gText_ApprenticeMonFirstThanks2::
#if GERMAN
	.string "Mein {STR_VAR_1} soll zuerst rausgehen?\n"
	.string "Okay, gut!\p"
	.string "Bis später dann!$"
#else
	.string "My {STR_VAR_1} goes first?\n"
	.string "Okay, I got it!\p"
	.string "See you again!$"
#endif

gText_ApprenticeWhichMonFirst3::
#if GERMAN
	.string "Hallo, {PLAYER}…\n"
	.string "Ich muss dich schon wieder belästigen.\l"
	.string "Ich habe noch eine wichtige Frage.\p"
	.string "Ich habe nicht gerade viel\n"
	.string "Selbstvertrauen und wüsste echt nicht,\l"
	.string "was ich ohne dich machen würde.\p"
	.string "Vielleicht vergeude ich ja auch meine\n"
	.string "Zeit mit unnützen Gedanken, aber ich\l"
	.string "kann mich nicht entscheiden…\p"
	.string "Welches meiner Pokémon soll ich als\n"
	.string "Erstes im Kampf einsetzen?$"
#else
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to disturb you again with\l"
	.string "another question.\p"
	.string "I have so little confidence, I don't\n"
	.string "know what I'd do without you, {PLAYER}.\p"
	.string "It may be a waste of time for me to\n"
	.string "even worry about it, but I just can't\l"
	.string "decide something…\p"
	.string "Which of my POKéMON should I send\n"
	.string "out first in a battle?$"
#endif

gText_ApprenticeMonFirstThanks3::
#if GERMAN
	.string "Mein {STR_VAR_1}?\n"
	.string "Ah, ich verstehe!\p"
	.string "Ich wundere mich echt, dass ich dir\n"
	.string "nicht mit meinen ganzen Fragen auf die\l"
	.string "Nerven gehe!\p"
	.string "Ich bin dir so dankbar, dass du\n"
	.string "überhaupt mit mir sprichst…\p"
	.string "Vielen, vielen Dank!$"
#else
	.string "My {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I can't believe that you would bother\n"
	.string "to answer my questions so often!\p"
	.string "I'm so grateful that you would even\n"
	.string "speak with me… Thank you!$"
#endif

gText_ApprenticeWhichMonFirst4::
#if GERMAN
	.string "Oh, {PLAYER}{KUN}! Ich bin’s!\n"
	.string "Ich bin froh, dich zu treffen, denn ich\l"
	.string "habe da ein Problem!\p"
	.string "Ich weiß nicht, wie ich meine Pokémon\n"
	.string "anordnen soll. Kannst du mir helfen?\p"
	.string "Du musst nicht alle neu anordnen. Sag\n"
	.string "mir nur, welches ich als Erstes im Kampf\p"
	.string "einsetzen soll. Ja, machst du das?$"
#else
	.string "Oh, {PLAYER}{KUN}! It's me!\n"
	.string "I'm so glad to see you because I have\l"
	.string "this little problem.\p"
	.string "I can't decide how my POKéMON should\n"
	.string "be lined up. Could you decide for me?\p"
	.string "Oh, you don't need to decide the whole\n"
	.string "party right now.\p"
	.string "How about deciding just the first\n"
	.string "POKéMON for me?$"
#endif

gText_ApprenticeMonFirstThanks4::
#if GERMAN
	.string "Mein {STR_VAR_1}? Großartig!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "My {STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticeWhichMonFirst5::
#if GERMAN
	.string "Hi, {PLAYER}{KUN}, mein Lehrer!\n"
	.string "Auch heute bin ich immens beschäftigt!\p"
	.string "Ich muss Rad fahren, einkaufen und\n"
	.string "diverse andere Dinge erledigen.\p"
	.string "Ich habe noch nicht einmal die Zeit zu\n"
	.string "entscheiden, in welcher Reihenfolge ich\p"
	.string "meine Pokémon für den Kampf aufstellen\n"
	.string "soll.\p"
	.string "Kannst du dir nicht bitte mein Team\n"
	.string "anschauen und mir sagen, welches ich\l"
	.string "als Erstes im Kampf einsetzen soll?$"
#else
	.string "Hi, my teacher {PLAYER}{KUN}!\n"
	.string "I'm busy again today!\p"
	.string "I have to do some cycling, shopping,\n"
	.string "and humming.\p"
	.string "I haven't even had the time to decide\n"
	.string "how to line up my POKéMON team.\p"
	.string "So, how about checking out my team?\n"
	.string "Which one should go first?$"
#endif

gText_ApprenticeMonFirstThanks5::
#if GERMAN
	.string "Okay, verstanden. Wenigstens habe\n"
	.string "ich so viel Zeit, mein {STR_VAR_1} an die\l"
	.string "erste Stelle zu setzen!\p"
	.string "Hups, meine Freundin wartet bereits\n"
	.string "auf mich. Vielen Dank! Und tschüss!$"
#else
	.string "Okay, gotcha.\n"
	.string "I have enough time at least to put\l"
	.string "my {STR_VAR_1} at the head of the line!\p"
	.string "Whoops, my girlfriend's waiting!\n"
	.string "Thanks! See you around!$"
#endif

gText_ApprenticeWhichMonFirst6::
#if GERMAN
	.string "Hiya {PLAYER}!\n"
	.string "Du siehst irgendwie immer stark aus.\p"
	.string "Du, ich brauche schon wieder dein\n"
	.string "Gehirnschmalz. Wie so üblich…\p"
	.string "Trommelwirbel, tadaa!\n"
	.string "Ich habe eine Frage zu meinem Team.\p"
	.string "Welches Pokémon soll ich als Erstes\n"
	.string "im Kampf einsetzen?$"
#else
	.string "Yoohoo! Hiya, {PLAYER}!\n"
	.string "You always walk around looking tough!\p"
	.string "Listen, I need something from you\n"
	.string "again! It's the usual thing!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is about my team.\p"
	.string "Which POKéMON of mine should be first\n"
	.string "to go out in a battle?$"
#endif

gText_ApprenticeMonFirstThanks6::
#if GERMAN
	.string "Hmmm…\n"
	.string "{STR_VAR_1}, meinst du?\l"
	.string "Das ist eine coole Entscheidung!\p"
	.string "Und damit hast du mein heutiges\n"
	.string "Problem gelöst.\p"
	.string "Wir müssen uns bald mal wieder treffen.\n"
	.string "Danke und bis bald!$"
#else
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticeWhichMonFirst7::
#if GERMAN
	.string "Vielen Dank, dass du dir die Zeit nimmst,\n"
	.string "mit mir zu reden, {PLAYER}!\p"
	.string "Ich weiß, ich nutze deine\n"
	.string "Freundlichkeit aus, aber darf ich dich\l"
	.string "um einen Rat bitten?\p"
	.string "Könntest du mir helfen, die Reihenfolge\n"
	.string "meiner Pokémon festzulegen?\p"
	.string "Welches Pokémon soll ich im Kampf als\n"
	.string "Erstes einsetzen?$"
#else
	.string "Thank you so much for stopping to\n"
	.string "chat with me, {PLAYER}.\p"
	.string "I know I'm taking advantage of your\n"
	.string "kindness, but may I ask for advice?\p"
	.string "I would like you to decide on the order\n"
	.string "of my POKéMON team.\p"
	.string "It would please me if you could decide\n"
	.string "which POKéMON should come first.$"
#endif

gText_ApprenticeMonFirstThanks7::
#if GERMAN
	.string "Mein {STR_VAR_1}! Dann setze ich das\n"
	.string "sofort an die erste Stelle!\l"
	.string "Vielen Dank, {PLAYER}!\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticeWhichMonFirst8::
#if GERMAN
	.string "Iiihiii! {PLAYER}!!!\n"
	.string "Ich… Ich freu mich soooo sehr, dich\l"
	.string "wiederzusehen!\p"
	.string "Meine Pokémon sind mittlerweile\n"
	.string "viel, viel stärker geworden!\p"
	.string "Aber ich gewinne trotzdem nicht immer!\n"
	.string "Es liegt wohl an dem Pokémon, das ich\l"
	.string "als Erstes im Kampf einsetze? \p"
	.string "Bitte, {PLAYER}, ich brauche deine Hilfe!\p"
	.string "Welches Pokémon soll ich als Erstes\n"
	.string "im Kampf einsetzen?$"
#else
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "My POKéMON have become much\n"
	.string "stronger!\p"
	.string "But I don't always win. It seems to\n"
	.string "depend on which POKéMON goes first.\p"
	.string "{PLAYER}, please, I need your help!\p"
	.string "Please decide which of my POKéMON\n"
	.string "should go out first!$"
#endif

gText_ApprenticeMonFirstThanks8::
#if GERMAN
	.string "Seufz… Mir ist vor Freude ganz\n"
	.string "schwindelig…\p"
	.string "Es ist wie in einem Traum. Du hast für\n"
	.string "mich entschieden, {PLAYER}.\p"
	.string "Und ich habe den Sinn verstanden.\n"
	.string "Ich werde mein {STR_VAR_1} an die erste\l"
	.string "Stelle setzen.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"
#else
	.string "Sigh… I'm overwhelmed with happiness…\p"
	.string "It's like a dream having you decide\n"
	.string "for me, {PLAYER}.\p"
	.string "But perfectly understood!\n"
	.string "I will go with my {STR_VAR_1} first!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
#endif

gText_ApprenticeWhichMonFirst9::
#if GERMAN
	.string "Holla… Äh… Hallo!\n"
	.string "Meister {PLAYER}{KUN}! Lass mich\l"
	.string "bitte an deiner Weisheit teilhaben!\p"
	.string "Schau, ich habe ein Team von drei\n"
	.string "Pokémon zusammengestellt.\p"
	.string "Aber ich weiß nicht, in welcher\n"
	.string "Reihenfolge ich sie kämpfen lassen soll.\p"
	.string "Und hier kommst du ins Spiel, {PLAYER}{KUN}!\n"
	.string "Du entscheidest das jetzt für mich!\p"
	.string "Und sei bloß nicht schüchtern.\n"
	.string "Spuck’s einfach aus!$"
#else
	.string "Hello, hello!\n"
	.string "My mentor, {PLAYER}{KUN}!\l"
	.string "Hit me with your sage advice today!\p"
	.string "You see, I pulled together a team of\n"
	.string "three POKéMON. So far so good.\p"
	.string "But the team's battling order's not\n"
	.string "settled yet.\p"
	.string "This is where you come in, {PLAYER}{KUN}!\n"
	.string "You decide which POKéMON leads off!\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"
#endif

gText_ApprenticeMonFirstThanks9::
#if GERMAN
	.string "Ah, mein {STR_VAR_1} hat die Nase vorn!\n"
	.string "Elassk… Äh… Klasse!\l"
	.string "Ich ändere die Reihenfolge sofort!\p"
	.string "Sehr schön! Und vielen Dank!\n"
	.string "Bis dalb… Äh… bald!$"
#else
	.string "Uh-huh, my {STR_VAR_1} leads off!\n"
	.string "OK, A-OK!\l"
	.string "I'll reorder the lineup, like, wham!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
#endif

gText_ApprenticeWhichMonFirst10::
#if GERMAN
	.string "Hör mal, {PLAYER}{KUN}!\n"
	.string "Ich habe hier einen Notfall!\p"
	.string "Alle meine drei Pokémon gehen\n"
	.string "grundsätzlich Zusammen in einen Kampf.\l"
	.string "Alle auf einmal!!!\p"
	.string "Nee, das stimmt natürlich nicht!\n"
	.string "Muahahahahaha!\p"
	.string "Aber ich weiß nicht, in welcher\n"
	.string "Reihenfolge ich meine Pokémon setzen\l"
	.string "soll. Und das ist keine Lüge!\p"
	.string "Wie wäre es, wenn du für mich\n"
	.string "entscheidest, welches Pokémon ich als\l"
	.string "Erstes einsetzen soll?$"
#else
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My POKéMON, all three of them, go into\n"
	.string "battle at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "how I should line up my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "POKéMON should go first, master?$"
#endif

gText_ApprenticeMonFirstThanks10::
#if GERMAN
	.string "Ah, mein {STR_VAR_1} soll also das\n"
	.string "Erste sein? Okay, dann setze ich ein\l"
	.string "anderes Pokémon an die erste Stelle.\p"
	.string "Hahahaha! Das war doch ein guter Witz!\n"
	.string "Äh, nicht?!? Okay, ich folge deinem Rat.\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so it's my {STR_VAR_1} you chose?\n"
	.string "I'll let any but that one go first!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticeWhichMonFirst11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein Matrose!\n"
	.string "Ich habe eine Frage, die\l"
	.string "wird dir zur Plage!\p"
	.string "Ein Problem mit meinen Pokémon.\n"
	.string "Gib mir die Antwort, nun mach schon.\p"
	.string "Welches von diesen soll als Erstes\n"
	.string "in den Kampf düsen?$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's a team lineup question\n"
	.string "that begs your suggestion!\p"
	.string "Out of this lot, which should go first\n"
	.string "as the first on the spot?$"
#endif

gText_ApprenticeMonFirstThanks11::
#if GERMAN
	.string "Ich habe verstanden! So soll es sein!\n"
	.string "Dieses wird das erste Pokémon sein.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "Okay, I hear you, sure I do!\n"
	.string "I'll switch them up, that I'll do!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticeWhichMonFirst12::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Wie geht’s denn so?\p"
	.string "Wie es mir geht? Ich überlege, ob\n"
	.string "ich dich um einen Rat anhauen soll.\l"
	.string "Ich habe da ein Problem!\l"
	.string "Dabei könntest du mir bestimmt helfen.\p"
	.string "Welches meiner Pokémon soll ich als\n"
	.string "Erstes im Kampf einsetzen?$"
#else
	.string "Yahoo, {PLAYER}!\n"
	.string "How do you do?\p"
	.string "What should I do? Go ahead and ask?\n"
	.string "Uh-huh, I have something to ask!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "You have to decide, which of my\n"
	.string "POKéMON is the first to ride!\l"
	.string "Into battle, I mean to say.$"
#endif

gText_ApprenticeMonFirstThanks12::
#if GERMAN
	.string "Mein {STR_VAR_1}? Ja!\n"
	.string "Damit bin ich auf der sicheren Seite.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "My {STR_VAR_1}? Yes!\n"
	.string "That'll do, there's no distress!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticeWhichMonFirst13::
#if GERMAN
	.string "Auaaaa au au au! {PLAYER}{KUN}…\n"
	.string "Ich habe Bauchschmerzen… Auaaaaaa…\p"
	.string "Aber ich glaube, jetzt gerade wird es\n"
	.string "besser…\p"
	.string "Das liegt bestimmt daran, dass ich mir\n"
	.string "Gedanken gemacht habe, wie ich meine\l"
	.string "Pokémon anordnen soll.\p"
	.string "Aber jetzt bist du ja da. Welches\n"
	.string "Pokémon soll ich als Erstes im Kampf\l"
	.string "einsetzen? So dass ich sicher gewinne?$"
#else
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach's hurting all of a sudden…\p"
	.string "…It's getting better now…\p"
	.string "I must've worried myself sick racking\n"
	.string "my brains on how I should line up\l"
	.string "my posse of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, which of my POKéMON should\n"
	.string "go first? So I'd win, I mean.$"
#endif

gText_ApprenticeMonFirstThanks13::
#if GERMAN
	.string "Hm, ja, gut.\n"
	.string "Mein {STR_VAR_1} wird das erste\l"
	.string "Pokémon sein.\p"
	.string "Ich schlag mir jetzt den Bauch voll\n"
	.string "und dann ordne ich die Pokémon\l"
	.string "neu an.\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"
#else
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup like that after\n"
	.string "I have my supper.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
#endif

gText_ApprenticeWhichMonFirst14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}?\l"
	.string "…\p"
	.string "Schau mich doch nicht immer so an.\n"
	.string "Du bringst mich ganz aus dem Konzept.\p"
	.string "Äh…\n"
	.string "Ich brauche deinen Rat…\p"
	.string "Es ist mir peinlich, aber ich weiß nicht,\n"
	.string "in welcher Reihenfolge ich meine drei\l"
	.string "Pokémon anordnen soll.\p"
	.string "Welches Pokémon soll ich als Erstes im\n"
	.string "Kampf einsetzen?$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-POKéMON team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"
#endif

gText_ApprenticeMonFirstThanks14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Mein {STR_VAR_1} soll es also sein.\p"
	.string "Ich hoffe, ich werde mich nicht\n"
	.string "wieder blamieren.\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticeWhichMonFirst15::
#if GERMAN
	.string "Hm? Du bist {PLAYER}{KUN}?!?\n"
	.string "Bist du es wirklich? Nicht, dass ich hier\l"
	.string "einen Doppelgänger vor mir habe…\p"
	.string "Nein, nein, nein! Keine Angst!\n"
	.string "Wenn du wirklich {PLAYER} bist, dann\l"
	.string "verzeih bitte meine Dreistigkeit!\p"
	.string "Ich brauche deinen weisen Rat!\p"
	.string "Schau dir meine Pokémon an. Welches\n"
	.string "soll ich als Erstes im Kampf einsetzen?$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my POKéMON team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"
#endif

gText_ApprenticeMonFirstThanks15::
#if GERMAN
	.string "Mein {STR_VAR_1}…\n"
	.string "Und du führst mich auch nicht an der\l"
	.string "Nase herum?\p"
	.string "Nein?!? Dann werde ich deinem Rat\n"
	.string "folgen. Vielen Dank, dass du mir etwas\l"
	.string "von deiner Zeit geschenkt hast.\p"
	.string "Ich bin, was ich bin und werde mein\n"
	.string "Bestes geben.\p"
	.string "Bis hoffentlich bald mal!$"
#else
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticeWhichMon0::
#if GERMAN
	.string "Heul… Jammer… Schnüff…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Du kommst gerade recht!\n"
	.string "Ich kann mich nicht entscheiden…\p"
	.string "Ich kann mich nicht zwischen meinem\n"
	.string "{STR_VAR_1} und meinem {STR_VAR_2}\l"
	.string "entscheiden… Heul…\p"
	.string "Was meinst du, {PLAYER}, mit welchem\n"
	.string "habe ich die besten Chancen zu\l"
	.string "gewinnen?$"
#else
	.string "Snivel…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "be using.\p"
	.string "I can't decide between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"
#endif

gText_ApprenticeMonThanks0::
#if GERMAN
	.string "Heul… Jammer… Schnüff…\n"
	.string "Hihi, tut mir Leid… Du hast mich so froh\l"
	.string "gemacht, dass ich weinen muss… Heul…\p"
	.string "Ich werde mich anstrengen, ein\n"
	.string "{STR_VAR_1} zu fangen!\p"
	.string "Vielen Dank! Waaahaa… Heul…$"
#else
	.string "Snivel… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"
#endif

gText_ApprenticeWhichMon1::
#if GERMAN
	.string "Hey, du bist es, {PLAYER}!\n"
	.string "Gut, dass du hier bist. Ich brauche mal\l"
	.string "wieder deinen Rat!\p"
	.string "Ich bin schon ganz konfus… Soll ich\n"
	.string "mein {STR_VAR_1} oder mein {STR_VAR_2}\l"
	.string "einsetzen…\p"
	.string "Welches soll ich aufziehen und stärker\n"
	.string "machen, {PLAYER}?$"
#else
	.string "Yay! It's {PLAYER}!\n"
	.string "Yay, you came at the right time, too!\l"
	.string "I need your advice again!\p"
	.string "Um, I'm all mixed up--should I use\n"
	.string "my {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which do you think I should raise,\n"
	.string "{PLAYER}?$"
#endif

gText_ApprenticeMonThanks1::
#if GERMAN
	.string "Mein {STR_VAR_1} ist also besser?\n"
	.string "Gut, dann weiß ich, was ich machen muss.\p"
	.string "Vielen Dank für deinen Rat!$"
#else
	.string "Oh, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"
#endif

gText_ApprenticeWhichMon2::
#if GERMAN
	.string "Hallo {PLAYER}!\n"
	.string "Ich habe ein Frage an dich.\p"
	.string "Ich weiß nicht, ob ich ein {STR_VAR_1}\n"
	.string "oder ein {STR_VAR_2} fangen soll.\p"
	.string "Welches der beiden wird wohl das\n"
	.string "Stärkere werden?$"
#else
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I'm in a dilemma over whether I should\n"
	.string "raise one {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which POKéMON do you think will\n"
	.string "be stronger?$"
#endif

gText_ApprenticeMonThanks2::
#if GERMAN
	.string "{STR_VAR_1} meinst du?\n"
	.string "Ja.\p"
	.string "Ich werde mir sofort ein starkes\n"
	.string "{STR_VAR_1} fangen!\p"
	.string "Bis später dann!$"
#else
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go catch a strong {STR_VAR_1}\n"
	.string "right away!\p"
	.string "See you again!$"
#endif

gText_ApprenticeWhichMon3::
#if GERMAN
	.string "Hallo {PLAYER}…\p"
	.string "Du weißt bestimmt nicht mehr, wer ich\n"
	.string "bin…\p"
	.string "Aber das macht nichts… Solange\n"
	.string "du mir trotzdem einen Rat gibst…\p"
	.string "Ich weiß nicht, welches Pokémon ich\n"
	.string "aufziehen soll…\p"
	.string "Ich kann mich nicht zwischen einem\n"
	.string "{STR_VAR_1} oder einem {STR_VAR_2}\l"
	.string "entscheiden…\p"
	.string "Ich weiß, ich nerve, {PLAYER}… Aber\n"
	.string "kannst du mir nicht doch helfen?$"
#else
	.string "Hello, {PLAYER}…\p"
	.string "Um, you've probably already forgotten\n"
	.string "about someone like me…\p"
	.string "…But that doesn't matter if you\n"
	.string "could give me advice…\p"
	.string "I can't decide on the one kind of\n"
	.string "POKéMON I should raise…\p"
	.string "I've narrowed the field to the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's\l"
	.string "where I became stuck…\p"
	.string "{PLAYER}, you probably don't want to\n"
	.string "bother, but please decide for me.$"
#endif

gText_ApprenticeMonThanks3::
#if GERMAN
	.string "Aber wird ein wildes {STR_VAR_1} mich \n"
	.string "überhaupt bemerken?\p"
	.string "Ich versuche es!\p"
	.string "Auch wenn ich niemals eines fangen\n"
	.string "werde… Ich werde mich anstrengen!\p"
	.string "Vielen, vielen Dank!$"
#else
	.string "But will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I will try!\p"
	.string "But will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"
#endif

gText_ApprenticeWhichMon4::
#if GERMAN
	.string "Bin ich froh, dich zu sehen, {PLAYER}{KUN}!\n"
	.string "Ich habe dich schon gesucht!\p"
	.string "Ich weiß nicht, welches Pokémon ich\n"
	.string "fangen soll.\p"
	.string "Was hältst du von einem {STR_VAR_1}\n"
	.string "oder einem {STR_VAR_2}?\p"
	.string "Welches ist deiner Meinung nach\n"
	.string "besser?$"
#else
	.string "Oh, {PLAYER}{KUN}! I'm so glad to see you!\n"
	.string "I was about to go looking for you!\p"
	.string "Can you decide what kind of POKéMON\n"
	.string "I should use?\p"
	.string "For instance…\n"
	.string "How about the POKéMON {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you think would be\n"
	.string "better?$"
#endif

gText_ApprenticeMonThanks4::
#if GERMAN
	.string "{STR_VAR_1}? Das ist ja großartig!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticeWhichMon5::
#if GERMAN
	.string "Wenn das nicht {PLAYER}{KUN} ist. Wie geht’s?\n"
	.string "Ich bin wie immer schwer im Stress!\p"
	.string "Ich möchte auch mit Pokémon gut sein,\n"
	.string "aber ich weiß nicht, welche ich fangen\l"
	.string "soll.\p"
	.string "{STR_VAR_1} sieht stark aus, meinst\n"
	.string "du nicht? Aber {STR_VAR_2} ist auch\l"
	.string "nicht so ohne.\p"
	.string "Gib mir bitte einen Rat, {PLAYER}{KUN}!\n"
	.string "Welches soll ich fangen?$"
#else
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I'm busy again as always!\p"
	.string "I want to do good with POKéMON, too,\n"
	.string "but I haven't been able to decide\l"
	.string "which POKéMON I should use.\p"
	.string "You know how {STR_VAR_1} look strong?\n"
	.string "But {STR_VAR_2} are tough to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one'd be good for me?$"
#endif

gText_ApprenticeMonThanks5::
#if GERMAN
	.string "Verstanden!\n"
	.string "Ich werde die Zeit finden, ein\l"
	.string "{STR_VAR_1} zu fangen!\p"
	.string "Ich bin froh, dass du mein Mentor bist!\p"
	.string "Vielen Dank! Man sieht sich!$"
#else
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and catch me\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"
#endif

gText_ApprenticeWhichMon6::
#if GERMAN
	.string "Hey! Da ist ja {PLAYER}!\p"
	.string "Ich habe nicht viel Zeit damit\n"
	.string "verbracht, vor meinen Freunden zu\l"
	.string "prahlen, dass ich dich kenne.\p"
	.string "Ich brauche heute wieder dein\n"
	.string "Köpfchen. Diesmal wird es einfach für\l"
	.string "dich!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Meine Frage lautet…\p"
	.string "Wenn ich ein Pokémon fangen will und ich\n"
	.string "die Wahl zwischen einem {STR_VAR_1} und\p"
	.string "einem {STR_VAR_2} habe, welches nehme\n"
	.string "ich?$"
#else
	.string "Oh!\n"
	.string "Yay, it's {PLAYER}!\p"
	.string "I didn't waste any time boasting to\n"
	.string "my friends about meeting you!\p"
	.string "I need to tap your mind again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I were to raise a POKéMON,\n"
	.string "and the choices were one {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which should it be?$"
#endif

gText_ApprenticeMonThanks6::
#if GERMAN
	.string "Aaah!\n"
	.string "Das {STR_VAR_1} also!\l"
	.string "Vielen Dank für deine coole Antwort!\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"
#else
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticeWhichMon7::
#if GERMAN
	.string "Du bist das, {PLAYER}!\n"
	.string "Schön, dich wiederzusehen!\p"
	.string "Seit ich deine Schülerin bin, bin\n"
	.string "ich viel selbstbewusster geworden!\p"
	.string "Ich glaube, ich bin so weit, ein eigenes\n"
	.string "Pokémon aufzuziehen.\p"
	.string "{PLAYER}, würdest du mir sagen, welches\n"
	.string "ich aufziehen soll?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?\n"
	.string "Welches ist das richtige Pokémon\l"
	.string "für mich?$"
#else
	.string "Oh, is it you, {PLAYER}?\n"
	.string "I'm delighted to see you again!\p"
	.string "Ever since I became your apprentice,\n"
	.string "my confidence has been blooming.\p"
	.string "I think I'm ready to raise a POKéMON\n"
	.string "of my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which POKéMON I should raise?\p"
	.string "The choices are the POKéMON\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which POKéMON is right for me?$"
#endif

gText_ApprenticeMonThanks7::
#if GERMAN
	.string "Ein {STR_VAR_1}!\n"
	.string "Ich werde mir sofort eines fangen!\p"
	.string "Vielen Dank, {PLAYER}.\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticeWhichMon8::
#if GERMAN
	.string "Iiihiii! {PLAYER}! So trifft man sich\n"
	.string "wieder! Ich bin ja so glücklich…\p"
	.string "Ja, ja, ja! Ich weiß! Diese Chance muss\n"
	.string "ich einfach wahrnehmen!\p"
	.string "Darf ich dich um etwas bitten, {PLAYER}?\n"
	.string "Bitte wähle ein Pokémon für mich aus.\p"
	.string "Welches ist besser? Ein {STR_VAR_1}\n"
	.string "oder ein {STR_VAR_2}?$"
#else
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"
#endif

gText_ApprenticeMonThanks8::
#if GERMAN
	.string "Wow! Du hast mir geholfen!\n"
	.string "Ich werde ein {STR_VAR_1} aufziehen,\l"
	.string "so gut ich eben kann!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"
#else
	.string "Wow! You decided for me!\n"
	.string "One {STR_VAR_1} is what I'll raise to\l"
	.string "the best of my ability.\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
#endif

gText_ApprenticeWhichMon9::
#if GERMAN
	.string "Hey, hey!\n"
	.string "Mein Lehrer, {PLAYER}{KUN}!\p"
	.string "Ich brauche wieder deinen weisen Tar…\n"
	.string "Äh… Rat!\p"
	.string "Welches Pokémon passt zu mir? Ein \n"
	.string "{STR_VAR_1} oder ein {STR_VAR_2}?\p"
	.string "Nur nicht schüchtern. Spuck’s aus!$"
#else
	.string "Hey, hey!\n"
	.string "My mentor, {PLAYER}{KUN}!\p"
	.string "Hello, I've been looking for you\n"
	.string "for some more of your sage advice!\p"
	.string "Which kind of POKéMON would be right\n"
	.string "for me, one {STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"
#endif

gText_ApprenticeMonThanks9::
#if GERMAN
	.string "Ein {STR_VAR_1}…\n"
	.string "Gut, ich nehme einen Lalb… Äh… Ball und\l"
	.string "dann… zack!\p"
	.string "Sehr schön! Vielen Dank!\n"
	.string "Wir sehen snu… Äh… uns!$"
#else
	.string "Uh-huh, one {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll get one in a BALL, like, cram!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
#endif

gText_ApprenticeWhichMon10::
#if GERMAN
	.string "{PLAYER}{KUN}! Stell dir das mal vor!!!\n"
	.string "Ich habe ein unsichtbares Pokémon\l"
	.string "gefangen!!!\p"
	.string "Nee, ich erzähl schon wieder eine\n"
	.string "Lügengeschichte! Muahahahaha!\p"
	.string "Ich bin nicht gut im Fangen von\n"
	.string "Pokémon. Und das ist leider die\l"
	.string "Wahrheit.\p"
	.string "Meister, kannst du mir nicht sagen,\n"
	.string "welches Pokémon ich fangen soll?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?$"
#else
	.string "{PLAYER}{KUN}, listen! Big news!\n"
	.string "I caught a mirage POKéMON!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at catching\l"
	.string "POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of POKéMON I should catch,\l"
	.string "master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"
#endif

gText_ApprenticeMonThanks10::
#if GERMAN
	.string "Du würdest ein {STR_VAR_1} fangen?\n"
	.string "Gut, dann fange ich das andere!\p"
	.string "Hahaha! Du bist drauf reingefallen!\n"
	.string "Ich werde deinem Rat folgen!\p"
	.string "Vielen Dank, Meister! Ich hoffe,\n"
	.string "du hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticeWhichMon11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein Matrose!\n"
	.string "Du erinnerst dich an mich?\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}?\n"
	.string "Welches ist das richtige?$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "Surely you remember who am I?\p"
	.string "Today, I have a POKéMON question\n"
	.string "that begs your suggestion!\p"
	.string "I have the choice between this\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, you see.\l"
	.string "Which is the one to catch for me?$"
#endif

gText_ApprenticeMonThanks11::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Das werd ich mir fangen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go get me one right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticeWhichMon12::
#if GERMAN
	.string "Hey, wenn das nicht {PLAYER} ist!\p"
	.string "Und wieder stellt sich mir die Frage, Rat\n"
	.string "holen oder nicht? Dabei rede ich doch\l"
	.string "bereits mit dir.\p"
	.string "Es ist ja schon lange her, aber\n"
	.string "ich tue so, als sei es gestern gewesen\l"
	.string "und frage dich direkt.\p"
	.string "Welches Pokémon soll ich fangen?\n"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?$"
#else
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I'm also looking for advice!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"
#endif

gText_ApprenticeMonThanks12::
#if GERMAN
	.string "Du hältst das {STR_VAR_1} für das\n"
	.string "bessere Pokémon? Okay!\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticeWhichMon13::
#if GERMAN
	.string "Oh, hallo {PLAYER}{KUN}…\n"
	.string "Diesmal habe ich Kopfschmerzen, und\l"
	.string "frag nicht wie!\p"
	.string "Ich zerbreche mir nämlich gerade den\n"
	.string "Kopf darüber, welches Pokémon ich \l"
	.string "aufziehen soll.\p"
	.string "Kannst du das nicht für mich\n"
	.string "entscheiden?\p"
	.string "Ein {STR_VAR_1} oder ein {STR_VAR_2}?\n"
	.string "Welches würdest du an meiner Stelle\l"
	.string "fangen?$"
#else
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "I have this horrible headache…\p"
	.string "I must've worried too much about\n"
	.string "the kind of POKéMON I should raise.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "the POKéMON {STR_VAR_1} and\l"
	.string "{STR_VAR_2}, which should it be?$"
#endif

gText_ApprenticeMonThanks13::
#if GERMAN
	.string "Ein {STR_VAR_1}.\n"
	.string "Sobald es mir besser geht, werde ich\l"
	.string "eines suchen.\p"
	.string "Ich hoffe, ich darf dich auch das\n"
	.string "nächste Mal um Hilfe anhauen.$"
#else
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
#endif

gText_ApprenticeWhichMon14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Du schaust mich schon wieder so an,\n"
	.string "dass ich ganz verlegen werde…\l"
	.string "Und ich brauche doch deinen Rat…\p"
	.string "Es ist mir mehr als peinlich… Aber ich\n"
	.string "kann mich bei den Pokémon nicht\l"
	.string "entscheiden…\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}… Welches\n"
	.string "soll ich nehmen?$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which POKéMON to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"
#endif

gText_ApprenticeMonThanks14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Dann werde ich ein {STR_VAR_1} fangen.\p"
	.string "Ich hoffe, ich blamiere mich dabei\n"
	.string "nicht…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticeWhichMon15::
#if GERMAN
	.string "Du scheinst {PLAYER}{KUN} zu sein.\n"
	.string "Aber bist du wirklich echt?\p"
	.string "Wenn du echt bist, ist alles in Ordnung.\n"
	.string "Dann würde ich dich gerne um Rat\l"
	.string "fragen.\p"
	.string "Es geht um Pokémon, die ich aufziehen\n"
	.string "möchte.\p"
	.string "Wäre ein {STR_VAR_1} oder ein\n"
	.string "{STR_VAR_2} besser für mich?$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the POKéMON I am to use.\p"
	.string "If the choices are the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"
#endif

gText_ApprenticeMonThanks15::
#if GERMAN
	.string "Ein {STR_VAR_1}?\n"
	.string "Du bist dir da ganz sicher?\p"
	.string "Dann ist es ja gut.\n"
	.string "Ich danke dir für deine kostbare Zeit.\p"
	.string "Da werde ich ganz gelassen rangehen\n"
	.string "können.\p"
	.string "Danke! Bis bald mal!$"
#else
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticeWhichMove0::
#if GERMAN
	.string "Waaaahaaa! Oh, {PLAYER}!\n"
	.string "Schnüff… Hick… Hick…\p"
	.string "Ich habe ein Problem… Waaahaaa…\n"
	.string "Welche Attacke soll ich meinem\l"
	.string "{STR_VAR_1} beibringen… Heul…\p"
	.string "Bitte, bitte, {PLAYER}.\n"
	.string "Kannst du mir das nicht sagen?\p"
	.string "Soll ich meinem {STR_VAR_1}\n"
	.string "{STR_VAR_2} oder {STR_VAR_3}\l"
	.string "beibringen?$"
#else
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks0::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Waaahaaa… Hick…\p"
	.string "Oh, tut mir Leid… Hick…\n"
	.string "Du hast mich mit deiner Entscheidung…\p"
	.string "Hick… so glücklich gemacht, dass\n"
	.string "ich weinen muss… Schnüff…\p"
	.string "Schnüff… Hick…\n"
	.string "Vielen… Hick… Dank! Hick…$"
#else
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"
#endif

gText_ApprenticeWhichMove1::
#if GERMAN
	.string "Hi {PLAYER}!\n"
	.string "Ich brauche mal wieder deine Hilfe.\p"
	.string "Ich möchte meinem {STR_VAR_1} eine\n"
	.string "coole Attacke beibringen.\p"
	.string "Entweder {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}. Aber welche soll ich\l"
	.string "nehmen? Sag du es mir.$"
#else
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"
#endif

gText_ApprenticeMoveThanks1::
#if GERMAN
	.string "{STR_VAR_1} ist besser? Das dachte\n"
	.string "ich mir. Ich werde deinem Rat folgen.\p"
	.string "Sobald wir uns hier wieder treffen,\n"
	.string "musst du mir unbedingt was Neues\l"
	.string "beibringen.$"
#else
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, teacher!$"
#endif

gText_ApprenticeWhichMove2::
#if GERMAN
	.string "{PLAYER}, hallo!\n"
	.string "Es geht um mein {STR_VAR_1}. Ich habe\l"
	.string "Probleme mit seinen Attacken.\p"
	.string "Ich habe die Attacken {STR_VAR_2}\n"
	.string "und {STR_VAR_3} zur Auswahl.\p"
	.string "Aber welche ist die bessere für\n"
	.string "mein {STR_VAR_1}?$"
#else
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I'm\l"
	.string "worried about its moves.\p"
	.string "You see, it's the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"
#endif

gText_ApprenticeMoveThanks2::
#if GERMAN
	.string "{STR_VAR_1} meinst du?\n"
	.string "Okay, einverstanden.\p"
	.string "Ich werde meinem Pokémon gleich\n"
	.string "{STR_VAR_1} beibringen!\p"
	.string "Bis später dann!$"
#else
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go teach {STR_VAR_1} to\n"
	.string "my POKéMON right away!\p"
	.string "See you again!$"
#endif

gText_ApprenticeWhichMove3::
#if GERMAN
	.string "Ooooh, {PLAYER}…\n"
	.string "Ich bin ein hoffnungsloser Fall! Echt!\p"
	.string "Da habe ich mich entschlossen, ein\n"
	.string "Pokémon aufzuziehen und nun weiß\p"
	.string "ich nicht, welche Attacke ich ihm\n"
	.string "beibringen soll…\p"
	.string "Für dich ist das sicher kein Problem,\n"
	.string "{PLAYER}.\p"
	.string "Aber für mich schon…\p"
	.string "Bitte, {PLAYER}, kannst du nicht eine\n"
	.string "Attacke für mein {STR_VAR_1}\l"
	.string "aussuchen?\p"
	.string "Wir haben die Wahl zwischen\n"
	.string "{STR_VAR_2} und {STR_VAR_3}…$"
#else
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, no, really!\p"
	.string "I've decided to raise a POKéMON,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"
#endif

gText_ApprenticeMoveThanks3::
#if GERMAN
	.string "Ich verstehe!\p"
	.string "Aber wird es {STR_VAR_1} auch mögen?\n"
	.string "Ach, ich werde mein Bestes geben!\p"
	.string "Vielen Dank!$"
#else
	.string "I understand!\p"
	.string "But will it even be willing to learn\n"
	.string "{STR_VAR_1} for me…\l"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"
#endif

gText_ApprenticeWhichMove4::
#if GERMAN
	.string "{PLAYER}{KUN}!\n"
	.string "Wir treffen uns immer im richtigen\l"
	.string "Augenblick.\p"
	.string "Ich frage mich gerade, welche Attacke\n"
	.string "zu meinem {STR_VAR_1} passen würde.\p"
	.string "Kannst du mir helfen? Kannst du das\n"
	.string "für mich entscheiden?\p"
	.string "Wir müssen zwischen {STR_VAR_2} und\n"
	.string "{STR_VAR_3} wählen.\l"
	.string "Welche ist besser geeignet?$"
#else
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"
#endif

gText_ApprenticeMoveThanks4::
#if GERMAN
	.string "{STR_VAR_1}? Spitze!\p"
	.string "Und da ich weiß, dass dieser Rat von dir\n"
	.string "kommt, {PLAYER}{KUN}, werde ich auch eine\l"
	.string "Niederlage ertragen können.\p"
	.string "Ich hoffe, ich kann dich bald mal wieder\n"
	.string "um Rat fragen! Mach’s gut!$"
#else
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"
#endif

gText_ApprenticeWhichMove5::
#if GERMAN
	.string "Wie kommt es, dass immer alles in Stress\n"
	.string "ausarten muss?\l"
	.string "Hey, wenn das nicht {PLAYER}{KUN} ist?!?\p"
	.string "Seit ich aufgestanden bin, bin ich\n"
	.string "beschäftigt. Joggen, Schwimmen und\l"
	.string "Kochen!\p"
	.string "Du glaubst gar nicht, wie viel ich immer\n"
	.string "zu tun habe!\p"
	.string "Ich habe noch nicht einmal Zeit zu\n"
	.string "entscheiden, welche Attacke mein\l"
	.string "{STR_VAR_1} lernen soll.\p"
	.string "{STR_VAR_2} wäre eine Möglichkeit.\n"
	.string "Aber auch {STR_VAR_3} ist gut.\p"
	.string "{PLAYER}{KUN}, bitte entscheide du für\n"
	.string "mich!$"
#else
	.string "How could things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"
#endif

gText_ApprenticeMoveThanks5::
#if GERMAN
	.string "Okay, okay! Ich werde mir die Zeit\n"
	.string "nehmen und ihm die Attacke\l"
	.string "beibringen… Wenn ich Zeit habe…\p"
	.string "Ich bin froh, einen Mentor wie dich zu\n"
	.string "haben! Vielen Dank! Man sieht sich!$"
#else
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"
#endif

gText_ApprenticeWhichMove6::
#if GERMAN
	.string "Oh! Was habe ich wieder für ein Glück!\n"
	.string "Da treffe ich dich, {PLAYER}, genau dann,\l"
	.string "wenn ich dein Gehirnschmalz brauche!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Hier kommt meine Frage…\p"
	.string "Welche Attacke eignet sich für mein\n"
	.string "{STR_VAR_1}? {STR_VAR_2} oder\l"
	.string "{STR_VAR_3}?$"
#else
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks6::
#if GERMAN
	.string "Aahaa!\n"
	.string "{STR_VAR_1}!\l"
	.string "Vielen Dank für die schnelle Antwort.\p"
	.string "Ich glaube, das ist alles, was ich heute\n"
	.string "von dir wissen will.\p"
	.string "Wir müssen uns bald mal wieder treffen!\n"
	.string "Danke und bis bald!$"
#else
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
#endif

gText_ApprenticeWhichMove7::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Ich hoffe, dir geht es gut?\p"
	.string "Ich brauche wieder deinen Rat…\n"
	.string "Es geht um mein geliebtes {STR_VAR_1}.\p"
	.string "Welche Attacke wird es mögen?\n"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"
#else
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks7::
#if GERMAN
	.string "{STR_VAR_1}!\n"
	.string "Die werde ich ihm gleich beibringen.\p"
	.string "Vielen Dank, {PLAYER}.\p"
	.string "Ich hoffe, du stehst mir auch in\n"
	.string "Zukunft mit Rat und Tat zur Seite!\l"
	.string "Pass auf dich auf!$"
#else
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
#endif

gText_ApprenticeWhichMove8::
#if GERMAN
	.string "Iihiii! {PLAYER}! {PLAYER}!\n"
	.string "Oh… Ich bin außer mir vor Freude, dich\l"
	.string "hier zu treffen!\p"
	.string "Immer wenn ich dich brauche, bist du\n"
	.string "auch schon da, {PLAYER}!\p"
	.string "Du musst mir heute bei den Attacken\n"
	.string "helfen!\p"
	.string "Ich will eine für mein {STR_VAR_1}\n"
	.string "auswählen.\p"
	.string "Aber welche? {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}?$"
#else
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks8::
#if GERMAN
	.string "Oh oh oh! Vielen Dank!\n"
	.string "{STR_VAR_1} soll es sein!\l"
	.string "Die ist bestimmt perfekt!\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um Rat fragen.$"
#else
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
#endif

gText_ApprenticeWhichMove9::
#if GERMAN
	.string "Guten Gat… Äh… Tag, {PLAYER}{KUN}!\n"
	.string "Darf ich auch heute an deiner Weisheit\l"
	.string "teilhaben?\p"
	.string "Welche ist die richtige Attacke für mein\n"
	.string "{STR_VAR_1}?\p"
	.string "Ich will doch immer newinneg…\n"
	.string "Äh… gewinnen!\p"
	.string "Also? {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}?$"
#else
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I'm hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks9::
#if GERMAN
	.string "{STR_VAR_1}!\n"
	.string "Ykao… Äh… Okay!\l"
	.string "Das werde ich ihm zack zack beibringen.\p"
	.string "Und dir wie immer vielen Dank!\n"
	.string "Udiea… Äh… Adieu!$"
#else
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Si, bueno!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
#endif

gText_ApprenticeWhichMove10::
#if GERMAN
	.string "{PLAYER}{KUN}, dies hier ist komplett\n"
	.string "verrückt!\p"
	.string "Mein Pokémon!\n"
	.string "Es hat Sechs Attacken gelernt!!!\p"
	.string "Muahahahaha!\n"
	.string "Nee, das war dick gelogen!\p"
	.string "Ich bin, und das ist die Wahrheit, nicht\n"
	.string "gut in der Wahl von Attacken.\p"
	.string "Kannst du nicht für mich entscheiden,\n"
	.string "welche ich ihm beibringen soll?\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Was meinst du?$"
#else
	.string "{PLAYER}{KUN}, it's completely wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at choosing moves\l"
	.string "for my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"
#endif

gText_ApprenticeMoveThanks10::
#if GERMAN
	.string "{STR_VAR_1}? Mmmmh…\n"
	.string "Dann bringe ich ihm die andere\l"
	.string "Attacke bei!!!\p"
	.string "Nee, das war doch wieder nur ein Witz!\n"
	.string "Nimm nicht immer alles so ernst!\p"
	.string "Vielen Dank, Meister! Ich hoffe, du\n"
	.string "hilfst mir auch in Zukunft.$"
#else
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
#endif

gText_ApprenticeWhichMove11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein Matrose.\n"
	.string "Habe ein Problem, das an mir klebt\l"
	.string "wie Lehm.\p"
	.string "Ich habe eine Frage, die\n"
	.string "wird dir zur Plage!\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Welche Attacke ist gut für\l"
	.string "mein {STR_VAR_1}?$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I'm always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"
#endif

gText_ApprenticeMoveThanks11::
#if GERMAN
	.string "{STR_VAR_1}!\n"
	.string "Das werde ich ihm beibringen.\p"
	.string "{PLAYER}, auch in Zukunft, das ist klar,\n"
	.string "frag ich dich um Rat, das ist wahr.$"
#else
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go teach that right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
#endif

gText_ApprenticeWhichMove12::
#if GERMAN
	.string "Oh, {PLAYER}!\p"
	.string "Da ich dich jetzt bereits angequatscht\n"
	.string "habe, kann ich dir auch eine Frage\l"
	.string "stellen.\p"
	.string "{PLAYER}, überrasch mich mit deiner\n"
	.string "Weisheit.\p"
	.string "Mein {STR_VAR_1} - welche Attacke soll\n"
	.string "es lernen? {STR_VAR_2} oder\l"
	.string "{STR_VAR_3}?$"
#else
	.string "Oh, yeahah, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"
#endif

gText_ApprenticeMoveThanks12::
#if GERMAN
	.string "{STR_VAR_1} ist also die beste\n"
	.string "Attacke.\p"
	.string "Nun, {PLAYER}, dann vergiss mich nicht!\p"
	.string "Man sieht sich.$"
#else
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
#endif

gText_ApprenticeWhichMove13::
#if GERMAN
	.string "Hatschi… Hust… Schniiief…\n"
	.string "Ich habe diese doofe Erkältung…\p"
	.string "Ich möchte meinem Pokémon eine\n"
	.string "Attacke beibringen, aber ich weiß nicht,\l"
	.string "welche…\p"
	.string "Und wie die Dinge so stehen, musst du\n"
	.string "das für mich entscheiden.\p"
	.string "Mein {STR_VAR_1}… Soll es {STR_VAR_2}\n"
	.string "oder {STR_VAR_3} lernen?$"
#else
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"
#endif

gText_ApprenticeMoveThanks13::
#if GERMAN
	.string "{STR_VAR_1}, also gut. Hust…\n"
	.string "Sobald es mir besser geht, werde ich ihm\l"
	.string "die beibringen. Schniiief… Hust…\p"
	.string "Ich hoffe, ich darf dich auch in\n"
	.string "Zukunft um deinen Rat bitten?$"
#else
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
#endif

gText_ApprenticeWhichMove14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Schau mich nicht so an…\n"
	.string "Ich bin schon verlegen genug…\l"
	.string "Dabei brauche ich doch deine Hilfe…\p"
	.string "Es ist eine peinliche Angelegenheit,\n"
	.string "aber ich kann mich nicht entscheiden,\p"
	.string "welche Attacke ich meinem Pokémon\n"
	.string "beibringen soll.\l"
	.string "Ich meine mein {STR_VAR_1}…\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?\n"
	.string "Welche ist besser?$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my POKéMON.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"
#endif

gText_ApprenticeMoveThanks14::
#if GERMAN
	.string "Oh… Okay!\n"
	.string "Ich werde es mit {STR_VAR_1}\l"
	.string "versuchen.\p"
	.string "Ich hoffe nur, ich kann ihm das auch\n"
	.string "beibringen…\l"
	.string "Das macht mich ganz nervös…\p"
	.string "Vielen Dank, {PLAYER}{KUN}!\n"
	.string "Wenn wir uns wiedersehen, habe ich\l"
	.string "bestimmt eine neue Frage an dich.$"
#else
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
#endif

gText_ApprenticeWhichMove15::
#if GERMAN
	.string "Hm? Bist du {PLAYER}{KUN} oder bist du\n"
	.string "es nicht?\p"
	.string "Vielleicht bist du ja eine Marionette?\p"
	.string "Wenn du echt bist, ist alles in Ordnung.\n"
	.string "Du brauchst nicht gleich wütend zu\l"
	.string "werden.\p"
	.string "Ich brauche nämlich wieder deinen Rat.\n"
	.string "Es geht um mein {STR_VAR_1}.\p"
	.string "Soll ich ihm {STR_VAR_2} oder\n"
	.string "{STR_VAR_3} beibringen?$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"
#endif

gText_ApprenticeMoveThanks15::
#if GERMAN
	.string "{STR_VAR_1}?\n"
	.string "Und da gibt es keinen Zweifel dran?\p"
	.string "Nun, dann ist es ja gut.\n"
	.string "Vielen Dank für deine Zeit.\p"
	.string "Ich hoffe, mein Pokémon ist in der\n"
	.string "Lage, die Attacke zu lernen…\p"
	.string "Bis bald mal!$"
#else
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my POKéMON can learn.\p"
	.string "Let us meet again!$"
#endif

gText_ApprenticePickWinSpeech0::
#if GERMAN
	.string "Oh… {PLAYER}?\n"
	.string "Es ist tatsächlich {PLAYER}!\l"
	.string "Heul… Jammer… Schnüff…\p"
	.string "Wenn ich kämpfe, bin ich immer so\n"
	.string "nervös, dass ich in Tränen ausbreche…\l"
	.string "Selbst wenn ich gewinne, weine ich…\p"
	.string "Heul… Dabei würde ich gerne mal was\n"
	.string "Cooles sagen, wenn ich gewinne…\l"
	.string "Jammer… Schnüff…\p"
	.string "Bitte, {PLAYER}! Was kann ich Cooles\n"
	.string "sagen, anstatt zu weinen? \l"
	.string "Heul… Jammer… Schnüff…$"
#else
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"
#endif

gText_ApprenticeWinSpeechThanks0::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Klasse! Spitze! Fantastisch!\n"
	.string "Das ist wirklich cool!\p"
	.string "Heul… Jammer… Tut mir Leid…\n"
	.string "Ich bin glücklich, daher weine ich…\l"
	.string "Heul…\p"
	.string "Schnüff… {PLAYER}!\n"
	.string "Vielen, vielen Dank!\p"
	.string "Ich werde mich für dich anstrengen,\n"
	.string "{PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Das nächste Mal… sollten wir\l"
	.string "gegeneinander kämpfen!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Awesome! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will battle the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"
#endif

gText_ApprenticePickWinSpeech1::
#if GERMAN
	.string "Hui! {PLAYER}! Hallo!\n"
	.string "Ich muss dich wieder etwas fragen!\p"
	.string "Ich möchte etwas wirklich Cooles sagen,\n"
	.string "wenn ich gewinne.\p"
	.string "Weißt du nicht, was ich sagen könnte?$"
#else
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"
#endif

gText_ApprenticeWinSpeechThanks1::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Wow! Das ist echt cool!!!\n"
	.string "Das werde ich sagen!\p"
	.string "Vielen Dank für deinen Rat und deine\n"
	.string "Geduld, die du immer mit mir hast.\p"
	.string "Ich werde mich anstrengen, egal,\n"
	.string "wohin ich gehe!\p"
	.string "Das nächste Mal, wenn wir uns sehen,\n"
	.string "dann frage ich dich nicht um Rat,\l"
	.string "sondern fordere dich zum Kampf heraus.$"
#else
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I'm going to do the best I can\l"
	.string "wherever I go from now on!\p"
	.string "When we meet again, it'll be for\n"
	.string "a battle!$"
#endif

gText_ApprenticePickWinSpeech2::
#if GERMAN
	.string "{PLAYER}! Hallo!\p"
	.string "Meine Pokémon sind zu allem bereit.\n"
	.string "Aber eine Sache ist noch offen.\p"
	.string "Ich würde gerne etwas Tolles rufen,\n"
	.string "wenn ich gewonnen habe!\p"
	.string "Fällt dir nicht etwas Tolles ein?$"
#else
	.string "{PLAYER}, hello!\p"
	.string "My POKéMON and I are ready for\n"
	.string "anything, except for one thing.\p"
	.string "I think it would be good if I had\n"
	.string "something to shout when I win.\p"
	.string "Could you think up something good\n"
	.string "to say?$"
#endif

gText_ApprenticeWinSpeechThanks2::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Cool…\n"
	.string "Das passt zu mir!\p"
	.string "Ich werde jetzt überall in Kämpfen\n"
	.string "antreten.\p"
	.string "Und wer weiß? Vielleicht kämpfen wir\n"
	.string "auch bald gegeneinander, {PLAYER}?\p"
	.string "Nächstes Mal werde ich dich\n"
	.string "herausfordern.$"
#else
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I will use that!\p"
	.string "I'm going out to battle all over\n"
	.string "the place.\p"
	.string "Who knows, I may even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place\n"
	.string "of battle!$"
#endif

gText_ApprenticePickWinSpeech3::
#if GERMAN
	.string "Hallo, {PLAYER}…\n"
	.string "Ich bin ein hoffnungsloser Fall, ich\l"
	.string "muss dich schon wieder nerven…\p"
	.string "Sogar wenn ich… Wenn ich gewinne,\n"
	.string "fehlen mir die Worte… Ich würde\l"
	.string "dann gerne etwas Besonderes sagen…\p"
	.string "Dir bedeutet das vielleicht nichts,\n"
	.string "{PLAYER}…\p"
	.string "Aber mir bedeutet es sehr viel…\p"
	.string "Bitte, {PLAYER}, was soll ich sagen, wenn\n"
	.string "ich einen Kampf gewinne?$"
#else
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to bug you, but I'm hopeless…\p"
	.string "Even when…\n"
	.string "Even when I win, I don't have anything\l"
	.string "special to say…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I win a battle?$"
#endif

gText_ApprenticeWinSpeechThanks3::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Das ist inspirierend…\p"
	.string "Und… Äh… Ist das auch wirklich in\n"
	.string "Ordnung, wenn jemand wie ich das sagt?\p"
	.string "Ja! Ich werde von nun an mein\n"
	.string "Bestes geben!\p"
	.string "{PLAYER}, ich danke dir für die Geduld,\n"
	.string "die du mit mir hattest…\p"
	.string "Ich bin sicher, jemanden wie mich wirst\n"
	.string "du schnell vergessen, aber wir müssen\l"
	.string "uns trotzdem bald mal wieder treffen!$"
#else
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "Uh… Is it okay for someone like me\n"
	.string "to even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for\n"
	.string "putting up with me for so long…\p"
	.string "I promise to do my best from now on.\p"
	.string "I'm sure you'll quickly forget about\n"
	.string "someone like me, but let's meet\l"
	.string "somewhere again!$"
#endif

gText_ApprenticePickWinSpeech4::
#if GERMAN
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Ich muss etwas mit dir besprechen.\p"
	.string "Ich weiß, ich komme nicht immer nett\n"
	.string "und freundlich rüber…\p"
	.string "Und wenn ich gewinne, wirke ich, glaube\n"
	.string "ich, ganz schön arrogant…\p"
	.string "Ich möchte aber, dass die Leute mich\n"
	.string "mögen, daher möchte ich etwas Nettes\l"
	.string "zu meinem Gegner sagen.\p"
	.string "Mir fällt aber absolut nichts ein!\n"
	.string "Weißt du nicht etwas Nettes?$"
#else
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know that I don't always sound\n"
	.string "nice or polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as being arrogant.\p"
	.string "I don't want people to dislike me,\n"
	.string "so I want to say something nice to\l"
	.string "someone I beat.\p"
	.string "But I can't think of anything good!\n"
	.string "Could you think something up for me?$"
#endif

gText_ApprenticeWinSpeechThanks4::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Das klingt nicht schlecht!\n"
	.string "Ja, das werde ich von nun an sagen!\p"
	.string "Ich werde mich nun auf den Weg machen,\n"
	.string "und das, was du mir beigebracht hast,\l"
	.string "beherzigen!\p"
	.string "Tut mir Leid, dass ich dich immer wieder\n"
	.string "mit Fragen bedrängt habe.\p"
	.string "Nächstes Mal kämpfen wir gegen-\n"
	.string "einander, einverstanden? Bis dann!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I'm going to hit the road and do what\n"
	.string "I can with what you taught me in\l"
	.string "my head and heart.\p"
	.string "I'm sorry that I've been so pushy\n"
	.string "with you!\p"
	.string "Next time, we battle, okay?\n"
	.string "See you!$"
#endif

gText_ApprenticePickWinSpeech5::
#if GERMAN
	.string "Ich verstehe nicht, wieso ich immer so\n"
	.string "im Stress bin! Hey, dich habe ich schon\l"
	.string "gesucht, {PLAYER}{KUN}!\p"
	.string "Und? Alles klar?\n"
	.string "Bei mir ist alles beim Alten.\p"
	.string "Ich renne, kämpfe und bin auch sonst\n"
	.string "ziemlich beschäftigt.\p"
	.string "Aber auch wenn ich nie Zeit habe,\n"
	.string "möchte ich mich nach einem Kampf nicht\l"
	.string "einfach auf dem Absatz umdrehen\p"
	.string "und gehen. Ich möchte etwas sagen, was\n"
	.string "meine Coolness unterstreicht, bevor ich\l"
	.string "weggehe. Aber was, {PLAYER}{KUN}?$"
#else
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even though I'm busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I'm done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"
#endif

gText_ApprenticeWinSpeechThanks5::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Okay!\n"
	.string "Das zu sagen, nimmt auch nicht viel Zeit\l"
	.string "in Anspruch. Das schaffe ich locker.\p"
	.string "Ich bin echt froh, einen so guten\n"
	.string "Mentor wie dich gefunden zu haben!\p"
	.string "Wenn ich meine Zeit anders aufteile,\n"
	.string "werde ich auch die Zeit finden, mehr zu\l"
	.string "kämpfen.\p"
	.string "Vielen Dank für alles, {PLAYER}{KUN}!\n"
	.string "Eines Tages werden auch wir gegen-\l"
	.string "einander kämpfen. Bis dahin mach’s gut!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Okay, gotcha.\n"
	.string "I can find time to say that!\p"
	.string "Honestly, I'm glad I met a good mentor\n"
	.string "like you.\p"
	.string "I'm going to make time somehow so\n"
	.string "I can get into battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"
#endif

gText_ApprenticePickWinSpeech6::
#if GERMAN
	.string "Und wieder lächelt mir das Glück zu!\n"
	.string "Ich freu mich, dich zu sehen, {PLAYER}!\l"
	.string "Und wie immer brauche ich deinen Rat!\p"
	.string "Trommelwirbel, bitte!\n"
	.string "Dies wird meine letzte Frage…\p"
	.string "Gewinne ich einen Kampf, würde ich\n"
	.string "gerne etwas Cooles sagen.\l"
	.string "Aber ich weiß nicht was!$"
#else
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like usual, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The last question I have is…\p"
	.string "If I win a battle and want to end\n"
	.string "it with a cool flourish, what\l"
	.string "should I say?$"
#endif

gText_ApprenticeWinSpeechThanks6::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Das… Das ist klasse!!!\n"
	.string "Seriös und doch cool!\l"
	.string "Das werde ich sagen!\p"
	.string "Ich bin mittlerweile richtig gut\n"
	.string "geworden…\p"
	.string "Und daher denke ich darüber nach,\n"
	.string "andere Trainer herauszufordern.\p"
	.string "Du hast mir sehr geholfen, {PLAYER}.\p"
	.string "Vielleicht werden auch wir eines Tages\n"
	.string "gegeneinander antreten!\p"
	.string "Vielen Dank! Pass auf dich auf!$"
#else
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I'm getting decent\n"
	.string "at this, huh?\p"
	.string "So, I'm thinking of challenging other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day, there'll be a time when\n"
	.string "we battle!\p"
	.string "Thank you for everything!$"
#endif

gText_ApprenticePickWinSpeech7::
#if GERMAN
	.string "Oh, {PLAYER}!\n"
	.string "Ich bin froh, dich zu sehen!\p"
	.string "Ich habe keine Bedenken mehr, was meine\n"
	.string "Pokémon angeht.\p"
	.string "Jetzt mache ich mir Gedanken über mich…\p"
	.string "Weißt du, was ein Trainer sagen kann,\n"
	.string "wenn er einen Kampf gewonnen hat?\p"
	.string "Ich würde nämlich auch gerne etwas\n"
	.string "sagen.\p"
	.string "Kannst du mir da nicht weiterhelfen?\n"
	.string "Hast du eine Idee, was ich sagen kann?$"
#else
	.string "Oh, {PLAYER}.\n"
	.string "I'm so glad I met you!\p"
	.string "I no longer have any concerns with\n"
	.string "regard to my POKéMON.\p"
	.string "It's myself that worries me…\p"
	.string "Do you know how a TRAINER says\n"
	.string "a few things upon winning a battle?\p"
	.string "Definitely, I wish I could do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I win a battle?$"
#endif

gText_ApprenticeWinSpeechThanks7::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Oh! Das ist wirklich eine Aussage! Da\n"
	.string "fühle ich mich richtig gut mit!\p"
	.string "Das werde ich gleich mal ausprobieren.\p"
	.string "Ich muss dich jetzt verlassen,\n"
	.string "{PLAYER}…\p"
	.string "Ich werde viele Trainer treffen, aber\n"
	.string "dich und deine Hilfe werde ich nie\l"
	.string "vergessen!\p"
	.string "Und vielleicht eines Tages…\n"
	.string "Lebewohl!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me\n"
	.string "and makes me feel reborn!\p"
	.string "I must use that right away!\p"
	.string "And now, I must take my leave,\n"
	.string "{PLAYER}…\p"
	.string "I will go out to battle many others,\n"
	.string "but never will I forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"
#endif

gText_ApprenticePickWinSpeech8::
#if GERMAN
	.string "Iiihiii! Ich habe dich gesehen, {PLAYER}!\n"
	.string "Ich freue mich total, dass du hier bist…\p"
	.string "Und wieder habe ich eine dringende\n"
	.string "Frage an dich!\p"
	.string "Vor kurzem habe ich einen Kampf\n"
	.string "gewonnen! Das war einfach lächerlich…\p"
	.string "Aber ich war so erfreut darüber, dass\n"
	.string "mir die Worte im Halse stecken\l"
	.string "blieben und ich stumm wie ein Fisch war.\p"
	.string "{PLAYER}, kannst du dir nicht etwas\n"
	.string "ausdenken, das ich sagen kann, nachdem\l"
	.string "ich einen Kampf gewonnen habe?$"
#else
	.string "Eek! I spotted {PLAYER}!\n"
	.string "I… I'm overjoyed to see you!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was giddying!\p"
	.string "But it made me so overjoyed that\n"
	.string "I choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I want you to\n"
	.string "think up an exit line for when I win!$"
#endif

gText_ApprenticeWinSpeechThanks8::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Waaaaauuu!\n"
	.string "Das soll ich wirklich sagen?!?\l"
	.string "Iihiii! Ich freu mich total darüber!!!\p"
	.string "Vielen, vielen Dank!\n"
	.string "Nun habe ich keine Wünsche mehr offen!\p"
	.string "Ich kann durch das Land reisen und\n"
	.string "viele Menschen treffen.\p"
	.string "Und das verdanke ich allein dir,\n"
	.string "{PLAYER}. Wirklich! Vielen, vielen Dank!\p"
	.string "Ich muss jetzt los, aber ich hoffe, wir\n"
	.string "sehen uns bald wieder und kämpfen\l"
	.string "dann mal gegeneinander! Mach’s gut!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I'm going to say that?!\l"
	.string "I… I'm delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I'm going to travel now and battle\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet\n"
	.string "in battle one day!$"
#endif

gText_ApprenticePickWinSpeech9::
#if GERMAN
	.string "Holla… Äh… Hallo!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Weißt du, ich würde gerne durch die\n"
	.string "Gegend ziehen und kämpfen.\p"
	.string "Aber bevor ich aufbreche, brauche ich\n"
	.string "noch einmal deinen Rat.\p"
	.string "Wenn ich einen Kampf gewinne, was soll\n"
	.string "ich dann zu dem besiegten Trainer\l"
	.string "sagen?$"
#else
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I'm getting the itch to roam\n"
	.string "and battle where I may.\p"
	.string "But before I do, I want your advice\n"
	.string "once again, please!\p"
	.string "If I were to win a battle, what would\n"
	.string "be a good boast I could say to my\l"
	.string "fallen TRAINER opponent?$"
#endif

gText_ApprenticeWinSpeechThanks9::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Oh ja, das gefällt mir!\n"
	.string "Ja, hirklicw… Äh… wirklich!\l"
	.string "Genau das werde ich von nun an sagen!\p"
	.string "Und nun heißt es Auf Wiedersehen!\n"
	.string "Vielen Dank für alles!\p"
	.string "Wir müssen bald mal gegeneinander\n"
	.string "kämpfen! Web lohl… Äh… Leb wohl!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that's sweet!\n"
	.string "Si, bueno!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "And now, it's time to say good-bye!\n"
	.string "Thanks for all sorts of things!\p"
	.string "Give me a battle one day, OK?\n"
	.string "Adios!$"
#endif

gText_ApprenticePickWinSpeech10::
#if GERMAN
	.string "{PLAYER}{KUN}, der Weltuntergang steht\n"
	.string "bevor!\p"
	.string "Wenn ich einen Kampf gewinne, stehe ich\n"
	.string "vier Stunden später immer noch auf dem\p"
	.string "Platz und überlege, was ich zu meinem\n"
	.string "Sieg sagen könnte.\l"
	.string "Und mein Gegner ist längst gegangen.\p"
	.string "Nee, das war natürlich gelogen.\n"
	.string "Muahahahaha!\p"
	.string "Aber es ist keine Lüge, wenn ich dir\n"
	.string "verrate, dass ich tatsächlich nicht\l"
	.string "weiß, was ich nach einem Sieg sagen soll.\p"
	.string "Hast du nicht eine Idee?$"
#else
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for an hour at least!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at chatting.\p"
	.string "So, how about deciding for me what\n"
	.string "I should say after winning a battle,\l"
	.string "master?$"
#endif

gText_ApprenticeWinSpeechThanks10::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Das soll ich also sagen?\n"
	.string "Okay, dann wird das nicht über meine\l"
	.string "Lippen kommen!\p"
	.string "Haha! Da habe ich dich wieder auf den\n"
	.string "Arm genommen! Ich höre auf deinen Rat!\p"
	.string "Vielen Dank für alles, was du mir\n"
	.string "beigebracht hast, Meister!\p"
	.string "Nun weiß ich, was es heißt, ein Trainer\n"
	.string "zu sein!\p"
	.string "Ich werde nun auf die Reise gehen und\n"
	.string "viele Trainer herausfordern.\p"
	.string "Und eines Tages vielleicht auch dich!\p"
	.string "Bis dahin wünsche ich dir alles Gute,\n"
	.string "mein Meister!$"
#else
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then, I'll stay away from that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I'm finally understanding what being\n"
	.string "a TRAINER is about.\p"
	.string "I'm going to go out and win battles\n"
	.string "against any TRAINER.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"
#endif

gText_ApprenticePickWinSpeech11::
#if GERMAN
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Ich bin ein Matrose!\n"
	.string "Habe eine letzte Frage an dich,\l"
	.string "dann verabschiede ich mich.\p"
	.string "Gewinne ich einen Kampf, fehlen mir\n"
	.string "die Worte, das ist echt ein Krampf.\p"
	.string "Ein cooles Wort wäre die Tat.\n"
	.string "Weißt du Rat?$"
#else
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "This will be my last question,\l"
	.string "don't you cry!\p"
	.string "It's a saying question\n"
	.string "that begs your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"
#endif

gText_ApprenticeWinSpeechThanks11::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Perfekt! Das werde ich sagen!\n"
	.string "Es war gut, dich zu fragen.\p"
	.string "Und nun, das ist die beste Weise,\n"
	.string "begebe ich mich auf die Reise.\p"
	.string "Vielen Dank für alles!\p"
	.string "Ich grüße dich zum Abschied,\n"
	.string "hoffe, dass man sich mal sieht.$"
#else
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "And now, I think it'd be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'll be off on a battle spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "And that spells bon voyage,\l"
	.string "to you this is my homage!$"
#endif

gText_ApprenticePickWinSpeech12::
#if GERMAN
	.string "Yeah, {PLAYER}!\n"
	.string "So sieht man sich wieder!\p"
	.string "Soll ich dich was fragen? Klar,\n"
	.string "wo ich doch schon mal mit dir rede…\p"
	.string "{PLAYER}, ich brauche dringend deinen\n"
	.string "Rat. Hör gut zu!\p"
	.string "Was soll ich sagen, wenn ich einen Kampf\n"
	.string "gewonnen habe? Irgendetwas Cooles\l"
	.string "soll es sein.\p"
	.string "Hast du nicht einen Spruch auf Lager?$"
#else
	.string "Oh, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask you again?\n"
	.string "Why not? I'm already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need some more advice for me!\p"
	.string "It's about what I should yell.\n"
	.string "Something cool to holler when\l"
	.string "a battle ends well.\p"
	.string "Come on, I wanna hear you say it!$"
#endif

gText_ApprenticeWinSpeechThanks12::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Sehr gut! Sehr gut!\n"
	.string "Das ist wirklich supergut!\p"
	.string "Und nun heißt es für uns\n"
	.string "Abschied nehmen.\p"
	.string "Sollten wir uns eines Tages\n"
	.string "wiedersehen, werde ich dich um einen\l"
	.string "Kampf bitten.\p"
	.string "Aber genug geredet.\n"
	.string "Vielen Dank, {PLAYER}, und pass auf\l"
	.string "dich auf!\p"
	.string "Bis bald mal!$"
#else
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because it's so tight!\p"
	.string "I'm out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "But maybe one day we'll meet, with one\n"
	.string "destined to go down in defeat.\p"
	.string "But, it really is time to say farewell.\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"
#endif

gText_ApprenticePickWinSpeech13::
#if GERMAN
	.string "{PLAYER}{KUN}, ich hab’s geschafft!\n"
	.string "Aber meine Nase hört nicht auf zu\l"
	.string "laufen…\p"
	.string "Ich überlegte, was ich nach einem\n"
	.string "Sieg sagen kann.\p"
	.string "Und vor lauter Inspiration fing ich an\n"
	.string "zu weinen und meine Nase an zu laufen…\p"
	.string "Und da ich mit einer laufenden Nase\n"
	.string "nicht denken kann…\p"
	.string "Bitte ich dich, mir zu raten, was ich\n"
	.string "nach einem Sieg sagen kann.$"
#else
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"
#endif

gText_ApprenticeWinSpeechThanks13::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "… … … … …\p"
	.string "Das ist guuut! Total inspirierend!\n"
	.string "Das treibt mir glatt wieder die\l"
	.string "Tränen in die Augen!\p"
	.string "Aber auch mit Tränen in den Augen und\n"
	.string "einer laufenden Nase werde ich diese\l"
	.string "Worte aussprechen!\p"
	.string "Von nun an sind wir Rivalen und werden\n"
	.string "bald gegeneinander kämpfen.\p"
	.string "Trotzdem vielen Dank für alles,\n"
	.string "{PLAYER}{KUN}!$"
#else
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"
#endif

gText_ApprenticePickWinSpeech14::
#if GERMAN
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Du schaust mich immer wieder so an,\n"
	.string "dass ich total nervös und verlegen\l"
	.string "werde. Lass das bitte!\p"
	.string "Ich… brauche wieder deinen Rat.\n"
	.string "Diesmal wird es das letzte Mal sein… \p"
	.string "Es ist zwar sehr peinlich, aber ich muss\n"
	.string "dich fragen, was ich nach einem Sieg\l"
	.string "sagen soll. Hilf mir bitte.$"
#else
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"
#endif

gText_ApprenticeWinSpeechThanks14::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "Ich werde das sagen!\l"
	.string "Falls ich nicht zu nervös dazu bin…\p"
	.string "Vielen Dank, {PLAYER}{KUN}.\n"
	.string "Und nun muss ich mich von dir\l"
	.string "verabschieden.\p"
	.string "Ich werde mich an das halten, was du mir\n"
	.string "beigebracht hast. {PLAYER}{KUN}, ich werde\l"
	.string "mein Bestes geben!$"
#else
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"
#endif

gText_ApprenticePickWinSpeech15::
#if GERMAN
	.string "Hm? Du bist scheinbar {PLAYER}{KUN}…\n"
	.string "Oder doch nicht?\l"
	.string "Bist du eventuell eine {PLAYER}-Puppe?\p"
	.string "Oh, keine Sorge!\n"
	.string "Wenn du echt bist, dann verzeih bitte\l"
	.string "meine Grobheit!\p"
	.string "Du musst nicht gleich wütend werden.\n"
	.string "Ich möchte dich doch gerne um einen\l"
	.string "Rat bitten.\p"
	.string "Es geht um bestimmte Worte.\p"
	.string "Was soll ich sagen, wenn ich einen\n"
	.string "Kampf gewonnen habe?$"
#else
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"
#endif

gText_ApprenticeWinSpeechThanks15::
#if GERMAN
	.string "{STR_VAR_1}\p"
	.string "… … … … …\n"
	.string "…\l"
	.string "Wenn ich einen Kampf gewinne…\p"
	.string "{STR_VAR_1}\p"
	.string "Meinst du das wirklich so?\p"
	.string "Nun, dann ist es ja gut.\n"
	.string "Ich danke dir für deine Zeit.\p"
	.string "Ich hoffe, ich werde in der Lage sein,\n"
	.string "diese Worte oft zu sagen.\p"
	.string "Du hast mir alles beigebracht, was ich\n"
	.string "wissen muss.\p"
	.string "Es ist an der Zeit, dass sich unsere\n"
	.string "Wege trennen.\p"
	.string "Vielen Dank, mein Mentor! Und\n"
	.string "entschuldige meine dauernde Skepsis!$"
#else
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
#endif
