gText_Birch_Welcome::
#if GERMAN
	.string "Sorry, dass du warten musstest.\p"
	.string "Willkommen in der Welt der Pokémon!\p"
	.string "Mein Name ist Birk.\p"
	.string "Aber jeder nennt mich nur Professor\n"
	.string "Pokémon.\p"
	.string "$"
#else
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"
#endif

gText_Birch_Pokemon::
#if GERMAN
	.string "Das hier nennen wir “Pokémon.”\p"
	.string "\n"
	.string "$"
#else
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"
#endif

gText_Birch_MainSpeech::
#if GERMAN
	.string "Auf dieser Welt leben Wesen, die uns als\n"
	.string "Pokémon bekannt sind.\p"
	.string "Wir Menschen leben Seite an Seite mit\n"
	.string "ihnen, als Freunde oder als\l"
	.string "Arbeitskollegen.\p"
	.string "Und manchmal schließen wir uns mit\n"
	.string "ihnen zusammen und tragen Kämpfe\l"
	.string "gegen andere von uns aus.\p"
	.string "Doch obwohl wir den Pokémon so nahe\n"
	.string "stehen, wissen wir noch nicht alles über\l"
	.string "sie.\p"
	.string "Es gibt noch viele, viele Geheim-\n"
	.string "nisse um die Pokémon.\p"
	.string "Um die Mysterien der Pokémon\n"
	.string "aufzudecken, widme ich mich der\l"
	.string "Forschung. Genau das tue ich.\p"
	.string "$"
#else
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"
#endif

gText_Birch_AndYouAre::
#if GERMAN
	.string "Und wer bist du?$"
#else
	.string "And you are?$"
#endif

gText_Birch_BoyOrGirl::
#if GERMAN
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"
#else
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"
#endif

gText_Birch_WhatsYourName::
#if GERMAN
	.string "Fein!\n"
	.string "Und wie heißt du?$"
#else
	.string "All right.\n"
	.string "What's your name?$"
#endif

gText_Birch_SoItsPlayer::
#if GERMAN
	.string "Ah, du bist also {PLAYER}{KUN}?$"
#else
	.string "So it's {PLAYER}{KUN}?$"
#endif

gText_Birch_YourePlayer::
#if GERMAN
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt\n"
	.string "{PLAYER}{KUN} und bist gerade nach\l"
	.string "Wurzelheim, meinen Heimatort, gezogen!\p"
	.string "$"
#else
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"
#endif

gText_Birch_AreYouReady::
#if GERMAN
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird nun\n"
	.string "beginnen.\p"
	.string "Hab nur Mut und stürze dich in die Welt\n"
	.string "der Pokémon, wo Abenteuer, Träume und\l"
	.string "Freundschaft warten.\p"
	.string "Komm später in mein Pokémon-Labor,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
#else
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
#endif
