Text_PictureBookShelf:
#if GERMAN
	.string "Eine Sammlung von Pokémon-Büchern.$"
#else
	.string "There's a set of POKéMON picture books.$"
#endif

Text_BookShelf:
#if GERMAN
	.string "Hier stehen jede Menge Bücher.$"
#else
	.string "It's filled with all sorts of books.$"
#endif

Text_PokemonCenterBookShelf:
#if GERMAN
	.string "Pokémon-Magazine!\n"
	.string "Der Pokémon Freund…\p"
	.string "Pokémon Handbuch…\n"
	.string "Geliebte Pokémon…$"
#else
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"
#endif

Text_Vase:
#if GERMAN
	.string "Diese Vase sieht sehr teuer aus…\n"
	.string "Schauen wir mal hinein…\p"
	.string "Och, sie ist leer.$"
#else
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"
#endif

Text_EmptyTrashCan:
#if GERMAN
	.string "Leer…$"
#else
	.string "It's empty.$"
#endif

Text_ShopShelf:
#if GERMAN
	.string "Die Regale biegen sich unter dem\n"
	.string "Gewicht von Pokémon-Artikeln.$"
#else
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"
#endif

Text_Blueprint:
#if GERMAN
	.string "Sind das Blaupausen?\n"
	.string "Die sind zu kompliziert zu lesen.$"
#else
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
#endif

