gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Eich Pokémon-Labor$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Einen Führer mit allen\n"
	.string "Pokémon der Welt zu erstellen…\p"
	.string "Das war mein Traum!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Prof. Eich hört das nicht\n"
	.string "gerne, aber er ist eine\l"
	.string "Pokémon-Kapazität.\p"
	.string "Viele Pokémon Trainer schätzen\n"
	.string "ihn sehr.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es wird berichtet, dass Prof.\n"
	.string "Eich mit seinen Enkeln Sarah\l"
	.string "und {RIVAL} zusammenlebt.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass sich\n"
	.string "Eich sehr für dich interessiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Prof. Eich wird bald seine\n"
	.string "eigene Radiosendung haben.\p"
	.string "Die Sendung heißt, Prof. \n"
	.string "Eichs Pokémon-Seminar.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wenn du Sarah deine\n"
	.string "Pokémon zeigst, sagt sie dir\l"
	.string "wie sehr sie dich mögen.\p"
	.string "Manchmal pflegt sie auch deine\n"
	.string "Pokémon für dich!$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Dennoch ist die Person,\n"
	.string "die von den Pokémon am meisten\l"
	.string "geliebt wird, immer noch Sarah.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sie hat sich rührend um\n"
	.string "Pokémon gekümmert…\l"
	.string "Sie war ein kleiner Engel.\p"
	.string "Der Name des Mädchens…\n"
	.string "Ich glaube, er lautete Sarah.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es wird berichtet, dass Prof.\n"
	.string "Eich mit seinen Enkeln Sarah\l"
	.string "und {RIVAL} zusammenlebt.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sarah, ein Mädchen aus\n"
	.string "Alabastia, das täglich Tee trinkt.\p"
	.string "Sie kauft den Tee im Einkaufs-\n"
	.string "Zentrum von Prismania City.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Der Frühlingsmeister im\n"
	.string "Pokémon-Wettkampf ist\l"
	.string "Sarah Eich aus Alabastia!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Rocko, Arenaleiter von Marmoria\n"
	.string "City.\l"
	.string "Der Steinharte Pokémon Trainer!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine felsenstarke Willenskraft\n"
	.string "manifestiert sich in jedem\l"
	.string "meiner Pokémon.\l"
	.string "Meine Pokémon sind hart wie Stein\l"
	.string "und felsenfest entschlossen.\p"
	.string "Das stimmt! Meine Pokémon gehören\n"
	.string "alle der Elementklasse Gestein an!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt hier nicht viele\n"
	.string "Pokémon Trainer, die es\l"
	.string "ernst meinen.\l"
	.string "Sie sind wie Käfersammler, \l"
	.string "einfach nur Hobby-Trainer.\p"
	.string "Aber Rocko, der Arenaleiter\n"
	.string "von Marmoria City, ist nicht so!$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Rocko ist cool. Er ist nicht\n"
	.string "nur stark. Die Leute mögen und\l"
	.string "respektieren ihn.\p"
	.string "Ich möchte auch ein Arenaleiter\n"
	.string "wie er werden.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Hallo, ich grabe hier am\n"
	.string "Mondberg Fossilien aus.\p"
	.string "Manchmal hilft mir Rocko von\n"
	.string "der Arena aus Marmoria City.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Rocko lacht nur selten, wenn er\n"
	.string "aber doch lacht, kann er angeblich\l"
	.string "nicht mehr damit aufhören.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Misty, Arenaleiterin aus\n"
	.string "Azuria City.\l"
	.string "Die Burschikose Meerjungfrau!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine Strategie basiert\n"
	.string "auf der totalen Offensive meiner\l"
	.string "Wasser-Pokémon.$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Misty gehört zu der\n"
	.string "Kategorie Trainer, die sich\l"
	.string "ständig verbessern möchten.\l"
	.string "Sie würde gegen dich nie verlieren!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Starke Trainer und\n"
	.string "Wasser-Pokémon kommen\l"
	.string "hier häufig vor.\l"
	.string "Man sagt, dass Misty von der\l"
	.string "Arena aus Azuria City hier\l"
	.string "trainiert.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das Kap ist beliebt bei\n"
	.string "Pärchen.\p"
	.string "Die Arenaleiterin Misty\n"
	.string "hat hohe Erwartungen an\l"
	.string "diesen Ort.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass Misty,\n"
	.string "Lorelei von den Top Vier\l"
	.string "verehrt.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Major Bob, der Arena-\n"
	.string "Leiter von Orania City.\l"
	.string "Der Blitzende Amerikaner!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Mein Kind, im Krieg haben\n"
	.string "mir Elektro-Pokémon das\l"
	.string "Leben gerettet!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Während meiner Zeit beim\n"
	.string "Militär war Major Bob mein\l"
	.string "Vorgesetzter.\p"
	.string "Er war ein zäher Befehlshaber.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Beim Militär war Major\n"
	.string "Bob für seine vorsichtige Art\l"
	.string "bekannt.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Major Bob hat die Fallen\n"
	.string "in seiner Arena selbst aufgestellt.\p"
	.string "Er hat überall Doppelschlösser\n"
	.string "einbauen lassen.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Major Bob soll während seiner\n"
	.string "Zeit in Amerika ein Pilot\l"
	.string "gewesen sein.\l"
	.string "Er setzte die Elektrizität seiner\l"
	.string "Pokémon als Antrieb für\l"
	.string "sein Flugzeug ein.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Prismania City Pokémon-Arena\n"
	.string "Arenaleiterin: Erika\l"
	.string "Die Naturliebende Prinzessin!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich lerne die Kunst des\n"
	.string "Blumenanrichtens.\p"
	.string "Meine Pokémon gehören\n"
	.string "ausschließlich der Elementklasse\l"
	.string "Pflanze an.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Unsere Arenaleiterin\n"
	.string "Erika mag still sein, aber\l"
	.string "sie ist hier auch berühmt.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} In unserer Arena werden\n"
	.string "ausschließlich Pokémon der\l"
	.string "Elementklasse Pflanze eingesetzt.$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich würde nie Pokémon\n"
	.string "sammeln, wenn sie nicht so\l"
	.string "hübsch wären.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass Erika in der\n"
	.string "Arena öfters ein Nickerchen macht.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Koga, Arenaleiter von\n"
	.string "Fuchsania City.\l"
	.string "Der Giftige Ninja-Meister.$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Verzweifle am Gänsehaut\n"
	.string "verursachenden Horror der Gift-\l"
	.string "Pokémon.$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Auch wenn ich verliere,\n"
	.string "trainiere ich gemäß der Lehre\l"
	.string "meines Ninja-Meisters Koga.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Mein Vater ist der Arena-\n"
	.string "Leiter dieser Stadt.\p"
	.string "Ich trainiere auch den Einsatz\n"
	.string "von Gift-Pokémon wie\l"
	.string "mein Vater.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Koga verfügt über fundiertes\n"
	.string "Wissen im Bereich der Medizin.\p"
	.string "Er stellt sogar Medizin selbst her,\n"
	.string "um seine Pokémon damit zu\l"
	.string "heilen.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die Safari-Zone ist riesig,\n"
	.string "oder nicht?\p"
	.string "Der Arenaleiter von Fuchsania\n"
	.string "City, Koga, hält hier gelegentlich\l"
	.string "Wache.\p"
	.string "Dank ihm können wir hier in\n"
	.string "Sicherheit spielen.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sabrina, Arenaleiterin aus\n"
	.string "Saffronia City.\l"
	.string "Die Meisterin der Psycho-Pokémon!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Kennst du ein Mädchen, das\n"
	.string "in Saffronia City Arenaleiterin\l"
	.string "ist?\l"
	.string "Sie setzt Psycho-Pokémon ein,\l"
	.string "wenn ich mich nicht irre?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich beherrsche die Psychokinese,\n"
	.string "seit ich ein Kind war.\p"
	.string "Zunächst habe ich gelernt, mit\n"
	.string "Psychokinese Löffel zu verbiegen.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich verabscheue den Kampf!\n"
	.string "Aber wenn du es wünschst, beweise\l"
	.string "ich dir meine Kräfte!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass Sabrina im Kampf\n"
	.string "mit ihren Pokémon, ohne zu\l"
	.string "sprechen kommunizieren kann.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sabrina hat gerade mit dem\n"
	.string "Karate-Meister von nebenan\l"
	.string "den Boden gewischt.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Pyro, Arenaleiter von der\n"
	.string "Zinnoberinsel.\l"
	.string "Der Hitzköpfige Quizmaster!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine feurigen Pokémon sind\n"
	.string "stark, und brennen nur\l"
	.string "darauf loszulegen.\l"
	.string "Sie verbrennen alle Herausforderer!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Unser Arenaleiter Pyro hat sich\n"
	.string "einmal im Gebirge verlaufen, aber\l"
	.string "alles ging gut.\p"
	.string "Bei Einbruch der Nacht erschien\n"
	.string "ein Pokémon, das einem\l"
	.string "Feuervogel ähnelte.\l"
	.string "Sein Licht ermöglichte Pyro sicher\l"
	.string "nach Hause zurückzufinden.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Pyro, der Arenaleiter der\n"
	.string "Zinnoberinsel, ist ein seltsamer\l"
	.string "Mann. \p"
	.string "Er lebte schon hier, bevor das\n"
	.string "Labor errichtet wurde.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein Foto von Pyro und Mr. Fuji!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Pyro nimmt seine Sonnenbrille\n"
	.string "angeblich nur ab, wenn er sich\l"
	.string "neue Quizfragen ausdenkt.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin Lorelei von den\n"
	.string "Top Vier.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin die Nummer Eins, wenn es\n"
	.string "um Eis-Pokémon geht.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wo wurde diese Person geboren?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein wunderbarer, starker Trainer\n"
	.string "ist hier aufgewachsen.\p"
	.string "Ich wette, du kennst sie auch. Es\n"
	.string "ist Lorelei von den Top Vier.$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die für ihren logischen, coolen\n"
	.string "und berechnenden Kampfstil\l"
	.string "bekannte Lorelei hat ein\l"
	.string "überraschendes Geheimnis!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wusstest du, dass Lorelei eine\n"
	.string "ganze Menge Plüschpuppen besitzt?\p"
	.string "Bei jedem Besuch auf Eiland Vier\n"
	.string "wächst ihre Sammlung!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Sie hat immer noch das Lapras,\n"
	.string "das sie in ihrer Kindheit traf.\p"
	.string "Ich erinnere mich, dass sie es\n"
	.string "in der Eiskaskadenhöhle\l"
	.string "gefangen hatte.\l"
	.string "Vermutlich ist dieses Pokémon\l"
	.string "seither nicht von ihrer Seite\l"
	.string "gewichen.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin Bruno von den Top Vier!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich lebe und trainiere mit meinen\n"
	.string "Kampf-Pokémon!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bruno hat sich offensichtlich den\n"
	.string "Top Vier angeschlossen, um sein\l"
	.string "Verlangen, nur gegen die besten\l"
	.string "Trainer zu kämpfen, zu stillen.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bruno, der mir voransteht,\n"
	.string "kommt gelegentlich auch\l"
	.string "in diesen Kurort.\l"
	.string "Er kommt hierher, um seine\l"
	.string "Gebrechen und die seiner\l"
	.string "Pokémon zu lindern.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist einer der Top Vier!\n"
	.string "Sein Name ist Bruno!\p"
	.string "Er ist gegangen, weil er enttäuscht\n"
	.string "war, dass alle Wutkekse\l"
	.string "ausverkauft waren.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Auch Bruno…\n"
	.string "Er hat zuvor mit einem Kumpel\l"
	.string "namens Kamillo trainiert.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin Agathe von den Top Vier!$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Agathes Geist-Pokémon\n"
	.string "sind erschreckend hartnäckig.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die alte Dame ist auch leicht\n"
	.string "zu verärgern.\p"
	.string "Es bedarf nur einer Bagatelle und\n"
	.string "die Angst einflößende Dame\l"
	.string "legt los.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In ihrer Jugend war Agathe eine\n"
	.string "Rivalin von Prof. Eich und hat\l"
	.string "mit ihm um die Vorherrschaft\l"
	.string "als Trainer gekämpft.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass sich\n"
	.string "Eich sehr für dich interessiert!\p"
	.string "Dieser alte Knacker war früher\n"
	.string "stark und schön.\p"
	.string "Aber das ist Jahrzehnte her.\n"
	.string "Jetzt ist er nur noch ein\l"
	.string "Schatten seiner Selbst.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Nimm z.B. Agathe!\p"
	.string "Sie hält den Rekord als ältestes\n"
	.string "Mitglied der Top Vier.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin Siegfried,\n"
	.string "Drachen-Trainer\l"
	.string "und Oberhaupt der Top Vier!$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wusstest du, dass\n"
	.string "Drachen mystische Pokémon sind?\p"
	.string "Sie sind schwer zu fangen und zu\n"
	.string "zähmen! Doch die Mühe lohnt sich!\p"
	.string "Sie sind beinahe unbesiegbar!$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er verkörpert Gerechtigkeit!\n"
	.string "Er ist cool und leidenschaftlich!\l"
	.string "Siegfried ist der Größte!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt einen Kunden namens\n"
	.string "Siegfried, der gelegentlich\l"
	.string "vorbeikommt.\l"
	.string "Er kauft stets Umhänge.\p"
	.string "Ich frage mich, ob er\n"
	.string "viele gleiche Umhänge zu\l"
	.string "Hause hat.$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Man sagt, dass der Großvater von\n"
	.string "Siegfried der Älteste in einem\l"
	.string "berühmten Drachenklan ist.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich habe gehört, dass Siegfried\n"
	.string "einen Cousin hat, der irgendwo\l"
	.string "weit weg Arenaleiter ist.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bill ist weltweit als Pokémaniac\n"
	.string "bekannt!\p"
	.string "Er hat das Pokémon-Lagerungs-\n"
	.string "System für den PC entwickelt!$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bill besitzt viele Pokémon!\p"
	.string "Er hat einige sehr seltene in\n"
	.string "seiner Sammlung!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist mein Enkel!\p"
	.string "Schon als kleines Kind hat er gerne\n"
	.string "alles Mögliche gesammelt!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bill ist ein Pokémaniac, also mag\n"
	.string "er alle Pokémon.\p"
	.string "Es scheint, dass Abra sein erstes\n"
	.string "Pokémon war!$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bill kommt aus Dukatia City,\n"
	.string "wo seine Familie noch lebt.\p"
	.string "Das ist eine eher geschäftige,\n"
	.string "lebhafte Stadt.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Bill kann offensichtlich\n"
	.string "Milch nicht leiden!$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Er ist sehr fürsorglich!\p"
	.string "Er kümmert sich um ausgesetzte\n"
	.string "und verwaiste Pokémon!$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Da war so ein alter Knacker, der\n"
	.string "behauptet hat, wir würden Pokémon\l"
	.string "quälen!\p"
	.string "Willst Du meine Meinung hören?$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Großes Pokémon-Gewinnspiel!\p"
	.string "Es sind keine Teilnahmekarten mehr\n"
	.string "vorhanden!\p"
	.string "Sie wurden alle abgeschickt!$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Es gibt ein Gerücht…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich hörte, dass Mr. Fuji auch\n"
	.string "nicht von hier stammt!$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ein Foto von Pyro und Mr. Fuji!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Redakteur: Der publikumsscheue\n"
	.string "Mr. Fuji hat unsere Interview-\l"
	.string "anfragen zurückgewiesen.\p"
	.string "Er ist ein freundlicher Mann, der\n"
	.string "in Lavandia verehrt und respektiert\l"
	.string "wird.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das Team Rocket finanziert mit\n"
	.string "Pokémon seine finsteren Pläne!\p"
	.string "Ich bin hier der Boss, Giovanni!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Lieblings-Pokémon?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Diese Rüpel haben die Kontrolle in\n"
	.string "diesem Gebäude übernommen…\p"
	.string "Der Boss sagte, dass er nach\n"
	.string "starken Pokémon sucht.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Wie ist diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Der Boss von Team Rocket ist\n"
	.string "unheimlich grausam!\p"
	.string "Für ihn sind Pokémon schlicht\n"
	.string "Mittel zum Zweck.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Willkommen in meinem\n"
	.string "Geheimversteck!\p"
	.string "Hier wollte ich das Team Rocket\n"
	.string "wiederauferstehen lassen!$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Was macht diese Person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Das gibt es nicht!\n"
	.string "Giovanni war hier Arenaleiter?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Familie und Freunde?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Du… du bist nicht das Kind von\n"
	.string "Giovanni! Sein Kind ist rothaarig.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Prof. Oak$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Prof. Eich\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Warum strengen sich Pokémon\n"
	.string "im Kampf so für dich an?\p"
	.string "Weil sie deine Liebe und\n"
	.string "Hingabe ihnen gegenüber\l"
	.string "spüren!\p"
	.string "Das darfst du nie vergessen!$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Daisy$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Sarah\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Während ich meine Teepausen\n"
	.string "genoss, bist du stark und\l"
	.string "geschickt geworden.\p"
	.string "Ich hoffe, du bist auch in\n"
	.string "Zukunft ein guter\l"
	.string "Rivale für meinen Bruder!$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Brock$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Rocko\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} In unserer großen Welt muss\n"
	.string "es viele starke Trainer geben.\p"
	.string "Lass uns weiterhin hart\n"
	.string "trainieren, um noch\l"
	.string "stärker zu werden.$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Misty$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Misty\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich möchte hier in dieser Arena\n"
	.string "trainieren.\p"
	.string "Wenn ich besser bin, möchte ich\n"
	.string "hinaus in die weite Welt.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lt. Surge$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Major Bob\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Heh, Kiddie!\n"
	.string "Du hast mich in unserem Kampf\l"
	.string "gefrizzelt!\p"
	.string "Ich wusste nicht, dass es so\n"
	.string "mutige Trainer wie dich gibt!\p"
	.string "Dadurch habe ich meine\n"
	.string "Meinung über dich geändert!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Erika$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Erika\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich bin so froh, dass es solch\n"
	.string "starke Trainer wie dich gibt.\p"
	.string "Allein diese Tatsache inspiriert\n"
	.string "und motiviert mich,\l"
	.string "noch mehr zu trainieren.\p"
	.string "Bitte komme wieder!\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Koga$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Koga\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Du und ich, wir beide müssen\n"
	.string "unsere Ziele höher stecken und\l"
	.string "an unseren Herausforderungen\l"
	.string "arbeiten.\l"
	.string "Nun muss ich meine Tochter\l"
	.string "trainieren.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sabrina$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Sabrina\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die Liebe, die du für deine\n"
	.string "Pokémon empfindest…\p"
	.string "Diese Kraft wurde nie von\n"
	.string "meiner Psykraft besiegt.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Blaine$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Pyro\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Meine Feuer-Pokémon!\n"
	.string "Sie werden noch stärker!\p"
	.string "Und nun ein Quiz! Wie viele\n"
	.string "unterschiedliche Feuer-Pokémon\l"
	.string "gibt es?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lorelei$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Lorelei\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich musste dir für deine\n"
	.string "Hilfe danken.\p"
	.string "Aber das hat mit unseren Kämpfen\n"
	.string "nichts zu tun.\p"
	.string "Nimm dich beim nächsten Mal\n"
	.string "gefälligst in Acht!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bruno$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Bruno\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Die unbändige Kraft\n"
	.string "von dir und deinen Pokémon\l"
	.string "habe ich bereits kennen gelernt.\p"
	.string "Beim nächsten Mal sollte ich\n"
	.string "dir vielleicht zeigen, wie du\l"
	.string "dein Training gestalten solltest.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Agatha$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Agathe\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Wenn du älter wirst, darfst du\n"
	.string "nicht so ein Weichei wie dieser\l"
	.string "Knacker Eich werden!\p"
	.string "Sei wie ich und kämpfe weiter!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lance$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Siegfried\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Ich denke darüber nach,\n"
	.string "in meine Heimatstadt\l"
	.string "zurückzukehren.\p"
	.string "Ich möchte meine Drachen-\n"
	.string "Pokémon wieder trainieren\l"
	.string "und sie verbessern.\p"
	.string "Ich möchte, dass du mich\n"
	.string "auch einmal in meiner\l"
	.string "Heimatstadt besuchst.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bill$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Bill\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Heh! Celio hat dich in den\n"
	.string "höchsten Tönen gelobt.\p"
	.string "Das macht mich glücklich.\p"
	.string "Zeigst du mir seltene Pokémon,\n"
	.string "wenn du welche gefangen\l"
	.string "hast?$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Mr. Fuji$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Mr. Fuji\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Anstatt ausschließlich an das\n"
	.string "Wohlbefinden deiner Pokémon\l"
	.string "zu denken…\p"
	.string "… kann ich dich überzeugen,\n"
	.string "an das Glück aller Pokémon\l"
	.string "zu denken?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Giovanni$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Von: Giovanni\n"
	.string "An: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY} Es gibt nichts, was ich dir sagen\n"
	.string "möchte!\p"
	.string "Ich konzentriere mich\n"
	.string "ausschließlich darauf,\l"
	.string "mich zu verbessern\l"
	.string "und niemanden sonst!$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "Pallet Town$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
#if GERMAN
	.string "Research Lab$"
#else
	.string "RESEARCH LAB$"
#endif

gFameCheckerFlavorTextOriginLocation_ProfOak2::
#if GERMAN
	.string "Research Lab$"
#else
	.string "RESEARCH LAB$"
#endif

gFameCheckerFlavorTextOriginLocation_ProfOak3::
#if GERMAN
	.string "Viridian City$"
#else
	.string "VIRIDIAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_ProfOak4::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_ProfOak5::
#if GERMAN
	.string "Research Lab$"
#else
	.string "RESEARCH LAB$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy0::
#if GERMAN
	.string "Research Lab$"
#else
	.string "RESEARCH LAB$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy1::
#if GERMAN
	.string "Vermilion City$"
#else
	.string "VERMILION CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy2::
#if GERMAN
	.string "Water Labyrinth$"
#else
	.string "WATER LABYRINTH$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy3::
#if GERMAN
	.string "Viridian City$"
#else
	.string "VIRIDIAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy4::
#if GERMAN
	.string "Celadon Mansion$"
#else
	.string "CELADON MANSION$"
#endif

gFameCheckerFlavorTextOriginLocation_Daisy5::
#if GERMAN
	.string "Four Island$"
#else
	.string "FOUR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock0::
#if GERMAN
	.string "Pewter City$"
#else
	.string "PEWTER CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock1::
#if GERMAN
	.string "Pewter Gym$"
#else
	.string "PEWTER GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock2::
#if GERMAN
	.string "Pewter City$"
#else
	.string "PEWTER CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock3::
#if GERMAN
	.string "Route 4$"
#else
	.string "ROUTE 4$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock4::
#if GERMAN
	.string "MT. Moon$"
#else
	.string "MT. MOON$"
#endif

gFameCheckerFlavorTextOriginLocation_Brock5::
#if GERMAN
	.string "Pewter Museum$"
#else
	.string "PEWTER MUSEUM$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty0::
#if GERMAN
	.string "Cerulean City$"
#else
	.string "CERULEAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty1::
#if GERMAN
	.string "Cerulean Gym$"
#else
	.string "CERULEAN GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty2::
#if GERMAN
	.string "Cerulean Gym$"
#else
	.string "CERULEAN GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty3::
#if GERMAN
	.string "Seafoam Islands$"
#else
	.string "SEAFOAM ISLANDS$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty4::
#if GERMAN
	.string "Cerulean Cape$"
#else
	.string "CERULEAN CAPE$"
#endif

gFameCheckerFlavorTextOriginLocation_Misty5::
#if GERMAN
	.string "Cerulean City$"
#else
	.string "CERULEAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge0::
#if GERMAN
	.string "Vermilion City$"
#else
	.string "VERMILION CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge1::
#if GERMAN
	.string "Vermilion Gym$"
#else
	.string "VERMILION GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge2::
#if GERMAN
	.string "Vermilion Gym$"
#else
	.string "VERMILION GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge3::
#if GERMAN
	.string "Vermilion Gym$"
#else
	.string "VERMILION GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge4::
#if GERMAN
	.string "Vermilion Gym$"
#else
	.string "VERMILION GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_LtSurge5::
#if GERMAN
	.string "Vermilion City$"
#else
	.string "VERMILION CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika0::
#if GERMAN
	.string "Celadon City$"
#else
	.string "CELADON CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika1::
#if GERMAN
	.string "Celadon Gym$"
#else
	.string "CELADON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika2::
#if GERMAN
	.string "Celadon Gym$"
#else
	.string "CELADON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika3::
#if GERMAN
	.string "Celadon Gym$"
#else
	.string "CELADON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika4::
#if GERMAN
	.string "Celadon Gym$"
#else
	.string "CELADON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Erika5::
#if GERMAN
	.string "Celadon Mansion$"
#else
	.string "CELADON MANSION$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga0::
#if GERMAN
	.string "Fuchsia City$"
#else
	.string "FUCHSIA CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga1::
#if GERMAN
	.string "Fuchsia Gym$"
#else
	.string "FUCHSIA GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga2::
#if GERMAN
	.string "Fuchsia Gym$"
#else
	.string "FUCHSIA GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga3::
#if GERMAN
	.string "Fuchsia City$"
#else
	.string "FUCHSIA CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga4::
#if GERMAN
	.string "Fuchsia City$"
#else
	.string "FUCHSIA CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Koga5::
#if GERMAN
	.string "Safari Zone$"
#else
	.string "SAFARI ZONE$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina0::
#if GERMAN
	.string "Saffron City$"
#else
	.string "SAFFRON CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina1::
#if GERMAN
	.string "Three Island$"
#else
	.string "THREE ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina2::
#if GERMAN
	.string "Saffron Gym$"
#else
	.string "SAFFRON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina3::
#if GERMAN
	.string "Saffron Gym$"
#else
	.string "SAFFRON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina4::
#if GERMAN
	.string "Saffron City$"
#else
	.string "SAFFRON CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Sabrina5::
#if GERMAN
	.string "Saffron Gym$"
#else
	.string "SAFFRON GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine0::
#if GERMAN
	.string "Cinnabar Island$"
#else
	.string "CINNABAR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine1::
#if GERMAN
	.string "Cinnabar Gym$"
#else
	.string "CINNABAR GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine2::
#if GERMAN
	.string "Cinnabar Gym$"
#else
	.string "CINNABAR GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine3::
#if GERMAN
	.string "Cinnabar Island$"
#else
	.string "CINNABAR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine4::
#if GERMAN
	.string "Cinnabar Gym$"
#else
	.string "CINNABAR GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Blaine5::
#if GERMAN
	.string "Resort Gorgeous$"
#else
	.string "RESORT GORGEOUS$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei0::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei1::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei2::
#if GERMAN
	.string "Four Island$"
#else
	.string "FOUR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei3::
#if GERMAN
	.string "Five Island$"
#else
	.string "FIVE ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei4::
#if GERMAN
	.string "Four Island$"
#else
	.string "FOUR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Lorelei5::
#if GERMAN
	.string "Four Island$"
#else
	.string "FOUR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno0::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno1::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno2::
#if GERMAN
	.string "Saffron City$"
#else
	.string "SAFFRON CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno3::
#if GERMAN
	.string "Ember Spa$"
#else
	.string "EMBER SPA$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno4::
#if GERMAN
	.string "Two Island$"
#else
	.string "TWO ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Bruno5::
#if GERMAN
	.string "Sevault Canyon$"
#else
	.string "SEVAULT CANYON$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha0::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha1::
#if GERMAN
	.string "Indigo Plateau$"
#else
	.string "INDIGO PLATEAU$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha2::
#if GERMAN
	.string "Indigo Plateau$"
#else
	.string "INDIGO PLATEAU$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha3::
#if GERMAN
	.string "Seven Island$"
#else
	.string "SEVEN ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha4::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Agatha5::
#if GERMAN
	.string "Six Island$"
#else
	.string "SIX ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance0::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance1::
#if GERMAN
	.string "Pokémon League$"
#else
	.string "POKéMON LEAGUE$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance2::
#if GERMAN
	.string "Saffron City$"
#else
	.string "SAFFRON CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance3::
#if GERMAN
	.string "Celadon Dept.$"
#else
	.string "CELADON DEPT.$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance4::
#if GERMAN
	.string "Indigo Plateau$"
#else
	.string "INDIGO PLATEAU$"
#endif

gFameCheckerFlavorTextOriginLocation_Lance5::
#if GERMAN
	.string "Indigo Plateau$"
#else
	.string "INDIGO PLATEAU$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill0::
#if GERMAN
	.string "Cerulean City$"
#else
	.string "CERULEAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill1::
#if GERMAN
	.string "Cerulean City$"
#else
	.string "CERULEAN CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill2::
#if GERMAN
	.string "Fuchsia City$"
#else
	.string "FUCHSIA CITY$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill3::
#if GERMAN
	.string "One Island$"
#else
	.string "ONE ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill4::
#if GERMAN
	.string "One Island$"
#else
	.string "ONE ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Bill5::
#if GERMAN
	.string "One Island$"
#else
	.string "ONE ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji0::
#if GERMAN
	.string "Lavender Town$"
#else
	.string "LAVENDER TOWN$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji1::
#if GERMAN
	.string "Pokémon Tower$"
#else
	.string "POKéMON TOWER$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji2::
#if GERMAN
	.string "Lavender Town$"
#else
	.string "LAVENDER TOWN$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji3::
#if GERMAN
	.string "Lavender Town$"
#else
	.string "LAVENDER TOWN$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji4::
#if GERMAN
	.string "Cinnabar Gym$"
#else
	.string "CINNABAR GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_MrFuji5::
#if GERMAN
	.string "Cinnabar Island$"
#else
	.string "CINNABAR ISLAND$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni0::
#if GERMAN
	.string "Rocket Hideout$"
#else
	.string "ROCKET HIDEOUT$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni1::
#if GERMAN
	.string "Silph Co.$"
#else
	.string "SILPH CO.$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni2::
#if GERMAN
	.string "Silph Co.$"
#else
	.string "SILPH CO.$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni3::
#if GERMAN
	.string "Viridian Gym$"
#else
	.string "VIRIDIAN GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni4::
#if GERMAN
	.string "Viridian Gym$"
#else
	.string "VIRIDIAN GYM$"
#endif

gFameCheckerFlavorTextOriginLocation_Giovanni5::
#if GERMAN
	.string "Rocket Warehouse$"
#else
	.string "ROCKET WAREHOUSE$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
#if GERMAN
	.string "Prof. Oak$"
#else
	.string "PROF. OAK$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
#if GERMAN
	.string "Aide$"
#else
	.string "AIDE$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
#if GERMAN
	.string "Agatha$"
#else
	.string "AGATHA$"
#endif

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
#if GERMAN
	.string "Aide$"
#else
	.string "AIDE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy0::
#if GERMAN
	.string "Aide$"
#else
	.string "AIDE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy1::
#if GERMAN
	.string "Woman$"
#else
	.string "WOMAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy2::
#if GERMAN
	.string "Man$"
#else
	.string "MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy3::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy4::
#if GERMAN
	.string "Old Lady$"
#else
	.string "OLD LADY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Daisy5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock1::
#if GERMAN
	.string "Brock$"
#else
	.string "BROCK$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock2::
#if GERMAN
	.string "Young man$"
#else
	.string "YOUNG MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock3::
#if GERMAN
	.string "Boy$"
#else
	.string "BOY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock4::
#if GERMAN
	.string "Man$"
#else
	.string "MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Brock5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty1::
#if GERMAN
	.string "Misty$"
#else
	.string "MISTY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty2::
#if GERMAN
	.string "Luis$"
#else
	.string "LUIS$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty3::
#if GERMAN
	.string "Young man$"
#else
	.string "YOUNG MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty4::
#if GERMAN
	.string "Dame$"
#else
	.string "DAME$"
#endif

gFameCheckerFlavorTextOriginObjectName_Misty5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
#if GERMAN
	.string "Lt. Surge$"
#else
	.string "LT. SURGE$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
#if GERMAN
	.string "Tucker$"
#else
	.string "TUCKER$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
#if GERMAN
	.string "Tucker$"
#else
	.string "TUCKER$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
#if GERMAN
	.string "Dwayne$"
#else
	.string "DWAYNE$"
#endif

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika1::
#if GERMAN
	.string "Erika$"
#else
	.string "ERIKA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika2::
#if GERMAN
	.string "Lola$"
#else
	.string "LOLA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika3::
#if GERMAN
	.string "Tamia$"
#else
	.string "TAMIA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika4::
#if GERMAN
	.string "Erika$"
#else
	.string "ERIKA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Erika5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga1::
#if GERMAN
	.string "Koga$"
#else
	.string "KOGA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga2::
#if GERMAN
	.string "Kirk$"
#else
	.string "KIRK$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga3::
#if GERMAN
	.string "Charine$"
#else
	.string "CHARINE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga4::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Koga5::
#if GERMAN
	.string "Man$"
#else
	.string "MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
#if GERMAN
	.string "Young man$"
#else
	.string "YOUNG MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
#if GERMAN
	.string "Sabrina$"
#else
	.string "SABRINA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
#if GERMAN
	.string "Sabrina$"
#else
	.string "SABRINA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
#if GERMAN
	.string "Tyron$"
#else
	.string "TYRON$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine0::
#if GERMAN
	.string "Sign$"
#else
	.string "SIGN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine1::
#if GERMAN
	.string "Blaine$"
#else
	.string "BLAINE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine2::
#if GERMAN
	.string "Derek$"
#else
	.string "DEREK$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine3::
#if GERMAN
	.string "Woman$"
#else
	.string "WOMAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine4::
#if GERMAN
	.string "Photo$"
#else
	.string "PHOTO$"
#endif

gFameCheckerFlavorTextOriginObjectName_Blaine5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
#if GERMAN
	.string "Lorelei$"
#else
	.string "LORELEI$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
#if GERMAN
	.string "Lorelei$"
#else
	.string "LORELEI$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
#if GERMAN
	.string "Old man$"
#else
	.string "OLD MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
#if GERMAN
	.string "Little Girl$"
#else
	.string "LITTLE GIRL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
#if GERMAN
	.string "Old Lady$"
#else
	.string "OLD LADY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno0::
#if GERMAN
	.string "Bruno$"
#else
	.string "BRUNO$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno1::
#if GERMAN
	.string "Bruno$"
#else
	.string "BRUNO$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno2::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno3::
#if GERMAN
	.string "Crusher$"
#else
	.string "CRUSHER$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno4::
#if GERMAN
	.string "Woman$"
#else
	.string "WOMAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bruno5::
#if GERMAN
	.string "Crusher$"
#else
	.string "CRUSHER$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha0::
#if GERMAN
	.string "Agatha$"
#else
	.string "AGATHA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha1::
#if GERMAN
	.string "Crusher$"
#else
	.string "CRUSHER$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha2::
#if GERMAN
	.string "Crusher$"
#else
	.string "CRUSHER$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha3::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha4::
#if GERMAN
	.string "Agatha$"
#else
	.string "AGATHA$"
#endif

gFameCheckerFlavorTextOriginObjectName_Agatha5::
#if GERMAN
	.string "Old Lady$"
#else
	.string "OLD LADY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance0::
#if GERMAN
	.string "Lance$"
#else
	.string "LANCE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance1::
#if GERMAN
	.string "Lance$"
#else
	.string "LANCE$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance2::
#if GERMAN
	.string "Woman$"
#else
	.string "WOMAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance3::
#if GERMAN
	.string "Little Girl$"
#else
	.string "LITTLE GIRL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance4::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Lance5::
#if GERMAN
	.string "Young man$"
#else
	.string "YOUNG MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
#if GERMAN
	.string "Little Boy$"
#else
	.string "LITTLE BOY$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bill2::
#if GERMAN
	.string "Old man$"
#else
	.string "OLD MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bill3::
#if GERMAN
	.string "Celio$"
#else
	.string "CELIO$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bill4::
#if GERMAN
	.string "Celio$"
#else
	.string "CELIO$"
#endif

gFameCheckerFlavorTextOriginObjectName_Bill5::
#if GERMAN
	.string "Celio$"
#else
	.string "CELIO$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
#if GERMAN
	.string "Little Girl$"
#else
	.string "LITTLE GIRL$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
#if GERMAN
	.string "Team Rocket$"
#else
	.string "TEAM ROCKET$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
#if GERMAN
	.string "Magazine$"
#else
	.string "MAGAZINE$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
#if GERMAN
	.string "Man$"
#else
	.string "MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
#if GERMAN
	.string "Photo$"
#else
	.string "PHOTO$"
#endif

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
#if GERMAN
	.string "Pokémon Journal$"
#else
	.string "POKéMON JOURNAL$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
#if GERMAN
	.string "Giovanni$"
#else
	.string "GIOVANNI$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
#if GERMAN
	.string "Scientist$"
#else
	.string "SCIENTIST$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
#if GERMAN
	.string "Scientist$"
#else
	.string "SCIENTIST$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
#if GERMAN
	.string "Giovanni$"
#else
	.string "GIOVANNI$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
#if GERMAN
	.string "Man$"
#else
	.string "MAN$"
#endif

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
#if GERMAN
	.string "Gideon$"
#else
	.string "GIDEON$"
#endif

PokemonJournal_Text_SpecialFeatureBrock::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiter\n"
	.string "Rocko aus Marmoria City!\p"
	.string "Rocko lacht selten, aber er kann nicht\n"
	.string "aufhören, wenn er angefangen hat.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"
#endif

PokemonJournal_Text_SpecialFeatureMisty::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiterin\n"
	.string "Misty aus Azuria City!\p"
	.string "Misty vergöttert angeblich Lorelei von\n"
	.string "den Top Vier.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"
#endif

PokemonJournal_Text_SpecialFeatureLtSurge::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiter\n"
	.string "Major Bob aus Orania City!\p"
	.string "Major Bob war angeblich Pilot\n"
	.string "in seiner Heimat Amerika.\p"
	.string "Sein Flugzeug ist mittels der\n"
	.string "elektrischen Energie von Pokémon\l"
	.string "geflogen.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"
#endif

PokemonJournal_Text_SpecialFeatureErika::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiterin\n"
	.string "Erika aus Prismania City!\p"
	.string "Man sagt, dass man bei einer Stippvisite\n"
	.string "in der Arena von Prismania City, Erika\l"
	.string "bei einem Nickerchen beobachten kann.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"
#endif

PokemonJournal_Text_SpecialFeatureKoga::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiter\n"
	.string "Koga aus Fuchsania City!\p"
	.string "Man sagt, dass Koga fundiertes Wissen\n"
	.string "auf dem Gebiet der Medizin besitzt.\l"
	.string "Er stellt seine eigene Medizin her, um\l"
	.string "seine Pokémon zu heilen.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"
#endif

PokemonJournal_Text_SpecialFeatureSabrina::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiterin\n"
	.string "Sabrina aus Saffronia City!\p"
	.string "Man sagt, dass Sabrina mit ihren\n"
	.string "Pokémon im Kampf wortlos kommunizieren\l"
	.string "kann.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"
#endif

PokemonJournal_Text_SpecialFeatureBlaine::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Arenaleiter\n"
	.string "Pyro von der Zinnoberinsel!\p"
	.string "Pyro nimmt seine Sonnenbrille angeblich\n"
	.string "nur ab, wenn er sich neue Quizfragen\l"
	.string "ausdenkt.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"
#endif

PokemonJournal_Text_SpecialFeatureLorelei::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Lorelei von den\n"
	.string "Top Vier!\p"
	.string "Die für ihren logischen, coolen und\n"
	.string "berechnenden Kampfstil bekannte\l"
	.string "Lorelei hat ein überraschendes\l"
	.string "Geheimnis.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"
#endif

PokemonJournal_Text_SpecialFeatureBruno::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Bruno von den\n"
	.string "Top Vier!\p"
	.string "Bruno hat sich offensichtlich den Top\n"
	.string "Vier angeschlossen, um sein Verlangen,\l"
	.string "nur gegen die besten Trainer zu\l"
	.string "kämpfen, zu stillen.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"
#endif

PokemonJournal_Text_SpecialFeatureAgatha::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Agathe von den\n"
	.string "Top Vier!\p"
	.string "In ihrer Jugend war Agathe eine Rivalin\n"
	.string "von Prof. Eich und hat mit ihm um die\l"
	.string "Vorherrschaft als Trainer gekämpft.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"
#endif

PokemonJournal_Text_SpecialFeatureLance::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Siegfried von\n"
	.string "den Top Vier!\p"
	.string "Man sagt, dass der Großvater von\n"
	.string "Siegfried der Älteste in einem\l"
	.string "berühmten Drachenklan ist.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"
#endif

PokemonJournal_Text_SpecialFeatureProfOak::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Prof. Eich, der\n"
	.string "Pokémon-Forscher!\p"
	.string "Berichten zufolge lebt Prof. Eich mit\n"
	.string "seinen Enkeln Sarah und {RIVAL}\l"
	.string "zusammen.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "PROF. OAK reportedly lives with his\n"
	.string "grandchildren DAISY and {RIVAL}.$"
#endif

PokemonJournal_Text_SpecialFeatureDaisyOak::
#if GERMAN
	.string "Dies ist ein Jahre altes Pokémon\n"
	.string "Journal…\p"
	.string "Pokémon Journal\n"
	.string "Wettkampf-Sonderbericht!\p"
	.string "Der Frühlingsmeister im\n"
	.string "Pokémon-Wettkampf ist Sarah Eich aus\l"
	.string "Alabastia!$"
#else
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"
#endif

PokemonJournal_Text_SpecialFeatureMrFuji::
#if GERMAN
	.string "Pokémon Journal\p"
	.string "Sonderreportage: Mr. Fuji vom\n"
	.string "Pokémon-Clubhaus!\p"
	.string "Redakteur: Der publikumsscheue Mr. Fuji\n"
	.string "hat unsere Interviewanfragen\l"
	.string "zurückgewiesen.\p"
	.string "Er ist ein freundlicher Mann, der in\n"
	.string "Lavandia verehrt und respektiert wird.$"
#else
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
#endif
