gText_HowMayIServeYou::
#if GERMAN
	.string "Willkommen!\p"
	.string "Kann ich dir helfen?$"
#else
	.string "Welcome!\p"
	.string "How may I serve you?$"
#endif

gText_PleaseComeAgain::
#if GERMAN
	.string "Bitte komm bald wieder!$"
#else
	.string "Please come again!$"
#endif

gText_PlayerWhatCanIDoForYou::
#if GERMAN
	.string "{PLAYER}{KUN}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"
#else
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"
#endif
