@ Crystal-accurate phone dialogue for HnS rematch trainers
@ Greetings from Crystal callee/caller files prepended to each text

@ Joey - Knirps, Route 30
MatchCall_HNS_Joey_General1::
#if GERMAN
	.string "Yo, {PLAYER}! Wie geht es dir?\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Mein {STR_VAR_3} ist nicht zu\n"
	.string "halten, wie immer.\p"
	.string "Es ist mein Ein und Alles. Ich werde\n"
	.string "mit ihm ein toller Trainer sein!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "How're you doing?\p"
	.string "How are your POKéMON doing?\p"
	.string "My {STR_VAR_3}'s raring to go,\n"
	.string "just like always.\p"
	.string "It's the only one I have.\n"
	.string "I'm going to become a great\l"
	.string "trainer with it!$"
#endif

MatchCall_HNS_Joey_General2::
#if GERMAN
	.string "Yo, {PLAYER}! Hast du Zeit?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "entschlossener aus!\p"
	.string "Ich bezweifle, dass du auch so ein\n"
	.string "cooles Pokémon in deinem Team hast!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "Got a minute?\p"
	.string "My {STR_VAR_3}'s looking\n"
	.string "sharper than before!\p"
	.string "I doubt there's a POKéMON\n"
	.string "as cool as this guy in\l"
	.string "your party!$"
#endif

MatchCall_HNS_Joey_General3::
#if GERMAN
	.string "Yo, {PLAYER}! Wie geht es dir?\p"
	.string "Ich experimentiere gerade mit den\n"
	.string "Attacken von {STR_VAR_3}, um eine\l"
	.string "Strategie zu finden.\p"
	.string "Finde ich eine gute, dann müssen\n"
	.string "wir kämpfen!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "How're you doing?\p"
	.string "I'm checking out\n"
	.string "{STR_VAR_3}'s moves and\l"
	.string "devising some strategies.\p"
	.string "When I come up with a good\n"
	.string "one, let's battle!$"
#endif

MatchCall_HNS_Joey_Battle::
#if GERMAN
	.string "Yo, {PLAYER}!\p"
	.string "Treffen wir uns für einen Kampf!\p"
	.string "Ich verspreche, es wird anders!$"
#else
	.string "Yo, {PLAYER}!\p"
	.string "Let's get together and\n"
	.string "battle!\p"
	.string "I promise things will be\n"
	.string "different!$"
#endif

@ Wade - Käfersammler, Route 31
MatchCall_HNS_Wade_General1::
#if GERMAN
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Meine Pokémon haben zu viel\n"
	.string "Energie.\p"
	.string "Das ist ein Problem.\p"
	.string "Von all meinen Pokémon ist\n"
	.string "{STR_VAR_3} am schwierigsten.\p"
	.string "Mit ihm zu arbeiten ist ermüdend.$"
#else
	.string "{PLAYER}, howdy!\p"
	.string "How are your POKéMON doing?\p"
	.string "My POKéMON have too much\n"
	.string "energy to burn.\p"
	.string "It gets to be a problem.\p"
	.string "Of all my POKéMON,\n"
	.string "{STR_VAR_3} is the hardest\l"
	.string "to handle.\p"
	.string "Working with it is\n"
	.string "exhausting.$"
#endif

MatchCall_HNS_Wade_General2::
#if GERMAN
	.string "{PLAYER}, alles senkrecht? Schön\n"
	.string "heute, oder?\p"
	.string "Wachsen deine Pokémon?\p"
	.string "Meine Pokémon wachsen mir zu\n"
	.string "schnell. Es ist überwältigend!\p"
	.string "{STR_VAR_3} wächst besonders\n"
	.string "schnell.\p"
	.string "Ich denke, es wird stark.$"
#else
	.string "{PLAYER}, howdy!\n"
	.string "Isn't it nice out?\p"
	.string "Are your POKéMON growing?\p"
	.string "My POKéMON are growing a\n"
	.string "bit too quickly for me.\l"
	.string "It's overwhelming!\p"
	.string "{STR_VAR_3}'s growing\n"
	.string "especially quickly.\p"
	.string "I think it'll get tough.$"
#endif

MatchCall_HNS_Wade_General3::
#if GERMAN
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Yo, wir haben ein wildes {STR_VAR_3} mit\n"
	.string "nur einem Schlag besiegt.\p"
	.string "Es ging so hart zu Boden, dass ich\n"
	.string "fast schon Mitleid hatte.$"
#else
	.string "{PLAYER}, howdy!\p"
	.string "Oh yeah, we KO'd a wild\n"
	.string "{STR_VAR_3} with one hit\l"
	.string "a while back.\p"
	.string "It went down so easily,\n"
	.string "I felt a little sorry for\l"
	.string "the poor thing.$"
#endif

MatchCall_HNS_Wade_FoundItem::
#if GERMAN
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Ich habe alle möglichen Beeren\n"
	.string "gefunden.\p"
	.string "Wenn du willst, teile ich mit dir.\p"
	.string "Ich warte auf\n"
	.string "Route 31.$"
#else
	.string "{PLAYER}, howdy!\p"
	.string "I found all kinds of\n"
	.string "BERRIES.\p"
	.string "If you want, I'll share\n"
	.string "some with you.\p"
	.string "I'll be waiting on\n"
	.string "ROUTE 31.$"
#endif

MatchCall_HNS_Wade_Battle::
#if GERMAN
	.string "{PLAYER}, alles senkrecht?\p"
	.string "Lust auf einen Pokémon-Kampf?\p"
	.string "Es wird nicht so wie das letzte Mal!$"
#else
	.string "{PLAYER}, howdy!\p"
	.string "Do you feel like a POKéMON\n"
	.string "battle?\p"
	.string "It won't be like last\n"
	.string "time!$"
#endif

@ Ralph - Angler, Route 32
MatchCall_HNS_Ralph_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s Angeln?\p"
	.string "Versorgst du deine Pokémon auch\n"
	.string "gut?\p"
	.string "Behandle sie gut, sie sind deine\n"
	.string "Kameraden!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "How's the fishing?\p"
	.string "Are you taking good care of\n"
	.string "your POKéMON?\p"
	.string "You have to be good to\n"
	.string "your partners!$"
#endif

MatchCall_HNS_Ralph_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich habe mehr Zeit mit meinem {STR_VAR_3}\n"
	.string "verbracht, als mit meinen Kindern.\p"
	.string "Das ist in der Tat schade.$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I've been spending more\n"
	.string "time with my {STR_VAR_3}\l"
	.string "than I have with my kids.\p"
	.string "That's a bit sad,\n"
	.string "actually.$"
#endif

MatchCall_HNS_Ralph_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hör dir das an!\p"
	.string "Ich besiegte ein wildes\n"
	.string "{STR_VAR_3}.\p"
	.string "Ich erzählte es meinem Sohn, aber er\n"
	.string "sagte, er könne das auch leicht tun.\p"
	.string "Er ist sehr aufsässig geworden…$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "Listen to this!\p"
	.string "I just beat a wild\n"
	.string "{STR_VAR_3}.\p"
	.string "I told my kid, but he\n"
	.string "scoffed that he could do\l"
	.string "the same thing easily.\p"
	.string "Boy, has he gotten\n"
	.string "cocky…$"
#endif

MatchCall_HNS_Ralph_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Liz - Picknicker, Route 32
MatchCall_HNS_Liz_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Ich hatte etwas Zeit, also hab ich dich\l"
	.string "angerufen.\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Ich bringe mein {STR_VAR_3} jeden Tag ins\n"
	.string "Pokémon Center in Violet,\p"
	.string "also geht’s ihm\n"
	.string "fantastisch!\p"
	.string "Die Rezeptionistin ist eine\n"
	.string "Freundin!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "I had some time, so I\l"
	.string "called you.\p"
	.string "So anyway, how are your\n"
	.string "POKéMON?\p"
	.string "Me, I take my {STR_VAR_3}\n"
	.string "to the POKéMON CENTER in\l"
	.string "VIOLET every day,\p"
	.string "so it's doing just\n"
	.string "fantastic!\p"
	.string "I'm friends with the\n"
	.string "receptionist!$"
#endif

MatchCall_HNS_Liz_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Du musst dir das anhören.\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "bezaubernd!\p"
	.string "Es kuschelt sich ständig an mich!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "You have to hear this.\p"
	.string "My {STR_VAR_3} is so\n"
	.string "adorable!\p"
	.string "It always wants to\n"
	.string "nuzzle me!$"
#endif

MatchCall_HNS_Liz_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hör mal, hör mal!\p"
	.string "Denkst du nicht auch, dass Falk, der\n"
	.string "Arenaleiter von Viola City, cool und\l"
	.string "schön ist?\p"
	.string "Aber, man sagt, dass sein Vater, der im\n"
	.string "Freien trainiert, noch cooler und\l"
	.string "schöner als Falk ist.\p"
	.string "Ich würde ihn gerne kennen lernen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "Listen, listen!\p"
	.string "Don't you think FALKNER of\n"
	.string "VIOLET GYM is cool and\l"
	.string "handsome?\p"
	.string "But they say his dad, who's\n"
	.string "out training on the road,\l"
	.string "is even more cool and\l"
	.string "handsome than FALKNER.\p"
	.string "I wish I could meet him!$"
#endif

MatchCall_HNS_Liz_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Anthony - Wanderer, Route 33
MatchCall_HNS_Anthony_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Sind deine Pokémon immer noch wild?\p"
	.string "Mein {STR_VAR_3} und ich, wir\n"
	.string "strotzen vor Energie.\p"
	.string "Wir wandern täglich in den Bergen,\n"
	.string "um so Energie abzubauen.$"
#else
	.string "Hey there, {PLAYER}!\p"
	.string "Are your POKéMON as feisty\n"
	.string "as ever?\p"
	.string "My {STR_VAR_3} and me--we\n"
	.string "have energy to burn.\p"
	.string "We hike up mountains every\n"
	.string "day to work out all our\l"
	.string "energy.$"
#endif

MatchCall_HNS_Anthony_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Neulich hab ich zugesehen, wie mein\n"
	.string "{STR_VAR_3} Beeren gegessen hat.\p"
	.string "Es sah so aus, als würde es das Essen\n"
	.string "genießen, also hab ich auch probiert.\p"
	.string "Ich weiß nicht, ob Menschen das essen\n"
	.string "sollten, aber es war lecker!$"
#else
	.string "Hey there, {PLAYER}!\p"
	.string "The other day, I was\n"
	.string "watching my {STR_VAR_3}\l"
	.string "eat some BERRIES.\p"
	.string "It looked like it was\n"
	.string "enjoying its meal, so I\l"
	.string "decided to try some.\p"
	.string "I'm not sure if people\n"
	.string "should eat that stuff, but\l"
	.string "it was delicious!$"
#endif

MatchCall_HNS_Anthony_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "In letzter Zeit sind mir viele wilde\n"
	.string "{STR_VAR_3} begegnet.\p"
	.string "Sie sind kein großes Problem.$"
#else
	.string "Hey there, {PLAYER}!\p"
	.string "Lately, I've been running\n"
	.string "across wild {STR_VAR_3}\l"
	.string "quite often.\p"
	.string "They're easily taken\n"
	.string "care of.$"
#endif

MatchCall_HNS_Anthony_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey there, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Todd - Camper, Route 34
MatchCall_HNS_Todd_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Wie ziehst du deine\n"
	.string "Pokémon groß?\p"
	.string "Ich mach so allerlei, wie sie in die\n"
	.string "Kinderkrippe geben und\p"
	.string "sie mit Items\n"
	.string "abhärten.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "What's up?\p"
	.string "How do you raise your\n"
	.string "POKéMON?\p"
	.string "I do all sorts of things,\n"
	.string "like leaving them in\l"
	.string "DAY-CARE and\p"
	.string "toughening them up with\n"
	.string "items.$"
#endif

MatchCall_HNS_Todd_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Mein {STR_VAR_3} wird mir immer\n"
	.string "ähnlicher.\p"
	.string "Es wird immer niedlicher!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "What's up?\p"
	.string "My {STR_VAR_3} is looking\n"
	.string "more and more like me.\p"
	.string "It's getting cuter!$"
#endif

MatchCall_HNS_Todd_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Was geht?\p"
	.string "Und, pass auf!\p"
	.string "Jetzt besiegen wir\n"
	.string "{STR_VAR_3} mühelos.\p"
	.string "Ich sollte die\n"
	.string "Rosalia-Arena fordern.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "What's up?\p"
	.string "And, you know?\p"
	.string "Now we can KO {STR_VAR_3}\n"
	.string "easily.\p"
	.string "I should challenge the\n"
	.string "GOLDENROD GYM.$"
#endif

MatchCall_HNS_Todd_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Gina - Picknicker, Route 34
MatchCall_HNS_Gina_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Sind deine Pokémon noch immer\n"
	.string "stark?\p"
	.string "Ich trainiere mein {STR_VAR_3}\n"
	.string "täglich.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "How are you?\p"
	.string "Are your POKéMON still\n"
	.string "tough?\p"
	.string "I train every day\n"
	.string "with {STR_VAR_3}.$"
#endif

MatchCall_HNS_Gina_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Mein {STR_VAR_3} und ich stimmen\n"
	.string "uns immer besser aufeinander ab.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "How are you?\p"
	.string "My {STR_VAR_3} and I are\n"
	.string "getting more in sync with\l"
	.string "each other.$"
#endif

MatchCall_HNS_Gina_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Wie geht’s dir?\p"
	.string "Wir kämpften gegen ein wildes\n"
	.string "{STR_VAR_3} und gewannen knapp.\p"
	.string "Wir kommen jetzt in Schwung!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "How are you?\p"
	.string "We battled a wild\n"
	.string "{STR_VAR_3} and managed\l"
	.string "to drop it in a close\l"
	.string "match.\p"
	.string "We're getting into the\n"
	.string "groove!$"
#endif

MatchCall_HNS_Gina_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Irwin - Jongleur, Route 35
MatchCall_HNS_Irwin_General1::
#if GERMAN
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab neulich den\n"
	.string "erstaunlichsten Kampf gesehen!\p"
	.string "Ich wünschte, ich könnte so\n"
	.string "kämpfen.\p"
	.string "Ach halt, ich kann! Ich\n"
	.string "brauch nur jemanden zum Kämpfen!$"
#else
	.string "Uh, hello, {PLAYER}?\n"
	.string "It's your pal, IRWIN!\p"
	.string "I saw the most amazing\n"
	.string "battle the other day!\p"
	.string "I wish I could battle\n"
	.string "like that.\p"
	.string "Oh wait, I can! I just\n"
	.string "need someone to battle!$"
#endif

MatchCall_HNS_Irwin_General2::
#if GERMAN
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Hehe, ich habe gleich angerufen!\p"
	.string "Ich denke, wir werden sehr gute\n"
	.string "Kameraden!$"
#else
	.string "Uh, hello, {PLAYER}?\n"
	.string "It's your pal, IRWIN!\p"
	.string "Hehe, I called right away!\p"
	.string "I think we can be good\n"
	.string "friends!$"
#endif

MatchCall_HNS_Irwin_General3::
#if GERMAN
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Als ich deine Geschichten hörte,\n"
	.string "weinte meine Seele!\p"
	.string "Wirklich!$"
#else
	.string "Uh, hello, {PLAYER}?\n"
	.string "It's your pal, IRWIN!\p"
	.string "Hearing about your\n"
	.string "escapades rocks my soul!\p"
	.string "It sure does!$"
#endif

MatchCall_HNS_Irwin_Battle::
#if GERMAN
	.string "Äh, hallo, {PLAYER}?\n"
	.string "Hier ist dein Kumpel Erich!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Uh, hello, {PLAYER}?\n"
	.string "It's your pal, IRWIN!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Arnie - Käfersammler, Route 35
MatchCall_HNS_Arnie_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Ich wette, deine Pokémon sind viel\n"
	.string "stärker als zuvor.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "How's it going?\p"
	.string "I bet your POKéMON are a\n"
	.string "lot stronger than before.$"
#endif

MatchCall_HNS_Arnie_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Mein {STR_VAR_3} ist immer dabei!\p"
	.string "Es ist so süß! Ich liebe es!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "How's it going?\p"
	.string "I'm always with my\n"
	.string "{STR_VAR_3}!\p"
	.string "It's so cute!\n"
	.string "I just love it!$"
#endif

MatchCall_HNS_Arnie_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Wie läuft’s?\p"
	.string "Um mal das Thema zu wechseln, ich hab\n"
	.string "dieses {STR_VAR_3} zum ersten Mal\l"
	.string "gesehen.\p"
	.string "Es war leicht zu besiegen,\n"
	.string "ehrlich gesagt.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "How's it going?\p"
	.string "Changing the topic here,\n"
	.string "I saw this {STR_VAR_3}\l"
	.string "for the first time.\p"
	.string "It was easy to beat,\n"
	.string "actually.$"
#endif

MatchCall_HNS_Arnie_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Alan - Schulkind, Route 36
MatchCall_HNS_Alan_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "{PLAYER}, trainierst du deine\n"
	.string "Pokémon richtig?\p"
	.string "Ich habe gelesen, dass man die Pokémon,\n"
	.string "die man fängt mit Liebe und Umsicht\l"
	.string "trainieren soll.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ALAN!\p"
	.string "{PLAYER}, are you raising\n"
	.string "your POKéMON properly?\p"
	.string "I read in a book that you\n"
	.string "should raise any POKéMON\l"
	.string "you catch with love and\l"
	.string "care.$"
#endif

MatchCall_HNS_Alan_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Mein {STR_VAR_3} wird immer\n"
	.string "stärker, womit ich gerechnet habe!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ALAN!\p"
	.string "My {STR_VAR_3}'s getting\n"
	.string "stronger, exactly as I\l"
	.string "calculated!$"
#endif

MatchCall_HNS_Alan_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Apropos, wir besiegten neulich ein\n"
	.string "wildes {STR_VAR_3}.\p"
	.string "Die richtige Vorbereitung lohnt!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ALAN!\p"
	.string "By the way, we knocked\n"
	.string "out a wild {STR_VAR_3}\l"
	.string "just the other day.\p"
	.string "Studying up in advance\n"
	.string "worked!$"
#endif

MatchCall_HNS_Alan_FoundItem::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Hehehe, ich fand etwas Schönes!\p"
	.string "Es gehört dir!\p"
	.string "Wieso kommst du nicht zu\n"
	.string "Route 36 und holst es ab?$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ALAN!\p"
	.string "Hehehe, I picked up\n"
	.string "something nice!\p"
	.string "You can have it!\p"
	.string "Why don't you come to\n"
	.string "ROUTE 36 and pick it up?$"
#endif

MatchCall_HNS_Alan_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Holger!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ALAN!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Dana - Göre, Route 38
MatchCall_HNS_Dana_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} strotzt vor Energie, das\n"
	.string "macht mir ein wenig Angst.\p"
	.string "Wie geht es deinen Pokémon?$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's DANA!\p"
	.string "My {STR_VAR_3} is so full\n"
	.string "of energy, it's a little\l"
	.string "scary.\p"
	.string "How are your POKéMON\n"
	.string "doing?$"
#endif

MatchCall_HNS_Dana_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Mein {STR_VAR_3} wird immer\n"
	.string "süßer!\p"
	.string "Ich habe schon viele Fotos\n"
	.string "gemacht!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's DANA!\p"
	.string "My {STR_VAR_3} is getting\n"
	.string "prettier!\p"
	.string "I've been taking photos\n"
	.string "galore!$"
#endif

MatchCall_HNS_Dana_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Im Handumdrehen war das wilde\n"
	.string "{STR_VAR_3} K.O.\p"
	.string "Das kommt bestimmt davon, dass du\n"
	.string "mir Kampftipps gegeben hast.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's DANA!\p"
	.string "It took only an instant to\n"
	.string "KO a wild {STR_VAR_3}.\p"
	.string "It must be because you\n"
	.string "gave me some battling tips\l"
	.string "last time.$"
#endif

MatchCall_HNS_Dana_FoundItem::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Weißt du was?\n"
	.string "Ich hab ein tolles Geschenk!\p"
	.string "Wie versprochen, gehört es dir!\n"
	.string "Ich bin sicher, es gefällt dir.\p"
	.string "Komm es dir holen! Ich warte\n"
	.string "auf Route 38!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's DANA!\p"
	.string "You know what?\n"
	.string "I got a good gift!\p"
	.string "As I promised, it's yours!\n"
	.string "I'm sure you'd like it.\p"
	.string "Come get it! I'm waiting\n"
	.string "on ROUTE 38!$"
#endif

MatchCall_HNS_Dana_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Rosemarie!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's DANA!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Chad - Schulkind, Route 38
MatchCall_HNS_Chad_General1::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Du kennst Prof. Eich, also geht’s deinen\n"
	.string "Pokémon natürlich gut!\p"
	.string "Meinen Pokémon geht’s auch\n"
	.string "gut.\p"
	.string "Aber ich versuche ja auch, ein\n"
	.string "Pokémon-Professor zu werden.$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's CHAD!\p"
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "You know PROF. OAK, so of\n"
	.string "course your POKéMON are\l"
	.string "fine!\p"
	.string "My POKéMON are doing well\n"
	.string "too.\p"
	.string "But then, I am trying to\n"
	.string "become a POKéMON\l"
	.string "professor.$"
#endif

MatchCall_HNS_Chad_General2::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich beobachte neuerdings\n"
	.string "wilde {STR_VAR_3}.\p"
	.string "Ich lerne allerlei neue Dinge durch\n"
	.string "meine Beobachtungen.\p"
	.string "Ich wünschte, ich könnte bald ein\n"
	.string "Pokémon-Forscher wie Prof. Eich werden.$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's CHAD!\p"
	.string "I recently began observing\n"
	.string "wild {STR_VAR_3}.\p"
	.string "I've been learning all\n"
	.string "sorts of new things\l"
	.string "through my observations.\p"
	.string "I wish I could become a\n"
	.string "POKéMON researcher like\l"
	.string "PROF. OAK soon.$"
#endif

MatchCall_HNS_Chad_General3::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich lerne fleißig, damit Prof. Eich mich\n"
	.string "zu seinem Assistenten macht!$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's CHAD!\p"
	.string "I'm going to study hard\n"
	.string "so PROF. OAK will make\l"
	.string "me his assistant!$"
#endif

MatchCall_HNS_Chad_Battle::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Lutz!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's CHAD!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Derek - Pokéfan M, Route 39
MatchCall_HNS_Derek_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Das musst du hören!\p"
	.string "Mein liebenswürdiges {STR_VAR_3}\n"
	.string "sah mich an und lachte!\p"
	.string "Es muss daran liegen, weil unsere\n"
	.string "Herzen im Einklang schlagen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's DEREK!\p"
	.string "You have to hear this!\p"
	.string "My lovable {STR_VAR_3}\n"
	.string "looked at me and grinned!\p"
	.string "It must be because our\n"
	.string "hearts beat together as\l"
	.string "one!$"
#endif

MatchCall_HNS_Derek_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Hör genau zu.\p"
	.string "Mein {STR_VAR_3} lächelt fröhlich, wenn\n"
	.string "ich es in die Wangen zwicke.\p"
	.string "Aber es lacht nur bei mir.\p"
	.string "Ich bin etwas Besonderes.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's DEREK!\p"
	.string "Listen to this.\p"
	.string "My {STR_VAR_3} grins\n"
	.string "happily when I pinch its\l"
	.string "cheek.\p"
	.string "But it never grins for\n"
	.string "anyone else.\p"
	.string "I must be special.$"
#endif

MatchCall_HNS_Derek_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Wie geht es deinem Pikachu?\p"
	.string "Lass uns zusammenkommen und mit\n"
	.string "unseren Pikachu angeben!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's DEREK!\p"
	.string "How is your PIKACHU\n"
	.string "doing?\p"
	.string "Let's get together and\n"
	.string "brag about our PIKACHU!$"
#endif

MatchCall_HNS_Derek_FoundItem::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich möchte, dass du dieses Nugget\n"
	.string "bekommst.\p"
	.string "Ich bin auf Route 39.\n"
	.string "Komm es dir holen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's DEREK!\p"
	.string "I'd like you to have a\n"
	.string "NUGGET.\p"
	.string "I'm on ROUTE 39.\n"
	.string "Come pick it up!$"
#endif

MatchCall_HNS_Derek_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Söncke!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's DEREK!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Tully - Angler, Route 42
MatchCall_HNS_Tully_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Wie läuft es mit deinem Abenteuer?\p"
	.string "Ich kann mich über das Angeln\n"
	.string "nicht beschweren!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's TULLY!\p"
	.string "How's your trip coming\n"
	.string "along?\p"
	.string "I can't complain about\n"
	.string "my fishing!$"
#endif

MatchCall_HNS_Tully_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Mein {STR_VAR_3} ist erneut\n"
	.string "gewachsen.\p"
	.string "Es war groß, als ich es fing, aber\n"
	.string "jetzt ist es noch größer.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's TULLY!\p"
	.string "My {STR_VAR_3} has grown\n"
	.string "again.\p"
	.string "It was only about so big\n"
	.string "when I caught it, but now\l"
	.string "it's way bigger.$"
#endif

MatchCall_HNS_Tully_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Oh yo, ich schlug ein wildes\n"
	.string "{STR_VAR_3} K.O.\p"
	.string "Es war riesig, ungefähr soo groß.\p"
	.string "He, ich glaube, man kann das am\n"
	.string "Telefon nicht beschreiben…$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's TULLY!\p"
	.string "Oh yeah, I KO'd a wild\n"
	.string "{STR_VAR_3}.\p"
	.string "It was huge, like this big\n"
	.string "even.\p"
	.string "Heh, I guess you can't\n"
	.string "tell over the phone…$"
#endif

MatchCall_HNS_Tully_FoundItem::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich fand etwas Kleines am Ufer.\p"
	.string "Wie versprochen, es gehört dir.\p"
	.string "Ich warte auf\n"
	.string "Route 42.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's TULLY!\p"
	.string "I picked up a good little\n"
	.string "thing at the water's edge.\p"
	.string "Like I promised, it's\n"
	.string "yours.\p"
	.string "I'll be waiting on\n"
	.string "ROUTE 42.$"
#endif

MatchCall_HNS_Tully_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Amadeus!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's TULLY!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Brent - Pokémaniac, Route 43
MatchCall_HNS_Brent_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ach ja, ich hab dich neulich aus einem\n"
	.string "Pokémon Center kommen sehen.\p"
	.string "Du heilst deine Pokémon regelmäßig,\n"
	.string "oder?\l"
	.string "Ich bin beeindruckt.\p"
	.string "Heh, mein {STR_VAR_3} ist so zäh, es muss\n"
	.string "nicht oft zu Pokémon Centern gehen.\l"
	.string "Heheh!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BRENT!\p"
	.string "Oh yeah, I saw you coming\n"
	.string "out of a POKéMON CENTER\l"
	.string "the other day.\p"
	.string "You heal your POKéMON\n"
	.string "regularly, don't you?\l"
	.string "I'm impressed.\p"
	.string "Heh, my {STR_VAR_3} is\n"
	.string "so tough, it doesn't need\l"
	.string "to go to POKéMON CENTERS\l"
	.string "often. Heheh!$"
#endif

MatchCall_HNS_Brent_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Oh yo, ich habe vor geraumer Zeit ein\n"
	.string "sehr seltenes Pokémon in einem Tausch\l"
	.string "erhalten.\p"
	.string "Möchtest du wissen welches?\p"
	.string "Hehe, das verrate ich dir nicht!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BRENT!\p"
	.string "Oh yeah, I got an\n"
	.string "extremely rare POKéMON in\l"
	.string "a trade a while back.\p"
	.string "Do you want to know what\n"
	.string "it is?\p"
	.string "Hehe, I'm keeping it a\n"
	.string "secret!$"
#endif

MatchCall_HNS_Brent_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Wusstest du…?\p"
	.string "Bill kommt ursprünglich aus Dukatia\n"
	.string "City.\p"
	.string "Offenbar ist Bill kein wirklich\n"
	.string "guter Kämpfer.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BRENT!\p"
	.string "Did you know…?\p"
	.string "BILL's originally from\n"
	.string "GOLDENROD.\p"
	.string "Evidently, BILL isn't very\n"
	.string "good at battling.$"
#endif

MatchCall_HNS_Brent_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Taro!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BRENT!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Tiffany - Picknicker, Route 43
MatchCall_HNS_Tiffany_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Sind deine Pokémon in Ordnung?\p"
	.string "Ich hoffe, du bringst sie täglich in\n"
	.string "ein Pokémon-Center.\p"
	.string "Übertreib es nicht.\p"
	.string "Mein {STR_VAR_3} ist süß und lebhaft, weil\n"
	.string "ich es täglich in ein Pokémon-Center\l"
	.string "bringe.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TIFFANY!\p"
	.string "Are your POKéMON doing\n"
	.string "well?\p"
	.string "I hope you take them to a\n"
	.string "POKéMON CENTER every day.\p"
	.string "Don't push them too hard.\p"
	.string "My {STR_VAR_3} is cute and\n"
	.string "lively precisely because I\l"
	.string "take it to a POKéMON\l"
	.string "CENTER every day.$"
#endif

MatchCall_HNS_Tiffany_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "bezaubernd, nicht wahr?\p"
	.string "Ich schlafe immer mit ihm - es ist\n"
	.string "so weich und warm!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TIFFANY!\p"
	.string "My {STR_VAR_3}'s adorable,\n"
	.string "don't you think so?\p"
	.string "I always sleep with it--\n"
	.string "it's so fluffy and warm!$"
#endif

MatchCall_HNS_Tiffany_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Oh, wir mussten vor kurzem gegen\n"
	.string "ein wildes {STR_VAR_3} kämpfen…\p"
	.string "Mein Piepi war fast besiegt!\p"
	.string "Schrecklich, oder? Ich hasse diese\n"
	.string "{STR_VAR_3}!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TIFFANY!\p"
	.string "Oh, and we had to battle\n"
	.string "a wild {STR_VAR_3} a\l"
	.string "while ago…\p"
	.string "My CLEFAIRY came close to\n"
	.string "fainting!\p"
	.string "Isn't that awful?\n"
	.string "I hate those nasty\l"
	.string "{STR_VAR_3}!$"
#endif

MatchCall_HNS_Tiffany_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ilona!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TIFFANY!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Vance - Vogelfänger, Route 44
MatchCall_HNS_Vance_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Geht es dir und deinen Pokémon\n"
	.string "gut?\p"
	.string "Mein {STR_VAR_3} sieht aus,\n"
	.string "als würde es stark genug\p"
	.string "um es mit den legendären\n"
	.string "Vogel-Pokémon aufzunehmen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's VANCE!\p"
	.string "Are you and your POKéMON\n"
	.string "fine?\p"
	.string "My {STR_VAR_3} looks like\n"
	.string "it will get tough enough\p"
	.string "to face and beat the\n"
	.string "legendary bird POKéMON!$"
#endif

MatchCall_HNS_Vance_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Mein {STR_VAR_3} wurde stärker.\p"
	.string "Wir sind abgehoben!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's VANCE!\p"
	.string "My {STR_VAR_3}'s become\n"
	.string "tougher.\p"
	.string "We've achieved liftoff!$"
#endif

MatchCall_HNS_Vance_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Wir können {STR_VAR_3} leicht\n"
	.string "besiegen!\p"
	.string "…Huh? Du auch? Das ist doch toll?$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's VANCE!\p"
	.string "We can easily beat\n"
	.string "{STR_VAR_3}!\p"
	.string "…Huh? You too?\n"
	.string "Isn't that great?$"
#endif

MatchCall_HNS_Vance_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Arno!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's VANCE!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Wilton - Angler, Route 44
MatchCall_HNS_Wilton_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Sind deine Pokémon gewachsen?\p"
	.string "Mein {STR_VAR_3} ist ein bisschen\n"
	.string "gewachsen.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's WILTON!\p"
	.string "Have your POKéMON grown\n"
	.string "any?\p"
	.string "My {STR_VAR_3} has grown\n"
	.string "quite a bit.$"
#endif

MatchCall_HNS_Wilton_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Mein {STR_VAR_3} ist sehr\n"
	.string "gewachsen!\p"
	.string "Meine Angelfähigkeiten haben sich\n"
	.string "auch verbessert!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's WILTON!\p"
	.string "My {STR_VAR_3}'s grown\n"
	.string "impressive!\p"
	.string "My fishing skills have\n"
	.string "improved too!$"
#endif

MatchCall_HNS_Wilton_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Wir besiegten ein wildes\n"
	.string "{STR_VAR_3}…\p"
	.string "Du weißt, dass mir Angeln mehr Spaß\n"
	.string "macht, als wilde Pokémon zu besiegen.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's WILTON!\p"
	.string "We beat a wild\n"
	.string "{STR_VAR_3}…\p"
	.string "You know, I have more fun\n"
	.string "fishing than beating wild\l"
	.string "POKéMON.$"
#endif

MatchCall_HNS_Wilton_FoundItem::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich habe beim Angeln ein Item\n"
	.string "gefunden.\p"
	.string "Komm es dir holen auf\n"
	.string "Route 44.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's WILTON!\p"
	.string "I snagged an item while\n"
	.string "fishing.\p"
	.string "Come pick it up on\n"
	.string "ROUTE 44.$"
#endif

MatchCall_HNS_Wilton_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alfried!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's WILTON!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Kenji - Schwarzgurt, Route 45
MatchCall_HNS_Kenji_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "{PLAYER}! Schönes Wetter, oder?$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p"
	.string "{PLAYER}! Beautiful\n"
	.string "weather, hey?$"
#endif

MatchCall_HNS_Kenji_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Bist du noch auf Reisen?\p"
	.string "Ich bin meinem Training treu\n"
	.string "geblieben.\p"
	.string "Oooooaaarrrgh!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p"
	.string "Are you still on your\n"
	.string "journey?\p"
	.string "I remain dedicated to my\n"
	.string "training.\p"
	.string "Oooooaaarrrgh!$"
#endif

MatchCall_HNS_Kenji_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich trainiere gerade.\p"
	.string "Entschuldige, aber rufe mich\n"
	.string "später noch mal an.\p"
	.string "Oooooaaarrrgh!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p"
	.string "I'm in training now.\p"
	.string "I apologize, but call me\n"
	.string "back another time.\p"
	.string "Oooooaaarrrgh!$"
#endif

MatchCall_HNS_Kenji_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich mach gerade Pause!\p"
	.string "Komm vorbei, wenn du Zeit hast!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p"
	.string "I'm taking a break!\p"
	.string "Why not drop by if you\n"
	.string "are free?$"
#endif

MatchCall_HNS_Kenji_FoundItem::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Timon!\p"
	.string "Ich mach gerade Pause vom\n"
	.string "Training.\p"
	.string "Ich hab was Gutes gefunden.\n"
	.string "Komm es dir holen, wenn du willst!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p"
	.string "I'm taking a break from\n"
	.string "training.\p"
	.string "I found something good.\n"
	.string "Come get it if you want!$"
#endif

@ Parry - Wanderer, Route 45
MatchCall_HNS_Parry_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Sehen deine Pokémon gut aus?\p"
	.string "Mein {STR_VAR_3} und ich, wir\n"
	.string "sehen hervorragend aus! Hahaha!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's PARRY!\p"
	.string "Are your POKéMON looking\n"
	.string "good?\p"
	.string "My {STR_VAR_3} and me--\n"
	.string "we're looking mighty\l"
	.string "dandy! Hahahah!$"
#endif

MatchCall_HNS_Parry_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Nichts kann es mit meinem\n"
	.string "{STR_VAR_3} aufnehmen.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's PARRY!\p"
	.string "Nothing can match my\n"
	.string "{STR_VAR_3} now.$"
#endif

MatchCall_HNS_Parry_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Ja, wir haben ein wildes\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Das war ok, aber ich wollte\n"
	.string "es eigentlich fangen…$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's PARRY!\p"
	.string "Yeah, we KO'd a wild\n"
	.string "{STR_VAR_3}!\p"
	.string "That was OK, but I wanted\n"
	.string "to get it…$"
#endif

MatchCall_HNS_Parry_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Günter!\p"
	.string "Du kämpfst wieder gegen mich,\n"
	.string "oder?$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's PARRY!\p"
	.string "You'll battle with me\n"
	.string "again, right?$"
#endif

@ Erin - Picknicker, Route 46
MatchCall_HNS_Erin_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Trainierst du deine Pokémon?\p"
	.string "Mein {STR_VAR_3} sieht\n"
	.string "gut aus!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ERIN!\p"
	.string "Are you raising your\n"
	.string "POKéMON?\p"
	.string "My {STR_VAR_3} is looking\n"
	.string "good!$"
#endif

MatchCall_HNS_Erin_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Mein {STR_VAR_3} ist viel\n"
	.string "stärker als zuvor!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ERIN!\p"
	.string "My {STR_VAR_3} is much\n"
	.string "stronger than before!$"
#endif

MatchCall_HNS_Erin_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Und, und… Ich habe gerade ein\n"
	.string "{STR_VAR_3} besiegt!\p"
	.string "Ich trainiere meine Pokémon\n"
	.string "intensiv!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ERIN!\p"
	.string "And, and… I just battled\n"
	.string "and beat {STR_VAR_3}!\p"
	.string "I've raised my POKéMON\n"
	.string "properly!$"
#endif

MatchCall_HNS_Erin_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Nanette!\p"
	.string "Ich arbeite hart an meinen\n"
	.string "Pokémon!\p"
	.string "Komme für einen Rückkampf zurück!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's ERIN!\p"
	.string "I'm working hard to raise\n"
	.string "my POKéMON!\p"
	.string "Come back for another\n"
	.string "battle!$"
#endif

@ Jack - Schulkind, National Park
MatchCall_HNS_Jack_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Wie geht’s deinen Pokémon\n"
	.string "so?\p"
	.string "Mein {STR_VAR_3} ist so\n"
	.string "neugierig, das wird zum Problem.\p"
	.string "Vielleicht ist es wie ich…$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JACK!\p"
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "My {STR_VAR_3} is so\n"
	.string "curious, it's a problem.\p"
	.string "Maybe it's like me…$"
#endif

MatchCall_HNS_Jack_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Die Intelligenz von meinem\n"
	.string "{STR_VAR_3} steigt und steigt.\p"
	.string "Es könnte intelligenter als deines\n"
	.string "sein!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JACK!\p"
	.string "My {STR_VAR_3}'s\n"
	.string "intelligence keeps rising.\p"
	.string "It might be smarter\n"
	.string "than yours!$"
#endif

MatchCall_HNS_Jack_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Hast du gewusst?\p"
	.string "Wenn es regnet, gibt es bestimmt\n"
	.string "auch Donner.\p"
	.string "Mein Kamerad erhielt einige gute Tipps.\n"
	.string "Wenn er sie mir sagt, rufe ich dich\l"
	.string "sofort an.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JACK!\p"
	.string "Did you know?\p"
	.string "When it's raining, THUNDER\n"
	.string "is sure to strike.\p"
	.string "My friend heard some great\n"
	.string "tips. When he tells me,\l"
	.string "I'll call right away and\l"
	.string "tell you.$"
#endif

MatchCall_HNS_Jack_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Julius!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JACK!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Beverly - Pokéfan F, National Park
MatchCall_HNS_Beverly_General1::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Sorgst du gut für deine Pokémon?\p"
	.string "Meinem {STR_VAR_3} geht es gut.\n"
	.string "Es frisst viel.$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's BEVERLY!\p"
	.string "Keeping your POKéMON\n"
	.string "happy?\p"
	.string "My {STR_VAR_3} is healthy.\n"
	.string "It eats a lot every day.$"
#endif

MatchCall_HNS_Beverly_General2::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich habe mein {STR_VAR_3} verschönert\n"
	.string "und es ist somit noch süßer als zuvor!$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's BEVERLY!\p"
	.string "I fancied up my\n"
	.string "{STR_VAR_3} and made it\l"
	.string "even cuter than before!$"
#endif

MatchCall_HNS_Beverly_General3::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Sind deine Pokémon in Top-Form?\p"
	.string "Lass uns mal wieder über Pokémon\n"
	.string "plaudern.$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's BEVERLY!\p"
	.string "Are your POKéMON in prime\n"
	.string "form?\p"
	.string "Let's chat about POKéMON\n"
	.string "again.$"
#endif

MatchCall_HNS_Beverly_FoundItem::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Mein Mann hat einige Nuggets.\p"
	.string "Wenn du möchtest, gebe ich dir einen\n"
	.string "dafür, dass du mir geholfen hast.\p"
	.string "Ich bin im Nationalpark.\n"
	.string "Komm bitte vorbei, wenn du kannst.$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's BEVERLY!\p"
	.string "My husband got some\n"
	.string "NUGGETS.\p"
	.string "If you'd like, you could\n"
	.string "have one as thanks for\l"
	.string "helping me out.\p"
	.string "I'll be at NATIONAL PARK.\n"
	.string "Please come see me when\l"
	.string "you can.$"
#endif

MatchCall_HNS_Beverly_Battle::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Irmgard!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hello, {PLAYER}!\n"
	.string "It's BEVERLY!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Huey - Matrose, Olivine Lighthouse
MatchCall_HNS_Huey_General1::
#if GERMAN
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wie geht es dir?$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "It's HUEY!\p"
	.string "How's it going?$"
#endif

MatchCall_HNS_Huey_General2::
#if GERMAN
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Wir müssen irgendwann wieder\n"
	.string "kämpfen.\p"
	.string "Ich werde dich herausfordern, bis ich\n"
	.string "gewinne, darauf kannst du wetten.$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "It's HUEY!\p"
	.string "We have to battle again\n"
	.string "sometime.\p"
	.string "You can bet I'm going to\n"
	.string "keep challenging you till\l"
	.string "I win.$"
#endif

MatchCall_HNS_Huey_Battle::
#if GERMAN
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Nepomuk!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "It's HUEY!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Gaven - Ass-Trainer M, Route 26
MatchCall_HNS_Gaven_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Wie geht es deinen Pokémon?\p"
	.string "Meinem {STR_VAR_3} geht es wie\n"
	.string "immer hervorragend.\p"
	.string "Lass uns am Ball bleiben und\n"
	.string "Pokémon-Champs werden!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's GAVEN!\p"
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "My {STR_VAR_3}'s doing as\n"
	.string "great as ever.\p"
	.string "Let's keep at it and\n"
	.string "become POKéMON CHAMPS!$"
#endif

MatchCall_HNS_Gaven_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Mein {STR_VAR_3} könnte stärker\n"
	.string "sein, als ich dachte.\p"
	.string "Ich bezweifle, dass ich je ein Pokémon\n"
	.string "sehe, das besser ist als meins.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's GAVEN!\p"
	.string "My {STR_VAR_3} might be\n"
	.string "greater than I imagined.\p"
	.string "I doubt I'll see a\n"
	.string "POKéMON that's better\l"
	.string "than mine.$"
#endif

MatchCall_HNS_Gaven_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich bin davon besessen, dich zu\n"
	.string "besiegen.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's GAVEN!\p"
	.string "I obsess over how to\n"
	.string "beat you.$"
#endif

MatchCall_HNS_Gaven_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Maik!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's GAVEN!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Beth - Ass-Trainer F, Route 26
MatchCall_HNS_Beth_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Gehörst du zu den Menschen, die\n"
	.string "oft in Pokémon-Center gehen?\p"
	.string "Ich gehe täglich. Sich um das\n"
	.string "Wohlergehen seiner Pokémon zu kümmern,\l"
	.string "gehört zu den Grundlagen eines Pokémon\l"
	.string "-Trainers.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's BETH!\p"
	.string "Are you the kind of person\n"
	.string "who goes to POKéMON\l"
	.string "CENTERS often?\p"
	.string "I go every day. Watching\n"
	.string "out for the health of your\l"
	.string "POKéMON is a basic part of\l"
	.string "being a POKéMON trainer.$"
#endif

MatchCall_HNS_Beth_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Erinnerst du dich an mein süßes\n"
	.string "{STR_VAR_3}?\p"
	.string "{STR_VAR_3} rennt sehr schnell.\p"
	.string "Es ist wahrlich berauschend auf\n"
	.string "ihm zu reiten, wenn es loslegt.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's BETH!\p"
	.string "Do you remember my sweet\n"
	.string "{STR_VAR_3}?\p"
	.string "{STR_VAR_3} runs very\n"
	.string "fast.\p"
	.string "It's exhilarating to ride\n"
	.string "on its back when it really\l"
	.string "gets going.$"
#endif

MatchCall_HNS_Beth_General3::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Lass uns wieder mal kämpfen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's BETH!\p"
	.string "Let's battle again\n"
	.string "sometime!$"
#endif

MatchCall_HNS_Beth_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Dea!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's BETH!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Jose - Vogelfänger, Route 27
MatchCall_HNS_Jose_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Geht es deinen Pokémon gut?\p"
	.string "Mein {STR_VAR_3} strotzt vor\n"
	.string "Energie.\p"
	.string "Hebt es ab, kommt es für eine Weile\n"
	.string "nicht wieder.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JOSE!\p"
	.string "Are your POKéMON still\n"
	.string "cooking?\p"
	.string "My {STR_VAR_3} has too\n"
	.string "much energy.\p"
	.string "Once it takes off, it\n"
	.string "won't come back for a\l"
	.string "while.$"
#endif

MatchCall_HNS_Jose_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Sperr die Ohren auf, die Stange meines\n"
	.string "{STR_VAR_3}s riecht verlockend.\p"
	.string "Der Duft bringt meine\n"
	.string "Geschmacksnerven in Ekstase!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JOSE!\p"
	.string "Hey listen, my\n"
	.string "{STR_VAR_3}'s stick has\l"
	.string "this really delicious\l"
	.string "aroma.\p"
	.string "That aroma gets my\n"
	.string "appetite going!$"
#endif

MatchCall_HNS_Jose_General3::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Vor geraumer Zeit schlug mein\n"
	.string "Porenta ein {STR_VAR_3} K.O.\p"
	.string "Du hättest sehen sollen, wie grazil\n"
	.string "Porenta mit seiner Stange umgeht!\p"
	.string "Einfach unfassbar!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JOSE!\p"
	.string "A while ago, my FARFETCH'D\n"
	.string "KO'd this {STR_VAR_3}.\p"
	.string "You should have seen\n"
	.string "FARFETCH'D wield that\l"
	.string "stick.\p"
	.string "Amazing stuff!$"
#endif

MatchCall_HNS_Jose_FoundItem::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Mein Porenta hatte etwas Schönes\n"
	.string "im Schnabel.\p"
	.string "Wie versprochen, gehört es dir.\p"
	.string "Hol mich auf Route 27 ein, und ich lass\n"
	.string "es dich haben.$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JOSE!\p"
	.string "My FARFETCH'D had\n"
	.string "something pretty in its\l"
	.string "beak.\p"
	.string "Like I promised, you can\n"
	.string "have it.\p"
	.string "Catch up to me on\n"
	.string "ROUTE 27, and I'll let\l"
	.string "you have it.$"
#endif

MatchCall_HNS_Jose_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Elmar!\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's JOSE!\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Reena - Ass-Trainer F, Route 27
MatchCall_HNS_Reena_General1::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sag mal, wie geht’s deinen\n"
	.string "Pokémon?\p"
	.string "Was? Toll? Ach so…\p"
	.string "Was? Meine Pokémon?\p"
	.string "Natürlich geht’s ihnen gut! Was für eine\n"
	.string "Frage ist das denn?$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's REENA.\p"
	.string "Hey, how are your POKéMON\n"
	.string "doing?\p"
	.string "What? Great? I see…\p"
	.string "What? My POKéMON?\p"
	.string "Of course they're doing\n"
	.string "great! What kind of a\l"
	.string "question is that?$"
#endif

MatchCall_HNS_Reena_General2::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Hör zu…\p"
	.string "Erinnerst du dich an mein\n"
	.string "{STR_VAR_3}?\p"
	.string "Ja, genau. Das süße {STR_VAR_3}.\p"
	.string "Meinst du nicht auch, dass es\n"
	.string "perfekt zu mir passt?$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's REENA.\p"
	.string "Listen, dear…\p"
	.string "Do you recall my\n"
	.string "{STR_VAR_3}?\p"
	.string "Yes, exactly. That lovely\n"
	.string "{STR_VAR_3}.\p"
	.string "Wouldn't you agree it's a\n"
	.string "perfect match for me?$"
#endif

MatchCall_HNS_Reena_General3::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Sei nicht zu stolz, dass du mich\n"
	.string "zufällig geschlagen hast…\p"
	.string "Das war Dusel!$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's REENA.\p"
	.string "Don't be too proud just\n"
	.string "because you happened to\l"
	.string "beat me…\p"
	.string "It was a fluke!$"
#endif

MatchCall_HNS_Reena_Battle::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Bea.\p"
	.string "Ich hab auf dich gewartet.\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's REENA.\p"
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
#endif

@ Alex - Kämpferin, Route 13
MatchCall_HNS_Alex_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Johann!\p"
	.string "Meine stolzen Pokémon\n"
	.string "werden von Tag zu Tag schärfer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "richtig stark!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's ALEX!\p"
	.string "My regal POKéMON\n"
	.string "grow sharper by the day.\p"
	.string "{STR_VAR_3} is getting\n"
	.string "really tough!$"
#endif

MatchCall_HNS_Alex_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab gehört, andere Regionen haben\n"
	.string "Könige und Königinnen. Wieso hat\p"
	.string "Kanto keine Königsfamilie?$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I heard other regions have\n"
	.string "kings and queens. Why\l"
	.string "doesn't KANTO have\p"
	.string "any royalty?$"
#endif

MatchCall_HNS_Alex_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Johann!\p"
	.string "Meine stolzen Pokémon sind bereit für\n"
	.string "einen Rückkampf! Komm zu Route 13!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's ALEX!\p"
	.string "My regal POKéMON are ready\n"
	.string "for a rematch! Come to ROUTE 13!$"
#endif

@ Riley - Rowdy, Route 17
MatchCall_HNS_Riley_General1::
#if GERMAN
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Hannes.\p"
	.string "Die Radstrecke ist die beste.\n"
	.string "Nichts geht über den Wind im Gesicht.\p"
	.string "{STR_VAR_3} liebt das\n"
	.string "Tempo auch!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "RILEY here.\p"
	.string "CYCLING ROAD is the best.\n"
	.string "Nothing beats the wind\l"
	.string "in your face.\p"
	.string "{STR_VAR_3} loves the\n"
	.string "speed too!$"
#endif

MatchCall_HNS_Riley_General2::
#if GERMAN
	.string "Yo, {PLAYER}!\p"
	.string "Ihr Johto-Kids sind gar nicht so\n"
	.string "übel. Hab euch wohl unterschätzt.\p"
	.string "Aber lass es dir nicht zu\n"
	.string "Kopf steigen!$"
#else
	.string "Yo, {PLAYER}!\p"
	.string "You JOHTO kids aren't bad.\n"
	.string "Maybe I misjudged you.\p"
	.string "Don't let it go to your\n"
	.string "head though!$"
#endif

MatchCall_HNS_Riley_Battle::
#if GERMAN
	.string "Yo, {PLAYER}!\n"
	.string "Hier ist Hannes.\p"
	.string "Komm runter zur Radstrecke!\n"
	.string "Ich will einen Rückkampf!$"
#else
	.string "Yo, {PLAYER}!\n"
	.string "RILEY here.\p"
	.string "Get down to CYCLING ROAD!\n"
	.string "I want a rematch!$"
#endif

@ Trevor - Jongleur, Route 14
MatchCall_HNS_Trevor_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Reinhold.\p"
	.string "Wusstest du, dass Pokémon freundlicher\n"
	.string "werden, wenn man an denkwürdigen Orten\l"
	.string "trainiert?\p"
	.string "{STR_VAR_3} scheint es\n"
	.string "hier zu mögen.$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TREVOR.\p"
	.string "Did you know POKéMON get\n"
	.string "friendlier when you train\l"
	.string "in memorable places?\p"
	.string "{STR_VAR_3} seems to\n"
	.string "like it here.$"
#endif

MatchCall_HNS_Trevor_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Manche Pokémon-Attacken\n"
	.string "sind stärker, wenn dein\p"
	.string "Pokémon dir gegenüber\n"
	.string "freundlicher ist!$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "Some POKéMON moves\n"
	.string "are stronger when your\p"
	.string "POKéMON feels more\n"
	.string "friendly toward you!$"
#endif

MatchCall_HNS_Trevor_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Reinhold.\p"
	.string "Meine Freunde sind bereit zum\n"
	.string "Kampf! Schau vorbei auf Route 14!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's TREVOR.\p"
	.string "My friends are ready for battle!\n"
	.string "Come see on ROUTE 14!$"
#endif

@ Kyle - Angler, Route 12
MatchCall_HNS_Kyle_General1::
#if GERMAN
	.string "Wer ist da dran?!\n"
	.string "Hab ich dich angerufen?\p"
	.string "Hier ist Alain. Vergiss das nicht!$"
#else
	.string "Who is this?!\n"
	.string "I called you?\p"
	.string "This is KYLE. Don't forget!$"
#endif

MatchCall_HNS_Kyle_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Erinnerst du dich?\n"
	.string "An die Geheimnisse des Angelns?$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "Do you remember?\n"
	.string "The secrets of fishing?$"
#endif

MatchCall_HNS_Kyle_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Alain.\p"
	.string "Ich hab ein paar starke\n"
	.string "neue Pokémon geangelt!\p"
	.string "Komm zu Route 12 für\n"
	.string "einen Kampf!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "KYLE here.\p"
	.string "I've reeled in some tough\n"
	.string "new POKéMON!\p"
	.string "Come to ROUTE 12 for\n"
	.string "a battle!$"
#endif

@ Carter - Pokéfan, Route 14
MatchCall_HNS_Carter_General1::
#if GERMAN
	.string "Hallo, {PLAYER}!\n"
	.string "Hier ist Ernst.\p"
	.string "Ich sammle seltene\n"
	.string "Starter-Pokémon.\p"
	.string "Mein {STR_VAR_3} ist mein\n"
	.string "neuester Stolz!$"
#else
	.string "Hi there, {PLAYER}!\n"
	.string "CARTER here.\p"
	.string "I've been collecting rare\n"
	.string "starter POKéMON.\p"
	.string "My {STR_VAR_3} is my\n"
	.string "newest pride and joy!$"
#endif

MatchCall_HNS_Carter_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Wusstest du, dass es Starter-Pokémon\n"
	.string "aus vielen verschiedenen Regionen\l"
	.string "gibt?\p"
	.string "Ich will sie alle\n"
	.string "sammeln!$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "Did you know there are\n"
	.string "starter POKéMON from many\l"
	.string "different regions?\p"
	.string "I want to collect them\n"
	.string "all!$"
#endif

MatchCall_HNS_Carter_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Ernst.\p"
	.string "Ich hab neue Starter zum Vorzeigen!\n"
	.string "Komm zu Route 14!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "CARTER here.\p"
	.string "I have new starters to\n"
	.string "show off! Come to\l"
	.string "ROUTE 14!$"
#endif

@ Hillary - Expertin, Route 15
MatchCall_HNS_Hillary_General1::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Lehrerin Sylvia.\p"
	.string "Wieso bist du nicht in der Schule?$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's TEACHER HILLARY.\p"
	.string "Why aren't you in school?$"
#endif

MatchCall_HNS_Hillary_General2::
#if GERMAN
	.string "Hallo, {PLAYER}.\p"
	.string "Spielst du Spiele, statt\n"
	.string "Hausaufgaben zu machen?$"
#else
	.string "Hello, {PLAYER}.\p"
	.string "Are you playing games\n"
	.string "instead of doing homework?$"
#endif

MatchCall_HNS_Hillary_Battle::
#if GERMAN
	.string "Hallo, {PLAYER}.\n"
	.string "Hier ist Sylvia.\p"
	.string "Meine Pokémon haben die\n"
	.string "nächste Stufe erreicht!\p"
	.string "Komm uns auf Route 15 testen!$"
#else
	.string "Hello, {PLAYER}.\n"
	.string "It's HILLARY.\p"
	.string "My POKéMON have graduated\n"
	.string "to the next level!\p"
	.string "Come test us on ROUTE 15!$"
#endif

@ Rob - Käfersammler, Route 2
MatchCall_HNS_Rob_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Der Vertania-Wald ist voller\n"
	.string "cooler Käfer!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "ROB here!\p"
	.string "VIRIDIAN FOREST is full\n"
	.string "of cool bugs!$"
#endif

MatchCall_HNS_Rob_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Ich hab einen Käfer-Arena-\n"
	.string "leiter im Vertania-Wald gesehen!$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "I saw a BUG TYPE GYM\n"
#endif

MatchCall_HNS_Rob_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Götz!\p"
	.string "Mein Käfer-Team ist stärker\n"
	.string "als je zuvor!\p"
	.string "Komm zu Route 2 für einen\n"
	.string "Rückkampf!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "ROB here!\p"
	.string "My bug team is stronger\n"
	.string "than ever!\p"
	.string "Come to ROUTE 2 for a\n"
	.string "rematch!$"
#endif

@ Nicole - Schwimmerin, Route 20
MatchCall_HNS_Nicole_General1::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Elke!\p"
	.string "Die Wellen sind heute toll!\n"
	.string "Meine Pokémon schwimmen gern im\l"
	.string "offenen Meer.\p"
	.string "{STR_VAR_3} wird\n"
	.string "so schnell!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's NICOLE!\p"
	.string "The waves are great today!\n"
	.string "My POKéMON love swimming\l"
	.string "in the open sea.\p"
	.string "{STR_VAR_3} is getting\n"
	.string "so fast!$"
#endif

MatchCall_HNS_Nicole_General2::
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Schwimmen mit Pokémon ist\n"
	.string "die beste Übung.$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "Swimming with POKéMON is\n"
	.string "the best exercise.$"
#endif

MatchCall_HNS_Nicole_Battle::
#if GERMAN
	.string "Hi, {PLAYER}!\n"
	.string "Hier ist Elke!\p"
	.string "Meine Wasser-Pokémon wollen\n"
	.string "unbedingt kämpfen!\p"
	.string "Komm zu Route 20!$"
#else
	.string "Hi, {PLAYER}!\n"
	.string "It's NICOLE!\p"
	.string "My water POKéMON are\n"
	.string "raring to battle!\p"
	.string "Come to ROUTE 20!$"
#endif

@ Billy - Schulkind, Route 15
MatchCall_HNS_Billy_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab im Unterricht\n"
	.string "Kampfstrategien gelernt.\p"
	.string "{STR_VAR_3} und ich haben\n"
	.string "sie geübt!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BILLY.\p"
	.string "I've been studying battle\n"
	.string "strategies in class.\p"
	.string "{STR_VAR_3} and I have\n"
	.string "been practicing them!$"
#endif

MatchCall_HNS_Billy_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Bald sind Prüfungen, aber\n"
	.string "ich würde lieber kämpfen.\p"
	.string "Buchwissen ist nicht\n"
	.string "alles, oder?$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "Tests are coming up, but\n"
	.string "I'd rather be battling.\p"
	.string "Book smarts aren't\n"
	.string "everything, right?$"
#endif

MatchCall_HNS_Billy_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Sandro.\p"
	.string "Ich hab neue Tricks gelernt!\n"
	.string "Komm zu Route 15!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "It's BILLY.\p"
	.string "I learned some new tricks!\n"
	.string "Come to ROUTE 15!$"
#endif

@ Kenny - Wanderer, Route 13
MatchCall_HNS_Kenny_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Wurden wirklich alle Berge\n"
	.string "von Ozeanen und Flüssen geformt?$"
#else
	.string "Hey there, {PLAYER}!\n"
	.string "KENNY here.\p"
	.string "Were all mountains really\n"
	.string "shaped by oceans and rivers?$"
#endif

MatchCall_HNS_Kenny_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Hilmar.\n"
	.string "Ich war im Marmoria-Museum!\p"
	.string "Wusstest du, dass ganz Kanto\n"
	.string "einst unter Wasser stand?$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "It's KENNY here.\n"
	.string "I visited the PEWTER museum!\p"
	.string "Did you know the entire KANTO\n"
	.string "region was once under water?$"
#endif

MatchCall_HNS_Kenny_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Hilmar.\p"
	.string "Ich hab hart in den Bergen\n"
	.string "trainiert!\p"
	.string "Komm zu Route 13 für\n"
	.string "einen Kampf!$"
#else
	.string "Hey there, {PLAYER}!\n"
	.string "KENNY here.\p"
	.string "I've trained hard in the\n"
	.string "mountains!\p"
	.string "Come to ROUTE 13 for\n"
	.string "a battle!$"
#endif

@ Joel - Rowdy, Route 17
MatchCall_HNS_Joel_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Manuel.\p"
	.string "Ich arbeite daran, im\n"
	.string "Kampf cool auszusehen.\p"
	.string "{STR_VAR_3} hat ein paar\n"
	.string "schicke neue Attacken!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "JOEL here.\p"
	.string "I've been working on\n"
	.string "looking cool in battle.\p"
	.string "{STR_VAR_3} has some\n"
	.string "flashy new moves!$"
#endif

MatchCall_HNS_Joel_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Hier ist Manuel.\p"
	.string "Es gab einen Unfall auf der\n"
	.string "Radstrecke.\p"
	.string "Sicher zu sein, ist das\n"
	.string "Coolste, was man sein kann.$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "JOEL here.\p"
	.string "There was an accident on\n"
	.string "CYCLING ROAD.\p"
	.string "Being safe is the coolest thing\n"
	.string "you can be.$"
#endif

MatchCall_HNS_Joel_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Manuel.\p"
	.string "Ich seh cool aus und kämpfe\n"
	.string "cool! Komm zur Radstrecke!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "JOEL here.\p"
	.string "I look AND fight cool now!\n"
	.string "Come to CYCLING ROAD!$"
#endif

@ Charles - Rowdy, Route 17
MatchCall_HNS_Charles_General1::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Fridolin.\p"
	.string "Ich war so etwas wie ein\n"
	.string "Herzensbrecher in Einall.\p"
	.string "Jetzt bin ich ein Highway-Star!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "CHARLES here.\p"
	.string "I was something of a\n"
	.string "heartbreaker in UNOVA.\p"
	.string "Now I'm a highway star!$"
#endif

MatchCall_HNS_Charles_General2::
#if GERMAN
	.string "Hey, {PLAYER}!\p"
	.string "Die Radstrecke bei Nacht ist\n"
	.string "etwas ganz Besonderes.\p"
	.string "Die Straßenlaternen und der\n"
	.string "Wind… das ist Freiheit!$"
#else
	.string "Hey, {PLAYER}!\p"
	.string "CYCLING ROAD at night is\n"
	.string "something else.\p"
	.string "The streetlights and the\n"
	.string "wind… it's freedom!$"
#endif

MatchCall_HNS_Charles_Battle::
#if GERMAN
	.string "Hey, {PLAYER}!\n"
	.string "Hier ist Fridolin.\p"
	.string "Die Highway-Stars wollen Rache! Komm\n"
	.string "zur Radstrecke!$"
#else
	.string "Hey, {PLAYER}!\n"
	.string "CHARLES here.\p"
	.string "The highway stars want\n"
	.string "revenge! Come to\l"
	.string "CYCLING ROAD!$"
#endif
