@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
#if GERMAN
	.string " so hübsch!$"
#else
	.string " so pretty!$"
#endif

GiddyText_SoDarling::
#if GERMAN
	.string " so reizend!$"
#else
	.string " so darling!$"
#endif

GiddyText_SoRelaxed::
#if GERMAN
	.string " so lässig!$"
#else
	.string " so relaxed!$"
#endif

GiddyText_SoSunny::
#if GERMAN
	.string " so überwältigend!$"
#else
	.string " so sunny!$"
#endif

GiddyText_SoDesirable::
#if GERMAN
	.string " so erstrebenswert!$"
#else
	.string " so desirable!$"
#endif

GiddyText_SoExciting::
#if GERMAN
	.string " so aufregend!$"
#else
	.string " so exciting!$"
#endif

GiddyText_SoAmusing::
#if GERMAN
	.string " so amüsant!$"
#else
	.string " so amusing!$"
#endif

GiddyText_SoMagical::
#if GERMAN
	.string " so zauberhaft!$"
#else
	.string " so magical!$"
#endif

GiddyText_Is::
#if GERMAN
	.string " klingt$"
#else
	.string " is$"
#endif

GiddyText_DontYouAgree::
#if GERMAN
	.string "\n"
	.string "Findest du nicht auch?$"
#else
	.string "\n"
	.string "Don't you agree?$"
#endif

GiddyText_ISoWantToGoOnAVacation::
#if GERMAN
	.string "Ich will unbedingt verreisen!\n"
	.string "Kennst du ein hübsches Reiseziel?$"
#else
	.string "I so want to go on a vacation.\n"
	.string "Would you happen to know a nice place?$"
#endif

GiddyText_IBoughtCrayonsWith120Colors::
#if GERMAN
	.string "Ich habe 120 verschiedene Farbstifte\n"
	.string "gekauft! Das ist doch toll, oder?$"
#else
	.string "I bought crayons with 120 colors!\n"
	.string "Don't you think that's nice?$"
#endif

GiddyText_WouldntItBeNiceIfWeCouldFloat::
#if GERMAN
	.string "Wäre es nicht herrlich, wir könnten auf\n"
	.string "einer Luftblasenwolke davonschweben?$"
#else
	.string "Wouldn't it be nice if we could float\n"
	.string "away on a cloud of bubbles?$"
#endif

GiddyText_WhenYouWriteOnASandyBeach::
#if GERMAN
	.string "Eine Botschaft in Sand geschrieben\n"
	.string "wird weggespült. Das ist traurig.$"
#else
	.string "When you write on a sandy beach,\n"
	.string "they wash away. It makes me sad.$"
#endif

GiddyText_WhatsTheBottomOfTheSeaLike::
#if GERMAN
	.string "Wie der Meeresgrund wohl ist? Ich\n"
	.string "würde ihn so gerne einmal erleben!$"
#else
	.string "What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"
#endif

GiddyText_WhenYouSeeTheSettingSunDoesIt::
#if GERMAN
	.string "Sehnst du dich beim Anblick der unter-\n"
	.string "gehenden Sonne nach deinem Zuhause?$"
#else
	.string "When you see the setting sun, does it\n"
	.string "make you want to go home?$"
#endif

GiddyText_LyingBackInTheGreenGrass::
#if GERMAN
	.string "Einfach so im grünen Gras liegen…\n"
	.string "Oh, das ist so was von angenehm!$"
#else
	.string "Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"
#endif

GiddyText_SecretBasesAreSoWonderful::
#if GERMAN
	.string "Geheimbasen sind superklasse!\n"
	.string "Findest du das nicht auch aufregend?$"
#else
	.string "SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
#endif
