MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
#if GERMAN
	.string "Diese Attacke kann nur einmal\n"
	.string "erlernt werden! Ist das in Ordnung?$"
#else
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"
#endif

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "Diese Attacke kann nur\n"
	.string "einmal gelernt werden, ok?$"

MoveTutor_Text_SwaggerTeach:
#if GERMAN
	.string "Heh! Mein Pokémon ist das Beste!\n"
	.string "Kein anderes ist so cool wie meins!\p"
	.string "Ich bin herumstolziert und habe\n"
	.string "angegeben, bis ein Vorsitzender mich\l"
	.string "zu Fall brachte.\p"
	.string "Das hat meinen Hochmut abgekühlt.\p"
	.string "Wenn du magst, dann bringe ich einem\n"
	.string "deiner Pokémon Angeberei bei.$"
#else
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"
#endif

MoveTutor_Text_SwaggerDeclined:
#if GERMAN
	.string "Echt nicht? Erkennst du denn nicht\n"
	.string "den tieferen Sinn dahinter?$"
#else
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"
#endif

MoveTutor_Text_SwaggerWhichMon:
#if GERMAN
	.string "Sehr schön! Und welches Pokémon soll\n"
	.string "es lernen?$"
#else
	.string "All right, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"
#endif

MoveTutor_Text_SwaggerTaught:
#if GERMAN
	.string "Ich werde von nun an meine Pokémon\n"
	.string "loben, ohne anzugeben.$"
#else
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"
#endif

MoveTutor_Text_RolloutTeach:
#if GERMAN
	.string "Wusstest du, dass du von hier lange\n"
	.string "in diese Richtung dort gehen kannst,\l"
	.string "ohne die Richtung wechseln zu müssen?\p"
	.string "Ich bin sogar in der Lage, den ganzen\n"
	.string "Weg entlang zu walzen.\p"
	.string "Ob eines deiner Pokémon das auch\n"
	.string "gerne tun würde? Was meinst du?\p"
	.string "Ich kann ihm Walzer beibringen, wenn\n"
	.string "du magst.$"
#else
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"
#endif

MoveTutor_Text_RolloutDeclined:
#if GERMAN
	.string "Ach, sei doch nicht so schüchtern.\n"
	.string "Walzen macht doch Spaß!$"
#else
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"
#endif

MoveTutor_Text_RolloutWhichMon:
#if GERMAN
	.string "Hehehe. Wäre doch klasse, wenn das\n"
	.string "Pokémon so aussehen würde wie ich.$"
#else
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"
#endif

MoveTutor_Text_RolloutTaught:
#if GERMAN
	.string "Ich walze total gerne durch Gras.\n"
	.string "Komm, ich lade dich zum Walzen ein.$"
#else
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"
#endif

MoveTutor_Text_FuryCutterTeach:
#if GERMAN
	.string "Es gibt eine Attacke, die stärker wird,\n"
	.string "wenn du sie mehrmals hintereinander\l"
	.string "einsetzt.\p"
	.string "Sie ist vom Typ Käfer und megacool!\p"
	.string "Sie heißt Zornklinge.\n"
	.string "Soll ich sie einem Pokémon beibringen?$"
#else
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Want me to teach it to a POKéMON?$"
#endif

MoveTutor_Text_FuryCutterDeclined:
#if GERMAN
	.string "Wir haben offensichtlich nicht die\n"
	.string "gleiche Wellenlänge.$"
#else
	.string "We're not on the same wavelength.$"
#endif

MoveTutor_Text_FuryCutterWhichMon:
#if GERMAN
	.string "Ja, klasse! Und welches Pokémon soll die\n"
	.string "Attacke lernen?$"
#else
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"
#endif

MoveTutor_Text_FuryCutterTaught:
#if GERMAN
	.string "Es ist einfach toll zu sehen, wenn die\n"
	.string "Attacke mehrmals hintereinander\l"
	.string "trifft.$"
#else
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"
#endif

MoveTutor_MimicTeach:
#if GERMAN
	.string "Ah, Jungchen!\p"
	.string "Ich bin auch noch jung, aber ich ahme\n"
	.string "die Sprache der älteren Leute nach, die\l"
	.string "ich in diesem Ort treffe.\p"
	.string "Was meinst du, Kindchen?\n"
	.string "Würde es dich freuen, wenn ich einem\l"
	.string "deiner Pokémon Mimikry beibringe?$"
#else
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move MIMIC?$"
#endif

MoveTutor_MimicDeclined:
#if GERMAN
	.string "Oh, buuuuh! Und ich wollte doch so gerne\n"
	.string "einem Pokémon Mimikry beibringen…$"
#else
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "to your POKéMON!$"
#endif

MoveTutor_Text_MimicWhichMon:
#if GERMAN
	.string "Hahaha! So soll es sein! Zeig mir das\n"
	.string "Pokémon, welches die Attacke lernen\l"
	.string "soll.$"
#else
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"
#endif

MoveTutor_Text_MimicTaught:
#if GERMAN
	.string "Mimikry ist eine Attacke mit Tiefe.\p"
	.string "Kannst du sie so perfekt anwenden, wie\n"
	.string "ich es kann?$"
#else
	.string "MIMIC is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"
#endif

MoveTutor_Text_MetronomeTeach:
#if GERMAN
	.string "Ich will alles Mögliche haben… Aber\n"
	.string "ich habe mein ganzes Geld ausgegeben…\p"
	.string "Ach, ich fände es toll, wenn es einen\n"
	.string "Spruch gäbe, bei dem man nur mit dem\l"
	.string "Finger wackelt und schon hat man Geld.\p"
	.string "Wenn du möchtest, bringe ich einem\n"
	.string "deiner Pokémon Metronom bei.\p"
	.string "Dadurch bekommst du kein Geld, aber\n"
	.string "dein Pokémon wackelt mit dem Finger.$"
#else
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"
#endif

MoveTutor_Text_MetronomeDeclined:
#if GERMAN
	.string "Okay. Solltest du es dir anders\n"
	.string "überlegen - du findest mich hier.$"
#else
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"
#endif

MoveTutor_Text_MetronomeWhichMon:
#if GERMAN
	.string "Okay. Ich werde es ihm beibringen.\n"
	.string "Und welchem soll ich es beibringen?$"
#else
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"
#endif

MoveTutor_Text_MetronomeTaught:
#if GERMAN
	.string "Wackelt ein Pokémon mit seinem Finger\n"
	.string "wie ein Metronom, passieren die\l"
	.string "schönsten Dinge.\p"
	.string "Wäre das toll, wenn wir das auch\n"
	.string "könnten. Meinst du nicht auch?$"
#else
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"
#endif

MoveTutor_Text_SleepTalkTeach:
#if GERMAN
	.string "Hmpf! Meine Frau vertraut auf\n"
	.string "Kraftreserve, um wach zu bleiben.\p"
	.string "Sie sollte lieber ein Nickerchen halten\n"
	.string "und eine Schlafrede halten.\p"
	.string "Ich kann einem deiner Pokémon\n"
	.string "Schlafrede beibringen. Interessiert?$"
#else
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. Interested?$"
#endif

MoveTutor_Text_SleepTalkDeclined:
#if GERMAN
	.string "Schon gut, schon gut. Dann bleib doch\n"
	.string "wach, dank Kraftreserve.$"
#else
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"
#endif

MoveTutor_Text_SleepTalkWhichMon:
#if GERMAN
	.string "Oh, was für ein verständiges Kind!\n"
	.string "Welchem Pokémon soll ich es beibringen?$"
#else
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"
#endif

MoveTutor_Text_SleepTalkTaught:
#if GERMAN
	.string "Ich kann meine Frau einfach nicht\n"
	.string "überlisten…\p"
	.string "Stattdessen hört sie interessiert\n"
	.string "meiner Schlafrede zu…$"
#else
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"
#endif

MoveTutor_Text_SubstituteTeach:
#if GERMAN
	.string "Wenn ich die weite Welt von hier oben\n"
	.string "aus betrachte…\p"
	.string "dann wünschte ich mir, es gäbe mich\n"
	.string "mehr als einmal, damit ich alle schönen\l"
	.string "Dinge des Lebens genießen kann.\p"
	.string "Aber das ist ja leider nicht möglich…\n"
	.string "Kicher…\p"
	.string "Ich weiß! Soll ich einem deiner Pokémon\n"
	.string "Delegator beibringen?$"
#else
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"
#endif

MoveTutor_Text_SubstituteDeclined:
#if GERMAN
	.string "Oh? Nicht?\p"
	.string "Ein Pokémon könnte damit aber einen\n"
	.string "Doppelgänger von sich schaffen!$"
#else
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"
#endif

MoveTutor_Text_SubstituteWhichMon:
#if GERMAN
	.string "Kicher…\n"
	.string "Welchem Pokémon soll ich es beibringen?$"
#else
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"
#endif

MoveTutor_Text_SubstituteTaught:
#if GERMAN
	.string "Wir Menschen sollten unser Leben voll\n"
	.string "ausschöpfen und genießen!\p"
	.string "Ich hoffe, du tust das bereits!$"
#else
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"
#endif

MoveTutor_Text_DynamicPunchTeach:
#if GERMAN
	.string "Ich kann nicht mehr!\p"
	.string "Das ist doch absolut hoffnungslos!\p"
	.string "Ich bin ein Kampf-Trainer, daher kann\n"
	.string "ich in der Arena von Moosbach City\p"
	.string "einfach nicht gewinnen, egal, wie sehr\n"
	.string "ich mich auch anstrenge!\p"
	.string "Argh! Schlag! Wucht! Schlag!\n"
	.string "Schlag! Wucht! Schlag!\p"
	.string "Hey, was starrst du mich so an?!?\n"
	.string "Ich schlage doch nur auf den Boden ein!\p"
	.string "Oder möchtest du, dass ich einem deiner\n"
	.string "Pokémon Wuchtschlag beibringe?!?$"
#else
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"
#endif

MoveTutor_Text_DynamicPunchDeclined:
#if GERMAN
	.string "Mist! Du machst dich lustig über mich!!!\n"
	.string "Schlag! Wucht! Schlag!$"
#else
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"
#endif

MoveTutor_Text_DynamicPunchWhichMon:
#if GERMAN
	.string "Das möchtest du? Das ist klug von dir!\n"
	.string "Welchem Pokémon soll ich es beibringen?$"
#else
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"
#endif

MoveTutor_Text_DynamicPunchTaught:
#if GERMAN
	.string "Ich möchte, dass du in der Arena von\n"
	.string "Moosbach City gewinnst, indem du\l"
	.string "Wuchtschlag einsetzt.$"
#else
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"
#endif

MoveTutor_Text_DoubleEdgeTeach:
#if GERMAN
	.string "Seufz…\p"
	.string "Der Arenaleiter von Xeneroville ist\n"
	.string "einfach anbetungswürdig.\p"
	.string "Aber das heißt auch, dass ich viele\n"
	.string "Rivalinnen habe, die um seine Gunst\l"
	.string "kämpfen.\p"
	.string "Er wurde mit Risikotackle verzaubert.\n"
	.string "Unsere Augen trafen sich nicht.\p"
	.string "Darf ich einem deiner Pokémon\n"
	.string "Risikotackle beibringen?$"
#else
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"
#endif

MoveTutor_Text_DoubleEdgeDeclined:
#if GERMAN
	.string "Oh…\n"
	.string "Auch du lehnst mich also ab…$"
#else
	.string "Oh…\n"
	.string "Even you rejected me…$"
#endif

MoveTutor_Text_DoubleEdgeWhichMon:
#if GERMAN
	.string "Schön!!! Welchem Pokémon soll ich\n"
	.string "Risikotackle beibringen?$"
#else
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"
#endif

MoveTutor_Text_DoubleEdgeTaught:
#if GERMAN
	.string "Ich werde nicht mehr für die Liebe\n"
	.string "leben! Ich werde stark werden!$"
#else
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"
#endif

MoveTutor_Text_ExplosionTeach:
#if GERMAN
	.string "Ich habe nicht vor, lange hier in der\n"
	.string "Ödnis zu bleiben.\p"
	.string "Pass nur auf! Ich werde diesen Ort\n"
	.string "verlassen und ganz groß rauskommen!\p"
	.string "Ernsthaft! Mein Ruhm wird\n"
	.string "explosionsartig zum Vorschein kommen.\p"
	.string "Wenn du an mich glaubst, bringe ich\n"
	.string "einem deiner Pokémon Explosion bei.$"
#else
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"
#endif

MoveTutor_Text_ExplosionDeclined:
#if GERMAN
	.string "Argh! Nur weil ich in der Pampa lebe,\n"
	.string "ignorierst du mein Angebot?!?$"
#else
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"
#endif

MoveTutor_Text_ExplosionWhichMon:
#if GERMAN
	.string "Super! Das wird eine Explosion!\n"
	.string "Welchem Pokémon soll ich es beibringen?$"
#else
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"
#endif

MoveTutor_Text_ExplosionTaught:
#if GERMAN
	.string "Schon lange bringe ich Pokémon\n"
	.string "Explosion bei. Jetzt wird es Zeit an\l"
	.string "meine eigene Explosion zu denken…\p"
	.string "Vielleicht bin ich schon so lange hier,\n"
	.string "weil es mir hier doch gefällt?!?$"
#else
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
#endif

MoveTutor_Text_HeadbuttTeach:
#if GERMAN
	.string "Was ich mache?\p"
	.string "Ich schüttle die Bäume mit\n"
	.string "einer Kopfnuss. Denkst du dein Pokémon\l"
	.string "möchte das auch lernen?\p"
	.string "Ich kann es einem beibringen,\n"
	.string "wenn du möchtest.$"
#else
	.string "What am I doing?\p"
	.string "I'm shaking trees using HEADBUTT.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to HEADBUTT, too?\p"
	.string "I can teach one the move HEADBUTT\n"
	.string "if you'd like. It's fun!$"
#endif

MoveTutor_Text_HeadbuttWhichMon:
#if GERMAN
	.string "Ehehe, alles klar! Es wäre schön\n"
	.string "wenn das Pokémon aussieht wie ich.$"
#else
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"
#endif

MoveTutor_Text_HeadbuttDeclined:
#if GERMAN
	.string "Sei nicht schüchtern.\n"
	.string "Kopfnuss los!$"
#else
	.string "You don't need to be shy about it.\n"
	.string "Let's butt heads!$"
#endif

MoveTutor_Text_HeadbuttTaught:
#if GERMAN
	.string "Schüttle Bäume mit Kopfnuss.\n"
	.string "Manchmal fallen schlafende Pokémon\l"
	.string "herunter.$"
#else
	.string "Rattle trees with HEADBUTT.\n"
	.string "Sometimes, sleeping POKéMON fall out.$"
#endif
