gText_ObtainedTheItem::
#if GERMAN
	.string "{STR_VAR_2} erhalten!$"
#else
	.string "Obtained the {STR_VAR_2}!$"
#endif

gText_TheBagIsFull::
#if GERMAN
	.string "Der Beutel ist voll…$"
#else
	.string "The BAG is full…$"
#endif

gText_PutItemInPocket::
#if GERMAN
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-Tasche.$"
#else
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"
#endif

gText_PlayerFoundOneItem::
#if GERMAN
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"
#else
	.string "{PLAYER} found one {STR_VAR_2}!$"
#endif

gText_TooBadBagIsFull::
#if GERMAN
	.string "Zu schade!\n"
	.string "Der Beutel ist voll…$"
#else
	.string "Too bad!\n"
	.string "The BAG is full…$"
#endif

gText_PlayerPutItemInBag::
#if GERMAN
	.string "{PLAYER} packt {STR_VAR_2} in den\n"
	.string "Pyrabeutel.$"
#else
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"
#endif

gText_ObtainedTheDecor::
#if GERMAN
	.string "{STR_VAR_2} erhalten.$"
#else
	.string "Obtained the {STR_VAR_2}!$"
#endif

gText_NoRoomLeftForAnother::
#if GERMAN
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}…$"
#else
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"
#endif

gText_TheDecorWasTransferredToThePC::
#if GERMAN
	.string "{STR_VAR_2} wurde auf den PC übertragen.$"
#else
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
#endif

gText_ObtainedTheItems::
#if GERMAN
	.string "Erhält {STR_VAR_1} {STR_VAR_2}!$"
#else
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"
#endif

gText_PlayerFoundItems::
#if GERMAN
	.string "{PLAYER} findet {STR_VAR_1} {STR_VAR_2}!$"
#else
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"
#endif

gText_PutCoinsAwayInCoinCase::
#if GERMAN
	.string "{PLAYER} legt die Münzen in den\n"
	.string "Münzkorb.$"
#else
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"
#endif

gText_FoundXCoins::
#if GERMAN
	.string "{PLAYER} findet {STR_VAR_1} {STR_VAR_2}!$"
#else
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"
#endif

gText_FoundXItems::
#if GERMAN
	.string "{PLAYER} findet {STR_VAR_1} {STR_VAR_2}(s)!$"
#else
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"
#endif

gText_CoinCaseIsFull::
#if GERMAN
	.string "Schade!\n"
	.string "Münzkorb ist voll…$"
#else
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"
#endif

gText_NothingToPutThemIn::
#if GERMAN
	.string "Schade!\n"
	.string "Ich habe nichts zum aufbewahren…$"
#else
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
#endif
