Text_BootUpPC:
#if GERMAN
	.string "{PLAYER} schaltet den PC ein.$"
#else
	.string "{PLAYER} booted up the PC.$"
#endif

gText_WhichPCShouldBeAccessed::
#if GERMAN
	.string "Zugriff auf wessen PC?$"
#else
	.string "Which PC should be accessed?$"
#endif

gText_AccessedSomeonesPC::
#if GERMAN
	.string "Verbindung zu Jemandes PC hergestellt.$"
#else
	.string "Accessed SOMEONE'S PC.$"
#endif

gText_StorageSystemOpened::
#if GERMAN
	.string "Pokémon-Lagerungs-System geöffnet.$"
#else
	.string "POKéMON Storage System opened.$"
#endif

gText_AccessedPlayersPC::
#if GERMAN
	.string "Verbindung mit PC von {PLAYER}.$"
#else
	.string "Accessed {PLAYER}'s PC.$"
#endif

gText_AccessedLanettesPC::
#if GERMAN
	.string "Verbindung zu Lanettes PC hergestellt.$"
#else
	.string "Accessed LANETTE's PC.$"
#endif

gText_AccessedBillsPC::
#if GERMAN
	.string "Verbindung zu Bills PC hergestellt.$"
#else
	.string "Accessed BILL's PC.$"
#endif
