gText_WouldYouLikeToRestYourPkmn::
#if GERMAN
	.string "Willkommen im Pokémon-Center!\p"
	.string "Wir heilen deine Pokémon und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine Pokémon.$"
#else
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"
#endif

gText_IllTakeYourPkmn::
#if GERMAN
	.string "Okay, ich nehme deine Pokémon für einen\n"
	.string "Moment in meine Obhut.$"
#else
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"
#endif

gText_RestoredPkmnToFullHealth::
#if GERMAN
	.string "Danke!\p"
	.string "Deine Pokémon sind wieder topfit!$"
#else
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"
#endif

gText_WeHopeToSeeYouAgain::
#if GERMAN
	.string "Komm jederzeit wieder vorbei!$"
#else
	.string "We hope to see you again!$"
#endif

gText_WelcomeCutShort::
#if GERMAN
	.string "Willkommen im Pokémon-Center!\p"
	.string "Wir heilen deine Pokémon und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine Pokémon.$"
#else
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"
#endif

gText_NoticesGoldCard::
#if GERMAN
	.string "Di-dieser Pass…\n"
	.string "Ist das der… Goldpass?!?\p"
	.string "Diese goldene Farbe ist brillant!\n"
	.string "Die vier Sterne funkeln richtig!\p"
	.string "Ich habe schon viele Trainer mit einem\n"
	.string "Silberpass gesehen, aber, {PLAYER},\l"
	.string "du bist der erste Trainer mit einem\l"
	.string "Goldpass!\p"
	.string "Okay, {PLAYER}, bitte gib mir die Ehre,\n"
	.string "mich um deine Pokémon kümmern\l"
	.string "zu dürfen!$"
#else
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"
#endif

gText_YouWantTheUsual::
#if GERMAN
	.string "Ich freue mich, dich zu sehen, {PLAYER}!\n"
	.string "Das Übliche, nicht wahr?$"
#else
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"
#endif

gText_IllTakeYourPkmn2::
#if GERMAN
	.string "Okay, ich nehme deine Pokémon für einen\n"
	.string "Moment in meine Obhut.$"
#else
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"
#endif

gText_ThankYouForWaiting::
#if GERMAN
	.string "Danke!$"
#else
	.string "Thank you for waiting.$"
#endif

gText_WeHopeToSeeYouAgain2::
#if GERMAN
	.string "Komm bald wieder!$"
#else
	.string "We hope to see you again!$"
#endif

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, du spielst mit\n"
    .string "der Pokécenter-Challenge!\p"
    .string "Viel Glück!{PAUSE_UNTIL_PRESS}$"
