gBirchDexRatingText_AreYouCurious::
#if GERMAN
	.string "Prof. Birk: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"
#else
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"
#endif

gBirchDexRatingText_Cancel::
#if GERMAN
	.string "Ach? Du hast erst so wenige Pokémon\n"
	.string "gefangen, dass es sich nicht lohnt, ihn\l"
	.string "mir zu zeigen?$"
#else
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"
#endif

gBirchDexRatingText_SoYouveSeenAndCaught::
#if GERMAN
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"
#else
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
#endif

gBirchDexRatingText_LessThan10::
#if GERMAN
	.string "Du solltest mehr ins hohe Gras gehen\n"
	.string "und mehr auf Pokémon achten.$"
#else
	.string "Go into grassy areas more and look\n"
	.string "for POKéMON more carefully.$"
#endif

gBirchDexRatingText_LessThan20::
#if GERMAN
	.string "So langsam bekommst du den Bogen raus.\n"
	.string "Aber es wird immer schwieriger werden!$"
#else
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"
#endif

gBirchDexRatingText_LessThan30::
#if GERMAN
	.string "Einige Pokémon tauchen nur in\n"
	.string "bestimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"
#else
	.string "Some POKéMON only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"
#endif

gBirchDexRatingText_LessThan40::
#if GERMAN
	.string "Nun, er könnte mehr Einträge enthalten,\n"
	.string "aber es sieht schon eher nach einem\l"
	.string "Pokédex aus.$"
#else
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a POKéDEX now.$"
#endif

gBirchDexRatingText_LessThan50::
#if GERMAN
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"
#else
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"
#endif

gBirchDexRatingText_LessThan60::
#if GERMAN
	.string "Verwendest du irgendwelche Angeln?\n"
	.string "Hier gibt es viele Pokémon im Meer.$"
#else
	.string "Are you using any RODS?\n"
	.string "There are many POKéMON in the sea.$"
#endif

gBirchDexRatingText_LessThan70::
#if GERMAN
	.string "Statt die Pokémon nur zu fangen, wie\n"
	.string "wäre es, sie sich entwickeln zu lassen?$"
#else
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"
#endif

gBirchDexRatingText_LessThan80::
#if GERMAN
	.string "Der Pokédex wird einfach fantastisch.\n"
	.string "Das habe ich im Gefühl…$"
#else
	.string "This is going to be a fantastic\n"
	.string "POKéDEX.\l"
	.string "That's the feeling I'm getting.$"
#endif

gBirchDexRatingText_LessThan90::
#if GERMAN
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches Talent!$"
#else
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"
#endif

gBirchDexRatingText_LessThan100::
#if GERMAN
	.string "Warst du schon mal in der\n"
	.string "Safari-Zone?\p"
	.string "Ich habe gehört, es gibt Pokémon,\n"
	.string "die man nur dort finden kann.$"
#else
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"
#endif

gBirchDexRatingText_LessThan110::
#if GERMAN
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"
#else
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"
#endif

gBirchDexRatingText_LessThan120::
#if GERMAN
	.string "Es gibt auch Pokémon, die man durch den\n"
	.string "Einsatz von Zertrümmerer findet.$"
#else
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"
#endif

gBirchDexRatingText_LessThan130::
#if GERMAN
	.string "Du solltest einige Pokémon fangen\n"
	.string "und sie mit anderen tauschen.$"
#else
	.string "You should get some more POKéMON\n"
	.string "by trading with others.$"
#endif

gBirchDexRatingText_LessThan140::
#if GERMAN
	.string "Ich habe von Pokémon gehört, die sich\n"
	.string "entwickeln, wenn sie ihren Trainer sehr\l"
	.string "lieben.$"
#else
	.string "I've heard of POKéMON that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"
#endif

gBirchDexRatingText_LessThan150::
#if GERMAN
	.string "Ich hatte keine Ahnung, dass es in der\n"
	.string "Hoenn-Region so viele verschiedene\l"
	.string "Pokémon-Arten gibt.$"
#else
	.string "I had no idea that there were so\n"
	.string "many POKéMON species in the HOENN\l"
	.string "region.$"
#endif

gBirchDexRatingText_LessThan160::
#if GERMAN
	.string "Manchmal erscheinen einige\n"
	.string "Pokémon in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"
#else
	.string "On occasion, some POKéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"
#endif

gBirchDexRatingText_LessThan170::
#if GERMAN
	.string "Dein Pokédex liefert einen erstaunlich\n"
	.string "guten Einblick in die Pokémon der\l"
	.string "Hoenn-Region!$"
#else
	.string "One can get a very good idea about\n"
	.string "the POKéMON of the HOENN region\l"
	.string "by looking through your POKéDEX.$"
#endif

gBirchDexRatingText_LessThan180::
#if GERMAN
	.string "Ich sage, du hast dich bereits als guter\n"
	.string "Pokémon-Professor qualifiziert.$"
#else
	.string "I would say you already qualify as\n"
	.string "a POKéMON PROFESSOR, and a good\l"
	.string "one, too!$"
#endif

gBirchDexRatingText_LessThan190::
#if GERMAN
	.string "Mit diesem Pokédex, der schon so weit\n"
	.string "gediehen ist, bist du ein echter Profi.$"
#else
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"
#endif

gBirchDexRatingText_LessThan200::
#if GERMAN
	.string "Du bist sehr nahe dran, den Pokédex zu\n"
	.string "vervollständigen.\l"
	.string "Das fühle ich einfach.$"
#else
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"
#endif

gBirchDexRatingText_DexCompleted::
#if GERMAN
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein Pokédex ist vollständig!$"
#else
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"
#endif

gBirchDexRatingText_OnANationwideBasis::
#if GERMAN
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} Pokémon gesehen\n"
	.string "und {STR_VAR_2} Pokémon gefangen…$"
#else
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
#endif

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
#if GERMAN
	.string "Prof. Eich: Ich freue mich, dich\n"
	.string "zu sehen! Was macht dein Pokédex?\p"
	.string "Zeig ihn mir!$"
#else
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"
#endif

PokedexRating_Text_SeenXOwnedY::
#if GERMAN
	.string "In deinem Pokédex steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "  Besitz: {STR_VAR_2} Pokémon\p"
	.string "Prof. Eichs Bewertung:$"
#else
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"
#endif

PokedexRating_Text_LessThan10::
#if GERMAN
	.string "Du hast noch eine Menge Arbeit vor dir.\p"
	.string "Suche in hohem Gras nach Pokémon!$"
#else
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"
#endif

PokedexRating_Text_LessThan20::
#if GERMAN
	.string "Das sieht schon ganz gut aus!\p"
	.string "Hole dir bei meinem Assistenten die VM\n"
	.string "Blitz ab!$"
#else
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"
#endif

PokedexRating_Text_LessThan30::
#if GERMAN
	.string "Du benötigst noch weitere!\p"
	.string "Fange also die verschiedensten\n"
	.string "Pokémon!$"
#else
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"
#endif

PokedexRating_Text_LessThan40::
#if GERMAN
	.string "Sehr gut! Du gibst dir sehr viel Mühe!\p"
	.string "Hole dir bei meinem Assistenten einen\n"
	.string "Detektor ab!$"
#else
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"
#endif

PokedexRating_Text_LessThan50::
#if GERMAN
	.string "Dein Pokédex macht gute Fortschritte!\p"
	.string "Ich habe einem meiner Assistenten ein\n"
	.string "Münzamulett gegeben. Hol es dir!$"
#else
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"
#endif

PokedexRating_Text_LessThan60::
#if GERMAN
	.string "Ah, nun hast du mehr als 50!\p"
	.string "Ich habe einem meiner Assistenten\n"
	.string "einen EP-Teiler gegeben. Hol in dir!$"
#else
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"
#endif

PokedexRating_Text_LessThan70::
#if GERMAN
	.string "Heh! Es wird immer besser!$"
#else
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"
#endif

PokedexRating_Text_LessThan80::
#if GERMAN
	.string "Fantastisch!\p"
	.string "Du solltest dir Wasser-Pokémon angeln!$"
#else
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"
#endif

PokedexRating_Text_LessThan90::
#if GERMAN
	.string "Wundervoll! Du bist ein\n"
	.string "leidenschaftlicher Sammler!$"
#else
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"
#endif

PokedexRating_Text_LessThan100::
#if GERMAN
	.string "Ich bin wirklich beeindruckt! Das war\n"
	.string "sicher eine Menge Arbeit!$"
#else
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"
#endif

PokedexRating_Text_LessThan110::
#if GERMAN
	.string "Du hast bereits 100 verschiedene\n"
	.string "Pokémon! Du leistest hervorragende\l"
	.string "Arbeit!$"
#else
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"
#endif

PokedexRating_Text_LessThan120::
#if GERMAN
	.string "Super! Einige deiner Pokémon haben sich\n"
	.string "sogar entwickelt!$"
#else
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"
#endif

PokedexRating_Text_LessThan130::
#if GERMAN
	.string "Ausgezeichnet! Tausche Pokémon mit\n"
	.string "Freunden, um weitere zu erhalten!$"
#else
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"
#endif

PokedexRating_Text_LessThan140::
#if GERMAN
	.string "Überragend! Du hast dich zu einem\n"
	.string "echten Profi gemausert!$"
#else
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"
#endif

PokedexRating_Text_LessThan150::
#if GERMAN
	.string "Ich bin sprachlos!\p"
	.string "Von nun an giltst du als Autorität für\n"
	.string "Pokémon!$"
#else
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"
#endif

PokedexRating_Text_Complete::
#if GERMAN
	.string "Dein Pokédex ist komplett fertig\n"
	.string "gestellt! Herzlichen Glückwunsch!$"
#else
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"
#endif

PokedexRating_Text_NationalDexSeenXOwnedY::
#if GERMAN
	.string "In deinem Nationalen Pokédex\n"
	.string "steht:\p"
	.string "Gesehen: {STR_VAR_1} Pokémon\n"
	.string "Besitz: {STR_VAR_2} Pokémon.$"
#else
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"
#endif

PokedexRating_Text_LookForwardToFilledNationalDex::
#if GERMAN
	.string "Ich bin gespannt, ob du den\n"
	.string "Nationalen Pokédex füllen kannst.$"
#else
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"
#endif

PokedexRating_Text_YouveCompletedDex::
#if GERMAN
	.string "Endlich…\p"
	.string "Dein Pokédex ist komplett!\p"
	.string "Das ist traumhaft!\n"
	.string "Wirklich fantastisch!$"
#else
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"
#endif

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
#if GERMAN
	.string "Danke, {PLAYER}!\n"
	.string "Meinen aufrichtigen Dank!\l"
	.string "Du hast meinen Traum erfüllt.$"
#else
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"
#endif

PokedexRating_Text_LoveSeeingYourPokedex::
#if GERMAN
	.string "Eich: Ah, willkommen!\p"
	.string "Wie ist es um deinen Pokédex\n"
	.string "bestellt?\p"
	.string "Wow!\p"
	.string "Ich weiß es natürlich, aber ich\n"
	.string "liebe es trotzdem!\p"
	.string "Zeig ihn mir…$"
#else
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
#endif

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Have you found MR. POKéMON's\n"
	.string "home yet? It is on ROUTE 30,\p"
	.string "you can't miss it!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Get here quick! Something\n"
	.string "awful has happened!$"

gElmDexRatingText_AreYouCurious::
#if GERMAN
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem Pokédex zeigen?$"
#else
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"
#endif

gElmDexRatingText_AreYouCuriousNational::
#if GERMAN
	.string "Prof. Lind: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem nationalen Pokédex zeigen?$"
#else
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "National POKéDEX is coming along?$"
#endif

gJohtoDexRatingText_LessThan10::
#if GERMAN
	.string "Du solltest mehr ins hohe Gras gehen\n"
	.string "und mehr auf Pokémon achten.$"
#else
	.string "Look for POKéMON in grassy areas!$"
#endif

gJohtoDexRatingText_LessThan20::
#if GERMAN
	.string "So langsam bekommst du den Bogen raus.\n"
	.string "Aber es wird immer schwieriger werden!$"
#else
	.string "Good. I see you understand how to\n"
	.string "use Poké Balls.$"
#endif

gJohtoDexRatingText_LessThan35::
#if GERMAN
	.string "Einige Pokémon tauchen nur in\n"
	.string "bestimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"
#else
	.string "You're getting good at this,\n"
	.string "but you have a long way to go.$"
#endif

gJohtoDexRatingText_LessThan50::
#if GERMAN
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"
#else
	.string "Hmm, you're catching POKéMON at a\n"
	.string "decent pace!$"
#endif

gJohtoDexRatingText_LessThan65::
#if GERMAN
	.string "Verwendest du irgendwelche Angeln?\n"
	.string "Hier gibt es viele Pokémon im Meer.$"
#else
	.string "You're trying--I can see that.\n"
	.string "Your POKéDEX is coming together.$"
#endif

gJohtoDexRatingText_LessThan80::
#if GERMAN
	.string "Der Pokédex wird einfach fantastisch.\n"
	.string "Das habe ich im Gefühl…$"
#else
	.string "You're training them well. You know\n"
	.string "some POKéMON don't evolve just by\p"
	.string "battling with others, right?$"
#endif

gJohtoDexRatingText_LessThan95::
#if GERMAN
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches Talent!$"
#else
	.string "Do you have a Fishing Rod?\n"
	.string "There are some POKéMON that can\p"
	.string "only be found by fishing!$"
#endif

gJohtoDexRatingText_LessThan110::
#if GERMAN
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "Pokédex!$"
#else
	.string "Excellent! You seem to be good at\n"
	.string "collecting things!$"
#endif

gJohtoDexRatingText_LessThan125::
#if GERMAN
	.string "Du kannst manchen Pokémon nur zu\n"
	.string "gewissen Tageszeiten begegnen!$"
#else
	.string "Some POKéMON only appear during\n"
	.string "certain times of the day.$"
#endif

gJohtoDexRatingText_LessThan140::
#if GERMAN
	.string "Die Zahl deiner registrierten Pokémon\n"
	.string "ist ja ziemlich gewachsen! Mach weiter\l"
	.string "so!$"
#else
	.string "Your POKéDEX is really filling up.\n"
	.string "Keep up the good work!$"
#endif

gJohtoDexRatingText_LessThan155::
#if GERMAN
	.string "Beeindruckend! Du fängst Pokémon\n"
	.string "nicht nur, sondern sorgst auch dafür,\l"
	.string "dass sie sich entwickeln!$"
#else
	.string "I'm impressed.\n"
	.string "You're evolving POKéMON, not just\p"
	.string "catching them.$"
#endif

gJohtoDexRatingText_LessThan170::
#if GERMAN
	.string "Wenn du Kurts Pokébälle mit Bedacht\n"
	.string "einzusetzen verstehst, dürfte die Zahl\l"
	.string "deiner gefangenen Pokémon in die Höhe\l"
	.string "schnellen!$"
#else
	.string "If you can learn how to use the\n"
	.string "custom Poké Balls made by Kurt\p"
	.string "effectively, you'll be able to catch\n"
	.string "POKéMON better!$"
#endif

gJohtoDexRatingText_LessThan185::
#if GERMAN
	.string "Wenn du Pokémon fangen möchtest, ist\n"
	.string "es von Vorteil, Informationen mit\l"
	.string "deinen Freunden auszutauschen!$"
#else
	.string "When you trade POKéMON, you can\n"
	.string "also trade information. Your\p"
	.string "friends can really help you!$"
#endif

gJohtoDexRatingText_LessThan200::
#if GERMAN
	.string "Tauschst du deine Pokémon mit\n"
	.string "Freunden? Alleine ist das sehr\l"
	.string "schwierig!$"
#else
	.string "Are you trading your POKéMON?\n"
	.string "It's tough to do this alone!$"
#endif

gJohtoDexRatingText_LessThan215::
#if GERMAN
	.string "Die 200-Marke ist erreicht! Dein\n"
	.string "Pokédex entwickelt sich ja prächtig!$"
#else
	.string "Wow! You've reached 200!\n"
	.string "Your POKéDEX is looking great!$"
#endif

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
#if GERMAN
	.string "Schon über 225,\n"
	.string "weiter so.$"
#else
	.string "You've proven yourself capable.\n"
    .string "There's nothing to worry about.\p"
    .string "Keep catching POKéMON the way\n"
    .string "you've been doing so far.$"
#endif

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
#if GERMAN
	.string "Schon über 240,\n"
	.string "weiter so.$"
#else
	.string "Your POKéDEX is well on the way to\n"
	.string "being filled up.\p"
	.string "This POKéDEX can be considered a\n"
	.string "journal of your adventure.$"
#endif

gJohtoDexRatingText_LessThan260::
#if GERMAN
	.string "Du hast so viele Pokémon gefunden!\n"
	.string "Dank deiner Hilfe kommt meine\l"
	.string "Forschung gut voran!$"
#else
	.string "You've found so many POKéMON!\n"
	.string "You've really helped my studies!$"
#endif

gJohtoDexRatingText_LessThan275::
#if GERMAN
	.string "Fantastisch! Was soll ich mehr sagen?\n"
	.string "Du hast das Zeug, ein ganz großer\l"
	.string "Pokémon-Professor zu werden!$"
#else
	.string "Magnificent! You have the ability\n"
	.string "to become a great POKéMON\p"
	.string "Professor someday!$"
#endif

gJohtoDexRatingText_LessThanMaxDex::
#if GERMAN
	.string "Dein Pokédex ist glatter Wahnsinn! Du\n"
	.string "wirst noch ein echter Profi!$"
#else
	.string "Your POKéDEX is amazing!\n"
	.string "You're ready to turn professional!$"
#endif

gJohtoDexRatingText_Complete::
#if GERMAN
	.string "Oh!\n"
	.string "Der Johto-Pokédex ist ja vollständig!\p"
	.string "Und das nur dank dir, {PLAYER}!!!\n"
	.string "Das ist wirklich eine außergewöhnliche\l"
	.string "Leistung!$"
#else
	.string "Wow!\n"
#endif

gNationalDexRatingText_LessThan100::
#if GERMAN
	.string "Es ist noch ein weiter Weg bis zum Ziel,\n"
	.string "aber lass dich davon nicht entmutigen!$"
#else
	.string "The goal may be far away, but don't\n"
	.string "give up yet! Keep going!$"
#endif

gNationalDexRatingText_LessThan150::
#if GERMAN
	.string "Unter 150.\n"
	.string "Weiter so!$"
#else
	.string "Don't forget, some POKéMON only\n"
	.string "appear at certain times of the day!$"
#endif

gNationalDexRatingText_LessThan200::
#if GERMAN
	.string "Unter 200.\n"
	.string "Weiter so!$"
#else
	.string "If you break rocks, some POKéMON\n"
	.string "that were hiding there might come\p"
	.string "jumping out!$"
#endif

gNationalDexRatingText_LessThan250::
#if GERMAN
	.string "Unter 250.\n"
	.string "Weiter so!$"
#else
	.string "That's wonderful you've been able\n"
	.string "to gather this many POKéMON!\p"
	.string "The path ahead is long. Keep up the\n"
	.string "great work!$"
#endif

gNationalDexRatingText_LessThan300::
#if GERMAN
	.string "Unter 300.\n"
	.string "Weiter so!$"
#else
	.string "If you Headbutt a tree, sometimes\n"
	.string "a POKéMON might fall out!$"
#endif

gNationalDexRatingText_LessThan350::
#if GERMAN
	.string "Unter 350.\n"
	.string "Weiter so!$"
#else
	.string "A lot of POKéMON not found in the\n"
	.string "Johto region like to congregate\p"
	.string "at the Safari Zone$"
#endif

gNationalDexRatingText_LessThan400::
@	.string "Musik im Radio könnte\n"
@	.string "Pokémon herauslocken$"
	.string "Es gibt überall versteckte\n"
	.string "Orte, überall auf der Welt.$"

gNationalDexRatingText_LessThan435::
#if GERMAN
	.string "Unter 435.\n"
	.string "Weiter so!$"
#else
	.string "Wow, you've gotten so far...!\n"
	.string "I'm actually a little surprised!$"
#endif

gNationalDexRatingText_LessThan465::
#if GERMAN
	.string "Unter 465.\n"
	.string "Weiter so!$"
#else
	.string "This is a critical moment!\n"
	.string "You can't become discouraged!$"
#endif

gNationalDexRatingText_LessThan475::
#if GERMAN
	.string "Unter 475.\n"
	.string "Weiter so!$"
#else
	.string "Just a little more!\n"
	.string "I've got high expectations for you!$"
#endif

gNationalDexRatingText_LessThanMaxDex::
#if GERMAN
	.string "Ich habe noch nie einen so\n"
	.string "herausragenden Trainer wie dich\l"
	.string "getroffen!$"
#else
	.string "I have never before in all my years\n"
	.string "seen such an incredible Trainer!$"
#endif

gNationalDexRatingText_Complete::
#if GERMAN
	.string "Ausgezeichnet! Der Nationale Pokédex\n"
	.string "ist ja vollständig!\p"
	.string "Ich habe mich nicht in dir getäuscht,\n"
	.string "als wir uns zum ersten Mal getroffen\l"
	.string "haben. Meine Entscheidung war\l"
	.string "goldrichtig!\p"
	.string "Ach, was sage ich! Du hast meine\n"
	.string "Erwartungen bei Weitem übertroffen,\l"
	.string "{PLAYER}! Dank dir!!!$"
#else
	.string "Excellent! That is an amazing\n"
	.string "National POKéDEX!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "You've lived up to my\n"
	.string "expectations wonderfully!\p"
	.string "No, you've exceeded them, {PLAYER}.\n"
	.string "You've become an amazing Trainer!\p"
	.string "Thank you, {PLAYER}!$"
#endif
