Questionnaire_Text_FillOut::
#if GERMAN
	.string "Dort liegt ein Fragebogen.\n"
	.string "Möchtest du ihn ausfüllen?$"
#else
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"
#endif

Questionnaire_Text_ThankYou::
#if GERMAN
	.string "Danke, dass du dir die Zeit genommen\n"
	.string "hast, den Fragebogen auszufüllen.\l"
	.string "Deine Antworten werden ausgewertet\l"
	.string "und zukünftig berücksichtigt.$"
#else
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"
#endif

Questionnaire_Text_YouKnowThoseWordsGift::
#if GERMAN
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "Geheimgeschehen Bescheid.\p"
	.string "Von nun an kannst du\n"
	.string "Geheimgeschehen empfangen.$"
#else
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"
#endif

Questionnaire_Text_YouCanAccessMysteryGift::
#if GERMAN
	.string "Sobald du dein Spiel gesichert hast,\n"
	.string "kannst du Geheimgeschehen auswählen.$"
#else
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"
#endif

Questionnaire_Text_YouKnowThoseWordsEvent::
#if GERMAN
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "Geheimgeschehen Bescheid.$"
#else
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY EVENT.$"
#endif

Questionnaire_Text_YouCanAccessMysteryEvent::
#if GERMAN
	.string "Sobald du dein Spiel gesichert hast,\n"
	.string "kannst du Geheimgeschehen auswählen.$"
#else
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY EVENT.$"
#endif

MysteryGift_Text_TheresATicketForYou::
#if GERMAN
	.string "Danke, dass du das Geheim-\n"
	.string "geschehen benutzt hast.\p"
	.string "Du musst {PLAYER} sein.\n"
	.string "Hier ist ein Ticket für dich!$"
#else
	.string "Thank you for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "There is a ticket here for you.$"
#endif

MysteryGift_Text_TryUsingItAtLilycovePort::
#if GERMAN
	.string "Du kannst es am Hafen von\n"
	.string "Seegrasulb City einsetzen.\p"
	.string "Warum probierst du es nicht\n"
	.string "einfach aus?$"
#else
	.string "It appears to be for use at\n"
	.string "the LILYCOVE CITY port.\p"
	.string "Why not give it a try and see what\n"
	.string "it is about?$"
#endif
