gText_WantToUseSurf::
#if GERMAN
	.string "Das Wasser ist tiefblau.\n"
	.string "Möchtest du Surfer einsetzen?$"
#else
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"
#endif

gText_PlayerUsedSurf::
#if GERMAN
	.string "{STR_VAR_1} setzt Surfer ein.$"
#else
	.string "{STR_VAR_1} used SURF!$"
#endif

Text_CurrentTooFast::
#if GERMAN
	.string "Die Strömung ist zu stark!\n"
	.string "Kann Surfer nicht verwenden…$"
#else
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"
#endif
