Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
#if GERMAN
	.string "Vor dem Schwimmen muss ich mich\n"
	.string "noch aufwärmen!$"
#else
	.string "I have to exercise and warm up\n"
	.string "before going out for a swim.$"
#endif

Route19_Text_RichardDefeat::
#if GERMAN
	.string "Wunderbar, jetzt ist mir warm!$"
#else
	.string "All warmed up!$"
#endif

Route19_Text_RichardPostBattle::
#if GERMAN
	.string "Danke!\n"
	.string "Jetzt kann ich schwimmen gehen!$"
#else
	.string "Thanks, kid!\n"
	.string "I'm ready for a swim.$"
#endif

Route19_Text_ReeceIntro::
#if GERMAN
	.string "Warte! Sonst bekommst du einen\n"
	.string "Herzinfarkt!$"
#else
	.string "Wait! Slow down!\n"
	.string "You'll have a heart attack!$"
#endif

Route19_Text_ReeceDefeat::
#if GERMAN
	.string "Wuah!\n"
	.string "Mir ist kalt!$"
#else
	.string "Ooh!\n"
	.string "That's chilly!$"
#endif

Route19_Text_ReecePostBattle::
#if GERMAN
	.string "Nimm dich vor Tentacha in Acht!$"
#else
	.string "Watch out for TENTACOOL.\n"
	.string "They sting so painfully.$"
#endif

Route19_Text_MatthewIntro::
#if GERMAN
	.string "Ich gehe gerne schwimmen!\n"
	.string "Du auch?$"
#else
	.string "I love swimming!\n"
	.string "What about you?$"
#endif

Route19_Text_MatthewDefeat::
#if GERMAN
	.string "Man, war das ein Bauchplatscher!$"
#else
	.string "Belly flop!$"
#endif

Route19_Text_MatthewPostBattle::
#if GERMAN
	.string "Ich kann Pokémon besiegen, während\n"
	.string "ich schwimme!$"
#else
	.string "I can beat even marine POKéMON\n"
	.string "at swimming.$"
#endif

Route19_Text_DouglasIntro::
#if GERMAN
	.string "Was mag sich hinter dem Horizont\n"
	.string "verbergen?$"
#else
	.string "What's beyond the horizon?$"
#endif

Route19_Text_DouglasDefeat::
#if GERMAN
	.string "Blubber! Gluck!$"
#else
	.string "Glub!$"
#endif

Route19_Text_DouglasPostBattle::
#if GERMAN
	.string "Ich sehe eine Inselgruppe!$"
#else
	.string "I see a couple of islands over\n"
	.string "yonder!$"
#endif

Route19_Text_DavidIntro::
#if GERMAN
	.string "Ich wollte nach Pokémon tauchen,\n"
	.string "doch das war keine gute Idee!$"
#else
	.string "I tried diving for POKéMON, but it\n"
	.string "was a no-go.$"
#endif

Route19_Text_DavidDefeat::
#if GERMAN
	.string "Hilfe!$"
#else
	.string "Help!$"
#endif

Route19_Text_DavidPostBattle::
#if GERMAN
	.string "Nach Wasser-Pokémon sollte man\n"
	.string "lieber angeln!$"
#else
	.string "I guess you have to fish for sea\n"
	.string "POKéMON.$"
#endif

Route19_Text_TonyIntro::
#if GERMAN
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"
#else
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.$"
#endif

Route19_Text_TonyDefeat::
#if GERMAN
	.string "Nein!\n"
	.string "Ein traumatisches Erlebnis!$"
#else
	.string "Ooh!\n"
	.string "Traumatic!$"
#endif

Route19_Text_TonyPostBattle::
#if GERMAN
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!$"
#else
	.string "I'm looking at the sea to forget\n"
	.string "the bad thing that happened!$"
#endif

Route19_Text_AnyaIntro::
#if GERMAN
	.string "Gibst du mir das Pokémon, auf dem\n"
	.string "du stehst, wenn ich gewinne?$"
#else
	.string "Oh, I just love your ride!\n"
	.string "Can I have it if I win?$"
#endif

Route19_Text_AnyaDefeat::
#if GERMAN
	.string "Oh! Ich habe verloren!$"
#else
	.string "Oh! I lost!$"
#endif

Route19_Text_AnyaPostBattle::
#if GERMAN
	.string "Bis zu den {COLOR RED}Seeschauminseln{COLOR DARK_GRAY} ist es\n"
	.string "noch ein weiter Weg!$"
#else
	.string "It's still a long way to go to\n"
	.string "SEAFOAM ISLANDS…\p"
	.string "I want to go back to FUCHSIA…$"
#endif

Route19_Text_AliceIntro::
#if GERMAN
	.string "Schwimmen macht Spaß, aber man\n"
	.string "holt sich schnell einen\l"
	.string "Sonnenbrand!$"
#else
	.string "Swimming's great!\n"
	.string "Sunburns aren't!$"
#endif

Route19_Text_AliceDefeat::
#if GERMAN
	.string "Du bist ein ganz schlimmer Finger!$"
#else
	.string "Shocker!$"
#endif

Route19_Text_AlicePostBattle::
#if GERMAN
	.string "Mein Freund wollte zu den\n"
	.string "{COLOR RED}Seeschauminseln{COLOR DARK_GRAY} schwimmen.$"
#else
	.string "My boyfriend wanted to swim to\n"
	.string "SEAFOAM ISLANDS.$"
#endif

Route19_Text_AxleIntro::
#if GERMAN
	.string "Diese Gewässer sind trügerisch!$"
#else
	.string "Ahoy, there!\n"
	.string "These waters are treacherous!$"
#endif

Route19_Text_AxleDefeat::
#if GERMAN
	.string "Das war gefährlich!$"
#else
	.string "Ooh!\n"
	.string "Dangerous!$"
#endif

Route19_Text_AxlePostBattle::
#if GERMAN
	.string "Ich habe einen Krampf!\n"
	.string "Blubber, gluck...$"
#else
	.string "M-my legs! They cramped up!\n"
	.string "Glub, glub…$"
#endif

Route19_Text_ConnieIntro::
#if GERMAN
	.string "Ich bin hierher geschwommen und\n"
	.string "nun bin ich müde!$"
#else
	.string "I swam here with my friends…\n"
	.string "I'm tired…$"
#endif

Route19_Text_ConnieDefeat::
#if GERMAN
	.string "Ich bin am Ende meiner Kraft...$"
#else
	.string "I'm exhausted…$"
#endif

Route19_Text_ConniePostBattle::
#if GERMAN
	.string "Lapras ist so groß, dass es dich\n"
	.string "trockenen Fußes über das Wasser\l"
	.string "tragen kann!$"
#else
	.string "If I were to ride a POKéMON on\n"
	.string "the sea, I'd like a LAPRAS.\p"
	.string "LAPRAS is so big, I bet it\n"
	.string "would keep me dry on water.$"
#endif

Route19_Text_RouteSign::
#if GERMAN
	.string "See-Route 19\n"
	.string "Fuchsania City - Seeschauminseln$"
#else
	.string "SEA ROUTE 19\n"
	.string "FUCHSIA CITY - SEAFOAM ISLANDS$"
#endif

Route19_Text_LiaIntro::
#if GERMAN
	.string "Nora: Ich kümmere mich um\n"
	.string "meinen Bruder. Er ist vor\l"
	.string "kurzem ein Trainer geworden.$"
#else
	.string "LIA: I'm looking after my brother.\n"
	.string "He just became a TRAINER.$"
#endif

Route19_Text_LiaDefeat::
#if GERMAN
	.string "Nora: Das ist keine Art meinen\n"
	.string "kleinen Bruder zu behandeln.$"
#else
	.string "LIA: That's no way to treat my\n"
	.string "little brother!$"
#endif

Route19_Text_LiaPostBattle::
#if GERMAN
	.string "Nora: Hast du einen kleinen Bruder?\p"
	.string "Ich hoffe, du bringst ihm alles\n"
	.string "Mögliche bei.$"
#else
	.string "LIA: Do you have a younger\n"
	.string "brother?\p"
	.string "I hope you're teaching him all\n"
	.string "sorts of things.$"
#endif

Route19_Text_LiaNotEnoughMons::
#if GERMAN
	.string "Nora: Ich möchte mit meinem kleinen\n"
	.string "Bruder zusammen kämpfen.\p"
	.string "Hast du keine zwei Pokémon?$"
#else
	.string "LIA: I want to battle together\n"
	.string "with my little brother.\p"
	.string "Don't you have two POKéMON?$"
#endif

Route19_Text_LucIntro::
#if GERMAN
	.string "Tom: Meine große Schwester hat\n"
	.string "mir das Schwimmen beigebracht\l"
	.string "und mir gezeigt, wie man\l"
	.string "Pokémon trainiert.$"
#else
	.string "LUC: My big sis taught me how\n"
	.string "to swim and train POKéMON.$"
#endif

Route19_Text_LucDefeat::
#if GERMAN
	.string "Tom: Oh, wow!\n"
	.string "Es gibt jemand, der stärker als\l"
	.string "meine Schwester ist!$"
#else
	.string "LUC: Oh, wow!\n"
	.string "Someone tougher than my big sis!$"
#endif

Route19_Text_LucPostBattle::
#if GERMAN
	.string "Tom: Meine große Schwester ist\n"
	.string "stark und nett. Sie ist wundervoll.$"
#else
	.string "LUC: My big sis is strong and nice.\n"
	.string "I think she's awesome!$"
#endif

Route19_Text_LucNotEnoughMons::
#if GERMAN
	.string "Tom: Ich will nicht ohne meine\n"
	.string "Schwester gegen dich kämpfen.\p"
	.string "Hast du keine zwei Pokémon?$"
#else
	.string "LUC: I don't want to if I can't\n"
	.string "battle you with my big sis.\p"
	.string "Don't you have two POKéMON?$"
#endif
