SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
#if GERMAN
	.string "Hugh!\n"
	.string "Ich besiege dich mit links!$"
#else
	.string "Kyahaha!\n"
	.string "I'll flick you away effortlessly!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
#if GERMAN
	.string "Tss!\n"
	.string "Zu stark für mich!$"
#else
	.string "Tch!\n"
	.string "Too strong for me!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
#if GERMAN
	.string "Wie war das?\n"
	.string "Ich handle nicht nach meinem Aussehen?\l"
	.string "Heh, das ist ein Teil meiner Strategie!$"
#else
	.string "What's that?\n"
	.string "I don't act the way I look?\p"
	.string "Heh, that's a part of my strategy!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
#if GERMAN
	.string "Servus!\n"
	.string "Bist du in meinem Fanclub?$"
#else
	.string "Howdy!\n"
	.string "Are you a member of my fan club?$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
#if GERMAN
	.string "Oh, du bist kein Fan…\p"
	.string "Nun, das kann ich ändern.\n"
	.string "Ich singe nur für dich!$"
#else
	.string "Oh, so you're not a fan…\p"
	.string "Well, I can change that.\n"
	.string "Let me sing for you!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
#if GERMAN
	.string "Lalala…\n"
	.string "Ich schicke meine Pokémon hinaus und\l"
	.string "die Mädchen schreien!$"
#else
	.string "Lalalah…\n"
	.string "My POKéMON, I send them out,\l"
	.string "all the girls scream and shout!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
#if GERMAN
	.string "Die Insel ist so weitläufig…\n"
	.string "Es ist schwierig, sie zu bewachen.$"
#else
	.string "This island is too spread out…\n"
	.string "It's not easy patrolling the place.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
#if GERMAN
	.string "Uh-uh…$"
#else
	.string "Uh-huh…$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
#if GERMAN
	.string "Trainer, die wie du aus Städten\n"
	.string "kommen, sind stark.\p"
	.string "Du bist auf dem Weg zum Turm, \n"
	.string "nicht wahr?$"
#else
	.string "TRAINERS like you from cities,\n"
	.string "they sure are tough.\p"
	.string "You'll be headed for the TOWER,\n"
	.string "won't you?$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
#if GERMAN
	.string "Ich bestrafe Leute, die Pokémon\n"
	.string "missbrauchen!$"
#else
	.string "I punish people who abuse\n"
	.string "POKéMON!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
#if GERMAN
	.string "Du scheinst kein Problem dar-\n"
	.string "zustellen, Trainer.$"
#else
	.string "You don't seem to be a problem\n"
	.string "TRAINER.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
#if GERMAN
	.string "Behandelst du deine Pokémon\n"
	.string "freundlich, verstehen sie dich.$"
#else
	.string "If you treat your POKéMON with\n"
	.string "kindness, they'll understand.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
#if GERMAN
	.string "Tizia: Ich bilde ein Team mit Till\n"
	.string "und wir kämpfen gemeinsam.$"
#else
	.string "EVE: I'll team up with JON and\n"
	.string "battle together.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
#if GERMAN
	.string "Tizia: Till und ich haben verloren. Hehe!$"
#else
	.string "EVE: Me and JON, we lost.\n"
	.string "Ehehe.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
#if GERMAN
	.string "Tizia: Ich muss härter mit Till\n"
	.string "trainieren.$"
#else
	.string "EVE: I'm going to work harder with\n"
	.string "JON.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
#if GERMAN
	.string "Tizia: Ich möchte gemeinsam mit Till\n"
	.string "gegen dich antreten.\p"
	.string "Komme mit zwei Pokémon wieder!$"
#else
	.string "EVE: I want to team up with JON\n"
	.string "when I battle you.\p"
	.string "Come back with two POKéMON, okay?$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
#if GERMAN
	.string "Till: Wenn ich an der Seite von Tizia bin,\n"
	.string "fühle ich, dass wir nicht verlieren\l"
	.string "können…$"
#else
	.string "JON: When I'm with EVE, it feels\n"
	.string "like we could never lose.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
#if GERMAN
	.string "Till: Wenn ich an der Seite von Tizia bin,\n"
	.string "fühle ich, dass wir nicht verloren\l"
	.string "haben…$"
#else
	.string "JON: When I'm with EVE,\n"
	.string "it doesn't feel like I've lost!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
#if GERMAN
	.string "Till: Wenn ich an der Seite von Tizia bin,\n"
	.string "ist mir schwindelig, egal, ob ich gewinne\l"
	.string "oder verliere.$"
#else
	.string "JON: When I'm with EVE, I feel\n"
	.string "giddy whether I win or lose.\p"
	.string "It's magical!$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
#if GERMAN
	.string "Till: Wenn ich mit Tizia gegen dich\n"
	.string "kämpfe, bin ich glücklich.\p"
	.string "Ich möchte also einen Zwei-gegen-\n"
	.string "Zwei-Kampf mit dir austragen.$"
#else
	.string "JON: If it's with EVE, I'll be\n"
	.string "happy to battle with you.\p"
	.string "So, I'd like to make it a\n"
	.string "two-on-two battle, if I may.$"
#endif

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
#if GERMAN
	.string "Eingang zur 7-Schatzschlucht\p"
	.string "Trainer werden gebeten, die Pflanzen in\n"
	.string "der Schlucht nicht zu beschädigen!$"
#else
	.string "SEVAULT CANYON ENTRANCE\p"
	.string "TRAINERS are asked to refrain from\n"
	.string "damaging plants in the CANYON.$"
#endif

