Route42_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route42_MapScript_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route42_MapScript_OnTransition::
	call_if_set FLAG_HIDE_ROUTE42_SUICUNE, Route42_MapScript_HideTrigger
	callnative SetTimeBasedEncounters
	end

Route42_MapScript_HideTrigger::
	setvar VAR_TEMP_0, 1
	return

Route42_EventScript_Suicune_Trigger::
	lock
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	waitmoncry
	playse SE_PIN
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	delay 60
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune2
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	waitmovement 0

	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement LOCALID_ROUTE42_SUICUNE, Route42_Movement_Suicune3
	applymovement OBJ_EVENT_ID_PLAYER, Route42_Movement_Player
	playse SE_LEDGE
	delay 60
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	waitmovement LOCALID_ROUTE42_SUICUNE
	waitmovement 0
	delay 60
	removeobject LOCALID_ROUTE42_SUICUNE
	setflag FLAG_HIDE_ROUTE42_SUICUNE
	clearflag FLAG_HIDE_ROUTE42_EUSINE
	addobject LOCALID_ROUTE42_EUSINE
	playse SE_EXIT
	turnobject OBJ_EVENT_ID_PLAYER, DIR_EAST
	applymovement LOCALID_ROUTE42_EUSINE, Route42_Movement_Eusine1
	waitmovement 0
	msgbox Route42_Text_EusineAdmireSuicune, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_ROUTE42_EUSINE, DIR_WEST
	msgbox Route42_Text_EusineJealous, MSGBOX_DEFAULT
	turnobject LOCALID_ROUTE42_EUSINE, DIR_EAST
	msgbox Route42_Text_EusineWontGiveUp, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROUTE42_EUSINE, Route42_Movement_Eusine2
	waitmovement 0
	setflag FLAG_HIDE_ROUTE42_EUSINE
	removeobject LOCALID_ROUTE42_EUSINE
	setvar VAR_TEMP_0, 1
	call_if_eq VAR_SUICUNE_ENCOUNTERS, 2, Route42_EventScript_DoneJohtoSuicune
	release
	end

Route42_EventScript_DoneJohtoSuicune::
	setvar VAR_SUICUNE_ENCOUNTERS, 3
	return

Route42_Movement_Suicune1:
	jump_in_place_right_left
	jump_in_place_right_left
	step_end

Route42_Movement_Suicune2:
	jump_2_left
	jump_2_left
	jump_2_left
	jump_2_up
	step_end

Route42_Movement_Suicune3:
	jump_in_place_up
	delay_2
	face_up
	jump_2_up
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	jump_2_right
	step_end

Route42_Movement_Player:
	lock_facing_direction
	delay_2
	jump_2_up
	unlock_facing_direction
	step_end

Route42_Movement_Eusine1:
	walk_down
	walk_down
	walk_left
	face_right
	step_end

Route42_Movement_Eusine2:
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	step_end

Route42_Text_EusineAdmireSuicune:
#if GERMAN
	.string "Eusin: Suicune… Du bist so tapfer… Du\n"
	.string "bist so jung und schön… Du bist so\l"
	.string "anmutig… Und du bist immer so schnell\l"
	.string "wieder weg!$"
#else
	.string "EUSINE: SUICUNE...\n"
	.string "How brave it is!\p"
	.string "How refreshing it is!\n"
	.string "How beautiful it is!\p"
	.string "And how quickly it moves!$"
#endif

Route42_Text_EusineJealous:
#if GERMAN
    .string "{PLAYER}!\p"
    .string "Du scheinst immer dort zu sein,\n"
    .string "wo Suicune auftaucht.\p"
    .string "Nun gut. Mein Verlangen,\n"
    .string "Suicune zu finden,\l"
    .string "übertrifft deines bei\p"
    .string "Weitem…\p"
    .string "Mein Großvater war…\n"
    .string "sehr von Legenden begeistert.\p"
    .string "Ich habe von ihm unzählige\n"
    .string "Geschichten über Suicune gehört.$"
#else
	.string "{PLAYER}!\p"
	.string "You seem to be around where\n"
	.string "SUICUNE would appear.\p"
	.string "Well, that's OK.\l"
	.string "My desire to search for\n"
	.string "SUICUNE is far beyond yours...\p"
	.string "My grandpa was... quite into\n"
	.string "myths.\p"
	.string "I've heard so many stories\n"
	.string "about SUICUNE from him.$"
#endif

Route42_Text_EusineWontGiveUp:
#if GERMAN
	.string "Suicune…\p"
	.string "Ich werde nicht eher ruhen, bis ich\n"
	.string "herausgefunden habe, wohin dich deine\l"
	.string "Reise führt…\p"
	.string "Ach ja, hab ich das nicht schön gesagt?$"
#else
	.string "SUICUNE...\n"
	.string "I won't stop following you\l"
	.string "until I've found out what\l"
	.string "you're after...\p"
	.string "You hear me!$"
#endif


Route42_EventScript_Tully::
	trainerbattle_single TRAINER_TULLY_HNS, Route42_Text_FisherTullySeen, Route42_Text_FisherTullyBeaten, Route42_EventScript_RegisterTully
	goto_if_set FLAG_TULLY_HAS_ITEM_HNS, Route42_EventScript_TullyGiveItem
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, Route42_EventScript_RematchTully
	msgbox Route42_Text_FisherTullyAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_RegisterTully::
	special PlayerFaceTrainerAfterBattle
	waitmovement 0
	msgbox Route42_Text_TullyRegister, MSGBOX_DEFAULT
	register_matchcall TRAINER_TULLY_HNS
	release
	end

Route42_EventScript_RematchTully::
	trainerbattle_rematch TRAINER_TULLY_HNS, Route42_Text_TullyRematchIntro, Route42_Text_TullyRematchDefeat
	msgbox Route42_Text_TullyPostRematch, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_TullyGiveItem::
	msgbox Route42_Text_TullyHasItem, MSGBOX_DEFAULT
	giveitem VAR_TULLY_ITEM_HNS
	goto_if_eq VAR_RESULT, FALSE, Route42_EventScript_TullyNoRoom
	clearflag FLAG_TULLY_HAS_ITEM_HNS
	msgbox Route42_Text_TullyGaveItem, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_TullyNoRoom::
	msgbox Route42_Text_TullyNoRoom, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Ben::
	trainerbattle_single TRAINER_BENJAMIN_HNS, Route42_Text_HikerBenjaminSeen, Route42_Text_HikerBenjaminBeaten
	msgbox Route42_Text_HikerBenjaminAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Shane::
	trainerbattle_single TRAINER_SHANE_HNS, Route42_Text_PokemaniacShaneSeen, Route42_Text_PokemaniacShaneBeaten
	msgbox Route42_Text_PokemaniacShaneAfter, MSGBOX_AUTOCLOSE
	end

Route42_EventScript_Sign::
	lock
	msgbox Route42_Text_Sign1, MSGBOX_SIGN
	closemessage
	release
	end

Route42_EventScript_MortarSign::
	lock
	msgbox Route42_Text_MtMortarSign1, MSGBOX_SIGN
	closemessage
	release
	end

Route42_EventScript_Item_SuperPotion::
	finditem ITEM_SUPER_POTION
	end
Route42_EventScript_Item_Shadow_Claw::
    finditem ITEM_TM_SHADOW_CLAW
    end
Route42_EventScript_Item_UltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route42_Text_FisherTullySeen:
#if GERMAN
	.string "Jetzt demonstriere ich dir die Kraft\n"
	.string "des Pokémon, das ich gefangen habe!$"
#else
	.string "Let me demonstrate the power\n"
	.string "of the POKéMON I caught!$"
#endif

Route42_Text_FisherTullyBeaten:
#if GERMAN
	.string "Was? Das kann nicht sein.$"
#else
	.string "What? That's not right.\n"
	.string "I can't believe this!$"
#endif

Route42_Text_FisherTullyAfter:
#if GERMAN
	.string "Mit dem Pokémon, das ich geangelt habe,\n"
	.string "werde ich der beste Trainer von allen!\l"
	.string "Das ist das A und O eines jeden Anglers!$"
#else
	.string "I want to become the trainer\n"
	.string "CHAMP using the POKéMON I\l"
	.string "caught myself.\p"
	.string "That's the best part of fishing!$"
#endif

Route42_Text_HikerBenjaminSeen:
#if GERMAN
	.string "Ach, ist das schön,\n"
	.string "im Freien zu sein! Ich fühle\l"
	.string "mich so frei!$"
#else
	.string "Ah, it's good to be outside!\n"
	.string "I feel so free!$"
#endif

Route42_Text_HikerBenjaminBeaten:
#if GERMAN
	.string "Hahaha!$"
#else
	.string "Gahahah! That was a good\n"
	.string "battle!$"
#endif

Route42_Text_HikerBenjaminAfter:
#if GERMAN
	.string "Humbug!$"
#else
	.string "Losing feels insignificant\n"
	.string "if you look up at the big sky!$"
#endif

Route42_Text_PokemaniacShaneSeen:
#if GERMAN
	.string "He!\p"
	.string "Das ist mein Geheimversteck!\n"
	.string "Verschwinde, du Außenseiter!$"
#else
	.string "HEY!\p"
	.string "This is my secret place!\n"
	.string "Get lost, you outsider!$"
#endif

Route42_Text_PokemaniacShaneBeaten:
#if GERMAN
	.string "Ich hätte meinen\n"
	.string "Mondstein verwenden sollen…$"
#else
	.string "I should have used my\n"
	.string "MOON STONE…$"
#endif

Route42_Text_PokemaniacShaneAfter:

Route42_Text_Sign1:
#if GERMAN
	.string "Route 42\p"
	.string "Teak City - Mahagonia City$"
#else
	.string "ROUTE 42\p"
	.string "ECRUTEAK CITY - MAHOGANY TOWN$"
#endif

Route42_Text_MtMortarSign1:
#if GERMAN
	.string "Kesselberg\p"
	.string "Im Inneren des Bergs befindet sich eine\n"
	.string "Höhle mit einem großen Wasserfall.$"
#else
	.string "MT.MORTAR\p"
	.string "WATERFALL CAVE INSIDE$"
#endif

Route42_Text_TullyRegister:
#if GERMAN
    .string "Ich will mit den Pokémon, die\n"
    .string "ich selbst gefangen habe,\l"
    .string "Pokémon-Champ werden.\p"
    .string "Das ist das Beste am Angeln!$"
#else
	.string "I want to become the trainer\n"
	.string "CHAMP using the POKéMON I\l"
	.string "caught myself.\p"
	.string "That's the best part of fishing!$"
#endif

Route42_Text_TullyRematchIntro:
#if GERMAN
	.string "Jetzt demonstriere ich dir die Kraft\n"
	.string "des Pokémon, das ich gefangen habe!$"
#else
	.string "Let me demonstrate the power\n"
	.string "of the POKéMON I caught!$"
#endif

Route42_Text_TullyRematchDefeat:
#if GERMAN
    .string "Was? Das kann nicht sein.\n"
    .string "Ich glaube es einfach nicht!$"
#else
	.string "What? That's not right.\n"
	.string "I can't believe this!$"
#endif

Route42_Text_TullyPostRematch:
#if GERMAN
    .string "Ich will mit den Pokémon, die\n"
    .string "ich selbst gefangen habe,\l"
    .string "Pokémon-Champ werden.\p"
    .string "Das ist das Beste am Angeln!$"
#else
	.string "I want to become the trainer\n"
	.string "CHAMP using the POKéMON I\l"
	.string "caught myself.\p"
	.string "That's the best part of fishing!$"
#endif

Route42_Text_TullyHasItem:
#if GERMAN
    .string "Hey! Ich habe beim Angeln\n"
    .string "etwas gefunden!\p"
    .string "Hier, du kannst es haben!$"
#else
	.string "Hey! I found something\n"
	.string "while I was fishing!\p"
	.string "Here, you can have it!$"
#endif

Route42_Text_TullyGaveItem:
#if GERMAN
    .string "Ich sage dir Bescheid, wenn\n"
    .string "ich noch etwas an Land ziehe!$"
#else
	.string "I'll let you know if I\n"
	.string "reel in anything else!$"
#endif

Route42_Text_TullyNoRoom:
#if GERMAN
    .string "Hm, dein Beutel ist voll.\p"
    .string "Komm wieder, wenn du Platz hast.$"
#else
	.string "Hmm, your BAG is full.\p"
	.string "Come back when you have room.$"
#endif
