NewBarkTown_PlayersHouse_1F_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, NewBarkTown_PlayersHouse_1F_OnTransition
	.byte 0

NewBarkTown_PlayersHouse_1F_OnTransition::
	call_if_eq VAR_NEWBARK_TOWN_STATE, 1, NewBarkTown_PlayersHouse_1F_SetMomStandingAtTable
	call_if_eq VAR_NEWBARK_TOWN_STATE, 2, NewBarkTown_PlayersHouse_1F_SetMomStandingAtTable
	call_if_eq VAR_NEWBARK_TOWN_STATE, 3, NewBarkTown_PlayersHouse_1F_SetMomStandingAtTable
	end

NewBarkTown_PlayersHouse_1F_SetMomStandingAtTable::
	setobjectxyperm LOCALID_MOM, 8, 4
	setobjectmovementtype LOCALID_MOM, MOVEMENT_TYPE_FACE_LEFT

	@add to newgame later
	clearflag FLAG_HIDE_MOMS_FRIEND
	clearflag FLAG_MOM_VISITED
	return

NewBarkTown_PlayersHouse_1F_EventScript_Mom::
	lock
	faceplayer
	goto_if_set FLAG_MOM_VISITED, NewBarkTown_PlayersHouse_1F_EventScript_Mom_Regular
	goto_if_set FLAG_ADVENTURE_STARTED, NewBarkTown_PlayersHouse_1F_MomEventScript_GoodLuck
	msgbox NewBarkTown_PlayersHouse_1F_Text_MomHurryUpElmIsWaiting, MSGBOX_DEFAULT
	applymovement LOCALID_MOM, NewBarkTown_PlayersHouse_1F_MovementFaceLeft
	waitmovement 0
	release
	end

NewBarkTown_PlayersHouse_1F_EventScript_MomsFriend::
	lock
	faceplayer
	msgbox NewBarkTown_PlayersHouse_1F_Text_MomsFriend, MSGBOX_DEFAULT
	applymovement LOCALID_MOMS_FRIEND, NewBarkTown_PlayersHouse_1F_MovementFaceRight
	waitmovement 0
	release
	end

NewBarkTown_PlayersHouse_1F_MomEventScript_GoodLuck::
	msgbox NewBarkTown_PlayersHouse_1F_Text_MomLeaving, MSGBOX_DEFAULT
	setflag FLAG_MOM_VISITED
	clearflag FLAG_HIDE_ROUTE_30_NPCS
	setvar VAR_NEWBARK_TOWN_STATE, 5
	release
	end


NewBarkTown_PlayersHouse_1F_EventScript_Mom_Regular::
	specialvar VAR_RESULT, IsPokecenterChallengeActivated
	goto_if_eq VAR_RESULT, TRUE, NewBarkTown_PlayersHouse_1F_EventScript_Mom_PokecenterChallenge
	msgbox PlayersHouse_1F_Text_YouShouldRestABit, MSGBOX_DEFAULT
	closemessage
	call Common_EventScript_OutOfCenterPartyHeal
	incrementgamestat GAME_STAT_RESTED_AT_HOME
	call NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	release
	end

NewBarkTown_PlayersHouse_1F_EventScript_Mom_PokecenterChallenge::
	msgbox PlayersHouse_1F_Text_YouShouldRestABit_PokecenterChallenge, MSGBOX_DEFAULT
	call NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	release
	end

NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu::
	special Special_MomEnsureInitialized
	msgbox NewBarkTown_PlayersHouse_1F_Text_MomAnythingElse, MSGBOX_DEFAULT
	multichoice 0, 0, MULTI_MOM_MENU, FALSE
	switch VAR_RESULT
	case 0, NewBarkTown_PlayersHouse_1F_EventScript_CheckSavings
	case 1, NewBarkTown_PlayersHouse_1F_EventScript_Deposit
	case 2, NewBarkTown_PlayersHouse_1F_EventScript_Withdraw
	case 3, NewBarkTown_PlayersHouse_1F_EventScript_ToggleSaving
	case 4, NewBarkTown_PlayersHouse_1F_EventScript_ExitSavings
	case MULTI_B_PRESSED, NewBarkTown_PlayersHouse_1F_EventScript_ExitSavings
	end

NewBarkTown_PlayersHouse_1F_EventScript_CheckSavings::
	special Special_MomGetBalance
	msgbox NewBarkTown_PlayersHouse_1F_Text_CurrentSavings, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_Deposit::
	checkmoney 1
	compare VAR_RESULT, FALSE
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_DepositFailed
	closemessage
	special Special_MomOpenDepositInput
	waitstate
	compare VAR_0x8000, 0
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	msgbox NewBarkTown_PlayersHouse_1F_Text_DepositSuccess, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_DepositFailed::
	msgbox NewBarkTown_PlayersHouse_1F_Text_NoMoneyToDeposit, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_Withdraw::
	special Special_MomGetBalance
	compare VAR_RESULT, 0
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_WithdrawFailed
	closemessage
	special Special_MomOpenWithdrawInput
	waitstate
	compare VAR_0x8000, 0
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	msgbox NewBarkTown_PlayersHouse_1F_Text_WithdrawSuccess, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_WithdrawFailed::
	msgbox NewBarkTown_PlayersHouse_1F_Text_NoMoneyToWithdraw, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_ToggleSaving::
	special Special_MomIsSavingEnabled
	compare VAR_RESULT, TRUE
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_DisableSaving
	msgbox NewBarkTown_PlayersHouse_1F_Text_EnableSaving, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_ConfirmEnable
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_ConfirmEnable::
	special Special_MomEnableSaving
	msgbox NewBarkTown_PlayersHouse_1F_Text_SavingEnabled, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_DisableSaving::
	msgbox NewBarkTown_PlayersHouse_1F_Text_DisableSaving, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq NewBarkTown_PlayersHouse_1F_EventScript_ConfirmDisable
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_ConfirmDisable::
	special Special_MomDisableSaving
	msgbox NewBarkTown_PlayersHouse_1F_Text_SavingDisabled, MSGBOX_DEFAULT
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomSavingsMenu
	end

NewBarkTown_PlayersHouse_1F_EventScript_ExitSavings::
	msgbox NewBarkTown_PlayersHouse_1F_Text_Goodbye, MSGBOX_DEFAULT
	return

NewBarkTown_PlayersHouse_1F_Text_MomAnythingElse:
#if GERMAN
	.string "Kann ich dir sonst noch helfen,\n"
	.string "Liebling?$"
#else
	.string "Is there anything else I can\n"
	.string "help you with, sweetie?$"
#endif

NewBarkTown_PlayersHouse_1F_Text_CurrentSavings:
#if GERMAN
	.string "Ich habe {STR_VAR_2} für dich gespart.$"
#else
	.string "I'm holding {STR_VAR_2}\n"
	.string "for you right now.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_EnableSaving:
#if GERMAN
	.string "Möchtest du, dass ich etwas von\n"
	.string "dem Geld spare, das du verdienst?$"
#else
	.string "Do you want me to save some of the\n"
	.string "money you earn?$"
#endif

NewBarkTown_PlayersHouse_1F_Text_SavingEnabled:
#if GERMAN
	.string "Okay! Ich spare 25% des Geldes von\n"
	.string "deinen Kämpfen.$"
#else
	.string "Okay! I'll save 25% of\n"
	.string "the money you earn from battles.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_DisableSaving:
#if GERMAN
	.string "Möchtest du, dass ich nicht mehr für\n"
	.string "dich spare?$"
#else
	.string "Would you like me to stop\n"
	.string "saving for you?$"
#endif

NewBarkTown_PlayersHouse_1F_Text_SavingDisabled:
#if GERMAN
	.string "Okay, ich höre auf zu sparen.$"
#else
	.string "Okay, I'll stop saving for now.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_Goodbye:
#if GERMAN
	.string "Sei vorsichtig, Liebling!$"
#else
	.string "Take care, sweetie!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_DepositSuccess:
#if GERMAN
	.string "Mama: Hört sich gut an!\n"
	.string "Das kommt ins Sparschwein.$"
#else
	.string "MOM: Sounds good! I'll put that in\n"
	.string "savings for you.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_WithdrawSuccess:
#if GERMAN
	.string "Mama: Hier!$"
#else
	.string "MOM: Here you go!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_NoMoneyToDeposit:
#if GERMAN
	.string "Mama: Du hast leider kein Geld,\n"
	.string "das du sparen könntest, Liebling.$"
#else
	.string "MOM: You don't have any money to\n"
	.string "deposit right now, sweetie.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_NoMoneyToWithdraw:
#if GERMAN
	.string "Mama: Ich habe noch kein Geld\n"
	.string "für dich, Liebling$"
#else
	.string "MOM: I haven't saved any money\n"
	.string "for you yet, honey.$"
#endif

NewBarkTown_PlayersHouse_1F_EventScript_MomsIntroTrigger1::
	lock
	applymovement OBJ_EVENT_ID_PLAYER, NewBarkTown_PlayersHouse_1F_PlayerIntroMovement1
	waitmovement 0
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomsIntro
	end

NewBarkTown_PlayersHouse_1F_EventScript_MomsIntroTrigger2::
	lock
	applymovement OBJ_EVENT_ID_PLAYER, NewBarkTown_PlayersHouse_1F_PlayerIntroMovement2
	waitmovement 0
	goto NewBarkTown_PlayersHouse_1F_EventScript_MomsIntro
	end


NewBarkTown_PlayersHouse_1F_EventScript_MomsIntro::
	playse SE_PIN
	applymovement LOCALID_MOM, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_MOM
	applymovement LOCALID_MOM, NewBarkTown_PlayersHouse_1F_MomMovement_1
	waitmovement 0
	msgbox NewBarkTown_PlayersHouse_1F_Text_ElmsLookingForYou, MSGBOX_DEFAULT
	call NewBarkTown_PlayersHouse_1F_EventScript_GivePokeGear
	call NewBarkTown_PlayersHouse_1F_EventScript_GiveRunningShoes
	applymovement LOCALID_MOM, NewBarkTown_PlayersHouse_1F_MomMovement_2
	waitmovement 0
	setvar VAR_NEWBARK_TOWN_STATE, 2
	setvar VAR_NEWBARKTOWN_LABSTATE, 0
	setflag FLAG_HIDE_LAB_POLICEMAN
	setflag FLAG_VISITED_NEWBARK_TOWN

	@former flagheap location

	releaseall
	end



NewBarkTown_PlayersHouse_1F_EventScript_GivePokeGear::
	playfanfare MUS_OBTAIN_ITEM
	message NewBarkTown_PlayersHouse_1F_Text_ObtainedPokeGear
	waitfanfare
	setflag FLAG_SYS_POKENAV_GET
	setflag FLAG_HAS_MATCH_CALL
	setflag FLAG_RECEIVED_POKENAV
	setflag FLAG_ADDED_MATCH_CALL_TO_POKENAV
	setflag FLAG_REGISTER_RIVAL_POKENAV
	msgbox NewBarkTown_PlayersHouse_1F_Text_ExplainPokeGear, MSGBOX_DEFAULT
	closemessage
	delay 30
	return

NewBarkTown_PlayersHouse_1F_EventScript_GiveRunningShoes::
	msgbox NewBarkTown_PlayersHouse_1F_Text_WearTheseRunningShoes, MSGBOX_DEFAULT
	waitmessage
	closemessage
	playfanfare MUS_OBTAIN_ITEM
	msgbox NewBarkTown_PlayersHouse_1F_Text_SwitchShoesWithRunningShoes, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	setflag FLAG_RECEIVED_RUNNING_SHOES
	setflag FLAG_SYS_B_DASH
	msgbox NewBarkTown_PlayersHouse_1F_Text_ExplainRunningShoes, MSGBOX_DEFAULT
	closemessage
	delay 30
	return

NewBarkTown_PlayersHouse_1F_PlayerIntroMovement1:
	delay_8
	walk_down
	walk_right
	walk_down
	face_left
	delay_8
	step_end

NewBarkTown_PlayersHouse_1F_PlayerIntroMovement2:
	delay_8
	walk_down
	face_left
	delay_8
	step_end

NewBarkTown_PlayersHouse_1F_MomMovement_1:
	face_right
	walk_right
	step_end

NewBarkTown_PlayersHouse_1F_MomMovement_2:
	face_left
	walk_left
	delay_8
	step_end

NewBarkTown_PlayersHouse_1F_MovementFaceRight:
	face_right
	step_end

NewBarkTown_PlayersHouse_1F_MovementFaceLeft:
	face_left
	step_end

NewBarkTown_PlayersHouse_1F_Text_ElmsLookingForYou:
#if GERMAN
	.string "Oh, {PLAYER}…! Unser Nachbar,\n"
	.string "Prof. Lind, sucht nach dir.\p"
	.string "Er will, dass du ihm bei etwas hilfst.\p"
	.string "Oh! Fast vergessen! Dein PokéCom kam\n"
	.string "fertig aus der Werkstatt.\p"
	.string "Hier, nimm ihn!$"
#else
	.string "Oh, {PLAYER}…! Our neighbor,\n"
	.string "PROF.ELM, was looking for you.\p"
	.string "He said he wanted you to do\n"
	.string "something for him.\p"
	.string "Oh! I almost forgot! Your POKéGEAR\n"
	.string "is back from the repair shop.\p"
	.string "Here you go!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_ObtainedPokeGear:
#if GERMAN
	.string "{PLAYER} erhielt das PokéCom.$"
#else
	.string "{PLAYER} obtained the POKéGEAR.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_ExplainPokeGear:
#if GERMAN
	.string "Mama: Telefonnummern befinden\n"
	.string "sich im Speicher.\p"
	.string "Wähle einfach einen Namen aus,\n"
	.string "um anzurufen.\p"
	.string "Wie praktisch!$"
#else
	.string "MOM: Phone numbers are stored\n"
	.string "in memory.\p"
	.string "Just choose a name you want to call.\p"
	.string "Gee, isn't that convenient?$"
#endif

NewBarkTown_PlayersHouse_1F_Text_WearTheseRunningShoes:
#if GERMAN
	.string "Oh, und vergiss nicht deine\n"
	.string "Turbotreter!$"
#else
	.string "Oh, and don't forget your\n"
	.string "RUNNING SHOES!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_SwitchShoesWithRunningShoes:
#if GERMAN
	.string "{PLAYER} tauschte Schuhe gegen\n"
	.string "die Turbotreter.$"
#else
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"
#endif

NewBarkTown_PlayersHouse_1F_Text_ExplainRunningShoes:
#if GERMAN
	.string "Mama: {PLAYER}, halte B gedrückt,\n"
	.string "um mit diesen Schuhen zu laufen!$"
#else
	.string "MOM: {PLAYER}, press the B Button\n"
	.string "while wearing these to run fast!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_MomHurryUpElmIsWaiting:
#if GERMAN
	.string "Mama: Prof. Lind wartet auf dich.\p"
	.string "Beeil dich, Liebling!$"
#else
	.string "MOM: PROF.ELM is waiting for you.\p"
	.string "Hurry up, baby!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_MomsFriend:
#if GERMAN
	.string "Hi, {PLAYER}!\p"
	.string "Ich besuche euch!\p"
	.string "Hast du schon gehört?\p"
	.string "Meine Tochter will unbedingt Prof. Linds\n"
	.string "Assistentin werden.\p"
	.string "Sie liebt Pokémon wirklich sehr!$"
#else
	.string "Hi, {PLAYER}!\p"
	.string "I'm visiting!\p"
	.string "Have you heard?\p"
	.string "My daughter is adamant about\n"
	.string "becoming PROF.ELM's assistant.\p"
	.string "She really loves POKéMON!$"
#endif

NewBarkTown_PlayersHouse_1F_Text_MomLeaving:
#if GERMAN
	.string "Mama: Oh, was für ein süßes Pokémon!\p"
	.string "Wo hast du es her?\p"
	.string "…\p"
	.string "Du gehst also auf ein Abenteuer…\n"
	.string "Das wird bestimmt schwierig…\p"
	.string "Pass gut auf dich auf.\p"
	.string "Pokémon sind deine Freunde.\n"
	.string "Ihr müsst als Team arbeiten.\p"
	.string "Jetzt los!\n"
	.string "Ich stehe hinter dir!$"
#else
	.string "MOM: Wow, that's a cute POKéMON.\n"
	.string "Where did you get it?\p"
	.string "…\p"
	.string "So, you're leaving on an adventure...\n"
	.string "That does sound challenging...\p"
	.string "Just be careful.\p"
	.string "POKéMON are your friends.\n"
	.string "You need to work as a team.\p"
	.string "Now, go on!\n"
	.string "I'm behind you all the way!$"
#endif
