TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
#if GERMAN
	.string "Ich habe die ultimative Attacke\n"
	.string "dieser Elementklasse perfektioniert!\p"
	.string "Aber wird sie in Zukunft von niemandem\n"
	.string "eingesetzt?\p"
	.string "… hm?\p"
	.string "D-du…\n"
	.string "Da-das {STR_VAR_1}…$"
#else
	.string "I perfected the ultimate move of\n"
	.string "its type…\p"
	.string "But will no one take it for\n"
	.string "future use?\p"
	.string "…Hm? Hmmm!\p"
	.string "Y-you…\n"
	.string "Th-that {STR_VAR_1}…$"
#endif

Text_JustMistaken::
#if GERMAN
	.string "… nein…\n"
	.string "Ich hatte Unrecht.$"
#else
	.string "…No…\n"
	.string "I was just mistaken.$"
#endif

Text_AllowMeToTeachMonUltimateMove::
#if GERMAN
	.string "Oh! Das ist es!\n"
	.string "Das ist das Pokémon!\p"
	.string "Dieses {STR_VAR_1} ist des Erlernens\n"
	.string "meiner Attacke würdig!\p"
	.string "Lässt du es zu?\p"
	.string "Darf dein {STR_VAR_1} {STR_VAR_2}\n"
	.string "lernen?$"
#else
	.string "Oh! This is the one!\n"
	.string "This is the POKéMON!\p"
	.string "This {STR_VAR_1} is worthy of\n"
	.string "learning my ultimate move!\p"
	.string "Will you allow it?\p"
	.string "Will you allow your {STR_VAR_1} to\n"
	.string "learn my {STR_VAR_2}?$"
#endif

Text_YouRejectIt::
#if GERMAN
	.string "Wie?!? Du lehnst es ab? Nein, ich\n"
	.string "lasse mich davon nicht abbringen!$"
#else
	.string "Gaah! You reject it?\n"
	.string "No, I won't be dissuaded!$"
#endif

Text_LetMeConferUltimateMove::
#if GERMAN
	.string "Du lässt es zu?\p"
	.string "Somit lehre ich {STR_VAR_2} deinem\n"
	.string "{STR_VAR_1}.\p"
	.string "Cool!$"
#else
	.string "You will allow it?\p"
	.string "Then, let me confer my ultimate\n"
	.string "{STR_VAR_2} on your {STR_VAR_1}.\p"
	.string "Ggggrah-awooo!$"
#endif

Text_TaughtMove::
#if GERMAN
	.string "Schnauf, schnauf…\p"
	.string "Ich hätte nicht gedacht, dass ich diese\n"
	.string "Attacke noch in meinem Leben lehren\l"
	.string "durfte…$"
#else
	.string "Gasp, gasp, gasp…\p"
	.string "I didn't think I could teach that\n"
	.string "move while I still lived…$"
#endif

Text_MakeBestUseOfMove::
#if GERMAN
	.string "Ich erwarte, dass du die Attacke\n"
	.string "bestmöglich einsetzt und stärker\l"
	.string "wirst!$"
#else
	.string "I implore you to make the best\n"
	.string "use of that move and gain power!$"
#endif

Text_PassedOnEverythingIKnow::
#if GERMAN
	.string "Schnauf, schnauf…\p"
	.string "Ich bereue nichts! Ich habe all mein\n"
	.string "Wissen weitergegeben.\p"
	.string "Nun kann ich mit mir Frieden schließen\n"
	.string "und mein Leben leben. Meine Aufgabe ist\l"
	.string "erfüllt.$"
#else
	.string "Gasp, gasp, gasp…\p"
	.string "I have no regrets now.\n"
	.string "I've passed on everything I know.\p"
	.string "Now I can live out my life knowing\n"
	.string "my work is done.$"
#endif

Text_FeelRejuvenated::
#if GERMAN
	.string "Nachdem ich dir mein Wissen übergeben\n"
	.string "hatte, fühlte ich mich so erleichtert.\p"
	.string "Ich fühle mich in der Tat jünger, wie neu\n"
	.string "geboren!$"
#else
	.string "After I passed on my knowledge to\n"
	.string "you, I felt so much relief.\p"
	.string "In fact, I feel rejuvenated,\n"
	.string "as if I were younger again!$"
#endif
