ThreeIsland_BondBridge_Frlg_MapScripts::
	.byte 0

ThreeIsland_BondBridge_EventScript_BerryForestSign::
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_EventScript_BondBridgeSign::
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_Text_NikkiIntro::
#if GERMAN
	.string "Der salzige Geruch des Wassers…\n"
	.string "Er erfüllt mein Herz mit Freude.$"
#else
	.string "The salty tang of the sea…\n"
	.string "It tickles my heart.$"
#endif

ThreeIsland_BondBridge_Text_NikkiDefeat::
#if GERMAN
	.string "… schnief, schnief…\n"
	.string "Irgendetwas riecht unangenehm…$"
#else
	.string "…Sniff, sniff…\n"
	.string "Something smells unpleasant…$"
#endif

ThreeIsland_BondBridge_Text_NikkiPostBattle::
#if GERMAN
	.string "Vielleicht ist es der verschwitzte\n"
	.string "Körper eines deiner Pokémon,\l"
	.string "der hier so riecht…$"
#else
	.string "Perhaps that reek is your sweaty\n"
	.string "POKéMON's body odor…$"
#endif

ThreeIsland_BondBridge_Text_VioletIntro::
#if GERMAN
	.string "Wo willst du so eilig hin?$"
#else
	.string "Where are you off to in such\n"
	.string "a hurry?$"
#endif

ThreeIsland_BondBridge_Text_VioletDefeat::
#if GERMAN
	.string "Du trainierst einige eindrucks-\n"
	.string "volle Pokémon.$"
#else
	.string "You're raising some wonderful\n"
	.string "POKéMON.$"
#endif

ThreeIsland_BondBridge_Text_VioletPostBattle::
#if GERMAN
	.string "Wenn du hier weiterläufst, kommst\n"
	.string "du in den Beerenforst.$"
#else
	.string "If you keep going this way, you'll\n"
	.string "eventually reach BERRY FOREST.$"
#endif

ThreeIsland_BondBridge_Text_AmiraIntro::
#if GERMAN
	.string "Meine Mutter sagt, dass ich ohne\n"
	.string "meinen Schwimmreif nicht\l"
	.string "schwimmen kann.$"
#else
	.string "My mommy said that I can't swim\n"
	.string "without my float ring.$"
#endif

ThreeIsland_BondBridge_Text_AmiraDefeat::
#if GERMAN
	.string "Wah!\n"
	.string "Wah!$"
#else
	.string "Waaah!\n"
	.string "Waaah!$"
#endif

ThreeIsland_BondBridge_Text_AmiraPostBattle::
#if GERMAN
	.string "Dieses Jahr werde ich endlich\n"
	.string "das Schwimmen lernen!$"
#else
	.string "This year, I'm going to finally\n"
	.string "learn how to swim!$"
#endif

ThreeIsland_BondBridge_Text_AlexisIntro::
#if GERMAN
	.string "Jo, jo!\n"
	.string "Pokémon!$"
#else
	.string "Yay, yay!\n"
	.string "POKéMON!$"
#endif

ThreeIsland_BondBridge_Text_AlexisDefeat::
#if GERMAN
	.string "Was geschieht jetzt?$"
#else
	.string "What happens now?$"
#endif

ThreeIsland_BondBridge_Text_AlexisPostBattle::
#if GERMAN
	.string "Habe ich gerade gewonnen?\n"
	.string "Oder verloren?$"
#else
	.string "Did I just win?\n"
	.string "Or did I lose?$"
#endif

ThreeIsland_BondBridge_Text_TishaIntro::
#if GERMAN
	.string "Oh, nein, komm nicht näher!\n"
	.string "Bleib mir bitte vom Leib!$"
#else
	.string "Oh, no, don't come here!\n"
	.string "Please, stay away from me!$"
#endif

ThreeIsland_BondBridge_Text_TishaDefeat::
#if GERMAN
	.string "O.k., du hast gewonnen!\n"
	.string "Gehst du jetzt bitte weg?$"
#else
	.string "Okay, you've won!\n"
	.string "Now will you please go away?$"
#endif

ThreeIsland_BondBridge_Text_TishaPostBattle::
#if GERMAN
	.string "Ein Pokémon hat durch meinen\n"
	.string "Badeanzug gebissen.\p"
	.string "Ich kann nicht aus dem Wasser!$"
#else
	.string "A POKéMON bit through my \n"
	.string "swimsuit.\p"
	.string "I can't get out of the water!$"
#endif

ThreeIsland_BondBridge_Text_JoyIntro::
#if GERMAN
	.string "Ute: Wir zeigen dir unser\n"
	.string "Lieblings-Pokémon!$"
#else
	.string "JOY: We'll teach you what our\n"
	.string "favorite POKéMON is!$"
#endif

ThreeIsland_BondBridge_Text_JoyDefeat::
#if GERMAN
	.string "Ute: Oh…\n"
	.string "Ida!$"
#else
	.string "JOY: Ohh…\n"
	.string "MEG!$"
#endif

ThreeIsland_BondBridge_Text_JoyPostBattle::
#if GERMAN
	.string "Ute: Hat das nicht Spaß gemacht?\n"
	.string "Ich hoffe, wir wiederholen das!$"
#else
	.string "JOY: Wasn't that fun?\n"
	.string "I hope we can battle again!$"
#endif

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
#if GERMAN
	.string "Ute: Ich wollte wirklich mit Ida\n"
	.string "kämpfen.\p"
	.string "Ein Pokémon reicht nicht aus!$"
#else
	.string "JOY: I really want to battle with\n"
	.string "MEG.\p"
	.string "One POKéMON isn't enough.$"
#endif

ThreeIsland_BondBridge_Text_MegIntro::
#if GERMAN
	.string "Ida: Wir zeigen dir unsere\n"
	.string "Lieblings-Pokémon.$"
#else
	.string "MEG: We'll show you our favorite\n"
	.string "POKéMON.$"
#endif

ThreeIsland_BondBridge_Text_MegDefeat::
#if GERMAN
	.string "Ida: Oh…\n"
	.string "Ute!$"
#else
	.string "MEG: Ohh…\n"
	.string "JOY!$"
#endif

ThreeIsland_BondBridge_Text_MegPostBattle::
#if GERMAN
	.string "Ida: Ute, das war ein Spaß!$"
#else
	.string "MEG: JOY, wasn't that fun?$"
#endif

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
#if GERMAN
	.string "Ida: Ich möchte mit Ute\n"
	.string "kämpfen.\p"
	.string "Ein Pokémon ist nicht genug.$"
#else
	.string "MEG: I want to battle together\n"
	.string "with JOY.\p"
	.string "One POKéMON isn't enough.$"
#endif

ThreeIsland_BondBridge_Text_BerryForestAhead::
#if GERMAN
	.string "Beerenforst Voraus$"
#else
	.string "BERRY FOREST AHEAD$"
#endif

ThreeIsland_BondBridge_Text_BondBridgeSign::
#if GERMAN
	.string "Bundbrücke\n"
	.string "Beim Überqueren bitte Ruhe!\p"
	.string "Beerenforst Voraus$"
#else
	.string "BOND BRIDGE\n"
	.string "Please be quiet when crossing.\p"
	.string "BERRY FOREST AHEAD$"
#endif

