Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
#if GERMAN
	.string "Wer da? Heh, hör auf, uns heimlich\n"
	.string "zu belauschen!$"
#else
	.string "Who's there?\n"
	.string "Quit listening in on us!$"
#endif

Route6_Text_RickyDefeat::
#if GERMAN
	.string "Ich kann einfach nie siegen!$"
#else
	.string "I just can't win!$"
#endif

Route6_Text_RickyPostBattle::
#if GERMAN
	.string "Flüster...\n"
	.string "Tuschel...$"
#else
	.string "Whisper…\n"
	.string "Whisper…$"
#endif

Route6_Text_NancyIntro::
#if GERMAN
	.string "Entschuldige, aber das hier ist\n"
	.string "Privatsache!$"
#else
	.string "Excuse me!\n"
	.string "This is a private conversation!$"
#endif

Route6_Text_NancyDefeat::
#if GERMAN
	.string "Grr!\n"
	.string "Ich hasse es, zu verlieren!$"
#else
	.string "Ugh!\n"
	.string "I hate losing.$"
#endif

Route6_Text_NancyPostBattle::
#if GERMAN
	.string "Flüster...\n"
	.string "Tuschel...$"
#else
	.string "Whisper…\n"
	.string "Whisper…$"
#endif

Route6_Text_KeigoIntro::
#if GERMAN
	.string "Man findet hier draußen nicht viele\n"
	.string "Käfer...$"
#else
	.string "There aren't many bugs out here.$"
#endif

Route6_Text_KeigoDefeat::
#if GERMAN
	.string "Du beliebst zu scherzen, oder?$"
#else
	.string "No!\n"
	.string "You're kidding!$"
#endif

Route6_Text_KeigoPostBattle::
#if GERMAN
	.string "Ich gehe in den {COLOR RED}Vertania{COLOR DARK_GRAY}-wald\n"
	.string "zurück. Dort gibt es mehr Käfer!$"
#else
	.string "I like bugs, so I'm going back to\n"
	.string "VIRIDIAN FOREST.$"
#endif

Route6_Text_JeffIntro::
#if GERMAN
	.string "Hörte ich da jemanden vom Kämpfen\n"
	.string "sprechen?$"
#else
	.string "Huh?\n"
	.string "You want to talk to me?$"
#endif

Route6_Text_JeffDefeat::
#if GERMAN
	.string "Hmm, ich hätte es besser überhört!$"
#else
	.string "This stinks…\n"
	.string "I couldn't beat your challenge…$"
#endif

Route6_Text_JeffPostBattle::
#if GERMAN
	.string "Zu meiner eigenen Sicherheit sollte\n"
	.string "ich mehr Pokémon bei mir tragen!$"
#else
	.string "I should bring more POKéMON with\n"
	.string "me. I'll feel safer that way.$"
#endif

Route6_Text_IsabelleIntro::
#if GERMAN
	.string "Kämpfen? Meinst du mich?\n"
	.string "Na gut!$"
#else
	.string "Me?\n"
	.string "Well, okay. I'll play!$"
#endif

Route6_Text_IsabelleDefeat::
#if GERMAN
	.string "Das hat nicht ganz geklappt!$"
#else
	.string "Things just didn't work…$"
#endif

Route6_Text_IsabellePostBattle::
#if GERMAN
	.string "Verrätst du mir dein Geheimnis?\n"
	.string "Ich möchte auch stärker werden!$"
#else
	.string "I want to get stronger.\n"
	.string "What's your secret?$"
#endif

Route6_Text_ElijahIntro::
#if GERMAN
	.string "Dich habe ich noch nie gesehen!\n"
	.string "Bist du ein guter Trainer?$"
#else
	.string "I've never seen you around.\n"
	.string "Are you good?$"
#endif

Route6_Text_ElijahDefeat::
#if GERMAN
	.string "Du bist ein zu guter Trainer!$"
#else
	.string "You're too good!$"
#endif

Route6_Text_ElijahPostBattle::
#if GERMAN
	.string "Ist mein Pokémon zu schwach,\n"
	.string "oder bin ich etwa nicht gut genug?$"
#else
	.string "Are my POKéMON weak?\n"
	.string "Or, am I just bad?\l"
	.string "Which do you think?$"
#endif

Route6_Text_UndergroundPathSign::
#if GERMAN
	.string "Tunnelpfad\n"
	.string "Azuria City - Orania City$"
#else
	.string "UNDERGROUND PATH\n"
	.string "CERULEAN CITY - VERMILION CITY$"
#endif

