LavenderTown_House2_hns_MapScripts::
	.byte 0

LavenderTown_House2_EventScript_Woman::
	msgbox LavenderSpeechHouse_Text_PokefanF, MSGBOX_NPC
	end

LavenderSpeechHouse_Text_PokefanF:
#if GERMAN
	.string "Lavandia ist eine ruhige, kleine\n"
	.string "Stadt am Fuß der Berge.\p"
	.string "Seit es den Radioturm gibt, ist\n"
	.string "hier auch richtig was los!$"
#else
	.string "LAVENDER is a tiny, quiet town at\n"
	.string "the foot of the mountains.\p"
	.string "It's gotten a bit busier since\n"
	.string "the RADIO TOWER was built.$"
#endif
