VermilionCity_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, VermilionCity_MapScript_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

VermilionCity_MapScript_OnTransition::
	setflag FLAG_VISITED_VERMILION_CITY
	goto_if_eq VAR_SUICUNE_ENCOUNTERS, 3, VermilionCity_EventScript_SetSuicuneScene
	setflag FLAG_HIDE_VERMILION_EUSINE_SUICUNE
	callnative SetTimeBasedEncounters
	end

VermilionCity_EventScript_SetSuicuneScene::
	clearflag FLAG_HIDE_VERMILION_EUSINE_SUICUNE
	callnative SetTimeBasedEncounters
	end

VermilionCity_EventScript_OldSeaMap::
	finditem ITEM_OLD_SEA_MAP
	end

VermilionCity_TriggerSuicuneNorth_Left::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_WalkRight1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_WalkRight1
	waitmovement 0
	goto VermilionCity_TriggerSuicuneNorth_Merge
VermilionCity_TriggerSuicuneNorth_Mid::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_WalkRight1
	waitmovement 0
	goto VermilionCity_TriggerSuicuneNorth_Merge
VermilionCity_TriggerSuicuneNorth_Right::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	goto VermilionCity_TriggerSuicuneNorth_Merge
VermilionCity_TriggerSuicuneNorth_Merge::
	applymovement OBJ_EVENT_ID_PLAYER, VermilionCity_Movement_NorthSuicune_PlayerWalkDown
	waitmovement 0
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement2 LOCALID_VERMILION_SUICUNE, VermilionCity_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_PLAYER, VermilionCity_Movement_NorthSuicune_PlayerWalkDown
	delay 60
	turnobject OBJ_EVENT_ID_PLAYER, DIR_EAST
	applymovement2 LOCALID_VERMILION_EUSINE, VermilionCity_Movement_EusineWalkToRail
	waitmovement LOCALID_VERMILION_EUSINE
	waitmovement OBJ_EVENT_ID_PLAYER
	goto VermilionCity_EventScript_SuicuneEpisode

VermilionCity_Movement_NorthSuicune_PlayerWalkDown:
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

VermilionCity_TriggerSuicuneTop::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement2 LOCALID_VERMILION_SUICUNE, VermilionCity_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_PLAYER, VermilionCity_Movement_PlayerWalkToRailTop
	delay 60
	applymovement2 LOCALID_VERMILION_EUSINE, VermilionCity_Movement_EusineWalkToRail
	waitmovement LOCALID_VERMILION_EUSINE
	waitmovement OBJ_EVENT_ID_PLAYER
	goto VermilionCity_EventScript_SuicuneEpisode
VermilionCity_TriggerSuicuneMid::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement2 LOCALID_VERMILION_SUICUNE, VermilionCity_Movement_Suicune1
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	waitse
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_PLAYER, VermilionCity_Movement_PlayerWalkToRailMid
	delay 60
	applymovement2 LOCALID_VERMILION_EUSINE, VermilionCity_Movement_EusineWalkToRail
	waitmovement LOCALID_VERMILION_EUSINE
	waitmovement OBJ_EVENT_ID_PLAYER
	goto VermilionCity_EventScript_SuicuneEpisode
VermilionCity_TriggerSuicuneBot::
	lock
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	waitmovement OBJ_EVENT_ID_PLAYER
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement2 LOCALID_VERMILION_SUICUNE, VermilionCity_Movement_Suicune1
	waitmovement 0
	applymovement2 OBJ_EVENT_ID_PLAYER, VermilionCity_Movement_PlayerWalkToRailBot
	waitmovement 0
	applymovement2 LOCALID_VERMILION_EUSINE, VermilionCity_Movement_EusineWalkToRail
	waitmovement LOCALID_VERMILION_EUSINE
	waitmovement OBJ_EVENT_ID_PLAYER
	goto VermilionCity_EventScript_SuicuneEpisode

VermilionCity_EventScript_SuicuneEpisode::
	playmoncry SPECIES_SUICUNE, CRY_MODE_NORMAL
	applymovement2 LOCALID_VERMILION_SUICUNE, VermilionCity_Movement_SuicuneLeave
	playse SE_LEDGE
	waitse
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	playse SE_LEDGE
	delay 30
	waitmovement 0
	msgbox VermilionCity_Text_Eusine, MSGBOX_DEFAULT
	turnobject LOCALID_VERMILION_EUSINE, DIR_SOUTH
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	msgbox VermilionCity_Text_Eusine2, MSGBOX_DEFAULT
	closemessage
	applymovement2 LOCALID_VERMILION_EUSINE, VermilionCity_Movement_EusineLeave
	waitmovement 0
	removeobject LOCALID_VERMILION_EUSINE
	removeobject LOCALID_VERMILION_SUICUNE
	setflag FLAG_HIDE_VERMILION_EUSINE_SUICUNE

	setvar VAR_SUICUNE_ENCOUNTERS, 4
	clearflag FLAG_HIDE_ROUTE14_SUICUNE
	release
	end

VermilionCity_EventScript_Teacher::
	msgbox VermilionCity_Text_Teacher, MSGBOX_NPC
	end

VermilionCity_EventScript_Oldman::
	msgbox VermilionCity_Text_MachopOwner, MSGBOX_NPC
	end

VermilionCity_EventScript_Machop::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MACHOP, CRY_MODE_NORMAL
	msgbox VermilionCity_Text_Machop1, MSGBOX_DEFAULT
	waitmoncry
	msgbox VermilionCity_Text_Machop2, MSGBOX_DEFAULT
	release
	end

VermilionCity_EventScript_Nerd::
	msgbox VermilionCity_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_EventScript_Snorlax::
	lock
	special CheckRadioStation
	goto_if_eq VAR_RESULT, TRUE, VermilionCity_EventScript_SnorlaxWakeUp
	@goto_if_set FLAG_KANTO_RADIO_GOT, VermilionCity_EventScript_SnorlaxWakeUp
	msgbox VermilionCity_Text_SnorlaxSleeping, MSGBOX_DEFAULT
	closemessage
	release
	end

VermilionCity_EventScript_SnorlaxWakeUp::
    playbgm MUS_HG_RADIO_POKE_FLUTE, FALSE
    msgbox VermilionCity_Text_RadioNearSnorlax, MSGBOX_DEFAULT
    playmoncry SPECIES_SNORLAX, CRY_MODE_ENCOUNTER
    delay 40
    waitmoncry
    setwildbattle SPECIES_SNORLAX, 50
    dowildbattle
    specialvar VAR_RESULT, GetBattleOutcome
    goto_if_eq VAR_RESULT, B_OUTCOME_RAN, VermilionCity_EventScript_SnorlaxRan
    fadescreenswapbuffers FADE_TO_BLACK
    removeobject LOCALID_VERMILION_SNORLAX
    removeobject 8
    removeobject 9
    removeobject 10
    removeobject 11
    setflag FLAG_HIDE_VERMILION_SNORLAX
    fadescreenswapbuffers FADE_FROM_BLACK
    setflag FLAG_INDIGOJUNCTION_HIDE_KANTO_GUARD
    fadedefaultbgm
    release
    end

VermilionCity_EventScript_SnorlaxRan::
    fadedefaultbgm
    release
    end

VermilionCity_EventScript_BadgeGuy::
	lock
	faceplayer
	goto_if_set FLAG_GOT_VERMILION_HP_UP, VermilionCity_EventScript_BadgeGuyAfter
	goto_if_ge VAR_NUM_BADGES, 16, VermilionCity_EventScript_BadgeGuyAll
	goto_if_ge VAR_NUM_BADGES, 12, VermilionCity_EventScript_BadgeGuyMost
	goto_if_ge VAR_NUM_BADGES, 9, VermilionCity_EventScript_BadgeGuySome
	msgbox VermilionCity_Text_BadgeGuy_Trainer, MSGBOX_DEFAULT
	closemessage
	release
	end
VermilionCity_EventScript_BadgeGuySome::
	msgbox VermilionCity_Text_BadgeGuy_SomeBadges, MSGBOX_DEFAULT
	closemessage
	release
	end
VermilionCity_EventScript_BadgeGuyMost::
	msgbox VermilionCity_Text_BadgeGuy_MostBadges, MSGBOX_DEFAULT
	closemessage
	release
	end
VermilionCity_EventScript_BadgeGuyAll::
	msgbox VermilionCity_Text_BadgeGuy_AllBadges, MSGBOX_DEFAULT
	giveitem ITEM_HP_UP
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_GOT_VERMILION_HP_UP
	closemessage
	release
	end
VermilionCity_EventScript_BadgeGuyAfter::
	msgbox VermilionCity_Text_BadgeGuy_BattleEdge, MSGBOX_DEFAULT
	closemessage
	release
	end


VermilionCity_Movement_Suicune1:
	jump_in_place_left
	jump_in_place_left
	jump_in_place_left
	step_end

VermilionCity_Movement_PlayerWalkToRailTop: @goal tile = 51, 28
	walk_right
	walk_right
	walk_up
	walk_up
	walk_right
	step_end
VermilionCity_Movement_PlayerWalkToRailMid:
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_right
	step_end
VermilionCity_Movement_PlayerWalkToRailBot:
	walk_right
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_right
	step_end

VermilionCity_Movement_EusineWalkToRail:
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_right
	step_end

VermilionCity_Movement_SuicuneLeave:
	jump_in_place_left
	jump_2_right
	jump_2_right
	jump_2_right
	step_end

VermilionCity_Movement_EusineLeave:
	walk_fast_left
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	step_end

VermilionCity_Text_Eusine:
#if GERMAN
	.string "Eusin: Um ein Haar hätte es geklappt!\p"
	.string "Ich dachte, ich könnte Suicune\n"
	.string "überraschen, wenn ich ihm hier\l"
	.string "auflauern würde…\p"
	.string "Aber wie soll man schon ein Pokémon\n"
	.string "fangen, das übers Wasser laufen kann?\l"
	.string "Ich habe Suicune jetzt allerdings lange\l"
	.string "genug verfolgt, um allmählich die Regeln\l"
	.string "zu erkennen, nach denen es handelt.\p"
	.string "Suicune erscheint vor allem an Orten,\n"
	.string "wo es Wasser gibt!\l"
	.string "Das würde demnach bedeuten, dass…$"
#else
	.string "EUSINE: That was so close!\n"
	.string "I though I could corner it by\l"
	.string "ambushing it here.\p"
	.string "But running on the water is beyond\n"
	.string "me.\p"
	.string "Still, I am starting to see\n"
	.string "a pattern.\p"
	.string "SUICUNE prefers water!\p"
	.string "That means...$"
#endif

VermilionCity_Text_Eusine2:
#if GERMAN
	.string "Tut mir leid, {PLAYER}!\n"
	.string "Ich muss sofort weiter!$"
#else
	.string "Sorry {PLAYER}, I've got to go!$"
#endif

VermilionCity_Text_Teacher:
#if GERMAN
	.string "Der Hafen von Orania City\n"
	.string "ist Kantos Tor zum Meer.\p"
	.string "Hier legen Luxusdampfer\n"
	.string "aus aller Welt an!$"
#else
	.string "VERMILION PORT is KANTO's seaside\n"
	.string "gateway.\p"
	.string "Luxury liners from around the\n"
	.string "world dock here.$"
#endif

VermilionCity_Text_MachopOwner:
#if GERMAN
	.string "Ich lasse mein Pokémon Land für ein\n"
	.string "Bauwerk ebnen, aber ich habe nicht\l"
	.string "genügend Geld für das gesamte Projekt.$"
#else
	.string "My POKéMON is preparing the land\n"
	.string "for construction.\p"
	.string "But I have no money to start the\n"
	.string "project…$"
#endif

VermilionCity_Text_Machop1:
#if GERMAN
	.string "Machollo: Ma, machollo!$"
#else
	.string "MACHOP: Guooh gogogoh!$"
#endif

VermilionCity_Text_Machop2:
#if GERMAN
	.string "Ein Machollo\n"
	.string "brüllt laut, während es auf den Boden\l"
	.string "stampft.$"
#else
	.string "A MACHOP is growling while\n"
	.string "stomping the ground flat.$"
#endif

VermilionCity_Text_SuperNerd:
#if GERMAN
	.string "Es gibt acht Arenen in Kanto.\n"
	.string "Siehst du das große Gebäude da drüben?\p"
	.string "Das ist die Pokémon-Arena von Orania\n"
	.string "Citys Arenaleiter Major Bob.$"
#else
	.string "There are eight GYMS in KANTO.\p"
	.string "That big building is VERMILION's\n"
	.string "POKéMON GYM.$"
#endif

VermilionCity_Text_SnorlaxSleeping:
#if GERMAN
	.string "Relaxo schläft friedlich…$"
#else
	.string "SNORLAX is snoring peacefully…$"
#endif

VermilionCity_Text_RadioNearSnorlax:
#if GERMAN
	.string "Der PokéCom wird\n"
	.string "in der Nähe des schlafenden Relaxos\l"
	.string "platziert…\p"
	.string "…\p"
	.string "Relaxo ist aufgewacht!$"
#else
	.string "The RADIO was placed near the\n"
	.string "sleeping SNORLAX…\p"
	.string "…\p"
	.string "SNORLAX woke up!$"
#endif

VermilionCity_Text_BadgeGuy_Trainer:
#if GERMAN
	.string "In Kanto gibt es einen ganzen Haufen\n"
	.string "sehr starker und talentierter Trainer.\p"
	.string "Die Arenaleiter sind besonders harte\n"
	.string "Brocken! Das wird nicht leicht für dich!$"
#else
	.string "Skilled trainers gather in KANTO.\p"
	.string "GYM LEADERS are especially strong.\p"
	.string "They won't be easy to defeat.$"
#endif

VermilionCity_Text_BadgeGuy_SomeBadges:
#if GERMAN
	.string "Oh, wie ich sehe, sammelst du jetzt auch\n"
	.string "die Orden der Arenaleiter von Kanto!\p"
	.string "Hier wimmelt es geradezu von starken\n"
	.string "Trainern, habe ich nicht recht?$"
#else
	.string "You've started to collect KANTO\n"
	.string "GYM BADGES?\p"
	.string "Don't you agree that the trainers\n"
	.string "here are tough?$"
#endif

VermilionCity_Text_BadgeGuy_MostBadges:
#if GERMAN
	.string "Endspurt! Bald hast du auch alle der\n"
	.string "acht Arenen von Kanto gemeistert!\p"
	.string "Lass mich wissen, wenn du alle acht\n"
	.string "Orden hast!$"
#else
	.string "I guess you'll be finished with\n"
	.string "your conquest of KANTO GYMS soon.\p"
	.string "Let me know if you get all eight\n"
	.string "BADGES.$"
#endif

VermilionCity_Text_BadgeGuy_AllBadges:
#if GERMAN
	.string "Gratuliere! Du hast dir alle Orden der\n"
	.string "Pokémon-Arenen in Kanto erkämpft!\p"
	.string "Für deine Anstrengungen bekommst\n"
	.string "du jetzt eine Belohnung von mir!$"
#else
	.string "Congratulations!\p"
	.string "You got all the KANTO GYM BADGES.\p"
	.string "I've got a reward for your efforts.$"
#endif

VermilionCity_Text_BadgeGuy_BattleEdge:
#if GERMAN
	.string "Es ist vorteilhaft, wenn du\n"
	.string "Pokémon verschie-\l"
	.string "dener Elemente kämpfen lässt.\p"
	.string "Ich bin sicher,\n"
	.string "dass die Orden der Arenen in Kanto dir\l"
	.string "helfen werden.$"
#else
	.string "Having a variety of POKéMON types\n"
	.string "should give you an edge in battle.\p"
	.string "I'm sure the KANTO GYM BADGES will\n"
	.string "help you.$"
#endif

VermilionCity_EventScript_CitySign::
	msgbox VermilionCity_Text_Sign, MSGBOX_SIGN
	end
VermilionCity_EventScript_GymSign::
	msgbox VermilionCity_Text_GymSign, MSGBOX_SIGN
	end
VermilionCity_EventScript_FanClubSign::
	msgbox VermilionCity_Text_FanClubSign, MSGBOX_SIGN
	end
VermilionCity_EventScript_DiglettsCaveSign::
	msgbox VermilionCity_Text_DiglettsCaveSign, MSGBOX_SIGN
	end

VermilionCity_Text_Sign:
#if GERMAN
	.string "Orania City\n"
	.string "Die abendrote Hafenstadt$"
#else
	.string "VERMILION CITY\p"
	.string "The Port of Exquisite Sunsets$"
#endif

VermilionCity_Text_GymSign:
#if GERMAN
	.string "Pokémon-Arena von Orania City\n"
	.string "Leiter: Major Bob\l"
	.string "Ein Blitz am Himmel des Militärs$"
#else
	.string "VERMILION CITY\n"
	.string "POKéMON GYM\p"
	.string "LEADER: LT.SURGE\p"
	.string "The Lightning American$"
#endif

VermilionCity_Text_FanClubSign:
#if GERMAN
	.string "Pokémon Fan Club\n"
	.string "Alle Pokémon-Fans sind willkommen!$"
#else
	.string "POKéMON FAN CLUB\p"
	.string "All POKéMON Fans Welcome!$"
#endif

VermilionCity_Text_DiglettsCaveSign:
#if GERMAN
	.string "Digdas Höhle$"
#else
	.string "DIGLETT'S CAVE$"
#endif

VermilionCity_Text_PortSign:
#if GERMAN
	.string "Eingang zum Hafen von Orania City$"
#else
	.string "VERMILION PORT\n"
	.string "ENTRANCE$"
#endif

VermilionCity_EventScript_TriggerStevenLeft::
	lock
	playse SE_PIN
	applymovement2 LOCALID_PLAYER, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_PLAYER
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkLeft1
	waitmovement 0
	call VermilionCity_EventScript_LatiChoice
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkRight1
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, VermilionCity_Movement_StevenWalkToPlayer
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkDown1
	waitmovement 0
	setvar VAR_VERMILION_CITY_STEVEN, 1
	removeobject LOCALID_VERMILIONCITY_STEVEN
	release
	end

VermilionCity_EventScript_TriggerStevenMiddle::
	lock
	playse SE_PIN
	applymovement2 LOCALID_PLAYER, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_PLAYER
	call VermilionCity_EventScript_LatiChoice
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkLeft1
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, VermilionCity_Movement_StevenWalkToPlayer
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkDown1
	waitmovement 0
	setvar VAR_VERMILION_CITY_STEVEN, 1
	removeobject LOCALID_VERMILIONCITY_STEVEN
	release
	end

VermilionCity_EventScript_TriggerStevenRight::
	lock
	playse SE_PIN
	applymovement2 LOCALID_PLAYER, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_PLAYER
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkRight1
	waitmovement 0
	call VermilionCity_EventScript_LatiChoice
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkLeft1
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, VermilionCity_Movement_StevenWalkToPlayer
	waitmovement 0
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, Common_Movement_WalkDown1
	waitmovement 0
	setvar VAR_VERMILION_CITY_STEVEN, 1
	removeobject LOCALID_VERMILIONCITY_STEVEN
	release
	end


VermilionCity_EventScript_LatiChoice::
	applymovement2 LOCALID_VERMILIONCITY_STEVEN, VermilionCity_Movement_StevenWalkToPlayer
	waitmovement 0
	msgbox VermilionCity_Text_StevenIntro, MSGBOX_DEFAULT
	multichoice 20, 8, MULTI_TV_LATI, TRUE
	@goto_if_eq VAR_RESULT, MULTI_B_PRESSED, VermilionCity_EventScript_LatiCancel
	copyvar VAR_0x8004, VAR_RESULT
	copyvar VAR_ROAMER_POKEMON_HNS, VAR_RESULT
	special InitKantoRoamers
	setflag FLAG_LATIOS_OR_LATIAS_ROAMING
	msgbox VermilionCity_Text_StevenOutro, MSGBOX_DEFAULT
	closemessage
	return

VermilionCity_Movement_StevenWalkToPlayer:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

VermilionCity_Text_StevenIntro:
#if GERMAN
	.string "Hallo!\n"
	.string "Mein Name ist Troy.\p"
	.string "Der Champion aus der Hoenn-region.\p"
	.string "Haben wir uns schon… getroffen?\p"
	.string "Das ist nicht möglich.\p"
	.string "Alle Trainer, gegen die ich\n"
	.string "gekämpft habe, haben irgendwie\l"
	.string "denselben Blick.\p"
	.string "Besonders die, die mir harte\n"
	.string "Kämpfe geliefert haben.\p"
	.string "Ich bin geschäftlich in Kanto.\n"
	.string "Viele Hoenn Pokémon sind kürzlich\l"
	.string "in diese Region eingewandert.\l"
	.string "Das gefährdet das natürliche\l"
	.string "Ökosystem hier.\p"
	.string "Mit Hilfe meines Unternehmens\n"
	.string "schaffe ich daher einen speziellen\l"
	.string "Lebensraum für die invasivsten\l"
	.string "Arten.\p"
	.string "Halt die Augen offen und fange\n"
	.string "alle Hoenn-Pokémon, die du siehst.\p"
	.string "Manche Trainer haben sogar eines\n"
	.string "gesichtet, das wie ein Jet durch\l"
	.string "den Himmel fliegt…\l"
	.string "Welche Farbe hatte es nochmal?$"
#else
	.string "Hi!\n"
	.string "My name is Steven.\l"
	.string "The Champion from the HOENN region.\p"
	.string "Have we met...before?\p"
	.string "That's not possible. \n"
	.string "All the trainers I have battled\l"
	.string "seem to have the same look, anyway.\p"
	.string "Especially the ones who gave me\n"
	.string "tough battles.\p"
	.string "I'm in KANTO for business.\n"
	.string "Recently many HOENN POKéMON have\l"
	.string "migrated to this region.\l"
	.string "This influx risks disrupting the\l"
	.string "natural ecosystem here.\p"
	.string "So with the help of my company,\n"
	.string "I'm creating a special habitat\l"
	.string "to attract and contain the most\l"
	.string "invasive species.\p"
	.string "Make sure you keep an eye out\n"
	.string "and catch any HOENN POKéMON you see.\p"
	.string "Some trainers have even reported\n"
	.string "one that soars through the sky like\l"
	.string "a jet... What color was it again?$"
#endif

VermilionCity_Text_StevenOutro:
#if GERMAN
	.string "Ah, stimmt.\p"
	.string "Ich muss weiter.\n"
	.string "Vielleicht kreuzen sich unsere\l"
	.string "Wege nochmal.$"
#else
	.string "Ah, that's right.\p"
	.string "I must go.\n"
	.string "May our journeys cross again.$"
#endif
