Mahoganytown_hns_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, Mahoganytown_OnLoad
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Mahoganytown_OnFrame
	.byte 0

Mahoganytown_OnLoad::
	call_if_ge VAR_MAHOGANY_TOWN_STATE, 13, MahoganyTown_EventScript_FixTree
	end

MahoganyTown_EventScript_FixTree::
	setmetatile 18, 8, 0x378, FALSE
	setmetatile 19, 8, 0x379, FALSE
	end

Mahoganytown_OnFrame::
	map_script_2 VAR_MAHOGANY_TOWN_STATE, 15, Mahoganytown_EventScript_DefeatedGym
	.2byte 0

Mahoganytown_EventScript_DefeatedGym::
	call_if_eq VAR_LUGIA_OR_HOOH, 0, Mahoganytown_EventScript_LegendaryTrigger
	call_if_ge VAR_LUGIA_OR_HOOH, 1, Mahoganytown_EventScript_RocketTrigger
	end

Mahoganytown_EventScript_RocketTrigger::
	lock
	setspeaker Mahoganytown_Text_ElmName
	pokenavcall ElmPhoneRadioTowerRocketTakeoverText
	waitmessage
	setvar VAR_GOLDENROD_CITY_STATE, 6
	clearflag FLAG_HIDE_GOLDENROD_ROCKETS
	setflag FLAG_HIDE_GOLDENROD_ROCKET_SCOUT
	setflag FLAG_HIDE_GOLDENROD_NPCS
	clearflag FLAG_HIDE_ROCKET_GOLDENROD_RADIOTOWER_1
	setvar VAR_MAHOGANY_TOWN_STATE, 16
	delay 10
	release
	end

Mahoganytown_EventScript_LegendaryTrigger::
	lock
	setspeaker Mahoganytown_Text_ElmName
	pokenavcall ElmPhoneRoute39LegendaryText
	waitmessage
	setvar VAR_MAHOGANY_TOWN_STATE, 18
	delay 10
	release
	end

MahoganyTown_EventScript_TownTrigger::
	clearflag FLAG_HIDE_LAKE_OF_RAGE_GYARADOS
	clearflag FLAG_HIDE_MAHOGANY_TOWN_FATMAN
	clearflag FLAG_HIDE_MAHOGANY_ROCKETS
	clearflag FLAG_GOT_TM_FROM_MAHOGANY_COP
	clearflag FLAG_GOT_BLACK_BELT
	clearflag FLAG_ROCKETHIDEOUT_SWITCH
	clearflag FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
	clearflag FLAG_HIDE_ROCKETHIDEOUT2_GATE
	clearflag FLAG_HIDE_ROCKETHIDEOUT3_GATE
	clearflag FLAG_GOT_PASSWORD_FROM_ETO
	clearflag FLAG_GOT_PASSWORD_FROM_GRUNTF
	clearflag FLAG_HIDE_ROCKETHIDEOUT3_MURKROW
	clearflag FLAG_HIDE_ROCKETHIDEOUT3_GIOVANNI
	clearflag FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE1
	clearflag FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE2
	clearflag FLAG_HIDE_ROCKETHIDEOUT_ELECTRODE3
	clearflag FLAG_GOT_HIDDEN_POWER
	clearflag FLAG_HIDE_ICE_PATH_KIMONO

	setflag FLAG_VISITED_MAHOGANY_TOWN
	setflag FLAG_HIDE_LAKE_OF_RAGE_LANCE
	setflag FLAG_HIDE_MAHOGANY_TOWN_SHOP_NPCS
	setflag FLAG_HIDE_MAHOGANY_COP
	setflag FLAG_HIDE_ROCKETHIDEOUT_ROCKETS
	setflag FLAG_HIDE_ROCKETHIDEOUT3_SILVER
	setflag FLAG_HIDE_ROCKETHIDEOUT3_PETREL
	setflag FLAG_HIDE_ROCKETHIDEOUT2_MURKROWSTAIRS
	setflag FLAG_HIDE_ROCKETHIDEOUT2_MURKROWGATE
	setflag FLAG_HIDE_ROCKETHIDEOUT3_MURKROWSTAIRS
	setflag FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT
	setflag FLAG_HIDE_ICEPATH_B2F_BOULDER1
	setflag FLAG_HIDE_ICEPATH_B2F_BOULDER2
	setflag FLAG_HIDE_ICEPATH_B2F_BOULDER3
	setflag FLAG_HIDE_ICEPATH_B2F_BOULDER4

	setvar VAR_ROCKET_HIDEOUT_STATUE_1, 0
	setvar VAR_ROCKET_HIDEOUT_STATUE_2, 0
	setvar VAR_ROCKET_HIDEOUT_STATUE_3, 0
	setvar VAR_ROCKET_HIDEOUT_STATUE_4, 0
	setvar VAR_ROCKET_HIDEOUT_STATUE_5, 0
	setvar VAR_ROCKET_PASSWORD, 0
	setvar VAR_ELECTRODES_FAINTED, 0
	setvar VAR_LAKE_OF_RAGE_FISHERMAN, 0
	setvar VAR_ICE_PATH_STATE, 0
	setvar VAR_ROUTE27_BAOBA_CALL, 0

	setvar VAR_MAHOGANY_TOWN_STATE, 1

	@blackthorn flagheap
	setvar VAR_BLACKTHORN_CITY_STATE, 1
    setflag FLAG_HIDE_DRAGONS_DEN_CAVERN_SILVER
	setflag FLAG_HIDE_DRAGONS_DEN_CAVERN_CLAIR
	setflag FLAG_HIDE_DRAGONS_DEN_CAVERN_LANCE
	setflag FLAG_HIDE_DRAGONS_DEN_SHRINE_CLAIR
	clearflag FLAG_GOT_SPELL_TAG
	clearflag FLAG_GOT_DRATINI
	setvar VAR_BLACKTHORN_GYM_STATE, 0
	setvar VAR_DRAGONS_DEN_QUIZ, 0
	end

MahoganyTown_EventScript_MerchantTrigger::
	lock
	turnobject LOCALID_MAHOGANY_MERCHANT, DIR_SOUTH
	playse SE_PIN
	applymovement LOCALID_MAHOGANY_MERCHANT, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_MAHOGANY_MERCHANT
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_1, 14, MahoganyTown_EventScript_WalkUp2
	call_if_eq VAR_TEMP_1, 13, MahoganyTown_EventScript_WalkUp1
	showmoneybox 0, 0
	msgbox MahoganyTown_Text_RageCandyBarMerchantTryOne, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, FALSE, MahoganyTown_EventScript_MerchantRefused
	checkmoney 300, 0
	goto_if_eq VAR_RESULT, FALSE, MahoganyTown_EventScript_MerchantBroke
	removemoney 300
	updatemoneybox 0
	playse SE_SHOP
	msgbox MahoganyTown_Text_RageCandyBarMerchantSavorIt, MSGBOX_DEFAULT
	giveitem ITEM_RAGE_CANDY_BAR
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
	hidemoneybox
	closemessage
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_0, 30, MahoganyTown_EventScript_PushPlayer
	release
	end

MahoganyTown_EventScript_WalkUp1::
	applymovement OBJ_EVENT_ID_PLAYER, MahoganyTown_Movement_PlayerMerchant1
	waitmovement 0
	return

MahoganyTown_EventScript_WalkUp2::
	applymovement OBJ_EVENT_ID_PLAYER, MahoganyTown_Movement_PlayerMerchant2
	waitmovement 0
	return

MahoganyTown_EventScript_Merchant::
	lock
	faceplayer
	goto_if_eq VAR_MAHOGANY_TOWN_STATE, 17, MahoganyTown_EventScript_MerchantAfter
	showmoneybox 0, 0
	msgbox MahoganyTown_Text_RageCandyBarMerchantTryOne, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, FALSE, MahoganyTown_EventScript_MerchantRefused
	checkmoney 300, 0
	goto_if_eq VAR_RESULT, FALSE, MahoganyTown_EventScript_MerchantBroke
	removemoney 300
	updatemoneybox 0
	msgbox MahoganyTown_Text_RageCandyBarMerchantSavorIt, MSGBOX_DEFAULT
	giveitem ITEM_RAGE_CANDY_BAR
	hidemoneybox
	closemessage
	release
	end

MahoganyTown_EventScript_MerchantRefused::
	msgbox MahoganyTown_Text_RageCandyBarMerchantRefused, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	closemessage
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_0, 30, MahoganyTown_EventScript_PushPlayer
	release
	end

MahoganyTown_EventScript_MerchantBroke::
	msgbox MahoganyTown_Text_RageCandyBarMerchantNotEnoughMoney, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	closemessage
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_0, 30, MahoganyTown_EventScript_PushPlayer
	release
	end

MahoganyTown_EventScript_NotEnoughSpace:
	msgbox MahoganyTown_Text_RageCandyBarMerchantRefused, MSGBOX_DEFAULT
	closemessage
	hidemoneybox
	closemessage
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_0, 30, MahoganyTown_EventScript_PushPlayer
	release
	return

MahoganyTown_EventScript_MerchantAfter::
	msgbox MahoganyTown_Text_RageCandyBarMerchantSoldOut, MSGBOX_DEFAULT
	closemessage
	release
	end

MahoganyTown_EventScript_PushPlayer::
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkLeft1
	waitmovement 0
	return

MahoganyTown_EventScript_Gramps::
	lock
	faceplayer
	goto_if_eq VAR_MAHOGANY_TOWN_STATE, 6, MahoganyTown_EventScript_GrampsAfter
	msgbox MahoganyTown_Text_Gramps, MSGBOX_DEFAULT
	closemessage
	release
	end

MahoganyTown_EventScript_GrampsAfter::
	msgbox MahoganyTown_Text_GrampsClearedRocketHideout, MSGBOX_DEFAULT
	closemessage
	release
	end

MahoganyTown_EventScript_Fisher::
	lock
	faceplayer
	msgbox MahoganyTown_Text_Fisher, MSGBOX_DEFAULT
	closemessage
	release
	end

MahoganyTown_EventScript_Lass::
	lock
	faceplayer
	msgbox MahoganyTown_Text_Lass, MSGBOX_DEFAULT
	closemessage
	release
	end

MahoganyTown_EventScript_Sign::
	lock
	msgbox MahoganyTown_Text_Sign, MSGBOX_SIGN
	closemessage
	release
	end

MahoganyTown_EventScript_CandybarSign::
	lock
	msgbox MahoganyTown_Text_RagecandybarSign, MSGBOX_SIGN
	closemessage
	release
	end

MahoganyTown_EventScript_GymSign::
	lock
	msgbox MahoganyTown_Text_GymSign, MSGBOX_SIGN
	closemessage
	release
	end

MahoganyTown_Movement_PlayerMerchant1:
	walk_up
	step_end

MahoganyTown_Movement_PlayerMerchant2:
	walk_up
	walk_up
	step_end

MahoganyTown_Text_RageCandyBarMerchantTryOne:
#if GERMAN
	.string "Hey, du! Komm doch mal eben her!\p"
	.string "Wenn du schon mal in Mahagonia City\n"
	.string "bist, solltest du unbedingt einen\l"
	.string "Wutkeks kaufen!\p"
	.string "Ich hätte einen für 300 $ für\n"
	.string "dich im Angebot. Na, was sagst du?$"
#else
	.string "Hiya, kid!\p"
	.string "I see you're new in MAHOGANY TOWN.\p"
	.string "Since you're new, you should try a\n"
	.string "yummy RAGECANDYBAR!\p"
	.string "Right now, it can be yours for just\n"
	.string "¥300! Want one?$"
#endif

MahoganyTown_Text_RageCandyBarMerchantSavorIt:
#if GERMAN
	.string "Gut! Genieße ihn!$"
#else
    .string "Good! Savor it!$"
#endif

MahoganyTown_Text_RageCandyBarMerchantNotEnoughMoney:
#if GERMAN
	.string "Du hast nicht genug Geld.$"
#else
    .string "You don't have enough money.$"
#endif

MahoganyTown_Text_RageCandyBarMerchantRefused:
#if GERMAN
	.string "Dann eben nicht…$"
#else
    .string "Oh, fine then…$"
#endif

MahoganyTown_Text_RageCandyBarMerchantSoldOut:
#if GERMAN
	.string "Die Wutkekse sind ausverkauft.\p"
	.string "Ich verschwinde.\n"
	.string "Stör mich nicht, Kind.$"
#else
    .string "RAGECANDYBAR's sold out.\p"
    .string "I'm packing up. Don't bother me,\n"
    .string "kiddo.$"
#endif

MahoganyTown_Text_Gramps:
#if GERMAN
	.string "Willst du auch zum See und dir das\n"
	.string "Garados ansehen?$"
#else
    .string "Are you off to see the GYARADOS\n"
    .string "rampage at the LAKE?$"
#endif

MahoganyTown_Text_GrampsClearedRocketHideout:
#if GERMAN
	.string "Die Karpador sind zum\n"
	.string "See des Zorns zurückgekehrt.\p"
	.string "Das sind gute Neuigkeiten\n"
	.string "für die Angler.$"
#else
    .string "MAGIKARP have returned to LAKE\n"
    .string "OF RAGE.\p"
    .string "That should be good news for the\n"
    .string "anglers there.$"
#endif

MahoganyTown_Text_Fisher:
#if GERMAN
	.string "Wenn du schon so weit gekommen bist,\n"
	.string "solltest du dir die Zeit nehmen, um\l"
	.string "etwas\p"
	.string "die Gegend zu besichtigen.\p"
	.string "Geh nach Norden und sieh dir den\n"
	.string "See des Zorns an.$"
#else
    .string "Since you came this far, take the\n"
    .string "time to do some sightseeing.\p"
    .string "You should head north and check\n"
    .string "out LAKE OF RAGE right now.$"
#endif

MahoganyTown_Text_Lass:
#if GERMAN
	.string "Besuche Großmutters Laden.\p"
	.string "Sie verkauft Artikel,\n"
	.string "die du sonst nirgends bekommen kannst.$"
#else
    .string "Visit Grandma's shop. She sells\n"
    .string "stuff that nobody else has.$"
#endif

MahoganyTown_Text_Sign:
#if GERMAN
	.string "Mahagonia City\p"
	.string "Willkommen in der Stadt der Ninja.$"
#else
    .string "MAHOGANY TOWN\p"
    .string "Welcome to the Home of the Ninja$"
#endif

MahoganyTown_Text_RagecandybarSign:
#if GERMAN
	.string "Versuchen Sie den leckeren Wutkeks!$"
#else
    .string "While visiting MAHOGANY TOWN, try\n"
    .string "a RAGECANDYBAR!$"
#endif

MahoganyTown_Text_GymSign:
#if GERMAN
	.string "Pokémon-Arena von Mahagonia City\n"
	.string "Leiter: Norbert Er wird dir beibringen,\l"
	.string "was ein harter Winter ist!$"
#else
    .string "MAHOGANY TOWN POKéMON GYM\p"
    .string "LEADER: PRYCE\p"
    .string "The Teacher of Winter's Harshness$"
#endif

Mahoganytown_Text_ElmName:
#if GERMAN
	.string "Lind$"
#else
	.string "PROF.ELM$"
#endif

ElmPhoneRadioTowerRocketTakeoverText:
#if GERMAN
	.string "He, {PLAYER}!\n"
	.string "Wie stehen die Dinge?\p"
	.string "Hör mal, im Radio geschieht gerade\n"
	.string "irgendetwas Merkwürdiges.\l"
	.string "Ich höre immer bloß “Team Rocket”…\p"
	.string "Da dachte ich, ich rufe mal an.\n"
	.string "{PLAYER}, weißt du, was da los ist?\p"
	.string "Team Rocket feiert doch nicht etwa ein\n"
	.string "Comeback?\l"
	.string "Nein… das wäre doch zu abwegig.\p"
	.string "Entschuldige, ich wollte dich nicht\n"
	.string "beunruhigen. Pass auf dich auf!$"
#else
	.string "PROF.ELM: {PLAYER}, how are\n"
	.string "things going?\p"
	.string "I called because something weird\n"
	.string "is happening with the radio\l"
	.string "broadcasts.\p"
	.string "They were talking about TEAM\n"
	.string "ROCKET.\p"
	.string "{PLAYER}, do you know anything\n"
	.string "about it?\p"
	.string "Maybe TEAM ROCKET has returned.\n"
	.string "No, that just can't be true.\p"
	.string "Sorry to bug you.\n"
	.string "Take care!$"
#endif

ElmPhoneRoute39LegendaryText:
#if GERMAN
	.string "Prof. Lind: Wow!\n"
	.string "{PLAYER}, hast du das gesehen?!\p"
	.string "Ein riesiges Pokémon flog über\n"
	.string "Teak City hinweg!\p"
	.string "Ich konnte es sogar von meinem\n"
	.string "Labor aus sehen!\p"
	.string "War es eines der legendären\n"
	.string "Pokémon??\p"
	.string "Es flog nach Westen,\n"
	.string "Richtung Route 39.\p"
	.string "{PLAYER}!\n"
	.string "Das könnte eine seltene Chance zur\l"
	.string "Verfolgung sein!$"
#else
	.string "PROF.ELM: WOAH!\n"
	.string "{PLAYER}, did you see that?!\p"
	.string "A massive POKéMON just flew over\n"
	.string "ECRUTEAK CITY!\l"
	.string "I could see it from my LAB!\p"
	.string "Could it be one of the legendary\n"
	.string "POKéMON??\p"
	.string "It looked like it was headed West,\n"
	.string "toward ROUTE 39.\p"
	.string "{PLAYER}!\n"
	.string "This may be a rare opportunity\l"
	.string "to give chase!$"
#endif
