EventScript_MomGiftCall_Item::
	lockall
	pokenavcall Mom_Text_GiftCall_Item
	waitmessage
	delay 30
	clearflag FLAG_MOM_HAS_GIFT
	releaseall
	end

EventScript_MomGiftCall_Berry::
	lockall
	pokenavcall Mom_Text_GiftCall_Berry
	waitmessage
	delay 30
	clearflag FLAG_MOM_HAS_GIFT
	releaseall
	end

EventScript_MomGiftCall_Decoration::
	lockall
	pokenavcall Mom_Text_GiftCall_Decoration
	waitmessage
	delay 30
	clearflag FLAG_MOM_HAS_GIFT
	releaseall
	end

Mom_Text_GiftCall_Item:
#if GERMAN
	.string "Mama: Hallo, {PLAYER}!\n"
	.string "Wie geht es dir?\p"
	.string "Ich habe heute beim Einkaufen ein\n"
	.string "nützliches Item gefunden und es dir\l"
	.string "von deinem Geld gekauft! Tut mir leid!\p"
	.string "Ich habe es auf deinen PC übertragen.\n"
	.string "Du wirst es sicher brauchen können!\p"
	.string "Mach’s gut!$"
#else
	.string "MOM: Hi, sweetie!\p"
	.string "I bought something nice\n"
	.string "for you with your savings!\p"
	.string "I sent it to your PC.\n"
	.string "Take care!$"
#endif

Mom_Text_GiftCall_Berry:
#if GERMAN
	.string "Mama: Hallo, {PLAYER}!\n"
	.string "Wie geht es dir?\p"
	.string "Ich habe heute beim Einkaufen leckere\n"
	.string "Beeren gefunden und sie dir von deinem\l"
	.string "Geld gekauft! Tut mir leid!\p"
	.string "Ich habe sie auf deinen PC übertragen.\n"
	.string "Du wirst sie sicher brauchen können!\p"
	.string "Mach’s gut!$"
#else
	.string "MOM: Hi, sweetie!\p"
	.string "I found some nice BERRIES\n"
	.string "at the store for you!\p"
	.string "I sent them to your PC.\n"
	.string "Take care!$"
#endif

Mom_Text_GiftCall_Decoration:
#if GERMAN
	.string "Mama: Hallo, {PLAYER}!\n"
	.string "Wie geht es dir?\p"
	.string "Ich habe heute beim Einkaufen eine\n"
	.string "niedliche Poképuppe für dein Zimmer\l"
	.string "gefunden! Tut mir leid!\p"
	.string "Sieh dir die Dekorationen an, wenn du\n"
	.string "wieder zu Hause bist!\p"
	.string "Mach’s gut!$"
#else
	.string "MOM: Hi, sweetie!\p"
	.string "I bought a cute POKé DOLL\n"
	.string "for your room!\p"
	.string "Check your DECORATIONS when you\n"
	.string "come home. Take care!$"
#endif
