Route24_hns_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route24_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route24_OnTransition:
	call_if_eq VAR_KANTO_ROCKET_STORY_STATE, 4, Route24_MapScript_SetRocketScene
	callnative SetTimeBasedEncounters
	end

Route24_MapScript_SetRocketScene:
	setobjectxyperm LOCALID_ROUTE24_GRUNT, 16, 8
	setobjectxyperm LOCALID_ROUTE24_WOMAN, 16, 9
	setobjectmovementtype LOCALID_ROUTE24_GRUNT, MOVEMENT_TYPE_FACE_LEFT
	setobjectmovementtype LOCALID_ROUTE24_WOMAN, MOVEMENT_TYPE_FACE_UP
	setobjectmovementtype LOCALID_ROUTE24_MAN, MOVEMENT_TYPE_FACE_DOWN
	return

Route24_EventScript_Woman::
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 4, Route24_EventScript_WomanRocket
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 5, Route24_EventScript_WomanAfterRocket
	msgbox Route24_Text_Woman, MSGBOX_NPC
	end

Route24_EventScript_WomanRocket::
	msgbox Route24_Text_WomanRocket, MSGBOX_NPC
	end

Route24_EventScript_WomanAfterRocket::
	msgbox Route24_Text_WomanAfterRocket, MSGBOX_NPC
	end

Route24_EventScript_Man::
	goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 4, Route24_EventScript_ManRocket
		goto_if_eq VAR_KANTO_ROCKET_STORY_STATE, 5, Route24_EventScript_ManAfterRocket
	msgbox Route24_Text_Man, MSGBOX_NPC
	end

Route24_EventScript_ManRocket::
	msgbox Route24_Text_ManRocket, MSGBOX_NPC
	end

Route24_EventScript_ManAfterRocket::
	msgbox Route24_Text_ManAfterRocket, MSGBOX_NPC
	end

Route24_Trigger_GruntScene::
	lock
	playse SE_PIN
	applymovement2 LOCALID_ROUTE24_GRUNT Common_Movement_ExclamationMark
	delay 60
	applymovement2 LOCALID_ROUTE24_GRUNT, Route24_Movement_GruntHide
	delay 10
	applymovement2 LOCALID_ROUTE24_WOMAN, Route24_Movement_WomanMove
	waitmovement 0
	turnobject LOCALID_ROUTE24_MAN, DIR_SOUTH
	setvar VAR_KANTO_ROCKET_STORY_STATE, 4
	call Route24_MapScript_SetRocketScene
	release
	end

Route24_Movement_GruntHide:
	walk_fast_left
	walk_fast_left
	step_end

Route24_Movement_WomanMove:
	lock_facing_direction
	walk_fast_down
	unlock_facing_direction
	face_up
	step_end

Route24_EventScript_Grunt::
	lock
	faceplayer
	msgbox Route24_Text_RocketSeen, MSGBOX_DEFAULT
	trainerbattle_no_intro TRAINER_GRUNT_31_HNS, Route24_Text_RocketBeaten
	msgbox Route24_Text_RocketAfter, MSGBOX_DEFAULT
	closemessage
	playse SE_PIN
	applymovement2 FLAG_HIDE_CERULEAN_CAPE_ROCKET, Common_Movement_QuestionMark
	delay 50
	msgbox Route24_Text_RocketDisappears, MSGBOX_DEFAULT
	closemessage
	applymovement OBJ_EVENT_ID_PLAYER, Route24_Movement_PlayerSlide
	delay 20
	applymovement LOCALID_ROUTE24_GRUNT, Route24_Movement_GruntLeave
	waitmovement LOCALID_ROUTE24_GRUNT
	setflag FLAG_HIDE_CERULEAN_CAPE_ROCKET
	removeobject LOCALID_ROUTE24_GRUNT
	setvar VAR_KANTO_ROCKET_STORY_STATE, 5
	clearflag FLAG_HIDDEN_ITEM_MACHINE_PART
	release
	end

Route24_Movement_PlayerSlide:
	delay_16
	lock_facing_direction
	walk_fast_up
	unlock_facing_direction
	face_down
	step_end

Route24_Movement_GruntLeave:
	walk_fast_right
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	step_end

Route24_Text_RocketSeen:
#if GERMAN
	.string "Hey, Minimensch!\n"
	.string "Ich sein von Team Rocket.\p"
	.string "Sein aus fremde\n"
	.string "Land, Trainer eins ich sein!\p"
	.string "Geglaubt, wenn nix Energie mehr,\n"
	.string "mache viel Panik bei Leute!\p"
	.string "Geheim mein Auftrag sein,\n"
	.string "ich dir nix verraten!\p"
	.string "Doch! Wenn mich besiegen, ich sein\n"
	.string "lieb und dir verrate Geheimnis.\p"
	.string "Du, Kind! Kämpfen lass uns!$"
#else
	.string "Hey, kid! Me am a TEAM ROCKET\n"
	.string "member kind of guy!\p"
	.string "Come from another country, a\n"
	.string "trainer number one, me!\p"
	.string "Think I did, if stop the energy,\n"
	.string "be big panic for here people!\p"
	.string "Secret it is my mission, so tell\n"
	.string "you I not!\p"
	.string "But! If win you do versus me, a\n"
	.string "man I be and mine secret to you\l"
	.string "I tell.\p"
	.string "Hey, kid! Battle begin we do!$"
#endif

Route24_Text_RocketBeaten:
#if GERMAN
	.string "Oh no!\n"
	.string "Was ich rede für einen Quark?\p"
	.string "Du bist Strawberry… Brombeer -\n"
	.string "nein - very stark!\l"
	.string "An dir I bite me alle Zähne aus!\l"
	.string "Respect! I salute you!\l"
	.string "Großer Applaus!$"
#else
	.string "Ayieeeh! No, no, no, believe it\n"
	.string "I can't!\p"
	.string "Strong very much be you! Match\n"
	.string "I am not to you!$"
#endif

Route24_Text_RocketAfter:
#if GERMAN
	.string "Okay, alles klar!\n"
	.string "Ich verrate dir meine secret Geheimnis!\p"
	.string "I have die Spule in die Arena\n"
	.string "von Azuria City versteckt. Yes, I have!\p"
	.string "Wenn du neben die Schwimmreifen\n"
	.string "checkst, find you sie bestimmt! You will!\p"
	.string "Aaaaber! However!\n"
	.string "Nicht vergessen! Don't forget!\p"
	.string "Team Rocket wird dich definitely\n"
	.string "besiegen! Yes, we will!\l"
	.string "All meine Friends werden kommen\l"
	.string "aus die Johto!$"
#else
	.string "OK. Tell you mine secret will I?\n"
	.string "MACHINE PART steal by me, hide it\l"
	.string "I did in GYM of the CERULEAN.\p"
	.string "Inside water put it I did. Look\n"
	.string "for in water center of GYM at.\p"
	.string "But you forget me not!\p"
	.string "Beat you for sure will TEAM\n"
	.string "ROCKET.\p"
	.string "Come from JOHTO will they, mine\n"
	.string "friends, yes. Will revenge they\l"
	.string "are.$"
#endif

Route24_Text_RocketDisappears:
#if GERMAN
	.string "…\p"
	.string "Was du sagen? Team Rocket nix mehr\n"
	.string "gibt? Kaputt gemacht, du sagen?\p"
	.string "Oh, nein! Ich tun was jetzt machen?$"
#else
	.string "…\p"
	.string "You say what? TEAM ROCKET bye-\n"
	.string "bye a go-go? Broken it is says\l"
	.string "you?\p"
	.string "Oh, no! Should I do what now on\n"
	.string "from, me?$"
#endif



Route24_Text_Woman:
#if GERMAN
	.string "Ist das nicht eine schöne Aussicht?$"
#else
	.string "Isn't it a lovely view?$"
#endif
Route24_Text_Man:
	.string "Ich könnte den ganzen Tag hier\n"
	.string "bleiben.$"

Route24_Text_WomanRocket:
#if GERMAN
	.string "Niemand schubst mich!$"
#else
	.string "Nobody pushes me!$"
#endif
Route24_Text_ManRocket:
	.string "Niemand schubst meine Freundin!$"

Route24_Text_WomanAfterRocket:
#if GERMAN
	.string "Was sollte das denn?$"
#else
	.string "What was that all about?$"
#endif
Route24_Text_ManAfterRocket:
	.string "War das etwa ein Rocket?$"
