Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
#if GERMAN
	.string "Puh! Ich muss eine Pause machen!\p"
	.string "Der Weg durch den Tunnel aus\n"
	.string "Azuria City ist sehr beschwerlich!$"
#else
	.string "Whew… I better take a rest…\n"
	.string "Groan…\p"
	.string "That tunnel from CERULEAN takes a\n"
	.string "lot out of you!$"
#endif

Route3_Text_ColtonIntro::
#if GERMAN
	.string "Heh! Ich kenne dich aus dem\n"
	.string "Vertania-wald!$"
#else
	.string "Hey!\n"
	.string "I saw you in VIRIDIAN FOREST!$"
#endif

Route3_Text_ColtonDefeat::
#if GERMAN
	.string "Du hast mich wieder besiegt!$"
#else
	.string "You beat me again!$"
#endif

Route3_Text_ColtonPostBattle::
#if GERMAN
	.string "Neben den Pokémon hier im Wald,\n"
	.string "gibt es noch Unmengen anderer\l"
	.string "Pokémon zu entdecken!$"
#else
	.string "There are other kinds of POKéMON\n"
	.string "than the ones you find in forests.$"
#endif

Route3_Text_BenIntro::
#if GERMAN
	.string "Überall sind Brennnesseln! Und ich\n"
	.string "trage Shorts! So ein Mist!$"
#else
	.string "Hi!\n"
	.string "I like shorts!\p"
	.string "They're delightfully comfy and\n"
	.string "easy to wear!$"
#endif

Route3_Text_BenDefeat::
#if GERMAN
	.string "Wäre ich heute doch nur daheim\n"
	.string "geblieben!$"
#else
	.string "I don't believe it!$"
#endif

Route3_Text_BenPostBattle::
#if GERMAN
	.string "Du kannst Pokémon via PC in Boxen\n"
	.string "ablegen.\p"
	.string "Jede Box fasst 30 Pokémon!$"
#else
	.string "Are you using a POKéMON CENTER's\n"
	.string "PC for storing your POKéMON?\p"
	.string "Each BOX can hold up to\n"
	.string "30 POKéMON.$"
#endif

Route3_Text_JaniceIntro::
#if GERMAN
	.string "Was starrst du mich so an?$"
#else
	.string "Excuse me!\n"
	.string "You looked at me, didn't you?$"
#endif

Route3_Text_JaniceDefeat::
#if GERMAN
	.string "Du bist gefährlich!$"
#else
	.string "You're mean!$"
#endif

Route3_Text_JanicePostBattle::
#if GERMAN
	.string "Hör auf, Leute anzustarren!\n"
	.string "Dann musst du auch nicht kämpfen!$"
#else
	.string "You shouldn't be staring if you\n"
	.string "don't want to battle!$"
#endif

Route3_Text_GregIntro::
#if GERMAN
	.string "Bist du auch ein Trainer?\n"
	.string "Lass uns kämpfen!$"
#else
	.string "Are you a TRAINER?\n"
	.string "Let's get with it right away!$"
#endif

Route3_Text_GregDefeat::
#if GERMAN
	.string "Mit diesen Pokémon hätte ich auch\n"
	.string "leicht gewonnen!$"
#else
	.string "If I had new POKéMON, I would've\n"
	.string "won!$"
#endif

Route3_Text_GregPostBattle::
#if GERMAN
	.string "Wenn auf dem PC eine Pokémon-Box\n"
	.string "voll ist, wechsle einfach zu einer\l"
	.string "anderen Box!$"
#else
	.string "If a POKéMON BOX on the PC gets\n"
	.string "full, just switch to another BOX.$"
#endif

Route3_Text_SallyIntro::
#if GERMAN
	.string "Warum schaust du mich so fasziniert\n"
	.string "an?$"
#else
	.string "That look you gave me…\n"
	.string "It's so intriguing!$"
#endif

Route3_Text_SallyDefeat::
#if GERMAN
	.string "Bleib immer nett!$"
#else
	.string "Be nice!$"
#endif

Route3_Text_SallyPostBattle::
#if GERMAN
	.string "Vermeide Kämpfe, indem du anderen\n"
	.string "Trainern aus dem Weg gehst!$"
#else
	.string "You can avoid battles by not\n"
	.string "letting TRAINERS see you.$"
#endif

Route3_Text_CalvinIntro::
#if GERMAN
	.string "Hehe! Ich habe meinem Bruder\n"
	.string "gesagt, er soll Shorts anziehen!$"
#else
	.string "Hey! You're not wearing shorts!\n"
	.string "What's wrong with you?$"
#endif

Route3_Text_CalvinDefeat::
#if GERMAN
	.string "Nein!\n"
	.string "Verloren!$"
#else
	.string "Lost!\n"
	.string "Lost! Lost!$"
#endif

Route3_Text_CalvinPostBattle::
#if GERMAN
	.string "Man sollte nicht alles machen, was\n"
	.string "der große Bruder verlangt! Hehe!$"
#else
	.string "I always wear shorts, even in\n"
	.string "winter. That's my policy.$"
#endif

Route3_Text_JamesIntro::
#if GERMAN
	.string "Meine neuen Pokémon wollen\n"
	.string "kämpfen!$"
#else
	.string "I'll battle you with the POKéMON\n"
	.string "I just caught.$"
#endif

Route3_Text_JamesDefeat::
#if GERMAN
	.string "Du hast meine Pokémon besiegt!$"
#else
	.string "Done like dinner!$"
#endif

Route3_Text_JamesPostBattle::
#if GERMAN
	.string "Die Pokémon eines Trainers sind\n"
	.string "stärker als wildlebende!$"
#else
	.string "Trained POKéMON are stronger than\n"
	.string "the wild ones.$"
#endif

Route3_Text_RobinIntro::
#if GERMAN
	.string "Huch! Sollen das etwa\n"
	.string "Annäherungsversuche sein?$"
#else
	.string "Eek!\n"
	.string "Did you touch me?$"
#endif

Route3_Text_RobinDefeat::
#if GERMAN
	.string "Bleib mir fern!$"
#else
	.string "That's it?$"
#endif

Route3_Text_RobinPostBattle::
#if GERMAN
	.string "Die Route 4 liegt am Fuße des\n"
	.string "Mondberges.$"
#else
	.string "ROUTE 4 is at the foot of\n"
	.string "MT. MOON.$"
#endif

Route3_Text_RouteSign::
#if GERMAN
	.string "Route 3\n"
	.string "Zum Mondberg$"
#else
	.string "ROUTE 3\n"
	.string "MT. MOON AHEAD$"
#endif

