SinjohRuins_RegirockRoom_hns_MapScripts::
	.byte 0

SinjohRuins_RegirockRoom_EventScript_Regirock::
	lock
	faceplayer
	playmoncry SPECIES_DIALGA, CRY_MODE_ENCOUNTER
	waitmoncry
	seteventmon SPECIES_DIALGA, 80
	special BattleSetup_StartLegendaryBattle
	waitstate
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, SinjohRuins_RegirockRoom_EventScript_RegirockRan
	fadescreenswapbuffers FADE_TO_BLACK
	removeobject LOCALID_SINJOHRUINS_REGIROCK
	setflag FLAG_HIDE_SINJOHRUINS_REGIROCK
	fadescreenswapbuffers FADE_FROM_BLACK
	release
	end

SinjohRuins_RegirockRoom_EventScript_RegirockRan::
	release
	end

