RocketHideout_B2F_hns_MapScripts::
	map_script MAP_SCRIPT_ON_LOAD, RocketHideout_B2F_OnLoad
	.byte 0

RocketHideout_B2F_OnLoad::
	call_if_set FLAG_HIDE_ROCKETHIDEOUT2_GATE, RocketHideout_B2F_HideGate
	call_if_eq VAR_MAHOGANY_TOWN_STATE, 13, RocketHideout_B2F_MoveLanceDragonite
	call_if_ge VAR_ELECTRODES_FAINTED, 4, RockerHideout2_DeactivateGenerator
	end

RockerHideout2_DeactivateGenerator::
	setmetatile 13, 8, 0x303, TRUE
	setmetatile 13, 9, 0x303, TRUE
	setmetatile 13, 10, 0x303, TRUE
	setmetatile 13, 11, 0x303, TRUE
	setmetatile 13, 12, 0x303, TRUE
	setmetatile 13, 13, 0x303, TRUE
	setmetatile 13, 14, 0x303, TRUE
	setmetatile 13, 15, 0x303, TRUE

	setmetatile 14, 8, 0x303, TRUE
	setmetatile 14, 9, 0x303, TRUE
	setmetatile 14, 10, 0x303, TRUE
	setmetatile 14, 11, 0x303, TRUE
	setmetatile 14, 12, 0x303, TRUE
	setmetatile 14, 13, 0x303, TRUE
	setmetatile 14, 14, 0x303, TRUE
	setmetatile 14, 15, 0x303, TRUE

	setmetatile 15, 8, 0x303, TRUE
	setmetatile 15, 9, 0x303, TRUE
	setmetatile 15, 10, 0x303, TRUE
	setmetatile 15, 11, 0x303, TRUE
	setmetatile 15, 12, 0x303, TRUE
	setmetatile 15, 13, 0x303, TRUE
	setmetatile 15, 14, 0x303, TRUE
	setmetatile 15, 15, 0x303, TRUE

	setmetatile 16, 8, 0x303, TRUE
	setmetatile 16, 9, 0x303, TRUE
	setmetatile 16, 10, 0x303, TRUE
	setmetatile 16, 11, 0x303, TRUE
	setmetatile 16, 12, 0x303, TRUE
	setmetatile 16, 13, 0x303, TRUE
	setmetatile 16, 14, 0x303, TRUE
	setmetatile 16, 15, 0x303, TRUE

	setmetatile 17, 8, 0x303, TRUE
	setmetatile 17, 9, 0x303, TRUE
	setmetatile 17, 10, 0x303, TRUE
	setmetatile 17, 11, 0x303, TRUE
	setmetatile 17, 12, 0x303, TRUE
	setmetatile 17, 13, 0x303, TRUE
	setmetatile 17, 14, 0x303, TRUE
	setmetatile 17, 15, 0x303, TRUE

	setmetatile 18, 8, 0x303, TRUE
	setmetatile 18, 9, 0x303, TRUE
	setmetatile 18, 10, 0x303, TRUE
	setmetatile 18, 11, 0x303, TRUE
	setmetatile 18, 12, 0x303, TRUE
	setmetatile 18, 13, 0x303, TRUE
	setmetatile 18, 14, 0x303, TRUE
	setmetatile 18, 15, 0x303, TRUE
	return

RocketHideout_B2F_HideGate::
	setmetatile 14, 19, 0x378, FALSE
	setmetatile 14, 20, 0x380, FALSE
	setmetatile 15, 19, 0x379, FALSE
	setmetatile 15, 20, 0x379, FALSE
	setmetatile 16, 19, 0x379, FALSE
	setmetatile 16, 20, 0x379, FALSE
	return

RocketHideout_B2F_MoveLanceDragonite::
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_DRAGONITE, 20, 16
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_LANCE, 19, 16
	setobjectmovementtype LOCALID_ROCKETHIDEOUT2_DRAGONITE, MOVEMENT_TYPE_WALK_IN_PLACE_UP
	setobjectmovementtype LOCALID_ROCKETHIDEOUT2_LANCE, MOVEMENT_TYPE_FACE_UP
	return

RocketHideout_B2F_Trigger_MurkrowStairs::
	lock
	applymovement LOCALID_ROCKETHIDEOUT2_MURKROWSTAIRS, RocketHideout_B2F_Movement_MurkrowStairs1
	waitmovement 0
	playmoncry SPECIES_MURKROW, CRY_MODE_NORMAL
	msgbox RocketHideout_B3F_Text_MurkrowSpeak1, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_MURKROWSTAIRS, RocketHideout_B2F_Movement_MurkrowStairs2
	waitmovement 0
	setflag FLAG_HIDE_ROCKETHIDEOUT2_MURKROWSTAIRS
	removeobject LOCALID_ROCKETHIDEOUT2_MURKROWSTAIRS
	clearflag FLAG_HIDE_ROCKETHIDEOUT3_MURKROWSTAIRS
	setvar VAR_MAHOGANY_TOWN_STATE, 10
	release
	end

RocketHideout_B2F_Movement_MurkrowStairs1:
	jump_in_place_left
	jump_in_place_left
	step_end

RocketHideout_B2F_Movement_MurkrowStairs2:
	jump_in_place_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	step_end

RocketHideout_B2F_Trigger_MurkrowGate::
	lock
	applymovement LOCALID_ROCKETHIDEOUT2_MURKROWGATE, RocketHideout_B2F_Movement_MurkrowGate1
	waitmovement 0
	playmoncry SPECIES_MURKROW, CRY_MODE_NORMAL
	msgbox RocketHideout_B3F_Text_Murkrow, MSGBOX_DEFAULT
	msgbox RocketHideout_B2F_Text_MurkrowUnlock, MSGBOX_DEFAULT
	playse SE_CLICK
	setmetatile 14, 19, 0x378, FALSE
	setmetatile 14, 20, 0x380, FALSE
	setmetatile 15, 19, 0x379, FALSE
	setmetatile 15, 20, 0x379, FALSE
	setmetatile 16, 19, 0x379, FALSE
	setmetatile 16, 20, 0x379, FALSE
	special DrawWholeMapView
	setflag FLAG_HIDE_ROCKETHIDEOUT2_GATE
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_MURKROWGATE, RocketHideout_B2F_Movement_MurkrowGate2
	waitmovement 0
	setflag FLAG_HIDE_ROCKETHIDEOUT2_MURKROWGATE
	removeobject LOCALID_ROCKETHIDEOUT2_MURKROWGATE
	setvar VAR_MAHOGANY_TOWN_STATE, 12
	release
	end
RocketHideout_B2F_Movement_MurkrowGate1:
	jump_in_place_up
	jump_in_place_up
	step_end

RocketHideout_B2F_Movement_MurkrowGate2:
	jump_in_place_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	step_end

RocketHideout_B2F_Text_MurkrowUnlock:
#if GERMAN
	.string "Kramurx kreischt das Passwort mit\n"
	.string "exakt derselben Stimme wie Lambda\l"
	.string "heraus!\p"
	.string "…\p"
	.string "Das sprachgesteuerte Schloss löst\n"
	.string "sich!$"
#else
    .string "MURKROW screamed the password,\n"
    .string "mimicking the voice of PETREL.\p"
    .string "..................\n"
    .string "The voice-recognition system\l"
    .string "unlocked the door!$"
#endif

@============================================================================================================================================

RocketHideout_B2F_Trigger_PlayerMoveLeft::
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkRight1
	waitmovement 0
	return
RocketHideout_B2F_Trigger_PlayerMoveRight::
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkLeft1
	waitmovement 0
	return

RocketHideout_B2F_Trigger_Ariana::
	lock
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_LANCE, 6, 26
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_DRAGONITE, 5, 26
	clearflag FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT
	addobject LOCALID_ROCKETHIDEOUT2_ARIANA
	addobject LOCALID_ROCKETHIDEOUT2_GRUNT
	delay 20
	msgbox RocketHideout_B2F_Text_ArianaHoldIt, MSGBOX_AUTOCLOSE
	playse SE_PIN
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	delay 60
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_0, 14, RocketHideout_B2F_Trigger_PlayerMoveLeft
	call_if_eq VAR_TEMP_0, 16, 	RocketHideout_B2F_Trigger_PlayerMoveRight
	applymovement OBJ_EVENT_ID_PLAYER, RocketHideout_B2F_Movement_PlayerMeetAriana
	applymovement LOCALID_ROCKETHIDEOUT2_ARIANA, RocketHideout_B2F_Movement_Ariana
	delay 20
	applymovement LOCALID_ROCKETHIDEOUT2_GRUNT, RocketHideout_B2F_Movement_Ariana
	waitmovement LOCALID_ROCKETHIDEOUT2_GRUNT
	msgbox RocketHideout_B2F_Text_ArianaChallenge, MSGBOX_DEFAULT
	closemessage
	clearflag FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
	addobject LOCALID_ROCKETHIDEOUT2_LANCE
	addobject LOCALID_ROCKETHIDEOUT2_DRAGONITE
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_Lance
	delay 20
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_Lance
	waitmovement 0
	msgbox RocketHideout_B2F_Text_LanceInterrupt, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_ARIANA, Common_Movement_WalkInPlaceFasterUp
	msgbox RocketHideout_B2F_Text_ArianaOutraged
	closemessage
	goto RocketHideout_B2F_EventScript_ReadyForBattlePrompt
	end

RocketHideout_B2F_Movement_PlayerMeetAriana:
	walk_down
	walk_down
	walk_down
	step_end

RocketHideout_B2F_Movement_Ariana:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

RocketHideout_B2F_Movement_Lance:
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	step_end

RocketHideout_B2F_Text_ArianaHoldIt:
#if GERMAN
	.string "Athena: Stehengeblieben!$"
#else
    .string "ARIANA: Hold it right there!$"
#endif

RocketHideout_B2F_Text_ArianaChallenge:
#if GERMAN
	.string "Athena: Wenn wir zulassen, dass sich ein\n"
	.string "Balg wie du hier so aufspielt, wird der\l"
	.string "Ruf von Team Rocket dadurch immer mehr\l"
	.string "Schaden nehmen. Das wäre nicht nur\l"
	.string "schade, sondern eine Schande!\p"
	.string "…Und genau deshalb werden wir hier\n"
	.string "langsam mal den Schlussstrich ziehen!\p"
	.string "Du magst noch so stark sein, wenn du es\n"
	.string "mit uns beiden gleichzeitig zu tun hast,\l"
	.string "ist das auch für dich das Ende der\l"
	.string "Fahnenstange! Sieh es ein!\p"
	.string "Mwahahaha! Tut uns leid, jetzt wirst du\n"
	.string "zermalmt!$"
#else
    .string "ARIANA: We can't let a brat like you\n"
    .string "do as you please forever.\p"
    .string "It'll hurt Team Rocket's pride over\n"
    .string "and over again. Making it lessen,\l"
    .string "you see.\p"
    .string "...So, it's time to finish you.\n"
    .string "However strong you may be,\p"
    .string "if the two of us fight at the same\n"
    .string "time, you'll have no chance of\l"
    .string "winning. Don't you agree?\p"
    .string "Hee hee hee! Sorry, baby.\n"
    .string "Now, get ready to be thrashed.$"
#endif

RocketHideout_B2F_Text_LanceInterrupt:
#if GERMAN
	.string "Siegfried: Augenblick mal!\p"
	.string "Zwei gegen einen? Findet ihr das nicht\n"
	.string "auch reichlich unausgewogen?\p"
	.string "Aber was erwarte ich schon von Team\n"
	.string "Rocket? Ihr lebt ja von solchen Tricks!\p"
	.string "Tut mir wirklich leid für euch, aber ich\n"
	.string "werde auch an diesem Kampf teilnehmen!$"
#else
    .string "LANCE: Hold it!\n"
    .string "A two-on-one battle?\p"
    .string "That is so unfair!\n"
    .string "Typical of Team Rocket to be so\l"
    .string "sneaky.\p"
    .string "Allow me to join the battle!$"
#endif

RocketHideout_B2F_Text_ArianaOutraged:
#if GERMAN
	.string "Athena: Nanu, du bist nicht alleine? Das\n"
	.string "passt mir aber gar nicht…\p"
	.string "Ihr frechen Rotzlöffel! Lasst euch von\n"
	.string "mir, Giovannis Vertreterin, eins gesagt\l"
	.string "sein!\p"
	.string "Ihr werdet noch früh genug erfahren,\n"
	.string "was mit Leuten geschieht, die sich Team\l"
	.string "Rocket in den Weg stellen!$"
#else
    .string "ARIANA: What? You had an accomplice?\n"
    .string "Where is your sense of dignity?\p"
    .string "As interim boss in place of GIOVANNI,\n"
    .string "I'll show you how wrong it is to meddle\l"
    .string "with Team Rocket!$"
#endif

RocketHideout_B2F_Text_LanceChooseMons:
#if GERMAN
	.string "Siegfried: Schnell, {PLAYER}, wähle\n"
	.string "deine Pokémon!$"
#else
    .string "LANCE: Quickly {PLAYER}, choose\n"
	.string "your POKéMON!$"
#endif

RocketHideout_B2F_EventScript_ReadyForBattlePrompt::
	msgbox RocketHideout_B2F_Text_LanceChooseMons, MSGBOX_DEFAULT
	goto RocketHideout_B2F_EventScript_ChoosePartyForMultiBattle
	end

RocketHideout_B2F_EventScript_ChoosePartyForMultiBattle::
	setflag FLAG_ROCKETHIDEOUT2_BATTLE
	special SavePlayerParty
	fadescreen FADE_TO_BLACK
	special ChooseHalfPartyForBattle
	waitstate
	goto_if_ne VAR_RESULT, 0, RocketHideout_B2F_EventScript_DoLanceMultiBattle
	special LoadPlayerParty
	goto RocketHideout_B2F_EventScript_ReadyForBattlePrompt

RocketHideout_B2F_EventScript_DoLanceMultiBattle::
	@ special ReducePlayerPartyToSelectedMons
	@ frontier_set FRONTIER_DATA_SELECTED_MON_ORDER
	@ setvar VAR_0x8004, SPECIAL_BATTLE_LANCE
	@ setvar VAR_0x8005, 0
	applymovement LOCALID_ROCKETHIDEOUT2_ARIANA, Common_Movement_WalkUp1
	applymovement LOCALID_ROCKETHIDEOUT2_GRUNT, Common_Movement_WalkUp1
	waitmovement 0
	turnobject LOCALID_ROCKETHIDEOUT2_GRUNT, DIR_WEST
	multi_2_vs_2 TRAINER_ARIANA_1_HNS, Debug_Text_ArianaDefeat, TRAINER_GRUNT_23_HNS, Debug_Text_Grunt23Defeat, PARTNER_LANCE_HNS
	@ special DoSpecialTrainerBattle
	@ waitstate
	@ frontier_saveparty
	@ special LoadPlayerParty
	switch VAR_RESULT
	case 1, RocketHideout_B2F_EventScript_DefeatedAriana
	fadescreen FADE_TO_BLACK
	setflag FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
	setflag FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT
	special SetCB2WhiteOut
	waitstate

RocketHideout_B2F_EventScript_DefeatedAriana::
	clearflag FLAG_ROCKETHIDEOUT2_BATTLE
	msgbox RocketHideout_Text_ArianaRetreat, MSGBOX_DEFAULT
	closemessage
	fadescreenswapbuffers FADE_TO_BLACK
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, Common_Movement_WalkUp1
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, Common_Movement_WalkUp1
	waitmovement 0
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, Common_Movement_WalkRight1
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, Common_Movement_WalkRight1
	waitmovement 0
	setflag FLAG_HIDE_MAHOGANY_ROCKETS
	setflag FLAG_HIDE_ROCKETHIDEOUT2_ARIANA_AND_GRUNT
	removeobject LOCALID_ROCKETHIDEOUT2_ARIANA
	removeobject LOCALID_ROCKETHIDEOUT2_GRUNT
	turnobject OBJ_EVENT_ID_PLAYER, DIR_WEST
	fadescreenswapbuffers FADE_FROM_BLACK
	msgbox RocketHideout_Text_LanceStepBack, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceWalkToGenerator
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_DragoniteWalkToGenerator
	delay 55
	applymovement OBJ_EVENT_ID_PLAYER, RocketHideout_B2F_Movement_LanceWalkToGenerator
	waitmovement 0

	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_DragoniteInvestigateGenerator
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceInvestigateGenerator
	delay 165
	playmoncry SPECIES_DRAGONITE, CRY_MODE_NORMAL
	waitmovement LOCALID_ROCKETHIDEOUT2_DRAGONITE
	waitmovement LOCALID_ROCKETHIDEOUT2_LANCE
	msgbox RocketHideout_B2F_Text_LanceElectrodeFaint, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceWalkToElectrode
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_LanceWalkToElectrode
	waitmovement LOCALID_ROCKETHIDEOUT2_DRAGONITE
	waitmovement LOCALID_ROCKETHIDEOUT2_LANCE
	applymovement OBJ_EVENT_ID_PLAYER, RocketHideout_B2F_Movement_PlayerWalkToElectrode
	waitmovement 0
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_DRAGONITE, 20, 16
	setobjectxyperm LOCALID_ROCKETHIDEOUT2_LANCE, 19, 16
	setobjectmovementtype LOCALID_ROCKETHIDEOUT2_DRAGONITE, MOVEMENT_TYPE_WALK_IN_PLACE_UP
	setobjectmovementtype LOCALID_ROCKETHIDEOUT2_LANCE, MOVEMENT_TYPE_FACE_UP
	setvar VAR_MAHOGANY_TOWN_STATE, 13
	release
	end

RocketHideout_B2F_Movement_LanceWalkToGenerator:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

RocketHideout_B2F_Movement_DragoniteWalkToGenerator:
	delay_8
	delay_8
	walk_right
	walk_up
	walk_up
	walk_up
	step_end


RocketHideout_B2F_Movement_LanceInvestigateGenerator:
	walk_up
	walk_left
	face_up
	delay_8
	delay_8
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	face_up
	delay_8
	delay_8
	face_right
	delay_8
	delay_8
	delay_8
	delay_8
	walk_left
	walk_left
	walk_left
	face_down
	step_end

RocketHideout_B2F_Movement_DragoniteInvestigateGenerator:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	walk_left
	delay_16
	delay_16
	delay_8
	delay_8
	delay_8
	delay_8
	walk_left
	walk_left
	walk_left
	step_end

RocketHideout_B2F_Movement_LanceWalkToElectrode:
	walk_right
	walk_right
	walk_right
	walk_right
	face_up
	step_end

RocketHideout_B2F_Movement_PlayerWalkToElectrode:
	walk_left
	walk_left
	walk_left
	step_end

RocketHideout_B2F_Trigger_Electrode::
	lock
	goto_if_eq VAR_ELECTRODES_FAINTED, 3, RocketHideout_B2F_EventScript_ElectrodeDone
	turnobject LOCALID_ROCKETHIDEOUT2_LANCE, DIR_WEST
	msgbox RocketHideout_B2F_Text_LanceSide, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_ROCKETHIDEOUT2_LANCE, DIR_NORTH
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkLeft1
	waitmovement 0
	release
	end

RocketHideout_B2F_EventScript_Electrode::
	lock
	playmoncry SPECIES_ELECTRODE, CRY_MODE_ENCOUNTER
	delay 40
	waitmoncry
	setwildbattle SPECIES_ELECTRODE, 30
	dowildbattle
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, RocketHideout_B2F_EventScript_Ran_Electrode
	goto_if_eq VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED, RocketHideout_B2F_EventScript_Ran_Electrode
	removeobject VAR_LAST_TALKED
	addvar VAR_ELECTRODES_FAINTED, 1
	release
	end

RocketHideout_B2F_EventScript_Ran_Electrode::
	release
	end

RocketHideout_B2F_EventScript_ElectrodeDone::
	playse SE_M_HYPER_BEAM
	removeobject LOCALID_LANCEELECTRODE1
	removeobject LOCALID_LANCEELECTRODE2
	removeobject LOCALID_LANCEELECTRODE3
	waitse
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	call_if_eq VAR_TEMP_1, 16, RocketHideout_B2F_Movement_PlayerMeetLanceTop
	call_if_eq VAR_TEMP_1, 18, RocketHideout_B2F_Movement_PlayerMeetLanceBot
	turnobject OBJ_EVENT_ID_PLAYER, DIR_EAST
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceMeetPlayerAfterElectrode
	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_LanceMeetPlayerAfterElectrode
	waitmovement LOCALID_ROCKETHIDEOUT2_DRAGONITE

	playse SE_CLICK
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	turnobject LOCALID_ROCKETHIDEOUT2_LANCE, DIR_NORTH
	call RockerHideout2_DeactivateGenerator
	special DrawWholeMapView
	delay 55
	turnobject LOCALID_ROCKETHIDEOUT2_LANCE DIR_WEST
	turnobject OBJ_EVENT_ID_PLAYER, DIR_EAST
	delay 30
	msgbox RocketHideout_B2F_Text_LanceElectrodeDone, MSGBOX_DEFAULT
	giveitem ITEM_HM_WHIRLPOOL
	msgbox RocketHideout_B2F_Text_LanceWhirlpool, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_ROCKETHIDEOUT2_LANCE, DIR_SOUTH
	delay 20
	msgbox RocketHideout_B2F_Text_LanceMonMaster, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceFinalExit
	delay 20

	applymovement LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_DragoniteFinalExit
	waitmovement LOCALID_ROCKETHIDEOUT2_DRAGONITE
	waitmovement LOCALID_ROCKETHIDEOUT2_LANCE

	setflag FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
	removeobject LOCALID_ROCKETHIDEOUT2_DRAGONITE
	removeobject LOCALID_ROCKETHIDEOUT2_LANCE
	setvar VAR_ELECTRODES_FAINTED, 4
	setvar VAR_MAHOGANY_TOWN_STATE, 14
	clearflag FLAG_HIDE_MAHOGANY_COP
	setflag FLAG_HIDE_MAHOGANY_TOWN_FATMAN
	setvar VAR_ROCKET_HIDEOUT_STATUE_1, 2
	setvar VAR_ROCKET_HIDEOUT_STATUE_2, 2
	setvar VAR_ROCKET_HIDEOUT_STATUE_3, 2
	setvar VAR_ROCKET_HIDEOUT_STATUE_4, 2
	setvar VAR_ROCKET_HIDEOUT_STATUE_5, 2
	release
	end

RocketHideout_B2F_Movement_PlayerMeetLanceTop:
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkDown1
	waitmovement 0
	return

RocketHideout_B2F_Movement_PlayerMeetLanceBot:
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkUp1
	waitmovement 0
	return

RocketHideout_B2F_Movement_LanceMeetPlayerAfterElectrode:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

RocketHideout_B2F_Movement_LanceFinalExit:
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	step_end

RocketHideout_B2F_Movement_DragoniteFinalExit:
	walk_left
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_left
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	step_end

RocketHideout_B2F_Text_GruntLoss:
#if GERMAN
	.string "....................$"
#else
    .string "....................$"
#endif

RocketHideout_B2F_Text_ArianaLoss:
#if GERMAN
	.string "Hoppla, du bist ziemlich stark!\p"
	.string "Das ist echt ein Jammer! Jemand wie du\n"
	.string "könnte es bei Team Rocket bis in den\l"
	.string "Vorstand schaffen!$"
#else
    .string "Tch, you really are strong.\n"
    .string "It's too bad.\p"
    .string "If you were to join Team Rocket,\n"
    .string "you could become an Executive.$"
#endif

RocketHideout_Text_ArianaRetreat:
#if GERMAN
	.string "Athena: Ach, und wennschon!\p"
	.string "Jetzt, wo unser Sende-Experiment\n"
	.string "geglückt ist, kümmert es mich nicht, was\l"
	.string "aus diesem Versteck wird!\p"
	.string "Unsere Sache ist seeehr viel größer als\n"
	.string "das alles hier zusammengenommen!\p"
	.string "Du wirst schon noch sehen! Vor Team\n"
	.string "Rocket nimmt man sich lieber in Acht!\p"
	.string "Sieh diesem Tag mit Freude entgegen!\n"
	.string "Mwahhahaha…$"
#else
    .string "ARIANA: But that's fine.\n"
    .string "The broadcast experiment was a\l"
    .string "total success.\p"
    .string "It doesn't matter what happens to\n"
    .string "this hideout now.\p"
    .string "We have much bigger plans.\n"
    .string "You'll come to appreciate Team\l"
    .string "Rocket's true power soon enough.\p"
    .string "Enjoy yourself while you can...\n"
    .string "Hee hee hee...$"
#endif

RocketHideout_Text_LanceStepBack:
#if GERMAN
	.string "Entschuldige, {PLAYER}.\n"
	.string "Ich sah, wie gut du warst,\l"
	.string "also habe ich mich zurückgehalten.\p"
	.string "Jetzt müssen wir nur noch das\n"
	.string "seltsame Radiosignal ausschalten.$"
#else
    .string "Sorry, {PLAYER}. I saw how well you\n"
    .string "were doing, so I just hung back.\p"
    .string "Now all there is left to do is to turn\n"
    .string "off that odd radio signal.$"
#endif


RocketHideout_B2F_Text_LanceElectrodeFaint:
#if GERMAN
	.string "Diese Maschine verursacht\n"
	.string "all die Probleme.\p"
	.string "Ich sehe keinen Schalter daran…\p"
	.string "Wir haben keine Wahl. Wir müssen\n"
	.string "alle Lektrobal ohnmächtig machen.\p"
	.string "Dann hört die Maschine auf,\n"
	.string "dieses seltsame Signal zu senden.\p"
	.string "Es ist nicht die Schuld der Pokémon,\n"
	.string "also fühle ich mich schuldig.\p"
	.string "{PLAYER}, lass uns die Arbeit teilen.$"
#else
    .string "It's this machine that's causing\n"
    .string "all the problems.\p"
    .string "I don't see a switch on it…\p"
    .string "We have no choice. We have to\n"
    .string "make all the ELECTRODE faint.\p"
    .string "That should stop this machine\n"
    .string "from transmitting that strange\l"
    .string "signal.\p"
    .string "It's no fault of the POKéMON, so\n"
    .string "it makes me feel guilty.\p"
    .string "{PLAYER}, let's split the job.$"
#endif

RocketHideout_B2F_Text_LanceSide:
#if GERMAN
	.string "Siegfried: Diese Seite übernehme ich!$"
#else
    .string "LANCE: Leave this side to me.$"
#endif

RocketHideout_B2F_Text_LanceElectrodeDone:
#if GERMAN
	.string "Siegfried: Das seltsame Signal\n"
	.string "ist verschwunden.\p"
	.string "Der See sollte sich wieder\n"
	.string "normalisiert haben.\p"
	.string "Du bist ein Held! Ich danke dir\n"
	.string "im Namen aller Pokémon.\p"
	.string "Ja, du solltest es annehmen.\p"
	.string "Ich fand es hier, kann es aber\n"
	.string "nicht gebrauchen.$"
#else
    .string "LANCE: That odd signal has\n"
    .string "finally stopped.\p"
    .string "The LAKE should be back to\n"
    .string "normal.\p"
    .string "You're the hero! Let me thank\n"
    .string "you on behalf of all the\l"
    .string "POKéMON.\p"
    .string "Oh, yes. You should take this.\n"
    .string "I found it here, but I don't\l"
    .string "have any need for it.$"
#endif

RocketHideout_B2F_Text_LanceWhirlpool:
#if GERMAN
	.string "Das ist Whirlpool.\n"
	.string "Lehre es einem Pokémon, um\l"
	.string "über wildes Wasser zu kommen.\p"
	.string "Aber merke dir: Außerhalb des Kampfes\p"
	.string "kannst du es nur mit dem Orden\n"
	.string "der Arena von {COLOR RED}Mahagonia City{COLOR DARK_GRAY}\l"
	.string "nutzen.$"
#else
    .string "That's WHIRLPOOL. Teach it to a\n"
    .string "POKéMON to get across wild water.\p"
    .string "But keep this in mind.\p"
    .string "You can use that out of battle\n"
    .string "only with the BADGE from\l"
    .string "MAHOGANY GYM.$"
#endif

RocketHideout_B2F_Text_LanceMonMaster:
#if GERMAN
	.string "{PLAYER}…\p"
	.string "Der Weg zum Pokémon-Meister\n"
	.string "ist lang und schwer.\p"
	.string "Weißt du das… wirst du weitergehen?\n"
	.string "…\p"
	.string "Ich verstehe. Nein, du hast recht.\p"
	.string "Wenn du so leicht aufgegeben hättest,\n"
	.string "hättest du deinen Traum nie verfolgt.\p"
	.string "Ich freue mich darauf, dich wieder\n"
	.string "zusehen!$"
#else
    .string "{PLAYER}…\p"
    .string "The journey to becoming the\n"
    .string "POKéMON MASTER is long and\l"
    .string "difficult.\p"
    .string "Knowing that, will you keep\n"
    .string "going?\p"
    .string "…\p"
    .string "I see. No, you're right.\p"
    .string "If you would give up that easily,\n"
    .string "you would have never chased that\l"
    .string "dream in the first place.\p"
    .string "I look forward to seeing you\n"
    .string "again!$"
#endif

RocketHideout_B2F_Text_B2FTransmitter:
#if GERMAN
	.string "Dieser Radiotransmitter sendet\n"
	.string "das unheimliche Signal.\p"
	.string "Er läuft auf vollen Touren.$"
#else
    .string "It's the radio transmitter that's\n"
    .string "sending the sinister signal.\p"
    .string "It's working at full capacity.$"
#endif

RocketHideout_B2F_Text_B2FDeactivateTransmitter:
#if GERMAN
	.string "Der Radiotransmitter scheint nun nicht\n"
	.string "mehr zu laufen.$"
#else
    .string "The radio transmitter has finally\n"
    .string "stopped its evil broadcast.$"
#endif


@===========================================================================================================================================

RocketHideout_EventScript_Item_Thief::
	finditem ITEM_TM_THIEF
	end

RocketHideout_B2F_EventScript_LanceTriggerLeft::
	lock
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkRight1
	waitmovement 0
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	goto RocketHideout_B2F_EventScript_Lance

RocketHideout_B2F_EventScript_LanceTriggerRight::
	lock
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkLeft1
	waitmovement 0
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	goto RocketHideout_B2F_EventScript_Lance

RocketHideout_B2F_EventScript_Lance::
	lock
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkUp1
	waitmovement 0
	msgbox RocketHideout_B2F_Text_LanceHeals1, MSGBOX_DEFAULT
	closemessage
	call Common_EventScript_OutOfCenterPartyHeal
	msgbox RocketHideout_B2F_Text_LanceHeals2, MSGBOX_DEFAULT
	closemessage
	applymovement2 LOCALID_ROCKETHIDEOUT2_LANCE, RocketHideout_B2F_Movement_LanceGoDeeper
	applymovement2 LOCALID_ROCKETHIDEOUT2_DRAGONITE, RocketHideout_B2F_Movement_DragoniteGoDeeper
	waitmovement LOCALID_ROCKETHIDEOUT2_LANCE
	waitmovement LOCALID_ROCKETHIDEOUT2_DRAGONITE
	setflag FLAG_HIDE_ROCKETHIDEOUT2_LANCE_DRAGONITE
	removeobject LOCALID_ROCKETHIDEOUT2_LANCE
	setvar VAR_MAHOGANY_TOWN_STATE, 6
	removeobject LOCALID_ROCKETHIDEOUT2_DRAGONITE
	release
	end

RocketHideout_B2F_Movement_LanceGoDeeper:
	walk_right
	walk_right
	delay_2
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_right
	walk_right
	walk_right
	walk_right
	step_end

RocketHideout_B2F_Movement_DragoniteGoDeeper:
	delay_8
	delay_8
	delay_8
	delay_8
	walk_down
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_right
	walk_right
	walk_right
	step_end

RocketHideout_B2F_Text_LanceHeals1:
#if GERMAN
	.string "Siegfried: Alles in Ordnung bei dir?\p"
	.string "Deine Pokémon sind ziemlich\n"
	.string "angeschlagen! Komm, ich gebe dir was\l"
	.string "von meinen Tränken ab.$"
#else
    .string "LANCE: Are you all right?\p"
    .string "Your POKéMON are hurt and tired.\p"
    .string "Here, give them some of my\n"
    .string "medicine.$"
#endif

RocketHideout_B2F_Text_LanceHeals2:
#if GERMAN
	.string "Siegfried: {PLAYER}, lass uns\n"
	.string "alles für die Pokémon geben.$"
#else
    .string "LANCE: {PLAYER}, let's give it\n"
    .string "our best for POKéMON.$"
#endif

RocketHideout_B2F_Text_GruntM17Seen:
#if GERMAN
	.string "Du kriegst die Tür nicht auf?\p"
	.string "Kunststück. Die ist ja auch\n"
	.string "passwortgeschützt. Nur Team Rocket\l"
	.string "hat darauf Zugriff.$"
#else
    .string "The door won't open?\p"
    .string "Well, duh. It has to have a\n"
    .string "password that only TEAM ROCKET\l"
    .string "knows.$"
#endif

RocketHideout_B2F_Text_GruntM17Beaten:
#if GERMAN
	.string "Wie? Schon verloren?$"
#else
    .string "What? I lost?$"
#endif

RocketHideout_B2F_Text_GruntM17After:
#if GERMAN
	.string "Heh, ich bin nur ein Rüpel.\p"
	.string "Ich kenne das Passwort nicht.\n"
	.string "Pech für dich.$"
#else
    .string "Heh, I'm just a GRUNT.\p"
    .string "I don't know the password.\n"
    .string "Too bad for you.$"
#endif

RocketHideout_B2F_EventScript_Grunt14::
	trainerbattle_single TRAINER_GRUNT_14_HNS, RocketHideout_B2F_Text_GruntM17Seen, RocketHideout_B2F_Text_GruntM17Beaten
	msgbox RocketHideout_B2F_Text_GruntM17After, MSGBOX_AUTOCLOSE
	end

RocketHideout_B2F_Text_GruntM18Seen:
#if GERMAN
	.string "E-ein Kind? Ich mache das zwar nur\n"
	.string "widerwillig, aber ich muss dich\l"
	.string "ausschalten.$"
#else
    .string "Oh, a kid? I don't really like\n"
    .string "this, but eliminate you I must.$"
#endif

RocketHideout_B2F_Text_GruntM18Beaten:
#if GERMAN
	.string "Ich hätte es wissen sollen…$"
#else
    .string "I knew I'd lose…$"
#endif

RocketHideout_B2F_Text_GruntM18After:
#if GERMAN
	.string "Bei der letzten Mission hat mich\n"
	.string "auch ein Kind plattgemacht.\p"
	.string "Als wir Pokémon entführten, kam dieses\n"
	.string "Kind mit langen roten Haaren\l"
	.string "und bösen Augen.\p"
	.string "Er hat mich einfach niedergemacht…$"
#else
    .string "I got wiped out on the last\n"
    .string "mission by a kid too.\p"
    .string "When we were abducting POKéMON,\n"
    .string "this kid with long red hair and\l"
    .string "mean-looking eyes just\l"
    .string "creamed me…$"
#endif

RocketHideout_B2F_EventScript_Grunt15::
	trainerbattle_single TRAINER_GRUNT_15_HNS, RocketHideout_B2F_Text_GruntM18Seen, RocketHideout_B2F_Text_GruntM18Beaten
	msgbox RocketHideout_B2F_Text_GruntM18After, MSGBOX_AUTOCLOSE
	end

RocketHideout_B2F_Text_GruntM19Seen:
#if GERMAN
	.string "Du bist wirklich ein Quälgeist!$"
#else
    .string "You rotten little pest!$"
#endif

RocketHideout_B2F_Text_GruntM19Beaten:
#if GERMAN
	.string "Grrr…$"
#else
    .string "Grrrr…$"
#endif

RocketHideout_B2F_Text_GruntM19After:
#if GERMAN
	.string "Heh, nur der Boss kennt das\n"
	.string "Passwort für diese Tür.\p"
	.string "Wo der Boss ist? Wer weiß?\n"
	.string "Such ihn doch.$"
#else
    .string "Heh, only the boss knows the\n"
    .string "password for that door.\p"
    .string "Where's the boss? Who knows?\n"
    .string "Go look for yourself.$"
#endif

RocketHideout_B2F_EventScript_Grunt16::
	trainerbattle_single TRAINER_GRUNT_16_HNS, RocketHideout_B2F_Text_GruntM19Seen, RocketHideout_B2F_Text_GruntM19Beaten
	msgbox RocketHideout_B2F_Text_GruntM19After, MSGBOX_AUTOCLOSE
	end

