OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
#if GERMAN
	.string "Das Wetter ist wunderbar!\n"
	.string "Perfekt für einen Kampf!$"
#else
	.string "The weather's gorgeous!\n"
	.string "Perfect for a battle!$"
#endif

OneIsland_KindleRoad_Text_MariaDefeat::
#if GERMAN
	.string "Uhhhhhhhhh!$"
#else
	.string "Aiyeeeeh!$"
#endif

OneIsland_KindleRoad_Text_MariaPostBattle::
#if GERMAN
	.string "Bitte bespritze nicht mein Gesicht!\n"
	.string "Du ruinierst mein Makeup!$"
#else
	.string "Please don't splash my face!\n"
	.string "You'll ruin the makeup.$"
#endif

OneIsland_KindleRoad_Text_AbigailIntro::
#if GERMAN
	.string "Ich bekomme langsam einen\n"
	.string "Sonnenbrand…$"
#else
	.string "I'm beginning to get a sunburn…$"
#endif

OneIsland_KindleRoad_Text_AbigailDefeat::
#if GERMAN
	.string "Oh, du bist schrecklich!$"
#else
	.string "Oh, you're so awful.$"
#endif

OneIsland_KindleRoad_Text_AbigailPostBattle::
#if GERMAN
	.string "Ich mag deinen Hut. Vielleicht\n"
	.string "sollte ich auch einen tragen…$"
#else
	.string "I like that cap you have.\n"
	.string "Maybe I should wear one, too…$"
#endif

OneIsland_KindleRoad_Text_FinnIntro::
#if GERMAN
	.string "Von hier kann man den Glutberg\n"
	.string "in den Himmel ragen sehen.$"
#else
	.string "Seen from here, MT. EMBER towers\n"
	.string "into the sky.$"
#endif

OneIsland_KindleRoad_Text_FinnDefeat::
#if GERMAN
	.string "Hm, du bist stark, oder?$"
#else
	.string "Well, aren't you tough?$"
#endif

OneIsland_KindleRoad_Text_FinnPostBattle::
#if GERMAN
	.string "Der Himmel ist hier immens!$"
#else
	.string "The sky is immense around these\n"
	.string "parts.$"
#endif

OneIsland_KindleRoad_Text_GarrettIntro::
#if GERMAN
	.string "Habe ich beim Schwimmen nur eine Pause\n"
	.string "gemacht, um von dir herausgefordert zu\l"
	.string "werden?$"
#else
	.string "I took a break from swimming,\n"
	.string "only to have you challenge me?$"
#endif

OneIsland_KindleRoad_Text_GarrettDefeat::
#if GERMAN
	.string "Heh, was…\n"
	.string "Du bist wirklich gut!$"
#else
	.string "Hey, what the…\n"
	.string "You're good, you!$"
#endif

OneIsland_KindleRoad_Text_GarrettPostBattle::
#if GERMAN
	.string "Anstatt Surfer ständig einzusetzen,\n"
	.string "solltest du ein wenig schwimmen.$"
#else
	.string "Instead of using SURF all the time,\n"
	.string "you should swim some.$"
#endif

OneIsland_KindleRoad_Text_TommyIntro::
#if GERMAN
	.string "Warte! Warte einen Moment!\n"
	.string "Ich habe einen Großen am Haken!$"
#else
	.string "Wait! Wait a second!\n"
	.string "I think I've hooked a big one!$"
#endif

OneIsland_KindleRoad_Text_TommyDefeat::
#if GERMAN
	.string "Ich habe erneut verloren…$"
#else
	.string "I've lost it all again…$"
#endif

OneIsland_KindleRoad_Text_TommyPostBattle::
#if GERMAN
	.string "Ich habe nicht nur den Kampf, sondern\n"
	.string "auch den Fisch verloren!$"
#else
	.string "Not only did I lose, the big one\n"
	.string "got away from me, too!$"
#endif

OneIsland_KindleRoad_Text_SharonIntro::
#if GERMAN
	.string "Könntest du mir beim\n"
	.string "Training aushelfen?$"
#else
	.string "Could you help me out with my\n"
	.string "training?$"
#endif

OneIsland_KindleRoad_Text_SharonDefeat::
#if GERMAN
	.string "Du bist mir eine Nummer zu groß!$"
#else
	.string "You were a cut above me.$"
#endif

OneIsland_KindleRoad_Text_SharonPostBattle::
#if GERMAN
	.string "Es ist offensichtlich, dass du\n"
	.string "Talent hast! Ich mag dich!$"
#else
	.string "It's clear that you're skilled.\n"
	.string "I like you!$"
#endif

OneIsland_KindleRoad_Text_TanyaIntro::
#if GERMAN
	.string "Es gibt keinen Tag, an dem\n"
	.string "wir nicht trainieren!$"
#else
	.string "There isn't a day in which we don't\n"
	.string "train!$"
#endif

OneIsland_KindleRoad_Text_TanyaDefeat::
#if GERMAN
	.string "Ich bin so doof!$"
#else
	.string "I'm such a fool!$"
#endif

OneIsland_KindleRoad_Text_TanyaPostBattle::
#if GERMAN
	.string "Von jetzt an werde ich noch\n"
	.string "härter trainieren.$"
#else
	.string "I'll train even harder from now on!$"
#endif

OneIsland_KindleRoad_Text_SheaIntro::
#if GERMAN
	.string "Jeden Morgen vorm Frühstück\n"
	.string "schwimme ich um diese Insel.$"
#else
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island.$"
#endif

OneIsland_KindleRoad_Text_SheaDefeat::
#if GERMAN
	.string "Schnauf…\n"
	.string "Schnauf…$"
#else
	.string "Gasp…\n"
	.string "Gasp…$"
#endif

OneIsland_KindleRoad_Text_SheaPostBattle::
#if GERMAN
	.string "Ich habe verloren, weil ich wegen der\n"
	.string "Rennerei außer Puste war…$"
#else
	.string "I lost because I'm pooped from all\n"
	.string "the running I did…$"
#endif

OneIsland_KindleRoad_Text_HughIntro::
#if GERMAN
	.string "Kleide dich für einen Kampf!\n"
	.string "Wechsle dieses unwürdige Outfit!$"
#else
	.string "Dress appropriately for battle!\n"
	.string "Lose that frivolous outfit!$"
#endif

OneIsland_KindleRoad_Text_HughDefeat::
#if GERMAN
	.string "Warum gerade ich?!?$"
#else
	.string "Why me?!$"
#endif

OneIsland_KindleRoad_Text_HughPostBattle::
#if GERMAN
	.string "Sogar Kampfsportler sind heut-\n"
	.string "zutage modebewusst…$"
#else
	.string "Even martial artists are becoming\n"
	.string "fashion conscious these days…$"
#endif

OneIsland_KindleRoad_Text_BryceIntro::
#if GERMAN
	.string "Alles schmeckt großartig, wenn\n"
	.string "du in der Natur bist!$"
#else
	.string "You know, everything tastes great\n"
	.string "when you're out in the wild.$"
#endif

OneIsland_KindleRoad_Text_BryceDefeat::
#if GERMAN
	.string "Ugh! Vergeigt!$"
#else
	.string "Awww, blown!$"
#endif

OneIsland_KindleRoad_Text_BrycePostBattle::
#if GERMAN
	.string "Das Wasser in Gebieten mit\n"
	.string "Vulkanen ist köstlich!$"
#else
	.string "The water in volcanic regions is\n"
	.string "delicious.$"
#endif

OneIsland_KindleRoad_Text_ClaireIntro::
#if GERMAN
	.string "Mein Mittagessen hat uns gesättigt!\n"
	.string "Kämpfst du gegen uns, damit wir ein\l"
	.string "wenig Bewegung bekommen?$"
#else
	.string "My lunch filled us up, so will you\n"
	.string "battle us for some exercise?$"
#endif

OneIsland_KindleRoad_Text_ClaireDefeat::
#if GERMAN
	.string "Das brachte mich ins Schwitzen!$"
#else
	.string "That made me all sweaty.$"
#endif

OneIsland_KindleRoad_Text_ClairePostBattle::
#if GERMAN
	.string "Was soll ich tun?\n"
	.string "Ich sterbe vor Hunger!$"
#else
	.string "What should I do?\n"
	.string "I feel famished again.$"
#endif

OneIsland_KindleRoad_Text_KiaIntro::
#if GERMAN
	.string "Heidi: Mein großer Bruder und ich\n"
	.string "sind ein grandioses Gespann!$"
#else
	.string "KIA: My big brother and I make\n"
	.string "an awesome combination!$"
#endif

OneIsland_KindleRoad_Text_KiaDefeat::
#if GERMAN
	.string "Heidi: Häh!?!\n"
	.string "Ich kann es nicht glauben!$"
#else
	.string "KIA: Huh?!\n"
	.string "I can't believe it!$"
#endif

OneIsland_KindleRoad_Text_KiaPostBattle::
#if GERMAN
	.string "Heidi: Wie kann jemand besser\n"
	.string "als mein Bruder sein?$"
#else
	.string "KIA: How could there be anyone\n"
	.string "better than my big brother?$"
#endif

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
#if GERMAN
	.string "Heidi: Wenn du gegen uns kämpfen\n"
	.string "möchtest, musst du mindestens zwei\l"
	.string "Pokémon mitbringen!$"
#else
	.string "KIA: If you want to battle with\n"
	.string "us, you have to bring at least two\l"
	.string "POKéMON with you.$"
#endif

OneIsland_KindleRoad_Text_MikIntro::
#if GERMAN
	.string "Dirk: An der Seite von Heidi\n"
	.string "habe ich vor nichts Angst!$"
#else
	.string "MIK: Together with KIA, I'm afraid\n"
	.string "of nothing!$"
#endif

OneIsland_KindleRoad_Text_MikDefeat::
#if GERMAN
	.string "Dirk: Wow!\n"
	.string "Das ist zu viel!$"
#else
	.string "MIK: Whoa!\n"
	.string "That's too much!$"
#endif

OneIsland_KindleRoad_Text_MikPostBattle::
#if GERMAN
	.string "Dirk: Wie kann ich an der\n"
	.string "Seite von Heidi verlieren?$"
#else
	.string "MIK: How could my combination\n"
	.string "with KIA fail?$"
#endif

OneIsland_KindleRoad_Text_MikNotEnoughMons::
#if GERMAN
	.string "Dirk: Möchtest du gegen uns beide\n"
	.string "kämpfen?$"
#else
	.string "MIK: Hey, do you want to battle\n"
	.string "with us two?\p"
	.string "Bring two or more POKéMON with\n"
	.string "you, then.$"
#endif

OneIsland_KindleRoad_Text_RouteSign::
#if GERMAN
	.string "Das ist der Glühweg.\p"
	.string "Zum Glutberg geradeaus.$"
#else
	.string "This is KINDLE ROAD.\p"
	.string "Go straight for MT. EMBER.$"
#endif

OneIsland_KindleRoad_Text_EmberSpaSign::
#if GERMAN
	.string "Entfache das Feuer in dir!\n"
	.string "Gluttherme$"
#else
	.string "Light the Fire in Your Heart!\n"
	.string "EMBER SPA$"
#endif

