Route50_hns_MapScripts::
	.byte 0

Route50_EventScript_BlackBelt1::
	msgbox Route50_Text_BlackBelt1, MSGBOX_NPC
	end

Route50_Text_BlackBelt1::
#if GERMAN
	.string "Der Körper muss gestählt und der\n"
	.string "Geist gefestigt werden - unter den\l"
	.string "härtesten Bedingungen!$"
#else
	.string "The body must be hardened\n"
    .string "and the mind strengthened\l"
    .string "in the harshest of conditions!$"
#endif

Route50_EventScript_BlackBelt2::
	msgbox Route50_Text_BlackBelt2, MSGBOX_NPC
	end

Route50_Text_BlackBelt2::
#if GERMAN
	.string "Puh!\p"
	.string "Ich bin nicht so hart im Nehmen\n"
	.string "wie er.\p"
	.string "Hier gibt es aber auch wirklich\n"
	.string "nichts anderes zu tun als Training.$"
#else
    .string "Phew!\p"
    .string "I'm not as hardcore as he is.\p"
	.string "There's really not much else\n"
    .string "to do here but train.$"
#endif
  

Route50_EventScript_Wessel::
	goto_if_defeated TRAINER_WESSEL_HNS, Route50_EventScript_WesselAfter
	msgbox Route50_Text_WesselBefore, MSGBOX_NPC
	goto_if_not_defeated TRAINER_WESSEL_HNS, Route50_EventScript_TryWesselBattle
	end
Route50_EventScript_TryWesselBattle::
	goto_if_eq VAR_SINJOH_STORYLINE, 6, Route50_EventScript_WesselBattle
	end
Route50_EventScript_WesselBattle::
	lock
	msgbox Route50_Text_WesselBeforeBattle, MSGBOX_AUTOCLOSE
	trainerbattle_no_intro TRAINER_WESSEL_HNS, Route50_Text_WesselDefeat
	giveitem ITEM_IRON_PLATE
	addvar VAR_PLATECOUNTER, 1
	msgbox Route50_Text_WesselAfter, MSGBOX_AUTOCLOSE
	call_if_eq VAR_PLATECOUNTER, 3, SinjohRuins_Lab_EventScript_3Plates
	call_if_eq VAR_PLATECOUNTER, 6, SinjohRuins_Lab_EventScript_6Plates
	call_if_eq VAR_PLATECOUNTER, 9, SinjohRuins_Lab_EventScript_9Plates
	call_if_eq VAR_PLATECOUNTER, 12, SinjohRuins_Lab_EventScript_12Plates
	call_if_eq VAR_PLATECOUNTER, 15, SinjohRuins_Lab_EventScript_15Plates
	call_if_eq VAR_PLATECOUNTER, 16, SinjohRuins_Lab_EventScript_16Plates
	release
	end
Route50_EventScript_WesselAfter::
	msgbox Route50_Text_WesselAfter, MSGBOX_NPC
	end

Route50_Text_WesselBefore:
#if GERMAN
	.string "Unglaublich, ein Voltobal!\p"
	.string "Aber es scheint aus… Holz zu\n"
	.string "bestehen?\p"
	.string "Meine Hypothese, dass es auf dieser\n"
	.string "Route viele Stahl-Pokémon gibt, ist\l"
	.string "damit erneut widerlegt.\p"
	.string "Aber warum sonst hätte ich hier\n"
	.string "diese Eisentafel finden sollen?\p"
	.string "Ich muss mehr Daten sammeln!$"
#else
	.string "Incredible, A VOLTORB!\p"
    .string "But it appears to be made\n"
    .string "of... Wood?\p"
    .string "My hypothesis that this route\n"
    .string "would contain many steel types\l"
    .string "is disproven yet again.\p"
    .string "But why else would I have found\n"
    .string "this STEEL PLATE here?\p"
    .string "I must collect more data!$"
#endif

Route50_Text_WesselBeforeBattle:
#if GERMAN
	.string "Du willst diese Tafel haben?\n"
	.string "Aber ich habe sie noch gar nicht\l"
	.string "analysiert!\p"
	.string "Na schön, kämpfen wir darum.$"
#else
	.string "You want this PLATE?\n"
	.string "But I haven't analyzed it yet!\p"
	.string "Fine, we will battle for it.$"
#endif

Route50_Text_WesselDefeat:
#if GERMAN
	.string "Meine Hypothese war falsch…$"
#else
	.string "My hypothesis was wrong...$"
#endif

Route50_Text_WesselAfter:
#if GERMAN
	.string "Nimm die Tafel. Ich möchte nicht\n"
	.string "darüber reden.$"
#else
	.string "Take it the PLATE. I don't want to\n"
	.string "talk about it.$"
#endif

Route50_EventScript_Finley::
	goto_if_defeated TRAINER_FINLEY_HNS, Route50_EventScript_FinleyAfter
	msgbox Route50_Text_FinleyBefore, MSGBOX_NPC
	goto_if_not_defeated TRAINER_FINLEY_HNS, Route50_EventScript_TryFinleyBattle
	end
Route50_EventScript_TryFinleyBattle::
	goto_if_eq VAR_SINJOH_STORYLINE, 6, Route50_EventScript_FinleyBattle
	end
Route50_EventScript_FinleyBattle::
	lock
	msgbox Route50_Text_FinleyBeforeBattle, MSGBOX_AUTOCLOSE
	trainerbattle_no_intro TRAINER_FINLEY_HNS, Route50_Text_FinleyDefeat
	giveitem ITEM_DRACO_PLATE
	addvar VAR_PLATECOUNTER, 1
	msgbox Route50_Text_FinleyAfter, MSGBOX_AUTOCLOSE
	call_if_eq VAR_PLATECOUNTER, 3, SinjohRuins_Lab_EventScript_3Plates
	call_if_eq VAR_PLATECOUNTER, 6, SinjohRuins_Lab_EventScript_6Plates
	call_if_eq VAR_PLATECOUNTER, 9, SinjohRuins_Lab_EventScript_9Plates
	call_if_eq VAR_PLATECOUNTER, 12, SinjohRuins_Lab_EventScript_12Plates
	call_if_eq VAR_PLATECOUNTER, 15, SinjohRuins_Lab_EventScript_15Plates
	call_if_eq VAR_PLATECOUNTER, 16, SinjohRuins_Lab_EventScript_16Plates
	release
	end
Route50_EventScript_FinleyAfter::
	msgbox Route50_Text_FinleyAfter, MSGBOX_NPC
	end

Route50_Text_FinleyBefore:
#if GERMAN
	.string "Wie behandeln dich die\n"
	.string "Dorfbewohner?\p"
	.string "Fremden gegenüber können sie sehr\n"
	.string "abweisend sein.\p"
	.string "Dabei ist es eine der größten\n"
	.string "Freuden des Lebens, neue Menschen\l"
	.string "kennenzulernen.\p"
	.string "Eines Tages hoffe ich, Champ\n"
	.string "{COLOR RED}Siegfried{COLOR DARK_GRAY} zu begegnen.\p"
	.string "Er ist ein legendärer Drachen-\n"
	.string "Bändiger, ganz wie ich.\l"
	.string "Wer ich bin?\p"
	.string "Nun, ich bin Finley, Hüter der\n"
	.string "Dracotafel.$"
#else
	.string "How are the villagers treating\n"
    .string "you?\p"
    .string "They can be very unwelcoming to\n"
    .string "strangers.\p"
    .string "But meeting new people is one\n"
    .string "of life's greatest joys.\p"
    .string "One day, I hope to meet CHAMPION\n"
    .string "LANCE.\p"
    .string "He is a legendary dragon tamer,\n"
    .string "much like myself.\l"
    .string "Who am I?\p"
    .string "Well, I am FINLEY, keeper of the\n"
    .string "DRACO PLATE.$"
#endif

Route50_Text_FinleyBeforeBattle:
#if GERMAN
	.string "Ich weiß, dass die Kimono-Girls dich\n"
	.string "geschickt haben, um die Tafeln zu\l"
	.string "sammeln.\p"
	.string "Sie sagen, du seist würdig…\n"
	.string "Doch bezwingst du auch meine\l"
	.string "Drachen?$"
#else
	.string "I know the KIMONO's have sent you\n"
	.string "to collect these PLATES.\p"
	.string "They say you are worthy...\n"
	.string "But can you conquer my dragons?$"
#endif

Route50_Text_FinleyDefeat:
#if GERMAN
	.string "Meine Drachen haben tapfer\n"
	.string "gekämpft.$"
#else
	.string "My dragons fought well.$"
#endif

Route50_Text_FinleyAfter:
#if GERMAN
	.string "Vielleicht bist du sogar stark genug,\n"
	.string "um {COLOR RED}Siegfried{COLOR DARK_GRAY} zu schlagen…$"
#else
	.string "Perhaps you are even strong enough\n"
	.string "to beat LANCE...$"
#endif

Route50_EventScript_Item_ULtraBall::
    finditem ITEM_ULTRA_BALL
    end

Route50_EventScript_Item_Big_Nugget::
    finditem ITEM_BIG_NUGGET
    end

Route50_EventScript_ActivateKleavor::
    lock
    setobjectxyperm LOCALID_ROUTE50_NOBLE_KLEAVOR, 75, 12
    playse SE_M_DETECT
	getplayerxy VAR_TEMP_1, VAR_TEMP_2
	dofieldeffectsparkle VAR_TEMP_1, VAR_TEMP_2, 0
	waitfieldeffect FLDEFF_SPARKLE
    playse SE_PIN
    applymovement2 LOCALID_PLAYER, Common_Movement_ExclamationMark
    delay 60
    msgbox SinjohRuins_Lab_Text_PlayFlute, MSGBOX_YESNO
	closemessage
    goto_if_eq VAR_RESULT, FALSE, SinjohRuins_Lab_EventScript_NoOp
    playbgm MUS_DP_AZURE_FLUTE, FALSE
    delay 200
    fadedefaultbgm
    addobject LOCALID_ROUTE50_NOBLE_KLEAVOR
    clearflag FLAG_HIDE_ROUTE50_NOBLE_KLEAVOR
    applymovement2 LOCALID_ROUTE50_NOBLE_KLEAVOR, Route50_Movement_KleavorEntrance1
    delay 10
    playmoncry SPECIES_KLEAVOR, CRY_MODE_NORMAL
    waitmoncry
    playmoncry SPECIES_KLEAVOR, CRY_MODE_NORMAL
    waitmoncry
    waitmovement 0
    applymovement2 LOCALID_ROUTE50_NOBLE_KLEAVOR, Route50_Movement_KleavorEntrance2
    delay 10
    playse SE_LEDGE
    delay 20
	waitmovement LOCALID_ROUTE50_NOBLE_KLEAVOR
    setvar VAR_0x8004, 1  @ vertical pan
	setvar VAR_0x8005, 1  @ horizontal pan
	setvar VAR_0x8006, 5  @ num shakes
	setvar VAR_0x8007, 2  @ shake delay
	special ShakeCamera
    setobjectxyperm LOCALID_ROUTE50_NOBLE_KLEAVOR, 75, 14
    setvar VAR_NOBLE_KLEAVOR, 2
    release
    end

Route50_Movement_KleavorEntrance1:
    jump_in_place_down
    walk_in_place_fast_down
    walk_in_place_fast_down
	step_end

Route50_Movement_KleavorEntrance2:
	jump_2_down
    walk_in_place_slow_down
	walk_in_place_slow_down
	jump_in_place_down
	step_end

Route50_EventScript_Kleavor::
	lock
	faceplayer
	playmoncry SPECIES_KLEAVOR, CRY_MODE_ENCOUNTER
	waitmoncry
	setwildbossbattle species=SPECIES_KLEAVOR, level=80, item=ITEM_SCOPE_LENS, move1_1=MOVE_STONE_AXE, move1_2=MOVE_CROSS_POISON, move1_3=MOVE_LUNGE move1_4=MOVE_FOCUS_ENERGY
	settotemboost B_POSITION_OPPONENT_LEFT, 1, 2, 0, 0, 2, 0
	setflag FLAG_NO_WILD_CATCHING
	setflag FLAG_NO_WILD_RUNNING
	setflag FLAG_SMART_WILD_AI
	setflag FLAG_NO_SHINY
    dowildbattle
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, Route50_EventScript_KleavorRan
    bufferspeciesname STR_VAR_1, SPECIES_KLEAVOR
    msgbox SinjohRuins_Lab_Text_DropedItem, MSGBOX_DEFAULT
    giveitem ITEM_INSECT_PLATE
    addvar VAR_PLATECOUNTER, 1
	fadescreenswapbuffers FADE_TO_BLACK
	removeobject LOCALID_ROUTE50_NOBLE_KLEAVOR
	setflag FLAG_HIDE_ROUTE50_NOBLE_KLEAVOR
	fadescreenswapbuffers FADE_FROM_BLACK
    call_if_eq VAR_PLATECOUNTER, 3, SinjohRuins_Lab_EventScript_3Plates
    call_if_eq VAR_PLATECOUNTER, 6, SinjohRuins_Lab_EventScript_6Plates
    call_if_eq VAR_PLATECOUNTER, 9, SinjohRuins_Lab_EventScript_9Plates
    call_if_eq VAR_PLATECOUNTER, 12, SinjohRuins_Lab_EventScript_12Plates
    call_if_eq VAR_PLATECOUNTER, 15, SinjohRuins_Lab_EventScript_15Plates
    call_if_eq VAR_PLATECOUNTER, 16, SinjohRuins_Lab_EventScript_16Plates
	clearflag FLAG_NO_WILD_CATCHING
	clearflag FLAG_NO_WILD_RUNNING
	clearflag FLAG_SMART_WILD_AI
	clearflag FLAG_NO_SHINY
	release
	end

Route50_EventScript_KleavorRan::
	clearflag FLAG_NO_WILD_CATCHING
	clearflag FLAG_NO_WILD_RUNNING
	clearflag FLAG_SMART_WILD_AI
	clearflag FLAG_NO_SHINY
	release
	end


Route50_EventScript_ActivateElectrode::
    lock
    setobjectxyperm LOCALID_ROUTE50_NOBLE_ELECTRODE, 18, 26
    playse SE_M_DETECT
	getplayerxy VAR_TEMP_1, VAR_TEMP_2
	dofieldeffectsparkle VAR_TEMP_1, VAR_TEMP_2, 0
	waitfieldeffect FLDEFF_SPARKLE
    playse SE_PIN
    applymovement2 LOCALID_PLAYER, Common_Movement_ExclamationMark
    delay 60
    msgbox SinjohRuins_Lab_Text_PlayFlute, MSGBOX_YESNO
	closemessage
    goto_if_eq VAR_RESULT, FALSE, SinjohRuins_Lab_EventScript_NoOp
    playbgm MUS_DP_AZURE_FLUTE, FALSE
    delay 200
    fadedefaultbgm
    addobject LOCALID_ROUTE50_NOBLE_ELECTRODE
    clearflag FLAG_HIDE_ROUTE50_NOBLE_ELECTRODE
    applymovement2 LOCALID_ROUTE50_NOBLE_ELECTRODE, Route50_Movement_ElectrodeEntrance1
    delay 10
    playmoncry SPECIES_ELECTRODE, CRY_MODE_NORMAL
    waitmoncry
    playmoncry SPECIES_ELECTRODE, CRY_MODE_NORMAL
    waitmoncry
    waitmovement 0
    applymovement2 LOCALID_ROUTE50_NOBLE_ELECTRODE, Route50_Movement_ElectrodeEntrance2
    delay 10
    playse SE_LEDGE
    delay 20
	waitmovement 0
    setvar VAR_0x8004, 1  @ vertical pan
	setvar VAR_0x8005, 1  @ horizontal pan
	setvar VAR_0x8006, 5  @ num shakes
	setvar VAR_0x8007, 2  @ shake delay
	special ShakeCamera
	applymovement2 LOCALID_ROUTE50_NOBLE_ELECTRODE, Route50_Movement_ElectrodeEntrance3
	waitmovement LOCALID_ROUTE50_NOBLE_ELECTRODE
	removeobject LOCALID_ROUTE50_NOBLE_ELECTRODE
	delay 20
	setobjectxyperm LOCALID_ROUTE50_NOBLE_ELECTRODE, 14, 31
	addobject LOCALID_ROUTE50_NOBLE_ELECTRODE
	clearflag FLAG_HIDE_ROUTE50_NOBLE_ELECTRODE
    setvar VAR_NOBLE_ELECTRODE, 2
    release
    end

Route50_Movement_ElectrodeEntrance1:
	walk_right
    jump_in_place_right
    walk_in_place_fast_right
    walk_in_place_fast_right
	step_end

Route50_Movement_ElectrodeEntrance2:
	jump_2_right
    walk_in_place_slow_up
	walk_in_place_slow_up
	jump_in_place_down
	step_end

Route50_Movement_ElectrodeEntrance3:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	step_end

Route50_EventScript_Electrode::
	lock
	faceplayer
	playmoncry SPECIES_ELECTRODE, CRY_MODE_ENCOUNTER
	waitmoncry
	setwildbossbattle species=SPECIES_ELECTRODE, level=80, item=ITEM_SCOPE_LENS, move1_1=MOVE_STONE_AXE, move1_2=MOVE_CROSS_POISON, move1_3=MOVE_LUNGE move1_4=MOVE_FOCUS_ENERGY
	settotemboost B_POSITION_OPPONENT_LEFT, 1, 2, 0, 0, 2, 0
	setflag FLAG_NO_WILD_CATCHING
	setflag FLAG_NO_WILD_RUNNING
	setflag FLAG_SMART_WILD_AI
	setflag FLAG_NO_SHINY
    dowildbattle
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, Route50_EventScript_ElectrodeRan
    bufferspeciesname STR_VAR_1, SPECIES_ELECTRODE
    msgbox SinjohRuins_Lab_Text_DropedItem, MSGBOX_DEFAULT
    giveitem ITEM_ZAP_PLATE
    addvar VAR_PLATECOUNTER, 1
	fadescreenswapbuffers FADE_TO_BLACK
	removeobject LOCALID_ROUTE50_NOBLE_ELECTRODE
	setflag FLAG_HIDE_ROUTE50_NOBLE_ELECTRODE
	fadescreenswapbuffers FADE_FROM_BLACK
    call_if_eq VAR_PLATECOUNTER, 3, SinjohRuins_Lab_EventScript_3Plates
    call_if_eq VAR_PLATECOUNTER, 6, SinjohRuins_Lab_EventScript_6Plates
    call_if_eq VAR_PLATECOUNTER, 9, SinjohRuins_Lab_EventScript_9Plates
    call_if_eq VAR_PLATECOUNTER, 12, SinjohRuins_Lab_EventScript_12Plates
    call_if_eq VAR_PLATECOUNTER, 15, SinjohRuins_Lab_EventScript_15Plates
    call_if_eq VAR_PLATECOUNTER, 16, SinjohRuins_Lab_EventScript_16Plates
	clearflag FLAG_NO_WILD_CATCHING
	clearflag FLAG_NO_WILD_RUNNING
	clearflag FLAG_SMART_WILD_AI
	clearflag FLAG_NO_SHINY
	release
	end

Route50_EventScript_ElectrodeRan::
	clearflag FLAG_NO_WILD_CATCHING
	clearflag FLAG_NO_WILD_RUNNING
	clearflag FLAG_SMART_WILD_AI
	clearflag FLAG_NO_SHINY
	release
	end
